### ISSUE TITLE
[PRE REVIEW]: VBLinLogit: Variational Bayesian linear and logistic regression

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1314] opened 2019-03-11 01:15 UTC
**Submitting author:** @jdrugo (<a href="http://orcid.org/0000-0002-7846-0408">Jan Drugowitsch</a>)
**Repository:** <a href="https://github.com/DrugowitschLab/VBLinLogit" target ="_blank">https://github.com/DrugowitschLab/VBLinLogit</a>
**Version:** v0.2
**Editor:** @usethedata
**Reviewers:** @ManuelaS

**Author instructions**

Thanks for submitting your paper to JOSS @jdrugo. **Currently, there isn't an JOSS editor assigned** to your paper.

@jdrugo if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-03-11 01:15
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-03-11 01:15
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-11 01:15
PDF failed to compile for issue #1314 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    13    0    13    0     0    244      0 --:--:-- --:--:-- --:--:--   250
Error reading bibliography ./paper.bib (line 113, column 3):
unexpected "a"
expecting space or ","
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment] 2019-03-11 05:17
@jdrugo looks like there is an error in your bibliography preventing compilation of the paper.

**Comment by kyleniemeyer** [comment] 2019-03-11 05:20
@eramirem and @arokem as the resident machine learning editors, could one of you handle this submission?

**Comment by jdrugo** [comment] 2019-03-11 12:14
@kyleniemeyer I have fixed the paper.bib typo upstream. How do I get whedon to pick up that change?

**Comment by kyleniemeyer** [comment] 2019-03-11 16:07
@whedon generate pdf

**Comment by whedon** [comment] 2019-03-11 16:07
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-11 16:08
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01314/joss.01314/10.21105.joss.01314.pdf)

**Comment by jdrugo** [comment] 2019-03-11 17:12
@whedon generate pdf

**Comment by whedon** [comment] 2019-03-11 17:13
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-11 17:13
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01314/joss.01314/10.21105.joss.01314.pdf)

**Comment by jdrugo** [comment] 2019-03-11 17:14
The article proof looks good now.

**Comment by labarba** [comment] 2019-03-16 19:56
Hi @jdrugo — we're looking to assign a handling editor for your submission (I am the Associated Editor in Chief on rotation this week). Before we move forward, I do have some comments on your paper. 

From our [Review Criteria](https://joss.readthedocs.io/en/latest/review_criteria.html), the paper should contain:

- A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience
- A clear statement of need that illustrates the purpose of the software
- Mentions (if applicable) of any ongoing research projects using the software or recent scholarly publications enabled by it 

I want to emphasize the need for explaining the software to a diverse audience: currently, I don't see this in the paper; the second paragraph is especially jargon-heavy. You also don't mention if this software has been used in any research projects. 

Note also the section on "novelty":

> Submissions that implement solutions already solved in other software packages are accepted into JOSS provided that they meet the criteria listed above and cite prior similar work. 

Can you comment about existing related functionality in Matlab? For example, the Matlab documentation has a section on [Bayesian regression models](https://www.mathworks.com/help/econ/bayesian-linear-regression-models.html). How does your software fill a gap in this ecosystem?

**Comment by labarba** [comment] 2019-03-16 20:34
@usethedata — Taking into account editor workloads at the moment, I'd like to assign this submission to you for handling. Can you take it on? You're a statistician!

**Comment by usethedata** [comment] 2019-03-16 22:39
@whedon assign @usethedata as editor

**Comment by whedon** [comment] 2019-03-16 22:39
OK, the editor is @usethedata

**Comment by labarba** [comment] 2019-03-16 23:49
@whedon check references

**Comment by whedon** [comment] 2019-03-16 23:49
```
Attempting to check references...
```

**Comment by whedon** [comment] 2019-03-16 23:49
```Reference check summary:

OK DOIs

- None

MISSING DOIs

- https://doi.org/10.1214/06-ba126 may be missing for title: Variational Algorithms for Approximate Bayesian Inference
- https://doi.org/10.1108/03684920710743466 may be missing for title: Pattern Recognition and Machine Learning
- https://doi.org/10.1002/sim.1856 may be missing for title: Bayesian Data Analysis
- https://doi.org/10.2307/1271145 may be missing for title: Markov Chain Monte Carlo in Practice
- https://doi.org/10.1007/978-0-387-21606-5_14 may be missing for title: The Elements of Statistical Learning
- https://doi.org/10.1002/9781118266502.scard may be missing for title: Machine Learning: A Probabilistic Perspective
- https://doi.org/10.1145/1273496.1273625 may be missing for title: A New View of Automatic Relevance Determination
- https://doi.org/10.7551/mitpress/7503.001.0001 may be missing for title: Advances in Neural Information Processing Systems 20, Proceedings of the Twenty-First Annual Conference on Neural Information Processing Systems, Vancouver, British Columbia, Canada, December 3-6, 2007
- https://doi.org/10.1111/j.2517-6161.1996.tb02080.x may be missing for title: Regression Shrinkage and Selection via the Lasso
- https://doi.org/10.1162/neco.1992.4.3.415 may be missing for title: Bayesian Interpolation
- https://doi.org/10.1007/978-1-4612-0745-0 may be missing for title: Bayesian Learning for Neural Networks
- https://doi.org/10.1109/icdm.2012.58 may be missing for title: Sparse Bayesian Learning and the Relevance Vector Machine
- https://doi.org/10.2172/1128035 may be missing for title: Variational Bayesian inference for linear and logistic regression

INVALID DOIs

- None
```

**Comment by labarba** [comment] 2019-03-16 23:52
@jdrugo — Can you check your bibliography entries and add a DOI whenever one exists? Our helpful bot `whedon` has given some clues above for possible missing DOIs (it's not perfect, so some could be flukes).

**Comment by jdrugo** [comment] 2019-03-20 18:11
@whedon generate pdf

**Comment by whedon** [comment] 2019-03-20 18:11
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-20 18:12
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01314/joss.01314/10.21105.joss.01314.pdf)

**Comment by jdrugo** [comment] 2019-03-20 18:21
@whedon generate pdf

**Comment by whedon** [comment] 2019-03-20 18:21
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-20 18:22
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01314/joss.01314/10.21105.joss.01314.pdf)

**Comment by jdrugo** [comment] 2019-03-20 18:23
@labarba -- Thank you for your comments. I have now updated the paper accordingly, and have added DOIs whenever available.

**Comment by labarba** [comment] 2019-03-20 19:47
Did you also address my other comment, above?
https://github.com/openjournals/joss-reviews/issues/1314#issuecomment-473580071

**Comment by jdrugo** [comment] 2019-03-20 19:50
@labarba - yes, the updated version is an attempt to address these comments. I didn't go so far as to explain what linear and logistic regression are (I hope this knowledge can be assumed), but tried to simplify the summary.

**Comment by usethedata** [comment] 2019-03-30 13:08
@jdrugo My apologies for my delays in getting back to this submission.  My work life got a bit intense.  The revised manuscript looks good from my perspective.  Let me see about getting some reviewers assigned to this.

**Comment by usethedata** [comment] 2019-04-01 11:32
@whedon assign @ManuelaS as reviewer

**Comment by whedon** [comment] 2019-04-01 11:33
OK, the reviewer is @ManuelaS

**Comment by usethedata** [comment] 2019-04-01 11:33
@whedon start review

**Comment by whedon** [comment] 2019-04-01 11:33
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1359. Feel free to close this issue now!

**Comment by usethedata** [comment] 2019-04-01 11:33
closing pre-review issue.

**Closed by usethedata** 2019-04-01 11:33 UTC
Labels: Matlab, TeX, pre-review
