### ISSUE TITLE
[PRE REVIEW]: GB_code: A grain boundary generation code

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#853] opened 2018-07-26 17:26 UTC
**Submitting author:** @oekosheri (<a href="http://orcid.org/0000-0002-9616-4602">raheleh Hadian</a>)
**Repository:** <a href="https://github.com/oekosheri/GB_code" target ="_blank">https://github.com/oekosheri/GB_code</a>
**Version:** v1.0.0
**Editor:** @labarba
**Reviewers:** @vyasr, @trallard

**Author instructions**

Thanks for submitting your paper to JOSS @oekosheri. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@oekosheri if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by oekosheri** [comment] 2018-07-26 20:43
Thanks, I edited paper.md and merged. does it look alright now?

**Comment by arfon** [comment] 2018-07-27 11:44
@whedon generate pdf

**Comment by whedon** [comment] 2018-07-27 11:44
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-07-27 11:44
PDF failed to compile for issue #853 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0    150      0 --:--:-- --:--:-- --:--:--   151
pandoc-citeproc: reference Sutton:1996 not found
pandoc-citeproc: reference Bollmann:1984 not found
pandoc-citeproc: reference Sutton:1996 not found
pandoc-citeproc: reference Bollmann:1984 not found
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.283 

Looks like we failed to compile the PDF

**Comment by oekosheri** [comment] 2018-07-31 10:45
@whedon generate pdf

**Comment by whedon** [comment] 2018-07-31 10:45
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-07-31 10:45
PDF failed to compile for issue #853 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    12    0    12    0     0     28      0 --:--:-- --:--:-- --:--:--    28
Error producing PDF.
! Missing $ inserted.
<inserted text> 
                $
l.283 

Looks like we failed to compile the PDF

**Comment by oekosheri** [comment] 2018-07-31 10:47
@arfon Could you tell me what the problem is?

**Comment by oekosheri** [comment] 2018-08-01 10:48
@whedon commands

**Comment by whedon** [comment] 2018-08-01 10:48
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

🚧 🚧 🚧 Experimental Whedon features 🚧 🚧 🚧

# Compile the paper
@whedon generate pdf

```

**Comment by oekosheri** [comment] 2018-08-01 13:04
@arfon I used pandoc to generate the PDF myself and had no issues. Waiting for your help to see what the problem is.

**Comment by arfon** [comment] 2018-08-01 15:36
@oekosheri - I think the underscore in the title needs escaping. I fixed it in https://github.com/oekosheri/GB_code/pull/2

**Comment by oekosheri** [comment] 2018-08-01 20:29
Thank you, I merged it. Let me see if I can generate the PDF now.

**Comment by oekosheri** [comment] 2018-08-01 20:30
@whedon generate pdf

**Comment by whedon** [comment] 2018-08-01 20:30
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-08-01 20:30
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00853/joss.00853/10.21105.joss.00853.pdf)

**Comment by oekosheri** [comment] 2018-08-02 07:52
I made a minor change,
So:
@whedon generate pdf

**Comment by oekosheri** [comment] 2018-08-02 07:55
@whedon generate pdf

**Comment by whedon** [comment] 2018-08-02 07:55
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-08-02 07:55
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00853/joss.00853/10.21105.joss.00853.pdf)

**Comment by oekosheri** [comment] 2018-08-02 07:58
@arfon @labarba the pdf looks good to me. Looking forward to the review process!

**Comment by oekosheri** [comment] 2018-08-09 09:03
@arfon Dear Editor, I was wondering about the time frame of the review process. Could you let me know approximately when my code will be reviewed? Thanks and I appreciate it.

**Comment by labarba** [comment] 2018-08-09 09:20
It can take between two weeks and two months, typically, to complete the review and acceptance process. Thank you for your patience with our wholly volunteer-staffed journal.

**Comment by oekosheri** [comment] 2018-08-09 09:29
@labarba Thank you for your answer. I didn't know I should suggest reviewers. Is there a list I can choose from?

**Comment by oekosheri** [comment] 2018-08-09 15:23
Thanks! I would highly appreciate it if any of these reviewers: @bjmorgan @trallard @jochym, would agree to review my code.

**Comment by labarba** [comment] 2018-08-09 20:34
@whedon set @vyasr as reviewer

**Comment by labarba** [comment] 2018-08-10 09:35
@whedon assign @vyasr as reviewer

**Comment by whedon** [comment] 2018-08-10 09:35
OK, the reviewer is @vyasr

**Comment by labarba** [comment] 2018-08-14 18:30
FYI — I'm waiting for replies from potential second reviewers. Once I get a positive reply, I'll add the reviewer and start the review issue. Stay tuned.

**Comment by oekosheri** [comment] 2018-08-14 18:35
Thank you for informing me.

**Comment by trallard** [comment] 2018-08-17 12:47
hi @labarba  I can jump in as a second reviewer if you are still looking for someone to do it

**Closed as completed** 2018-08-17 13:22 UTC
Labels: pre-review, TeX, Python
