### ISSUE TITLE
[PRE REVIEW]: Pylustrator: An interactive interface to style matplotlib figures

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1499] opened 2019-06-08 17:57 UTC
**Submitting author:** @Randrian45 (<a href="http://orcid.org/0000-0001-5893-2650">Richard Gerum</a>)
**Repository:** <a href="https://bitbucket.org/fabry_biophysics/pylustrator" target ="_blank">https://bitbucket.org/fabry_biophysics/pylustrator</a>
**Version:** 0.9.2
**Editor:** @lheagy
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @Randrian45. **Currently, there isn't an JOSS editor assigned** to your paper.

@Randrian45 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-06-08 17:57
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-06-08 17:57
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-06-08 17:57
PDF failed to compile for issue #1499 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1499 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment] 2019-06-08 18:01
@whedon generate pdf

**Comment by whedon** [comment] 2019-06-08 18:01
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-06-08 18:01
PDF failed to compile for issue #1499 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1499 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/lib/whedon/processor.rb:61:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-e8270d9fd886/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by labarba** [comment] 2019-06-08 18:06
@arfon Help! The paper is in the submission repo under the `dos` folder
https://bitbucket.org/fabry_biophysics/pylustrator/src/default/docs/
... but `whedon` cannot find it.

**Comment by labarba** [comment] 2019-06-08 18:07
👋  @lheagy — Based on topic and current editor loads, I'd like to assign this submission to you for editing. Can you take it? Let me know!

**Comment by arfon** [comment] 2019-06-08 18:56
@labarba - @whedon can't deal with this as the source is in a mercurial repo. I will download manually and compile this.

**Comment by arfon** [comment] 2019-06-08 19:02
I've compiled the paper locally: [10.21105.joss.01499.pdf](https://github.com/openjournals/joss-reviews/files/3268846/10.21105.joss.01499.pdf)

**Comment by lheagy** [comment] 2019-06-08 23:52
Hi @labarba: yes, I am happy to take this one!

**Comment by labarba** [comment] 2019-06-09 05:18
@whedon assign @lheagy as editor

**Comment by whedon** [comment] 2019-06-09 05:18
OK, the editor is @lheagy

**Comment by lheagy** [comment] 2019-06-10 17:27
:wave: Hi @diegoenry, @maxscheurer, would you be willing to review this submission for JOSS?

**Comment by lheagy** [comment] 2019-06-21 21:09
👋 Hi @Randrian45 - thanks for your submission to JOSS. While this looks like a useful piece of software, I am afraid it is out of scope for JOSS as it appears to be a minor utility and it's not clear that it has an research application ([per our submission requirements](https://joss.readthedocs.io/en/latest/submitting.html#submission-requirements)).

**Closed by lheagy** 2019-06-21 21:09 UTC
Labels: pre-review

**Comment by Randrian45** [comment] 2019-07-22 14:25
Hi @lheagy thank you for considering my paper. 
But, I am a bit puzzled that the paper is considered out of scope here.
- minor utility: sure it is based on matplotlib but it offers a whole new way to address the problem of finding the best visualization. Also as more and more focus is laid on reproducibility, it is a crucial point that the researcher can provide a code that can exactly reproduce a figure (which pylustrator offers as it generates code) and not just a code that produces a raw figure that was then edited by an external graphics software (which also bears the risk of accidentally altering some plotted data).
- research application: https://scholar.google.de/scholar?q=pylustrator the software already has been used in some publications, which proves that there is an application of the software in a research context. Unfortunately, it currently cannot be cited properly without a peer reviewd publication. I thought JOSS would be the ideal format for such a project as it requires just a minimal summary and not a full length paper.

Also I am confused that it seemed that the paper was send out for review, but I can not find comments from the reviewers. Are the reviews intended kept secret?

**Comment by lheagy** [comment] 2019-07-24 16:11
Hi @Randrian45, thanks for your response and I will try to answer your questions here. 

First, to clarify on the review process - the review for this submission was never started, and there are no comments from reviewers at this point. We would have opened a new issue where reviewers could comment, and you would have seen comments there - JOSS reviews are open and in the public. 

Second, with respect to the "research application" criteria: the spirit of the criteria is that the software contributes to obtaining results in a scientific analysis. Tuning figures with a GUI interface, though it may be useful in the publication process, is out-of-scope for the research-focussed submissions JOSS accepts. 

I hope this provides some clarification.
