### ISSUE TITLE
[REVIEW]: cbcbeat: an adjoint-enabled framework for computational cardiac electrophysiology

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#224] opened 2017-04-04 20:27 UTC
**Submitting author:** @meg-simula (<a href="http://orcid.org/0000-0002-6872-3710">Marie Rognes</a>)
**Repository:** <a href="https://bitbucket.org/meg/cbcbeat" target ="_blank">https://bitbucket.org/meg/cbcbeat</a>
**Version:** v1.0
**Editor:** @labarba
**Reviewer:** @jessdtate
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.801552" target="_blank">10.5281/zenodo.801552</a>

## Status

[![status](http://joss.theoj.org/papers/8403a4b6cabff51d99d6b0a433358016/status.svg)](http://joss.theoj.org/papers/8403a4b6cabff51d99d6b0a433358016)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/8403a4b6cabff51d99d6b0a433358016"><img src="http://joss.theoj.org/papers/8403a4b6cabff51d99d6b0a433358016/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/8403a4b6cabff51d99d6b0a433358016/status.svg)](http://joss.theoj.org/papers/8403a4b6cabff51d99d6b0a433358016)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://bitbucket.org/meg/cbcbeat" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://bitbucket.org/meg/cbcbeat">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0)?
- [x] **Authorship:** Has the submitting author (@meg-simula) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment] 2017-04-04 20:27
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jessdtate it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by labarba** [comment] 2017-04-30 23:37
Hey, @jessdtate --- We were in touch by email ~20 days ago. Have you had a chance to look at the submission?
Cheers!

**Comment by jessdtate** [comment] 2017-05-08 06:43
@meg-simula,  I an error when trying to test the installation as describe in the install doc.  The error is: 
No module named 'dolfinimport'
I installed the fenics in my anaconda build, and I can import the dolfin module fine. Do I have to install dolfin separately, or is there something else wrong? .  I'm running on OS X 10.12.

**Comment by meg-simula** [comment] 2017-05-08 06:50
Are you using Python 2 or 3?

**Comment by jessdtate** [comment] 2017-05-08 15:18
OK, I'll try python 2

**Comment by jessdtate** [comment] 2017-05-17 22:54
I got it working with python 2.  This detail should be noted in the installation documentation.

It might help to have some other hints about the installation process.  For instance, using conda the py.test will not work (at least not for me) as it doesn't copy the py.test executable to the fenics environment.  However, using the docker method, there are problems getting the plots to visualize.  I know that these are fenics issues, but it affects your software.

**Comment by meg-simula** [comment] 2017-05-18 12:55
Thanks @jessdtate, I have updated the installation instructions to require Python 2 for now.

**Comment by labarba** [comment] 2017-05-18 13:19
What about the other suggestions in the second paragraph?

**Comment by meg-simula** [comment] 2017-05-18 13:23
If you give me a concrete suggestion for what to add and where, I would be happy to do so. 

Plotting in Docker is clearly FEniCS work-in-progress, but I would rather avoid duplication of issues in FEniCS in the cbcbeat documentation. I'm not familiar with using conda, so I wouldn't quite know what to write regarding py.test.

**Comment by jessdtate** [comment] 2017-05-18 17:35
these are suggestion to make the installation easier for those that may not know FEniCS or your software.  Since the cbcbeat API is based of FEniCS's, the users need to be familiar with the API of FEniCS, which should but noted in the documentation.  You could emphasis this in the documentation with statements like: 'Users should familiarize themselves with the FEniCS package..' or '...requires a working understanding of FEniCS...'.  I suggest including language like this in both the website and the install doc (in the dependencies section).  If the user follows this advise, they will probably learn of which limitations are from FEniCS as rather than assigning them to cbcbeat.

The extent that you do this for other dependences like dolfin-adjoint is up to you.  I had no problems installing or running that package after getting FEniCS working.  

If you do not test the conda version much or at all, it may help to steer users in that direction with a statement like: 'Any type of build of FEniCS should work, but cbcbeat is better tested using builds on docker.'

**Comment by jessdtate** [comment] 2017-05-18 17:46
I had a problem getting the niederer-benchmark demo to work.   It seems to need a case file that I cannot find.

**Comment by jessdtate** [comment] 2017-05-18 17:52
I'm also having trouble running the biventricular example.  I get the error:

`File "demo_biventricular.py", line 195, in main
    vs_timeseries = TimeSeries(mpi_comm, "%s/vs" % directory)
NameError: global name 'TimeSeries' is not defined`

**Comment by jessdtate** [comment] 2017-05-18 18:36
I'm a bit confused as to the description of the software for applications of forward and inverse cardiac electrophysiology.  My concern is that the description takes away the focus of what I think is a useful software.   

The examples provided are all tissue or cell models, which are forward problems in the technical sense, but traditional use of the term of cardiac forward problem most often refers to the calculation of the body surface from cardiac sources.  I can see how these simulations could be used with the traditional forward problems, but that does not seem to be the primary focus of the software.

As for the inverse problem capability, it is not clear that there is any in either the technical or tradition sense, as there are no examples, nor any description in the API documentation.  

One solution would be either clarify what is meant by forward and inverse problems and how it is used in such. I would suggest removing it and instead focus on the softwares uses for cell and tissue modeling, as that is a useful application by itself.

**Comment by meg-simula** [comment] 2017-05-18 18:54
Thanks for taking the time to look carefully at this Jess! I'll respond in sequence below. (Sidenote: threaded issues would be practical on Github, does that exist?) 

1. Installation and testing: I've updated the main readme doc, hopefully in accordance with your suggestions and pointed new users towards the FEniCS and dolfin-adjoint tutorials, and added your suggestions re: testing/development on native builds/Docker images.

**Comment by meg-simula** [comment] 2017-05-18 18:57
2. The niederer-demo runs out of the box on a clean clone of the repository for me. Could you please report the error message you get in (possibly) a separate issue?

**Comment by jessdtate** [comment] 2017-05-18 19:03
@whedon commands

**Comment by whedon** [comment] 2017-05-18 19:03
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by meg-simula** [comment] 2017-05-18 19:10
3. I'm not able to reproduce the TimeSeries error. Which version of FEniCS have you installed for conda?
(Try e.g.:
$ dolfin-version
)

**Comment by jessdtate** [comment] 2017-05-18 19:16
This is a different setup than most github repos.  Normally, we would split these into separate issues and each would be a thread.  I cannot create issues in bitbucket, but I could add these to your github repo.

**Comment by jessdtate** [comment] 2017-05-18 19:17
dolfin-version: 2016.2.0

**Comment by meg-simula** [comment] 2017-05-18 19:18
4. This sounds like naming/differing communities issue. How about just replacing:

"cbcbeat [@cbcbeat] is a Python-based software collection targeting forward and inverse solution of computational cardiac electrophysiology problems"

with

"cbcbeat [@cbcbeat] is a Python-based software collection targeting computational cardiac electrophysiology problems." 

The next sentences then describe what cbcbeat provides, namely solvers for bidomain + monodomain that are adjoint-enabled i.e. allows for computing gradients, which in turn allows for gradient-based PDE-constrained optimization (i.e. what I would call inverse problems). 

I can add a sentence clarifying the latter point and add a demo with an inverse (in the sense of PDE-constrained optimization) example. There are a bunch of tests for the adjoint computation under test/.

**Comment by meg-simula** [comment] 2017-05-18 19:29
3.2 The TimeSeries error would be a pure FEniCS + conda issue, I can follow that up with the maintainers of the FEniCS conda packages. (See the top of the demo_biventricular.py demo for a recommendation of running the demo with --T 1.0 to make it complete faster.) 

2.2 The niederer-demo issue would belong with the cbcbeat Bitbucket repo. If you can provide the error message, that would be useful.

**Comment by jessdtate** [comment] 2017-05-18 19:33
re 4.  That description is much more clear.

**Comment by jessdtate** [comment] 2017-05-18 19:34
hmm.  Looks like the niederer-demo is working with docker build now.

**Comment by jessdtate** [comment] 2017-05-18 19:35
3.2 the biventricular demo is failing in the docker build.  It reports 'killed' without an error message.

**Comment by meg-simula** [comment] 2017-05-18 20:00
3.2: I'm assuming this is not with --T 1.0... Thanks for patiently testing, I've just pushed a fix. Could you please test with Docker again?

**Comment by meg-simula** [comment] 2017-05-18 20:02
4.2: Text updated, and I've added an issue re adding an inverse demo.

**Comment by meg-simula** [comment] 2017-05-18 20:22
3.2: I've also removed the use of the old style TimeSeries, so perhaps it also works with Conda now.

**Comment by jessdtate** [comment] 2017-05-18 20:27
Both the biventricular and becnchmark examples are working in docker.  

I no longer get the TimeSeries error, but now I'm getting this error with both in the conda version:
NameError: global name 'HDF5File' is not defined

**Comment by meg-simula** [comment] 2017-05-18 20:37
Good! Missing TimeSeries/HDF5 in the conda packages seem to be a known FEniCS issue/feature see e.g: 
  https://github.com/conda-forge/fenics-feedstock/issues/37
  https://github.com/conda-forge/fenics-feedstock/issues/5

**Comment by jessdtate** [comment] 2017-05-23 20:29
@labarba what's the procedure now.  I'm satisfied with the changes.  There are plans to add another example, otherwise everything else is done.  Do we wait for the example to finish the review, or finish it up now.  Do I just close the issue when it is done, or are there other procedures?

**Comment by labarba** [comment] 2017-05-23 22:27
I see all the checkboxes are ticked. If you are happy with all fixes, @jessdtate, then we just ping @arfon to initiate acceptance, and ask @meg-simula to make an archive of the fixed software to get a DOI update.

**Comment by meg-simula** [comment] 2017-05-30 12:11
@labarba @jessdtate Sounds good. Will you let me know when things are ready for me to make a fixed archive? And, what is the best way of doing so?

**Comment by labarba** [comment] 2017-05-30 13:08
@jessdtate : We will need a statement from you indicating that you are satisfied and recommend acceptance.

**Comment by jessdtate** [comment] 2017-05-30 15:48
I am satisfied with the response to the feedback I provided and recommend acceptance.  @arfon

**Comment by arfon** [comment] 2017-05-30 22:00
@meg-simula - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by meg-simula** [comment] 2017-05-31 18:39
Done. DOI: 10.5281/zenodo.801552 cf: https://zenodo.org/record/801552#.WS8Nxx8xDb1

**Comment by arfon** [comment] 2017-05-31 18:50
@whedon set 10.5281/zenodo.801552  as archive

**Comment by whedon** [comment] 2017-05-31 18:50
OK. <a href="http://dx.doi.org/10.5281/zenodo.801552" target="_blank">10.5281/zenodo.801552</a> is the archive.

**Comment by arfon** [comment] 2017-05-31 23:56
@jessdtate many thanks for your review here and to @labarba for editing this submission ✨ 

@meg-simula - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00224 :zap: :rocket: :boom:

**Closed by arfon** 2017-05-31 23:56 UTC
Labels: review
