### ISSUE TITLE
[REVIEW]: schwimmbad: A uniform interface to parallel processing pools in Python

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#357] opened 2017-08-11 18:43 UTC
**Submitting author:** @adrn (<a href="http://orcid.org/0000-0003-0872-7098">Adrian Price-Whelan</a>)
**Repository:** <a href="https://github.com/adrn/schwimmbad" target ="_blank">https://github.com/adrn/schwimmbad</a>
**Version:** v0.2.1
**Editor:** @danielskatz
**Reviewer:** @jmjwozniak
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.885577" target="_blank">10.5281/zenodo.885577</a>

## Status

[![status](http://joss.theoj.org/papers/2112005eb19500411d63d871f84aee30/status.svg)](http://joss.theoj.org/papers/2112005eb19500411d63d871f84aee30)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/2112005eb19500411d63d871f84aee30"><img src="http://joss.theoj.org/papers/2112005eb19500411d63d871f84aee30/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/2112005eb19500411d63d871f84aee30/status.svg)](http://joss.theoj.org/papers/2112005eb19500411d63d871f84aee30)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/adrn/schwimmbad" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@jmjwozniak, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/adrn/schwimmbad">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.2.1)?
- [x] **Authorship:** Has the submitting author (@adrn) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment] 2017-08-11 18:43
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @jmjwozniak it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by danielskatz** [comment] 2017-08-11 18:45
Ok, @jmjwozniak - this is ready to go.

Please carry out your review in this issue by updating the checklist above (please make sure you're logged in to GitHub)

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Please avoid lengthy details of difficulties in this review thread. Instead, please create a new issue in the target repository and link to those issues (especially acceptance-blockers) in this review thread. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

Any questions/concerns, please let me know.

Thanks!!

**Comment by danielskatz** [comment] 2017-08-22 13:55
@jmjwozniak - any update on this?

**Comment by jmjwozniak** [comment] 2017-08-22 14:47
No but I can do it this week- when is it due?

**Comment by danielskatz** [comment] 2017-08-22 14:51
there's an expectation that it was be done somewhat promptly, but we don't currently have due dates for reviews.  If you can do it this week (or at least get started), please do.

**Comment by danielskatz** [comment] 2017-08-28 13:11
@jmjwozniak - any update on this review?

**Comment by jmjwozniak** [comment] 2017-08-28 18:04
Yes, I was able to run the software today.   I also went through the checkboxes.

**Comment by jmjwozniak** [comment] 2017-08-28 18:08
I also filed a minor issue: https://github.com/adrn/schwimmbad/issues/16

**Comment by jmjwozniak** [comment] 2017-08-28 20:29
As far as I can tell, the version is not v0.2.1 .  git tag has v0.2.0 , schwimmbad.__version__ has 0.3.dev .

**Comment by jmjwozniak** [comment] 2017-08-28 20:29
I do not see performance claims to review.

**Comment by jmjwozniak** [comment] 2017-08-28 20:30
I do not see notes for "Community guidelines".

**Comment by danielskatz** [comment] 2017-08-28 20:48
If there are no performance claims, you can check the box, since it says "Have any performance claims of the software been confirmed?" and there are none.  I will also suggest a change in wording for this item for the future, to make this more clear.

**Comment by adrn** [comment] 2017-08-30 16:12
I was planning to release v0.3 after the comments from this review. The current version is v0.2.1 on pypi (I had forgotten to push that tag, but [fixed now](https://github.com/adrn/schwimmbad/tree/v0.2.1)).

I also fixed the issue with the README.

Thanks!

**Comment by danielskatz** [comment] 2017-08-30 16:18
The link in the README points to http://schwimmbad.readthedocs.io/en/stable/, which says "Sorry, This page does not exist yet."

Also, the Community Guidelines issue needs to be addressed...

**Comment by adrn** [comment] 2017-08-30 16:38
Strange, looks like the readthedocs "stable" build started failing...Updated the link to the main RTD page instead.

I also added a [How to contribute and report issues](http://schwimmbad.readthedocs.io/en/latest/contributing.html) page to the documentation.

**Comment by jmjwozniak** [comment] 2017-09-05 14:42
All boxes are now checked.

**Comment by danielskatz** [comment] 2017-09-05 15:25
Thanks @jmjwozniak and @adrn !

@arfon, please take over and continue the acceptance/publication process

**Comment by arfon** [comment] 2017-09-06 00:14
@adrn - Could you please cite the references you have in your `paper.bib` directly please? (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html)). They're currently not being picked up by Pandoc.

**Comment by adrn** [comment] 2017-09-06 00:24
@arfon Done (I think)

**Comment by arfon** [comment] 2017-09-06 00:26
@adrn - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by adrn** [comment] 2017-09-06 00:37
Alrighty: https://zenodo.org/record/885577

**Comment by arfon** [comment] 2017-09-06 00:53
@whedon set 10.5281/zenodo.885577 as archive

**Comment by whedon** [comment] 2017-09-06 00:53
OK. <a href="http://dx.doi.org/10.5281/zenodo.885577" target="_blank">10.5281/zenodo.885577</a> is the archive.

**Comment by arfon** [comment] 2017-09-06 01:02
@jmjwozniak - many thanks for your review and to @danielskatz for editing this submission ✨ 

@adrn - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00357 ⚡️ 🚀 💥

**Closed by arfon** 2017-09-06 01:02 UTC
Labels: accepted, review
