### ISSUE TITLE
[REVIEW]: PyAFBF: a Python library to sample image textures from the anisotropic fractional Brownian field.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3821] opened 2021-10-12 22:13 UTC
**Submitting author:** @fjprichard (<a href="http://orcid.org/0000-0001-5146-9894">Frédéric Richard</a>)
**Repository:** https://github.com/fjprichard/PyAFBF/
**Branch with paper.md** (empty if default branch): main
**Version:** v0.1.5
**Editor:** @pibion
**Reviewers:** @vitorsr, @janmandel
**Archive:** 10.5281/zenodo.6860333

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/2588e2be0b39c4f48f30cff6b78d4041/status.svg)](https://joss.theoj.org/papers/2588e2be0b39c4f48f30cff6b78d4041)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/2588e2be0b39c4f48f30cff6b78d4041"><img src="https://joss.theoj.org/papers/2588e2be0b39c4f48f30cff6b78d4041/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/2588e2be0b39c4f48f30cff6b78d4041/status.svg)](https://joss.theoj.org/papers/2588e2be0b39c4f48f30cff6b78d4041)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/fjprichard/PyAFBF/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@vitorsr & @janmandel, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @pibion know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @vitorsr
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/fjprichard/PyAFBF/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fjprichard/PyAFBF/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fjprichard) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @janmandel
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/fjprichard/PyAFBF/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/fjprichard/PyAFBF/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@fjprichard) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by pibion** [comment] 2021-10-12 22:17
@fjprichard, @arfon do you have any thoughts about why the pdf compilation is failing?  Is the pdf in a non-standard location?

**Comment by fjprichard** [comment] 2021-11-04 12:07
Dear visitorsr,

Thank you for your review. Please find below some answers to your comments.


Major comments:

"I am unable to replicate the auto_examples (Example gallery) as I have not found enough information to replicate the development environment and locally generate the aforementioned documentation.

The same holds for the nose tests."

Information about the environment are in the setup file (packages required and versions). Would you suggest to have it somewhere else? 

-----------



Minor comments:

_"The API is incredibly well documented. Nice-to-haves for researchers and alike such as the inclusion of a glossary are of immense help. However, the repository documentation itself (mainly referring to README.rst) is not prominent enough to provide a good overview of the package."_

I added the content of the documentation in the README file.  

"Everything is otherwise stellar."
Thank you.

**Comment by vitorsr** [comment] 2021-11-05 16:51
Hi,

Thanks for addressing my comments.

> Information about the environment are in the setup file (packages required and versions). Would you suggest to have it somewhere else?

Yes. I am not sure if the following is clear, however please do note that the development requirements are a superset of the package requirements. The former includes packages for tests, coverage, documentation etc., to name a few development requirements. Moreover please note that I can only infer that [`nose`](https://github.com/fjprichard/PyAFBF/search?q=nose) is a development requirement because `setup.cfg` has an entry called [`nosetests`](https://github.com/fjprichard/PyAFBF/search?q=nosetests).

A common heuristic to determine precisely which are the development requirements is to match your environment from scratch, noting which packages you require to run tests, coverage, documentation etc. Commonly this information is included either in a `pip`-compatible `requirements-dev.txt` file, in a `Pipfile`, in a documentation entry addressing contributors, or with the `setuptools` `extras_requires` optional dependencies keyword.

Properly defining development requirements is useful in the open source community to open doors for contributors. As I mentioned, I cannot reproduce your environment as there are no steps on how to do so. Critically, this means I am not able to run your tests. I can verify that your code is sound, but I cannot run your test suite.

**Comment by fjprichard** [comment] 2021-12-08 14:55
Dear Vitor,

Thank you for your explanation. I did some corrections on the package to improve these points:

- I added a requirement directory where I included pip compatible requirement files (defaults and dev). 
- I added a line in the setup for extras_require
- I added a README file in the tests directory to explain how to run the tests with doctest.
- I added a PyAFBF.egg-info directory where such information can also be found.

I hope this will help contributors to reproduce the environment.

Best regards,
Frederic

**Comment by janmandel** [comment] 2021-12-15 04:35
> 👋 @janmandel, please update us on how your review is going (this is an automated reminder).

I am at the stage of checking and unchecking boxes. I did run the software back in October but I missed this issue then, any relevant messages got buried in an avalanche of notifications from this repository. Obvously I found it now and I am back at it! Sorry about that.

**Comment by fjprichard** [comment] 2022-02-04 11:59
Dear @vitorsr ,
I wonder if you received my answers to your comments sent on december, 8th.
Best regards,
Frederic

**Comment by vitorsr** [comment] 2022-02-05 00:11
Dear professor Richard,

Thanks for notifying me for I had not received your answers. I apologize if
this caused any delay. I have now updated the review checklist.

This concludes my review.

My kind regards,

Vítor

**Comment by janmandel** [comment] 2022-02-19 23:42
!pip install PyAFBF
errors out on Google Colab,. To make it work,

!pip install imgaug==0.2.6
!pip install PyAFBF

**Comment by janmandel** [comment] 2022-02-21 04:35
I copied the examples from the documentation to a google colab notebook and they work fine.

**Comment by pibion** [comment] 2022-02-21 18:11
@vitorsr thank you!

**Comment by pibion** [comment] 2022-03-04 18:22
@janmandel just checking in on the open review items in your list.  Has @fjprichard addressed all your issues, or is there more work that needs to be done?

**Comment by fjprichard** [comment] 2022-05-18 14:34
@janmandel I think I answered to all your comments. Is there any left ?

**Comment by janmandel** [comment] 2022-05-26 05:16
It's fine thank you. I had to step away from testing for few weeks but then it was not straightforward to find my way back here resulting in a delay.

**Comment by pibion** [comment] 2022-06-07 15:25
@janmandel thank you for the update!

**Comment by pibion** [comment] 2022-06-07 15:32
@arfon this paper is in a non-standard location , do you have a suggestion for how to proceed?

@fjprichard, @vitorsr pointed out:

> Yes, paper.md seems to be on a separate branch called joss, in a folder of the same name:
> https://github.com/fjprichard/PyAFBF/blob/joss/joss/paper.md

We need the paper to build, so you may need to move `paper.md` so it conforms to the expected location.

**Comment by pibion** [comment] 2022-06-07 15:34
@arfon on the form (https://joss.theoj.org/papers/new) it does look like you can set the branch that contains `paper.md` - can this be done after the paper is submitted?

**Comment by pibion** [comment] 2022-06-07 15:46
@editorialbot generate pdf

**Comment by pibion** [comment] 2022-06-07 22:32
@fjprichard minor suggestions for the paper:

* line 9-10, the sentence that begins, "It enables to set ..." -> "Users can generate a wide variety of textures by setting the simulated model manually or randomly."
* line 10, "It also include tools" -> "It also includes tools"
* line 65, "A documentation" -> "Documentation"

**Comment by fjprichard** [comment] 2022-06-13 14:18
> 

I corrected the doi

**Comment by fjprichard** [comment] 2022-06-13 14:21
> 

I made the corrections.

**Comment by fjprichard** [comment] 2022-06-13 14:23
> point_rightpage_facing_up [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03821/joss.03821/10.21105.joss.03821.pdf) page_facing_up [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03821/joss.03821/10.21105.joss.03821.pdf) page_facing_up point_left

I read the proof. It's fine.

**Comment by fjprichard** [comment] 2022-06-21 05:47
I think the review process is finished. What's next ?

**Comment by pibion** [comment] 2022-06-22 02:00
@editorialbot check references

**Comment by pibion** [comment] 2022-06-22 02:00
@editorialbot generate pdf

**Comment by pibion** [comment] 2022-06-22 02:02
@fjprichard I have a few more notes on minor corrections to the paper - I'm working on those now and will have them up tonight.  Then I'll ask you to do a code release and generate a DOI (zenodo is a popular choice for that) and we'll recommend acceptance.

Apologies for not getting you the complete set of edits earlier, I'm moving this week and things have been hectic!

**Comment by pibion** [comment] 2022-06-22 03:29
- line 16, reasearchs -> reasearchs
- line 19, "Simulations it generates" -> "Its simulations"?
- line 21, "The estimation issues tackled in these works concerned the functional parameters and features of the AFBF and related models. There are still largely open.", it sounds like you're saying there are questions that are still open.  But it's not clear what those questions are.
- line 28, "among which" -> "among which are"
- lines 30, 32, no comma at the end of the list item
- line 33, "None of these package deals directly with" -> "None of these packages deal directly with"
- line 33, maybe omit the "the" in "deals directly with the anisotropic Brownian field"
- line 37, "which both differ from the one of an AFBF", I'm not sure what "the one" refers to.  Perhaps "which both differ from the anisotropy of an AFBF"?
- line 40, "The implementation of random field simulation methods in Python are less manifest" -> "There are fewer implementations of random field simulation methods in Python"?  I'm not exactly sure what you mean by "less manifest" - do you mean they're harder to find, or less developed?
- line 43, "the package AFBF" -> "the package PyAFBF", "PyAFBF" should be bold and not italicized to match the rest of the paper
- lines 44-48 is in the paragraph about Python options, but it feels like a general statement about the usefulness of AFBF simulators.  Consider moving these sentences to line 25?
- equation between lines 51, 52, is a symbol missing in |h, u>|?  Should it be |<h, u>|?
- line 53, "These functions determined" -> "These functions determine"
- line 54, "the aspect of the textures that are sampled from it" -> "the textures that are sampled from it"?
- line 56, "that enable to easily set an AFBF" -> "that enable users to easily set an AFBF"
- line 56, "in a proper way" is intriguing to me but unclear.  Are there typical mistakes or pitfalls people encounter when setting up an AFBF?  Are there a lot of parameters and it's just a pain?  I would recommend either dropping "in a proper way" or making this more specific
- line 59, "This are simulated" -> "AFBF are simulated"?

**Comment by fjprichard** [comment] 2022-06-22 06:39
@pibion Thank you very much for these last valuable corrections. I have modified the text. I'm going to do a code release and set a DOI.

**Comment by fjprichard** [comment] 2022-06-23 06:23
@pibion I created a new release (v0.1.0) for the package including the joss paper. I have a question about the DOI, just to be sure. The DOI is for the new release ?  and not for the paper.

**Comment by fjprichard** [comment] 2022-06-23 07:17
@pibion I created the doi. The badge of the DOI is included in the README file of the new release (v0.1.3). Thank you very much.

**Comment by pibion** [comment] 2022-06-28 23:52
@editorialbot check references

**Comment by pibion** [comment] 2022-06-28 23:53
@editorialbot generate paper

**Comment by pibion** [comment] 2022-06-28 23:53
@editorialbot commands

**Comment by pibion** [comment] 2022-06-28 23:53
@editorialbot generate pdf

**Comment by pibion** [comment] 2022-06-29 01:10
Hi @fjprichard , thank you for your edits!  I have one outstanding minor comment and two more involved comments.  I've tried to suggest text for my involved comments.

Apologies for all the nitpickiness!  I promise this is at least somewhat useful, as it will make the process faster once I recommend your paper for publication.  The JOSS release managers will ask for edits if anything in the paper is unclear.

### A minor comment
line 16, reasearchs -> reasearchs

### PyAFBF supports investigation of open questions about anisotropic fields
The sentences that start on line 19 are still unclear to me.  Currently your paper says:

> Its simulations have been particularly useful to set experimental protocols aiming at assessing performances of estimation methods (citations). The issues tackled in these works concerned the statistical estimation of these functional parameters and features of the AFBF and related models. There are still largely open.

I'm not sure what "functional parameters" refers to.  I also get the sense that you're saying that there are still open questions, but I don't know what those questions are based on your text.  

After reading through some of your cited papers, here's my suggestion.  Is this what you're saying, or am I missing important points?

> Its simulations have been particularly useful for testing estimators designed to identify fields as isotropic or anisotropic (citations).  We still do not have estimators that reliably discriminate isotropic from anisotropic fields for all possible field parameters.

### General to specific in the statement of need

I would recommend moving the following to the very beginning of the "Statement of Need" section as it is the most general information:

> The library is also of interest for researchers in image processing where random fields can serve as texture or noise models for medical images (Biermé et al., 2009; Biermé & Richard, 2011; Richard, 2015, 2016a; Richard & Biermé, 2010) or photographic films (Richard, 2017). This is also of interest for researchers in machine learning where the random field simulation could be included in image generative models such as GAN.

I also have the following suggestions to make it read a little smoother.  Is this missing important points, or oversimplifying?  I think it is worth explicity saying that there is a need for reliable estimators that accurately identify anisotropic fields, this makes it very clear that your library is needed for testing metrics.

> Simulating anisotropic fields is useful both for developing metrics that identify anisotropic fields and for generative methods that need anisotropic fields as input.  Isotropy metrics have applications from medical diagnostics to biometric authentication (Richard, F. J. P. (2016b)).  Anisotropic field samples are needed for  texture or noise models for medical images (Biermé et al., 2009; Biermé & Richard, 2011; Richard, 2015, 2016a; Richard & Biermé, 2010), photographic films (Richard, 2017), and other image-generative applications such as Generative Adversarial Networks.

**Comment by fjprichard** [comment] 2022-07-01 07:44
@pibion Thank you for your valuable comments; there is no problem about continuing improving the text. I rewrite the introduction to take into account your comments. I separated it into two paragraphs: the first one presents generic interests of the package. The second one is more focused on its interest for the evaluation of estimation methods. In this part, I tried to be more specific about the estimation issues. I hope it is "smoother".

**Comment by fjprichard** [comment] 2022-07-01 15:31
@pibion I already merged it but I did not remove it. The change I made this morning were made in the main branch.

**Comment by pibion** [comment] 2022-07-01 15:40
@editorialbot commands

**Comment by pibion** [comment] 2022-07-01 21:22
@editorialbot commands

**Comment by pibion** [comment] 2022-07-01 21:22
@editorialbot set main as branch

**Comment by pibion** [comment] 2022-07-01 21:31
@editorialbot generate pdf

**Comment by pibion** [comment] 2022-07-07 18:18
- line 16, reasearchs -> reasearchs
- line 31, developping -> developing


Simulations of AFBF have been particularly useful to evaluate methods devoted to the estimation of the features derived from the parameters of the AFBF, namely the topothesy and the Hurst functions.  Such features are important to characterize directional properties of the field and describe the image texture anisotropy. They can be use to classify or segment images, and detect image abnormalities. However, issues raised by the statistical estimation of the model parameters and features remain open.

> Simulations of AFBF have been particularly useful to evaluate methods devoted to the estimation of the features derived from the parameters of the AFBF, namely the topothesy and the Hurst functions.  

I want to check that I'm understanding correctly: Are the topothesy and Hurst functions the "methods that estimate the features derived from the parameters of the AFBF," or are they the "features derived from the parameters of the AFBF?"

> Such features are important to characterize directional properties of the field and describe the image texture anisotropy. They can be use to classify or segment images, and detect image abnormalities.

I'm not confident I know what "features" refers to - the topothesy and Hurst functions?  Features of the AFBF like directionality?  Statistically-calculated estimators?  If "features" really means the topothesy and Hurst functions, maybe "Such functions(?) help characterize directional properties of the field and describe the image texture anisotropy."

> They can be use to classify or segment images, and detect image abnormalities. 

This is wonderfully clear, no comments :)

> However, issues raised by the statistical estimation of the model parameters and features remain open.

I don't have any sense of what "issues raised" could be.  I think this would be clearer if you gave a concrete example of an open issue.  Like, "However, we do not have accurate statistical estimators for model parameters and features for many AFBFs."

**Comment by fjprichard** [comment] 2022-07-18 11:19
**line 16, reasearchs -> researchs
    line 31, developping -> developing**

Done.


**I want to check that I'm understanding correctly: Are the topothesy and Hurst functions the "methods that estimate the features derived from the parameters of the AFBF," or are they the "features derived from the parameters of the AFBF?"
I'm not confident I know what "features" refers to - the topothesy and Hurst functions? Features of the AFBF like directionality? Statistically-calculated estimators? If "features" really means the topothesy and Hurst functions, maybe "Such functions(?) help characterize directional properties of the field and describe the image texture anisotropy."**

The topothesy function and Hurst functions are the two parameters of the field (they are defined after the first equation). We can define features 


      
**However, issues raised by the statistical estimation of the model parameters and features remain open.
I don't have any sense of what "issues raised" could be. I think this would be clearer if you gave a concrete example of an issue. Like, "However, we do not have accurate statistical estimators for model parameters and features for many AFBFs."**

I modified the text to be more specific.

**Comment by pibion** [comment] 2022-07-18 22:53
@editorialbot generate pdf

**Comment by pibion** [comment] 2022-07-18 22:56
@editorialbot generate pdf

**Comment by pibion** [comment] 2022-07-18 23:06
@fjprichard this version is very clear, thank you!  My only comment is that on line 16 I think that "researchs" should be "research".

Once you've made that change, make a tagged release and archive, and report the version number and archive DOI in this thread.  Then I'll follow the steps at https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance, which end in recommending acceptance!

We're almost there!

**Comment by fjprichard** [comment] 2022-07-19 07:43
Release TAG: v0.1.5
DOI: 10.5281/zenodo.6860333

**Comment by pibion** [comment] 2022-07-19 13:25
@editorialbot generate pdf

**Comment by pibion** [comment] 2022-07-19 13:48
@editorialbot set 10.5281/zenodo.6860333 as archive

**Comment by pibion** [comment] 2022-07-19 13:49
@editorialbot set v0.1.5 as version

**Comment by pibion** [comment] 2022-07-19 13:49
@editorialbot recommend-accept

**Comment by fjprichard** [comment] 2022-07-19 14:37
@editorialbot accept

**Comment by arfon** [comment] 2022-07-19 20:48
@editorialbot accept

**Comment by arfon** [comment] 2022-07-19 20:56
@vitorsr, @janmandel – many thanks for your reviews here and to @pibion for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@fjprichard – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Closed by arfon** 2022-07-19 20:56 UTC
Labels: accepted, review, Python, recommend-accept, published

**Comment by arfon** [comment] 2022-07-20 08:43
@editorialbot re-accept

**Comment by arfon** [comment] 2022-07-20 08:44
@editorialbot reaccept
