### ISSUE TITLE
[PRE REVIEW]: AliasFinder: A Python script to search for the true planetary frequency within radial velocity data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1767] opened 2019-09-26 16:06 UTC
**Submitting author:** @StephanStock (<a href="http://orcid.org/0000-0002-1166-9338">Stephan Stock</a>)
**Repository:** <a href="https://github.com/JonasKemmer/AliasFinder" target ="_blank">https://github.com/JonasKemmer/AliasFinder</a>
**Version:** v1.0.0
**Editor:** @xuanxu
**Reviewers:** @Juanlu001, @wtgee

**Author instructions**

Thanks for submitting your paper to JOSS @StephanStock. **Currently, there isn't an JOSS editor assigned** to your paper.

@StephanStock if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-09-26 16:06
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-09-26 16:06
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-09-26 16:07
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01767/joss.01767/10.21105.joss.01767.pdf)

**Comment by arfon** [comment] 2019-09-26 16:07
@StephanStock - this looks to be a duplicate of https://github.com/openjournals/joss-reviews/issues/1724 which was rejected as being out of scope. Could you clarify why there has been a resubmission?

/ cc @danielskatz

**Comment by StephanStock** [comment] 2019-09-26 16:13
Hello, 
as requested in #1724 we implemented the pip install for our software which was the reason why it was rejected. It is now  'designed for maintainable extension'.

/cc @JonasKemmer @xuanxu

**Comment by danielskatz** [comment] 2019-09-26 20:26
👋 @xuanxu - can I ask you to take the lead on making sure this is now suitable, and if so, editing it?

**Comment by xuanxu** [comment] 2019-09-27 08:53
@danielskatz yes, I'll edit it.

**Comment by xuanxu** [comment] 2019-09-27 08:53
I think in its current form it qualifies as a maintainable research software, so I'm moving this forward

**Comment by xuanxu** [comment] 2019-09-27 08:55
:wave: @Juanlu001:  Are you still willing to review this paper? It is an improved resubmission of #1724

**Comment by xuanxu** [comment] 2019-09-27 09:00
@whedon assign @xuanxu as editor

**Comment by whedon** [comment] 2019-09-27 09:00
OK, the editor is @xuanxu

**Comment by Juanlu001** [comment] 2019-09-27 09:12
Excellent! @xuanxu I will gladly review

**Comment by xuanxu** [comment] 2019-09-27 09:34
@Juanlu001 great!, I'll start the review issue once I find the second reviewer, stay tuned!

**Comment by xuanxu** [comment] 2019-09-27 09:43
:wave: @ygrange - would you be willing to review this submission for JOSS? I think your knowledge of Python and Astronomy makes you a good fit for this submission.

**Comment by StephanStock** [comment] 2019-09-27 11:17
As a potential reviewer we also suggest @nespinoza who also works with Exoplanets

**Comment by ygrange** [comment] 2019-09-27 11:48
Well, I am pretty busy the coming two weeks at least, so maybe it would be wise to have another reviewer. 
If there is no second reviewer and you are willing to wait a few weeks, I can do it though.

**Comment by xuanxu** [comment] 2019-09-27 12:11
@ygrange: ok, thanks!, let's see if I can find another reviewer

**Comment by xuanxu** [comment] 2019-09-27 12:12
:wave: @wtgee - would you be willing to review this submission for JOSS? I think your knowledge of Python and Exoplanets makes you a great fit for this submission.

**Comment by wtgee** [comment] 2019-09-28 02:46
@xuanxu yes, I have some time to do this. And I like the potential pun on 'fit'. :)

**Comment by xuanxu** [comment] 2019-09-28 10:12
@wtgee great, thanks!

**Comment by xuanxu** [comment] 2019-09-28 10:12
@whedon add @Juanlu001 as reviewer

**Comment by whedon** [comment] 2019-09-28 10:12
OK, @Juanlu001 is now a reviewer

**Comment by xuanxu** [comment] 2019-09-28 10:13
@whedon add @wtgee as reviewer

**Comment by whedon** [comment] 2019-09-28 10:13
OK, @wtgee is now a reviewer

**Comment by xuanxu** [comment] 2019-09-28 10:14
@whedon start review

**Comment by whedon** [comment] 2019-09-28 10:14
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1771. Feel free to close this issue now!

**Comment by xuanxu** [comment] 2019-09-28 10:14
@Juanlu001, @wtgee - please head over to #1771 where the review will take place.

**Closed** 2019-09-28 10:14 UTC
Labels: Python, TeX, pre-review
