### ISSUE TITLE
[REVIEW]: PyMPDATA v1: Numba-accelerated Pythonic implementation of MPDATA with examples in Python, Julia and Matlab

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3896] opened 2021-11-07 07:03 UTC
**Submitting author:** @slayoo (<a href="http://orcid.org/0000-0003-2361-0082">Sylwester Arabas</a>)
**Repository:** https://github.com/atmos-cloud-sim-uj/PyMPDATA
**Branch with paper.md** (empty if default branch): 
**Version:** v1
**Editor:** @arfon
**Reviewers:** @Chiil, @wdeconinck
**Archive:** 10.5281/zenodo.6934418

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a/status.svg)](https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a"><img src="https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a/status.svg)](https://joss.theoj.org/papers/10e7361e43785dbb1b3d659c5b01757a)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/atmos-cloud-sim-uj/PyMPDATA" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@dmikushin & @olekravchenko, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @mjsottile know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨

**Comment by whedon** [comment] 2021-11-07 07:03
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @dmikushin, @olekravchenko it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-11-07 07:03
PDF failed to compile for issue #3896 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment] 2021-11-07 07:03
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.11 s (659.4 files/s, 49581.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          60            586            375           3462
Markdown                         1             93              0            527
YAML                            10             33              6            257
-------------------------------------------------------------------------------
SUM:                            71            712            381           4246
-------------------------------------------------------------------------------


Statistical information for the repository '8066b4e37f38bca61302e6b0' was
gathered on 2021/11/07.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Maciej Manna                     9           196            263            1.06
Michael                         93          1687           1332            6.97
Michaeldz36                     38          3704           1752           12.60
Sylwester Arabas               334         14308           9780           55.61
kruci-no                         2            22              4            0.06
piotrbartman                     1            37           1207            2.87
prbartman                       42          3780           5245           20.83

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Michael                     109            6.5         17.4               10.09
Sylwester Arabas           4095           28.6          5.4                8.03
kruci-no                      4           18.2         14.6                0.00
piotrbartman                215          581.1         17.5                2.33
```

**Comment by mjsottile** [comment] 2021-11-07 07:04
@whedon generate pdf from branch JOSS

**Comment by whedon** [comment] 2021-11-07 07:04
```
Attempting PDF compilation from custom branch JOSS. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-11-07 07:04
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03896/joss.03896/10.21105.joss.03896.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03896/joss.03896/10.21105.joss.03896.pdf) :page_facing_up: :point_left:

**Comment by mjsottile** [comment] 2021-11-07 07:05
@whedon check references

**Comment by mjsottile** [comment] 2021-11-07 22:22
@whedon check references from branch JOSS

**Comment by whedon** [comment] 2021-11-07 22:22
```
Attempting to check references... from custom branch JOSS
```

**Comment by whedon** [comment] 2021-11-07 22:22
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/1520-0493(1983)111<0479:ASPDAS>2.0.CO;2 is OK
- 10.1016/0021-9991(84)90121-9 is OK
- 10.1016/0021-9991(86)90270-6  is OK
- 10.1016/0021-9991(90)90105-A is OK
- 10.1175/1520-0493(1993)121<1847:OFITDF>2.0.CO;2 is OK
- 10.1201/9780203711194 is OK
- 10.1006/jcph.1998.5901 is OK
- 10.1137/S106482759324700X is OK
- 10.1016/j.jcp.2004.12.021 is OK
- 10.1002/fld.1070 is OK
- doi:10.1002/fld.1071 is OK
- 10.1002/qj.1913 is OK
- 10.3233/SPR-140379 is OK
- 10.1016/j.jcp.2015.02.003 is OK
- 10.5194/gmd-8-1005-2015 is OK
- 10.1007/978-3-319-93864-6_5 is OK
- 10.5194/gmd-12-651-2019 is OK
- 10.1016/j.cam.2019.05.023 is OK
- 10.5194/gmd-2020-404 is OK

MISSING DOIs

- None

INVALID DOIs

- 10.1175/1520-0450(1968)007%3C0160:AOFDMA%3E2.0.CO;2 is INVALID
- 10.1175/1520-0493(1989)117%3C0102:TDSLTW%3E2.0.CO;2 is INVALID
```

**Comment by slayoo** [comment] 2021-11-07 23:29
it's puzzling as the above "INVALID DOIs" seem correct, at leat both of the below URLs redirect correctly to the journal site:
- https://doi.org/10.1175/1520-0450(1968)007%3C0160:AOFDMA%3E2.0.CO;2
- https://doi.org/10.1175/1520-0493(1989)117%3C0102:TDSLTW%3E2.0.CO;2

**Comment by danielskatz** [comment] 2021-11-07 23:35
Please make sure the DOIs are in doi entries in the bib file rather than url entries, and that they don't include the https://doi.org part

**Comment by danielskatz** [comment] 2021-11-07 23:37
And perhaps change the characters that are being encoded for example: 

10.1175/1520-0493(1989)117<0102:TDSLTW>2.0.CO;2

**Comment by slayoo** [comment] 2021-11-08 05:35
@whedon check references from branch JOSS

**Comment by whedon** [comment] 2021-11-08 05:35
```
Attempting to check references... from custom branch JOSS
```

**Comment by whedon** [comment] 2021-11-08 05:35
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1175/1520-0450(1968)007<0160:AOFDMA>2.0.CO;2 is OK
- 10.1175/1520-0493(1983)111<0479:ASPDAS>2.0.CO;2 is OK
- 10.1016/0021-9991(84)90121-9 is OK
- 10.1016/0021-9991(86)90270-6  is OK
- 10.1175/1520-0493(1989)117<0102:TDSLTW>2.0.CO;2 is OK
- 10.1016/0021-9991(90)90105-A is OK
- 10.1175/1520-0493(1993)121<1847:OFITDF>2.0.CO;2 is OK
- 10.1201/9780203711194 is OK
- 10.1006/jcph.1998.5901 is OK
- 10.1137/S106482759324700X is OK
- 10.1016/j.jcp.2004.12.021 is OK
- 10.1002/fld.1070 is OK
- doi:10.1002/fld.1071 is OK
- 10.1002/qj.1913 is OK
- 10.3233/SPR-140379 is OK
- 10.1016/j.jcp.2015.02.003 is OK
- 10.5194/gmd-8-1005-2015 is OK
- 10.1007/978-3-319-93864-6_5 is OK
- 10.5194/gmd-12-651-2019 is OK
- 10.1016/j.cam.2019.05.023 is OK
- 10.5194/gmd-2020-404 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by slayoo** [comment] 2021-11-08 05:36
thank you @danielskatz, indeed the URL escapes in the bib file were the cause - good job on the checker side!

**Comment by whedon** [comment] 2021-11-21 07:03
:wave: @dmikushin, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment] 2021-11-21 07:03
:wave: @olekravchenko, please update us on how your review is going (this is an automated reminder).

**Comment by mjsottile** [comment] 2021-12-03 02:08
Hello @dmikushin and @olekravchenko - I was wondering if you needed anything in starting the reviews?  I noticed that there hasn't been activity since the review was initiated.  I'm happy to help or answer questions in getting started.

**Comment by mjsottile** [comment] 2021-12-09 10:42
Hi @slayoo : it appears that the reviewers who agreed to review have vanished and are unresponsive (unless you’ve heard from them outside this review thread).  This unfortunately happens sometimes.  I will identify alternative reviewers to replace them so the review doesn’t go idle.  Give me a day or so to find people to take their place.

**Comment by slayoo** [comment] 2021-12-09 15:27
Thank you, @mjsottile. (I haven't heard from the reviewers)

**Comment by mjsottile** [comment] 2021-12-10 03:24
:wave: @d-chambers Would you be willing to perform a review for this submission to the Journal of Open Source Software?  I identified you based on your areas of expertise as listed on the spreadsheet of potential JOSS reviewers.  Please let me know if you would be interested.  Thank you!

**Comment by mjsottile** [comment] 2021-12-10 03:26
👋 @highlando Would you be willing to perform a review for this submission to the Journal of Open Source Software? I identified you based on your areas of expertise as listed on the spreadsheet of potential JOSS reviewers. Please let me know if you would be interested. Thank you!

**Comment by d-chambers** [comment] 2021-12-12 22:12
Hi @mjsottile, unfortunately this is pretty far outside of my area of expertise. So much so, I don't think I would be able to provide any sort of useful review of the functionality of the software (but it does look like an interesting program).

**Comment by dmikushin** [comment] 2021-12-31 22:21
Hi @slayoo , is there a performance comparison between Numba-based PyMPDATA and any other native code implementations of your choice? That would be really interesting to see!

**Comment by slayoo** [comment] 2022-01-03 00:51
@dmikushin Thanks for feedback. Very good point on including a performance comparison with other implementations,

We have so far:
- looked at wall times for these tests which have direct counterparts in libmpdata++ (Github Actions used in both projects - times on similar virtual machines are available for each CI build, but these include compilation times in the case of PyMPDATA, hence not straightforward to analyse "as is", but that would be the first candidate to start the analysis from);
- analysed execution times of various MPDATA varians versus upwind times for PyMPDATA and corroborated it with such wall-time ratios from literature, see Table 2 here: https://arxiv.org/pdf/2011.14726.pdf

Comparing with libmpdata++ times is certainly doable (February/March?).
Any other suggestion on what to compare with?

**Comment by highlando** [comment] 2022-01-03 20:10
> wave @highlando Would you be willing to perform a review for this submission to the Journal of Open Source Software? I identified you based on your areas of expertise as listed on the spreadsheet of potential JOSS reviewers. Please let me know if you would be interested. Thank you!

Sorry for my late reply. This is not exactly my area of expertise and I'm well occupied with other reviews right now. So I would prefer to skip this one. Please let me know, if there is an urgent need for a comment. :)

**Comment by mjsottile** [comment] 2022-01-12 23:55
@dmikushin Thanks for providing some feedback about this submission.  Did you have a chance to look at over entries from the review checklist at the top of this issue?

**Comment by mjsottile** [comment] 2022-01-12 23:56
> > wave @highlando Would you be willing to perform a review for this submission to the Journal of Open Source Software? I identified you based on your areas of expertise as listed on the spreadsheet of potential JOSS reviewers. Please let me know if you would be interested. Thank you!
> 
> Sorry for my late reply. This is not exactly my area of expertise and I'm well occupied with other reviews right now. So I would prefer to skip this one. Please let me know, if there is an urgent need for a comment. :)

@highlando No problem.  Thanks for responding!

**Comment by mjsottile** [comment] 2022-01-24 02:24
:wave: @slayoo Hello again.  I promise I haven't forgotten about your submission.  I have been reaching out to potential reviewers via email since contacting people via GitHub has proven to be ineffective for some reason.  I really hope I can get this review kickstarted again soon with responsive reviewers.  Thanks for your patience.

**Comment by arfon** [comment] 2022-02-10 10:30
@whedon assign me as editor

**Comment by arfon** [comment] 2022-02-10 10:58
Hi all, I'm going to take over here as editor and help @mjsottile out a little. 

@dmikushin, @olekravchenko – are you still able to review this submission for JOSS? If not, I will proceed to identify new reviewer candidates.

**Comment by arfon** [comment] 2022-02-10 11:51
@whedon re-invite @dmikushin as reviewer

**Comment by whedon** [comment] 2022-02-10 11:52
@dmikushin already has access.

**Comment by slayoo** [comment] 2022-02-11 07:11
thank you, @arfon; thank you, @mjsottile

**Comment by arfon** [comment] 2022-02-18 20:27
Just a quick update. I've heard back from @dmikushin that they're still planning on providing a review here but am yet to hear back from @olekravchenko that they are able to complete their review/

@slayoo – it might be a good idea for me to start looking for some additional reviewers here. Do you have any suggestions?

**Comment by arfon** [comment] 2022-02-28 09:49
:wave: @Chiil and @wdeconinck – would either of you be willing to review this submission for JOSS? The submission under consideration is [_PyMPDATA v1: Numba-accelerated Pythonic implementation of MPDATA with examples in Python, Julia and Matlab_](https://github.com/atmos-cloud-sim-uj/PyMPDATA).

**Comment by Chiil** [comment] 2022-02-28 09:52
Sure, I can review it.

**Comment by arfon** [comment] 2022-02-28 10:01
> Sure, I can review it.

Amazing, thank you! You can generate a review checklist by typing the following which will make you a checklist to work through:

```
@editorialbot generate my checklist
```
 
Our reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html.

**Comment by arfon** [comment] 2022-02-28 10:01
@editorialbot add @Chiil as reviewer

**Comment by wdeconinck** [comment] 2022-02-28 11:45
I am happy to review as well.

**Comment by arfon** [comment] 2022-02-28 11:52
> I am happy to review as well.

Thank you very much @wdeconinck! You can generate a review checklist by typing the following which will make you a checklist to work through:

```
@editorialbot generate my checklist
```
 
Our reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html.

**Comment by arfon** [comment] 2022-02-28 11:52
@editorialbot add @wdeconinck as reviewer

**Comment by slayoo** [comment] 2022-02-28 17:37
Thank you, @arfon, @Chiil, @wdeconinck

**Comment by arfon** [comment] 2022-03-13 19:42
@Chiil, @wdeconinckm – how are you getting on here? Do you think you might be able to complete your review in the next couple of weeks?

**Comment by Chiil** [comment] 2022-03-13 21:04
Yup, will do.

**Comment by wdeconinck** [comment] 2022-03-14 10:14
Certainly, thanks for the reminder :)

**Comment by slayoo** [comment] 2022-03-14 20:56
Thank you, @arfon, @Chiil, @wdeconinck

**Comment by arfon** [comment] 2022-04-07 07:35
:wave: @wdeconinck @Chiil – it's now been ~3 weeks since we were last in touch here. Can I have an update from you both on the status of your reviews?

**Comment by wdeconinck** [comment] 2022-04-07 15:22
@editorialbot generate my checklist

**Comment by Chiil** [comment] 2022-04-09 11:48
@editorialbot generate my checklist

**Comment by slayoo** [comment] 2022-04-18 19:38
@editorialbot check references

**Comment by slayoo** [comment] 2022-04-18 19:40
@arfon the check-references behaviour has apparently changed recently wrt handling of "<" and ">" characters in the DOIs - the above four invalid DOIs were not indicated as invalid up above: https://github.com/openjournals/joss-reviews/issues/3896#issuecomment-962827845
Was it intentional? Thanks,
Sylwester

**Comment by slayoo** [comment] 2022-04-23 17:49
Thank you @wdeconinck for the feedback!
Our plan is to add to the paper an analysis comparing libmpdata++ and PyMPDATA execution times for 1-2 examples that are already implemented in both packages. For both packages, we will check how the time scales with the number of threads, and for PyMPDATA we will report times with Numba enabled and without JIT. Please stay tuned for an update.

**Comment by arfon** [comment] 2022-04-24 14:06
> @arfon the check-references behaviour has apparently changed recently wrt handling of "<" and ">" characters in the DOIs - the above four invalid DOIs were not indicated as invalid up above: https://github.com/openjournals/joss-reviews/issues/3896#issuecomment-962827845
Was it intentional? Thanks,

I think we can just ignore this. Thanks for checking @slayoo.

**Comment by Chiil** [comment] 2022-05-05 08:28
Sorry for the slow action, but I wanted to complete my review today, but have I been removed due to the delay? I cannot find back my checklist.

**Comment by Chiil** [comment] 2022-05-05 08:36
The software is awesome and installs well out of the box and the Jupyter notebook examples work well. I do get a lot of deprecation warnings though in some of the examples. For instance the `advection_diffusion_1d` notebook give me a lot of warnings like 
```
/var/folders/4f/nykt4nhx4kn12sz633_msth40000gn/T/ipykernel_45402/528486334.py:52: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  steps = np.arange(nt + 1, dtype=np.int).reshape(-1, 1) * steps_per_iter
  ```

**Comment by Chiil** [comment] 2022-05-05 09:02
I have tested all examples, and the only one that did not work (and I hope the problem is not on my Julia installation side) is the Julia one. I have tested the code from the Appendix of `paper.md` and got: 
```
julia> using PyCall

julia> Options = pyimport("PyMPDATA").Options
Assertion failed: (findOption(Name) == Values.size() && "Option already exists!"), function addLiteralOption, file /Users/ci/miniconda3/conda-bld/llvmdev_1601977477900/work/include/llvm/Support/CommandLine.h, line 853.

signal (6): Abort trap: 6
in expression starting at REPL[2]:1
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
pthread_kill at /usr/lib/system/libsystem_pthread.dylib (unknown line)
abort at /usr/lib/system/libsystem_c.dylib (unknown line)
__assert_rtn at /usr/lib/system/libsystem_c.dylib (unknown line)
_ZN4llvm2cl6parserIPFPNS_12FunctionPassEvEE16addLiteralOptionIS5_EEvNS_9StringRefERKT_S8_ at /usr/local/lib/python3.9/site-packages/llvmlite/binding/libllvmlite.dylib (unknown line)
_ZN4llvm2cl3optIPFPNS_12FunctionPassEvELb0ENS_18RegisterPassParserINS_16RegisterRegAllocEEEEC2IJA9_cNS0_12OptionHiddenENS0_11initializerIS5_EENS0_4descEEEEDpRKT_ at /usr/local/lib/python3.9/site-packages/llvmlite/binding/libllvmlite.dylib (unknown line)
_GLOBAL__sub_I_TargetPassConfig.cpp at /usr/local/lib/python3.9/site-packages/llvmlite/binding/libllvmlite.dylib (unknown line)
Allocations: 716693 (Pool: 716197; Big: 496); GC: 1
Abort trap: 6
```

**Comment by Chiil** [comment] 2022-05-05 09:05
Furthermore, I have not checked the "State of the field" box, because the paper does not contain a comparison against other packages that can solve advection diffusion equations. It does show a nice overview though in the `README.md` of other packages that can do the same. A small comparison highlighting the benefits of PyMPDATA could improve the paper.

**Comment by Chiil** [comment] 2022-05-05 09:07
And for curiousity, what are the prospect of running this package on GPUs, given that `numba` is also improving its GPU support.

**Comment by Chiil** [comment] 2022-05-05 09:08
Let me close by apologize for the long time it took me to review the material. It is a great piece of work and I am sorry for the delay in publication.

**Comment by arfon** [comment] 2022-05-07 08:02
@Chiil - it looks like you don't have a review checklist here. You can create one for yourself with the command `@editorialbot generate my checklist`

**Comment by Chiil** [comment] 2022-05-07 08:36
There is one, I checked all boxes except one.

**Comment by arfon** [comment] 2022-05-08 18:58
> There is one, I checked all boxes except one.

Sorry, missed that!

**Comment by arfon** [comment] 2022-06-06 08:21
Looks like we've essentially got two complete reviews here from @Chiil & @wdeconinck at this point. @slayoo – are you still working on any updates based on reviewer feedback at this point?

**Comment by arfon** [comment] 2022-06-06 08:22
@editorialbot remove @olekravchenko as reviewer

**Comment by arfon** [comment] 2022-06-06 08:22
@editorialbot remove @dmikushin as reviewer

**Comment by slayoo** [comment] 2022-07-01 09:48
> I have tested all examples, and the only one that did not work (and I hope the problem is not on my Julia installation side) is the Julia one. I have tested the code from the Appendix of `paper.md` and got:
> 
> ```
> julia> using PyCall
> 
> julia> Options = pyimport("PyMPDATA").Options
> Assertion failed: (findOption(Name) == Values.size() && "Option already exists!"), function addLiteralOption, file /Users/ci/miniconda3/conda-bld/llvmdev_1601977477900/work/include/llvm/Support/CommandLine.h, line 853.
> 
> signal (6): Abort trap: 6
> in expression starting at REPL[2]:1
> __pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
> pthread_kill at /usr/lib/system/libsystem_pthread.dylib (unknown line)
> abort at /usr/lib/system/libsystem_c.dylib (unknown line)
> __assert_rtn at /usr/lib/system/libsystem_c.dylib (unknown line)
> _ZN4llvm2cl6parserIPFPNS_12FunctionPassEvEE16addLiteralOptionIS5_EEvNS_9StringRefERKT_S8_ at /usr/local/lib/python3.9/site-packages/llvmlite/binding/libllvmlite.dylib (unknown line)
> _ZN4llvm2cl3optIPFPNS_12FunctionPassEvELb0ENS_18RegisterPassParserINS_16RegisterRegAllocEEEEC2IJA9_cNS0_12OptionHiddenENS0_11initializerIS5_EENS0_4descEEEEDpRKT_ at /usr/local/lib/python3.9/site-packages/llvmlite/binding/libllvmlite.dylib (unknown line)
> _GLOBAL__sub_I_TargetPassConfig.cpp at /usr/local/lib/python3.9/site-packages/llvmlite/binding/libllvmlite.dylib (unknown line)
> Allocations: 716693 (Pool: 716197; Big: 496); GC: 1
> Abort trap: 6
> ```

IIUC, this seem to be a problem with Julia and Numba being linked to different versions of LLVM. There is little we can do at the level of PyMPDATA. The problem has been reported in numerous places, with no solution provided in most cases besides just upgrading/downgrading packages (on Github Actions, we do test the Julia code snippet on each merge to main, and there is no trouble on `ubuntu-latest`):
- https://github.com/JuliaPy/PyCall.jl/issues/861
- https://github.com/JuliaPy/PyCall.jl/issues/976
- https://github.com/e2nIEE/pandapower/issues/1217
- https://github.com/JuliaPy/pyjulia/issues/443
- https://github.com/JuliaPy/PyCall.jl/issues/903

**Comment by slayoo** [comment] 2022-07-01 09:51
> I do get a lot of deprecation warnings though in some of the examples. For instance the `advection_diffusion_1d` notebook give me a lot of warnings like
> 
> ```
> /var/folders/4f/nykt4nhx4kn12sz633_msth40000gn/T/ipykernel_45402/528486334.py:52: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
> Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
>   steps = np.arange(nt + 1, dtype=np.int).reshape(-1, 1) * steps_per_iter
> ```

Fixed here: https://github.com/atmos-cloud-sim-uj/PyMPDATA-examples/commit/763c004a890088ea662fe591ced5e8feaad5df19

**Comment by slayoo** [comment] 2022-07-05 09:12
Just a quick update regarding the performance analysis. We are done with JIT enabled vs. disabled + threading analysis, still working on comparison with libmpdata++. Here's a draft of the figure based on a 3D advection-only example from Smolarkiewicz 1984, and depicting that:
- disabling Numba JIT causes an over 1000-fold slowdown in PyMPDATA; 
- there is reasonable speedup measurable from using multiple threads in PyMPDATA;
- switching from dynamic grid (grid size decided at runtime) vs. static grid (grid size decided at compile time) gives noticeable and consistent speedup, although hardly striking when compared with the JIT-disabled timings on one plot. 
![image](https://user-images.githubusercontent.com/89685/177293196-22cd3e60-eb09-4886-82ad-ac87745944b5.png)

Please stay tuned a few days more for addition of libmpdata++ datapoints to the figure and for a PR merging the notebook covering this analysis into the PyMPDATA-examples repo, and a relevant additions to the JOSS manuscript.

**Comment by wdeconinck** [comment] 2022-07-05 09:42
That is very nice. I guess if you want to make the point of comparing the three PyMPDATA results, you would create a second picture with zoomed vertical axis.

**Comment by slayoo** [comment] 2022-07-12 22:36
Here's an updated plot with libmpdata++ timings added, and with the JIT-disabled timing shown in a separate subplot. It shows that, in this particular case (3D problem, 32x32x32 grid, 3 MPDATA iterations), PyMPDATA performs a even better than libmpdata++, and over 1000-times faster than with Numba JIT disabled.
![Screenshot from 2022-07-13 00-24-07](https://user-images.githubusercontent.com/89685/178606739-793fdb3f-21ae-4703-aa72-56a06a01bcdb.png)

Wall-times taken as minimal values over 5 repetitions ensuring that JIT-compilation times, thread scheduling or similar effects are filtered out.

A notebook orchestrating the analysis and plot generation plus C++ code for libmpdata++ timing is on its way to PyMPDATA-examples repo: https://github.com/atmos-cloud-sim-uj/PyMPDATA-examples/pull/64

paper text update coming very soon

**Comment by slayoo** [comment] 2022-07-13 22:41
@editorialbot generate pdf

**Comment by slayoo** [comment] 2022-07-13 22:47
@wdeconinck @Chiil, in the above updated pdf, the manuscript is extended with a 1.5-page long "Performance" section. There are two new plots composed into Fig. 2 which present analysis of scaling with the number of threads and scaling with the domain size. The plots include wall-time measurements for PyMPDATA with Numba JIT disabled and enabled, as well as measurements for libmpdata++. Comments welcome, thanks.

**Comment by wdeconinck** [comment] 2022-07-18 13:57
@slayoo That looks great, it shows off very nicely to be on par with the classic HPC languages or even better, with the added benefits of Python.
One typo in line 130: built-in instead of build-in.

**Comment by slayoo** [comment] 2022-07-29 05:44
Thank you, @wdeconinck.
Typo fixed in https://github.com/atmos-cloud-sim-uj/PyMPDATA/commit/3ba899ecfbd2f99d1426e534585fba57e532eaea
The performance-analysis notebook is now merged (https://github.com/atmos-cloud-sim-uj/PyMPDATA-examples/pull/64) and is executed as a part of CI including compilation, execution and timing of libmpdata++ code (but only on Linux).
New v1.0.3 package version also released and on its way to PyPI.org.

@wdeconinck, @Chiil, please confirm, by marking relevant checkboxes in the reviewers' checklist, if the added material comparing performance with libmpdata++ is sufficient? Thank you

**Comment by arfon** [comment] 2022-08-12 21:58
> @wdeconinck, @Chiil, please confirm, by marking relevant checkboxes in the reviewers' checklist, if the added material comparing performance with libmpdata++ is sufficient? Thank you

Yes, please let us know if you're satisfied with these changes.

**Comment by slayoo** [comment] 2022-08-29 07:10
@Chiil (CC: @arfon), please let us know if the added section with performance comparison against libmpdata++ is be enough to pass the missing checkbox item in your review?

Your checklist is here:
https://github.com/openjournals/joss-reviews/issues/3896#issuecomment-1093951893

(with the missing checkbox here:
![image](https://user-images.githubusercontent.com/89685/187143227-c68b9c6e-0001-404d-909d-56c061c36340.png)
)

The added section is in the most recent pdf preview:
https://raw.githubusercontent.com/openjournals/joss-papers/joss.03896/joss.03896/10.21105.joss.03896.pdf

Thanks!

**Comment by Chiil** [comment] 2022-08-29 08:06
The improvements are excellent. Sorry for the slow reply, I just returned from holidays.

**Comment by arfon** [comment] 2022-08-29 08:48
@slayoo – At this point could you make a new release of this software that includes the changes that have resulted from this review. Then, please make an archive of the software in Zenodo/figshare/other service and update this thread with the DOI of the archive? For the Zenodo/figshare archive, please make sure that:

- The title of the archive is the same as the JOSS paper title
- That the authors of the archive are the same as the JOSS paper authors

I can then move forward with accepting the submission.

**Comment by slayoo** [comment] 2022-08-29 10:34
Thank you, @Chiil!
Thank you, @arfon!
Here's the Zenodo url with updated metadata: https://zenodo.org/record/6934418

**Comment by slayoo** [comment] 2022-08-29 10:34
(and the DOI is https://doi.org/10.5281/zenodo.6934418)

**Comment by arfon** [comment] 2022-09-04 07:20
@editorialbot set 10.5281/zenodo.6934418 as archive

**Comment by arfon** [comment] 2022-09-04 07:20
@editorialbot recommend-accept

**Comment by arfon** [comment] 2022-09-04 07:26
@slayoo – this line in your BibTeX is tripping up the XML validation: https://github.com/atmos-cloud-sim-uj/PyMPDATA/blob/main/paper/paper.bib#L220

Could you change it to be a valid preprint BibTeX entry?

**Comment by slayoo** [comment] 2022-09-04 16:16
@arfon, fixed here: https://github.com/atmos-cloud-sim-uj/PyMPDATA/commit/1ad49aad3dcac7ec299637005f143ad363d6c7b6
Thank you!

**Comment by slayoo** [comment] 2022-09-04 16:16
@whedon check references from branch main

**Comment by slayoo** [comment] 2022-09-04 16:17
@editorialbot check references from branch main

**Comment by slayoo** [comment] 2022-09-04 16:17
@editorialbot generate pdf

**Comment by slayoo** [comment] 2022-09-04 17:49
@editorialbot generate pdf

**Comment by arfon** [comment] 2022-09-05 09:43
@editorialbot recommend-accept

**Comment by arfon** [comment] 2022-09-05 09:51
@slayoo – can you merge this PR please? It fixes a few minor formatting issues: https://github.com/atmos-cloud-sim-uj/PyMPDATA/pull/337

**Comment by slayoo** [comment] 2022-09-05 09:53
Merged, thank you, @arfon!

**Comment by arfon** [comment] 2022-09-05 10:39
@editorialbot recommend-accept

**Comment by arfon** [comment] 2022-09-05 10:43
@editorialbot accept

**Comment by slayoo** [comment] 2022-09-05 10:56
@arfon Thank you!
Unfortunately, we have an issue with a non-breaking space in the title that is wrongly displayed on the JOSS website here:
![image](https://user-images.githubusercontent.com/89685/188433194-a3b895ed-f181-4f4f-a2cd-8c37406a74a8.png)

**Comment by arfon** [comment] 2022-09-05 11:11
Can you remove the &nbsp; from the title text please and I'll reprocess.

**Comment by arfon** [comment] 2022-09-05 11:21
@slayoo fixed in https://github.com/atmos-cloud-sim-uj/PyMPDATA/pull/338

**Comment by slayoo** [comment] 2022-09-05 11:47
Merged, thank you, @arfon!

**Comment by slayoo** [comment] 2022-09-05 11:48
BTW, we have an analogous problem in https://github.com/openjournals/joss-reviews/issues/4326

**Comment by arfon** [comment] 2022-09-05 12:15
@editorialbot reaccept

**Comment by arfon** [comment] 2022-09-05 12:18
OK, this should be fixed now.

**Closed by arfon** 2022-09-05 12:18 UTC
Labels: accepted, review, Python, recommend-accept, published, Track: 3 (PE)

**Comment by slayoo** [comment] 2022-09-05 13:43
Thank you, @arfon !

**Comment by slayoo** [comment] 2022-09-06 07:37
@arfon I've noticed that there were three more nbsps in the author list that also go through into the paper metadata and JOSS website:

![image](https://user-images.githubusercontent.com/89685/188574978-f60daccc-31cd-4a70-89fa-81ed74eb025b.png)


Just removed it in the repo: https://github.com/atmos-cloud-sim-uj/PyMPDATA/commit/a35a159232f2021f31eab07bdc5178c534c2c848

Let me ask for one more regeneration of the metadata.
Thank you!
Sylwester

**Comment by slayoo** [comment] 2022-09-09 13:15
@arfon, please let us know if it would be possible to fix the remaining nbsp problems in the author list (already fixed in the project  repo) - see above, thanks, Sylwester

**Comment by kthyng** [comment] 2022-09-09 22:14
@openjournals/dev Could you take a look at this?

**Comment by xuanxu** [comment] 2022-09-15 08:54
@kthyng if the paper is already updated in the original repo, the `reaccept` command should regenerate the metadata

**Comment by kthyng** [comment] 2022-09-15 14:08
@editorialbot reaccept

**Comment by slayoo** [comment] 2022-09-15 15:49
@kthyng it's now fixed:
![image](https://user-images.githubusercontent.com/89685/190449370-a5fa4df0-b774-47ba-9170-2bbe5040c2df.png)

Thank you for your help!
