### ISSUE TITLE
[REVIEW]: CategoricalTimeSeries.jl: A toolbox for categorical time-series analysis

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3733] opened 2021-09-16 15:16 UTC
**Submitting author:** @johncwok (<a href="http://orcid.org/0000-0001-6266-5575">Corentin  Nelias</a>)
**Repository:** <a href="https://github.com/johncwok/CategoricalTimeSeries.jl" target ="_blank">https://github.com/johncwok/CategoricalTimeSeries.jl</a>
**Version:** v1.1.4
**Editor:** @jbytecode
**Reviewer:** @bkamins, @felixcremer
**Archive:** <a href="https://doi.org/10.6084/m9.figshare.16917625" target="_blank">10.6084/m9.figshare.16917625</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e/status.svg)](https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e"><img src="https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e/status.svg)](https://joss.theoj.org/papers/919a3be5c11e2add7274a8517066361e)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/johncwok/CategoricalTimeSeries.jl" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@bkamins & @felixcremer, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @jbytecode know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @bkamins
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/johncwok/CategoricalTimeSeries.jl">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/johncwok/CategoricalTimeSeries.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@johncwok) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @felixcremer
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/johncwok/CategoricalTimeSeries.jl">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/johncwok/CategoricalTimeSeries.jl">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@johncwok) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2021-09-16 15:16
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @bkamins, @felixcremer it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-09-16 15:16
Wordcount for `paper.md` is 784

**Comment by whedon** [comment] 2021-09-16 15:16
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/biomet/80.3.611 is OK
- 10.1002/9781119097013 is OK
- 10.1145/369133.369172 is OK
- 10.1162/neco_a_00961 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2021-09-16 15:16
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (381.9 files/s, 99031.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
SVG                              1              0              0           2671
JavaScript                       6            473           1213           2025
Julia                            8            183             17           1309
HTML                             7            272             18            950
Markdown                         8            134              0            513
CSS                              2             16             67             71
TeX                              1              8              0             70
YAML                             3             11              2             53
TOML                             1              5              0             20
XML                              1              0              0             11
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            39           1102           1317           7694
-------------------------------------------------------------------------------


Statistical information for the repository '194e50e4d4a79db82c104c3e' was
gathered on 2021/09/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Corentin Nelias                  1          3711              0          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Corentin Nelias            3711          100.0          0.0               32.69
```

**Comment by whedon** [comment] 2021-09-16 15:16
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03733/joss.03733/10.21105.joss.03733.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03733/joss.03733/10.21105.joss.03733.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment] 2021-09-16 15:20
Dear @bkamins and @felixcremer 👋👋👋

This is the review issue. There are 20 check items for each reviewer. Whenever you finish reviewing the corresponding item, you can set it checked. You can also interact with the author(s), other reviewer(s) and me (editor) during the reviewing process. 

Please do not hesitate to ask me anything.

Thank you in advance.

**Comment by jbytecode** [comment] 2021-09-26 08:45
Dear @bkamins and @felixcremer, do you need help? Could you please update your status on how is your reviewing going?

**Comment by bkamins** [comment] 2021-09-26 09:04
Thank you for pinging. Now I can see that the package got a release 5 days ago that I have requested for earlier. I will go back to the review then.

**Comment by bkamins** [comment] 2021-09-27 18:14
I am not fully sure where I should put the comments, so I put them here:
* I would recommend that all packages (also dependencies) get a proper release
* All packages should have explicit `[compat]` section in their Project.toml (including the `[extras]` part for e.g. CSV.jl)
* The `print_results` does not work under current release of DataFrames.jl (I can help fixing it if needed)
* The examples in the tutorial do not work under current release of CSV.jl (I can help fixing it if needed)
* In general before reviewing the whole documentation and manual should be tested against versions of the packages specified in `[compat]`
* also I would recommend to disambiguate the paths given in the manual (as they are e.g. given in the main package documentation while the files are in the IntegerIB.jl package sources)

Regarding the analytical side of the package:
* the authors mention nominal and ordinal categorical data but do not explain how (or if) the fact that data is ordinal would be used by the package;
* maybe also comment in the documentation how this package could be integrated with CategoricalArrays.jl?

Thank you for working on this.

**Comment by jbytecode** [comment] 2021-09-28 05:57
@bkamins it is okay to put your comments here in the thread, thank you.

**Comment by johncwok** [comment] 2021-09-29 11:47
Dear @bkamins,

I addressed your comments, specifically:
- made a release for all involved packages.
- updated the code to be compatible with the most recent versions of ```DataFrames.jl``` and ```CSV.jl```.
- the files linked in the doc are all contained in the ```CategoricalTimeSeries.jl``` repo, and not pointing to other repos anymore.
- I tested the functions with the most recent versions of every packages (as specified in ```compat```), and they are working.
- I adapted the description in the doc. The reason why I wrote about 'nominal' and 'ordinal' was just as a sort of introduction regarding what type of data are referred to as 'categorical'. 
In itself the package is agnostic about the precise type of data since none of the methods are relying on a pre-existing ordering. The only requirement is that the data should be discrete. One would still get results with continuous data, but these would most probably be nonsensical.

I have one question\need help:
- The reason why I didn't have any ```compat``` entry is because when I do add them, then the package doesn't pass the test on the travis virtual machine, even though it works perfectly otherwise. I end up having error like 
```Julia
Unsatisfiable requirements detected for package foo [xxxxx]:

 foo [xxxxx] log:

 ├─possible versions are: [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0, 1.0.0-1.0.1, 1.1.0-1.1.1, 1.2.0-1.2.4, 1.3.0-1.3.2, 1.4.0-1.4.5] or uninstalled
 ├─restricted to versions 1.4.5-1 by an explicit requirement, leaving only versions 1.4.5
 └─restricted by julia compatibility requirements to versions: [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0, 1.0.0-1.0.1, 1.1.0-1.1.1] or uninstalled — no versions left
```

When I try to fix it, another package will throw this error. For example, if I fix it for ```FFTW```, then ```Plots``` errors, and if I fix it for ```Plots``` then another one bugs and it is a never ending cycle. I search for a solution but  couldn't fix this so I just removed all "problematic" compats in order to have a working package.
Do you know what causes this and how I can solve it? There are already similar issues on the discourse but they are not resolved or do not solve my issue.

**Comment by bkamins** [comment] 2021-09-29 15:08
> then the package doesn't pass the test on the travis virtual machine, even though it works perfectly otherwise

The reason is the following. You seem not to have done the package releases properly. For instance IntegerIB.jl package has 0.1 tag only made yesterday. However, in Julia Global Registry, here https://github.com/JuliaRegistries/General/blob/master/I/IntegerIB/Versions.toml you see that 0.1 tag was added 13 months ago with git-tree-sha1 `786b9878a5889e1feec38510e694016c3bb76c47`.

This makes Julia Package manager install the IntegerIB.jl package from 13 months ago not from yesterday when you ask for it being installed (you can check it on a CLEAN environment - without any packages installed in a federated package repository - this is exactly what happens on Travis).

Note that Julia does not look at what is the tag in the GitHub repository for the release but it looks at  git-tree-sha1 in https://github.com/JuliaRegistries/General to resolve package versions. You can read how new releases of packages should be registered in https://github.com/JuliaRegistries/Registrator.jl

**Comment by johncwok** [comment] 2021-09-29 15:41
So re-registering all the packages to their current version should solve this right?

**Comment by bkamins** [comment] 2021-09-29 16:48
No - you have to bump the version number and then register. The problem is exactly the fact that you use the same version number for different states of package GitHub repository (Julia will not allow registering the same version number twice as it would be ambiguous).

Also note that this has to be done sequentially. If A depends on B and B on C then you have to:
* bump version of C
* register new version of C
* change B to depend on new version of C
* bump version of B
* register new version of B
* change A to depend on new version of B
* bump version of A
* register new version of A

**Comment by jbytecode** [comment] 2021-09-29 16:51
@bkamins just to inform you, you can send a pull request to the repo under review, if needed. all of the contributions are welcome.

**Comment by bkamins** [comment] 2021-09-29 16:58
@jbytecode - it probably requires like 5 PRs in different repos and testing if all works correctly sequentially. The repo maintainer OTOH can probably do each operation in 1 minute (as maintainer has full rights to the repo and knows the packages and their interdependencies).

**Comment by johncwok** [comment] 2021-09-30 11:51
@bkamins I took care of it, and it is passing CI now. I don't know how long it will take until the re-registration is done though.

**Comment by whedon** [comment] 2021-09-30 15:16
:wave: @bkamins, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment] 2021-09-30 15:16
:wave: @felixcremer, please update us on how your review is going (this is an automated reminder).

**Comment by bkamins** [comment] 2021-09-30 19:43
> I don't know how long it will take until the re-registration is complete though.

I have checked your PRs to General Registry. As you can see your packages (for different reasons) fail the registration process.
If you have any questions regarding the registration please ask me and I will try to help.

Otherwise - could you please let me know when the registration is finished - thank you!
(in particular at least one of the packages is missing license and having proper licensing is also a JOSS requirement)

**Comment by johncwok** [comment] 2021-09-30 21:46
Do you know why the auto-merge from ```MotifRecognition.jl``` failed? The license is there, and the error message is totally incomprehensible to me.
I have added the missing license to ```SpectralEnvelope.jl```.

**Comment by bkamins** [comment] 2021-09-30 21:52
> Do you know why the auto-merge from MotifRecognition.jl failed?

As you can see in https://github.com/JuliaRegistries/General/pull/45831#issuecomment-931248106 there are two problems:
* your `[compat]` section is incomplete (missing entry for DataStructures.jl)
* your version numbering is skipping versions. Since currently known to Julia Registry version of this package is 0.1 then it expected that the patch release would have number 0.1.1, while you have made the release with 0.1.11 version, which skips many versions in-between (like 0.1.1, 0.1.2, 0.1.3, ..., 0.1.10)

**Comment by johncwok** [comment] 2021-09-30 22:56
I have added the ```[compat]``` for DataStructures.jl.

I guess I will just let you know when the re-registration is complete then.

**Comment by johncwok** [comment] 2021-10-06 09:01
Thanks! I actually already fixed the ```compat```, but as bkamins stated earlier, this was not the only reason why the automatic registration was rejected by the bot. It is because my version numbering was not done according to the convention. 
Do you know how to trigger the registration bot again? I don't want to open another pull request for that and create extra work for the people dealing with the registrations by hand.

**Comment by jbytecode** [comment] 2021-10-06 09:06
how about using

`@ JuliaRegistrator register`

in the registration issue as stated in https://github.com/JuliaRegistries/Registrator.jl or using the JuliaHub?

**Comment by bkamins** [comment] 2021-10-06 09:09
Yes - re-triggering JuliaRegistrator should work.

**Comment by johncwok** [comment] 2021-10-06 09:37
I get the following message from the registrator: 
Error while trying to register: "Tag with name v1.0.1 already exists and points to a different commit
I made increments of the version when I fixed various bugs but did not register them, and now I can't auto merge because I cannot use an earlier version number that would meet the guidelines.

**Comment by bkamins** [comment] 2021-10-06 09:56
Have you tried removing the tag? Also which exact repository you are referring to? (and could you please share the link to the commit at which you have triggered the registrator). Thank you!

**Comment by johncwok** [comment] 2021-10-06 10:02
This is the link: https://github.com/johncwok/CategoricalTimeSeries.jl/commit/dbf270a8acfd43fa32cf531795d8358a0bc47cc4
I'll try to remove the tag (I am a bit unsure how) and see if it works.

**Comment by johncwok** [comment] 2021-10-06 16:01
I deleted the release tag but still get the same message... I will try the julia slack.

**Comment by johncwok** [comment] 2021-10-06 19:22
@bkamins The registering is done!

**Comment by bkamins** [comment] 2021-10-07 13:41
> external files in examples

These files are shipped along with the package installation, so I think it is OK to use them.

**Comment by bkamins** [comment] 2021-10-07 13:43
> Do you mean that this should be stated in the documentation

It should be stated in the documentation. If you do `using SerialDependence` you have to install SerialDependence.jl earlier. So either do not do `using SerialDependence` or instruct the user that it should be installed. I would prefer that `using CategoricalTimeSeries` should be enough and it should re-export all functionalities provided by dependencies, but it is of course up to you how you design it. The crucial thing is that it should be possible to just copy-paste the code from the documentation and it should work.

**Comment by bkamins** [comment] 2021-10-07 17:38
you have `dirname` twice in `joinpath(dirname(dirname(pathof(CategoricalTimeSeries))), "test", "pewee.txt")`

**Comment by johncwok** [comment] 2021-10-07 18:19
> 
> 
> Your bounds for versions of Plots.jl in CategoricalTimeSeries.jl are incorrect. They disallow installing latest Plots.jl and also disallow installing latest SerialDepencence.jl version (which is required for things to work AFAICT).
> 
> Can you please share Project.toml and Manifest.toml that you are using under which all works, as AFAICT, it is impossible to install the version configuration of the packages that you say that you have installed.

I was using the old version since I thought that the new one hadn't been merged yet. I changed the Plots.jl compat entry,  now the package can be installed from the url without error.

**Comment by bkamins** [comment] 2021-10-07 18:54
The easiest thing to do is to change `algorithm` into a keyword argument. Then all will be clean. Such a change is breaking so you would need to go for 0.2 release then.

**Comment by jbytecode** [comment] 2021-10-09 08:57
I reinstalled the package from the repository using 

```julia
] add CategoricalTimesSeries
```

and at least one test doesn't pass:

```julia
     Testing Running tests...
Test Failed at /Users/istar1/.julia/packages/CategoricalTimeSeries/lypxN/test/runtests.jl:17
  Expression: round(((spectral_envelope(DNA))[2])[5]; digits = 3) == round(0.175; digits = 3)
   Evaluated: 0.003 == 0.175
ERROR: LoadError: There was an error during testing
in expression starting at /Users/istar1/.julia/packages/CategoricalTimeSeries/lypxN/test/runtests.jl:17
ERROR: Package CategoricalTimeSeries errored during testing
```

**Comment by jbytecode** [comment] 2021-10-09 09:19
Addition: Your tests are somehow verbose as it prints 

```julia
merged clusters 1 and 2 
merged clusters 1 and 3 
```

and I think it comes from `IntegerIB.jl `

```julia
if calc_metrics(tmp)[4] < calc_metrics(best)[4]
                    best = deepcopy(tmp)
                    mergedt1 = t1
                    mergedt2 = t2
                    anybetter = true
                    print("merged clusters $mergedt1 and $mergedt2 \n")
                end
```

It seems it is for debugging, but I think throwing errors or using `@info`, `@error`, `@warn` is more convenient if you really want inform the user. Since it is not really essential at this time and maybe you would be willing to change it in forward releases.

**Comment by johncwok** [comment] 2021-10-10 11:39
I have updated the documentation, the docstring for ```bootstrap_CI``` as well as the ```plot_motif``` example.  I also ran again every example to make sure the output and the example show the same thing.

**Comment by bkamins** [comment] 2021-10-10 14:30
@jbytecode - I have finished the review in the first comment above (I guess this is what is required).

@johncwok some issues I would recommend to resolve in the future (they are non-blocking):
* still you use specification of types as `Array{any, 1}` (incorrect), `Array{Float, 1}` (incorrect), or `Array{Any, 1}` (correct but for sure not what you meant) in the documentation;
* the testset for the package is not comprehensive enough IMO;
* the change in the plot for `bootstrap_CI`: it is not clear for me if the old plot was incorrect? (I see you have changed the plot in the docs, but I do not fully understand what has changed in the code so that the plot changed)

Best,
Bogumił

**Comment by felixcremer** [comment] 2021-11-01 12:36
@johncwok  Thank you for this nice package. 

@jbytecode  - I have finished the review in the first comment above. 
It would be good to address the outstanding issues, that  I opened on the repo and linked to this issue. 

I think you could convert the list of open improvements in the Contributing.md files into github issue, to make it easier for others to comment and also work on them. 

You could set up coveralls.io or codecov.io to make it easier to see the state of testing on the package.

**Comment by johncwok** [comment] 2021-11-01 13:48
@felixcremer Thank you for the thorough code testing and the suggestions for doc improvement!
I have never worked with coveralls.io or codecov.io so far, but I will look into it.

**Comment by jbytecode** [comment] 2021-11-01 13:54
@johncwok please consider the last recommendations and ping me when you have done so I can start my editorial stuff.

**Comment by jbytecode** [comment] 2021-11-01 13:57
@felixcremer thank you so much for your valuable review and contributions

**Comment by felixcremer** [comment] 2021-11-01 15:51
@jbytecode  The last recommendations have been incorporated.

**Comment by jbytecode** [comment] 2021-11-01 16:44
@whedon check references

**Comment by whedon** [comment] 2021-11-01 16:44
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/biomet/80.3.611 is OK
- 10.1002/9781119097013 is OK
- 10.1145/369133.369172 is OK
- 10.1162/neco_a_00961 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2021-11-01 16:45
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03733/joss.03733/10.21105.joss.03733.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03733/joss.03733/10.21105.joss.03733.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment] 2021-11-01 17:05
Dear @johncwok 

I sent a pull request that includes possible correction in the `paper.md` file:

https://github.com/johncwok/CategoricalTimeSeries.jl/pull/12

- Please check the corrections and if you are agree with the correction, please apply them.

**Comment by johncwok** [comment] 2021-11-01 18:08
Dear @jbytecode 

I am fine with all corrections. I see you changed "time-series" to "time series", is this the correct way of writing it? I have seen "time-series", "timeseries" and "time series". After checking, all of these seem to be valid so I am always a bit unsure how to write it.

**Comment by jbytecode** [comment] 2021-11-01 18:09
@whedon generate pdf

**Comment by whedon** [comment] 2021-11-01 18:10
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03733/joss.03733/10.21105.joss.03733.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03733/joss.03733/10.21105.joss.03733.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment] 2021-11-01 18:11
@johncwok you mostly use `time-series`, so I changed all other use of this term (time series, timeseries) to `time-series`.

**Comment by jbytecode** [comment] 2021-11-01 18:13
Dear @johncwok 
 
- [ ] Please re-check the whole paper by means of both language and format (one more time). When it is finished, please ping me here.

- [ ] make a tagged release and archive (e.g. with [Zenodo](https://zenodo.org/)) as described [here](<https://joss.readthedocs.io/en/latest/submitting.html#the-review-process>), and report the version number and archive DOI in this thread. Please verify that the archive deposit has the correct metadata (title and author list), or edit these if that is not the case.

- [ ] use the format vx.y.z as your versioning format.

Thank you in advance.

**Comment by johncwok** [comment] 2021-11-02 10:48
Dear @jbytecode 

I have done a final check of the paper and made two minor word adjustments, I am finished now.

The latest release (v1.1.4) is archived on figshare with the following DOI [10.6084/m9.figshare.16917625](10.6084/m9.figshare.16917625)

**Comment by jbytecode** [comment] 2021-11-02 11:34
@whedon check references

**Comment by whedon** [comment] 2021-11-02 11:34
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/biomet/80.3.611 is OK
- 10.1002/9781119097013 is OK
- 10.1145/369133.369172 is OK
- 10.1162/neco_a_00961 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by jbytecode** [comment] 2021-11-02 11:34
@whedon generate pdf

**Comment by whedon** [comment] 2021-11-02 11:35
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03733/joss.03733/10.21105.joss.03733.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03733/joss.03733/10.21105.joss.03733.pdf) :page_facing_up: :point_left:

**Comment by jbytecode** [comment] 2021-11-02 11:40
@whedon set v1.1.4 as version

**Comment by whedon** [comment] 2021-11-02 11:40
OK. v1.1.4 is the version.

**Comment by jbytecode** [comment] 2021-11-02 11:41
@whedon set 10.6084/m9.figshare.16917625 as archive

**Comment by whedon** [comment] 2021-11-02 11:41
OK. <a href="https://doi.org/10.6084/m9.figshare.16917625" target="_blank">10.6084/m9.figshare.16917625</a> is the archive.

**Comment by jbytecode** [comment] 2021-11-02 11:42
@whedon recommend-accept

**Comment by whedon** [comment] 2021-11-02 11:42
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment] 2021-11-02 11:42
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/biomet/80.3.611 is OK
- 10.1002/9781119097013 is OK
- 10.1145/369133.369172 is OK
- 10.1162/neco_a_00961 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2021-11-02 11:42
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2723

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2723, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment] 2021-11-02 12:33
@johncwok - can you update the title of the figshare archive to match the title of the paper: "CategoricalTimeSeries.jl: A toolbox for categorical time-series analysis"?

**Comment by danielskatz** [comment] 2021-11-02 12:41
I've also suggested some small changes in the paper in https://github.com/johncwok/CategoricalTimeSeries.jl/pull/13 - please merge this, or let me know what you disagree with, then we can proceed to acceptance and publishing.

**Comment by johncwok** [comment] 2021-11-02 16:10
Dear @danielskatz,

I have no objections to the small changes you made to the paper, thanks for the suggestions.
I changed the title of the figshare archive to match the paper.

**Comment by danielskatz** [comment] 2021-11-02 16:12
@whedon recommend-accept

**Comment by whedon** [comment] 2021-11-02 16:12
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment] 2021-11-02 16:13
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1137/141000671 is OK
- 10.1093/biomet/80.3.611 is OK
- 10.1002/9781119097013 is OK
- 10.1145/369133.369172 is OK
- 10.1162/neco_a_00961 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2021-11-02 16:13
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2724

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2724, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by danielskatz** [comment] 2021-11-02 16:14
@whedon accept deposit=true

**Comment by whedon** [comment] 2021-11-02 16:14
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment] 2021-11-02 16:14
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1455569125011607553) 👈 🐦🐦🐦

**Comment by whedon** [comment] 2021-11-02 16:14
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2725
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03733](https://doi.org/10.21105/joss.03733)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by danielskatz** [comment] 2021-11-02 16:22
Congratulations to @johncwok (Corentin Nelias)!!

And thanks to @jbytecode for editing, and @bkamins and @felixcremer for reviewing!
We couldn't do this without you

**Comment by danielskatz** [comment] 2021-11-02 16:22
At least for me right now, the DOI is not resolving - sometimes it takes longer than other time.

Once it does, I will close this issue.

**Comment by danielskatz** [comment] 2021-11-02 17:11
the DOI now works for me - again, congratulations & thanks to everyone for making this a smooth and productive process!

**Comment by whedon** [comment] 2021-11-02 17:11
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03733/status.svg)](https://doi.org/10.21105/joss.03733)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03733">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03733/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03733/status.svg
   :target: https://doi.org/10.21105/joss.03733
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03733/status.svg)](https://doi.org/10.21105/joss.03733)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Closed by danielskatz** 2021-11-02 17:11 UTC
Labels: accepted, review, TeX, HTML, CSS, recommend-accept, published
