### ISSUE TITLE
[PRE REVIEW]: pyDeltaRCM: a flexible numerical delta model

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3345] opened 2021-06-08 22:15 UTC
**Submitting author:** @amoodie (<a href="http://orcid.org/0000-0002-6745-036X">Andrew Moodie</a>)
**Repository:** <a href="https://github.com/DeltaRCM/pyDeltaRCM" target ="_blank">https://github.com/DeltaRCM/pyDeltaRCM</a>
**Version:** v2.0
**Editor:** @kbarnhart
**Reviewers:** @zsylvester, @jhnienhuis
**Managing EiC:** Kristen Thyng

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/b5415fded71aee0c364eb7e3f9ca17fd/status.svg)](https://joss.theoj.org/papers/b5415fded71aee0c364eb7e3f9ca17fd)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/b5415fded71aee0c364eb7e3f9ca17fd"><img src="https://joss.theoj.org/papers/b5415fded71aee0c364eb7e3f9ca17fd/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/b5415fded71aee0c364eb7e3f9ca17fd/status.svg)](https://joss.theoj.org/papers/b5415fded71aee0c364eb7e3f9ca17fd)
```

**Author instructions**

Thanks for submitting your paper to JOSS @amoodie. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@amoodie if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2021-06-08 22:15
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-06-08 22:16
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5194/esurf-3-67-2015 is OK
- 10.5194/esurf-3-87-2015 is OK
- 10.2110/pec.05.83.0011 is OK
- 10.1002/2015JF003653 is OK
- 10.1002/2016GL070519 is OK
- 10.1029/2019GL082792 is OK
- 10.1029/2018GL079405 is OK
- 10.1016/j.earscirev.2016.06.016 is OK
- 10.1038/s41467-020-18531-4 is OK
- 10.1146/annurev-marine-120709-142856 is OK
- 10.21105/joss.02317 is OK
- 10.1145/2833157.2833162 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1109/MCSE.2007.55 is OK
- 10.1038/s41592-019-0686-2 is OK

MISSING DOIs

- None

INVALID DOIs

- https://doi.org/10.1029/2020JF005706 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment] 2021-06-08 22:16
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.16 s (640.5 files/s, 121766.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          50           3127           3412           8659
reStructuredText                37            948            937            801
YAML                             4             23              4            324
TeX                              1             16              0            172
Pascal                           1             77              0            154
CSS                              1             19              7             86
SVG                              2              1              1             76
Markdown                         1             22              0             69
DOS Batch                        1              8              1             26
make                             1             12              7             17
HTML                             1              2              0              2
-------------------------------------------------------------------------------
SUM:                           100           4255           4369          10386
-------------------------------------------------------------------------------


Statistical information for the repository '4cce487149fb889102cf5356' was
gathered on 2021/06/08.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Andrew Moodie                  199         14491           8070           41.60
Eric Barefoot                   44          2707           2493            9.59
JayH                            61          3255           1346            8.48
Mariela Perignon                29          4632           1634           11.55
Mark Piper                       6            28             28            0.10
amoodie                         98          5677           2739           15.52
deltarcm-helper                  4           409            309            1.32
jay                             24          3494           2921           11.83

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Andrew Moodie             12411           85.6          4.6               11.92
Eric Barefoot               475           17.5         16.6                5.47
Mariela Perignon            167            3.6         23.0                3.59
Mark Piper                    9           32.1         57.1                0.00
deltarcm-helper             104           25.4         13.7               34.62
jayh                       2032          100.0          5.0               11.71
```

**Comment by kthyng** [comment] 2021-06-08 22:17
Hi @amoodie and thanks for your submission! I am adding it to the backlog of submissions that we have currently until an editor with relevant expertise is available. Thank you for your patience.

**Comment by kbarnhart** [comment] 2021-06-08 22:19
@kthyng I can take this on. I'm currently handling two submissions, but one should be done very soon (maybe even tomorrow).

**Comment by kbarnhart** [comment] 2021-06-08 22:22
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment] 2021-06-08 22:22
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment] 2021-06-08 22:32
@amoodie I'll follow up in the next couple of days with any pre-review comments or issues. In the meantime, please identify reviewers you think would be appropriate for this submission (mention them without the @ in front of their github username).

**Comment by amoodie** [comment] 2021-06-08 23:43
Awesome, thank you @kbarnhart!

I'll get the malformed doi whedon pointed out above fixed, along with anything you point out that needs to be corrected.

Some potential reviewers:
* Katherine Ratliff (river avulsion and floodplain evolution model `rafem` developer) `katmratliff`
* Nathan Lyons (Python model development) `nathanlyons`
* Zoltán Sylvester (Python model development, surface processes) `zsylvester`

**Comment by kbarnhart** [comment] 2021-06-11 20:32
@amoodie a few things follow. All are minor so feel free to address them along with reviewer comments:

1. CI failing. Looking at it, it seems like its not failing tests, but just failing coverage upload (https://github.com/DeltaRCM/pyDeltaRCM/runs/2776370520?check_suite_focus=true).
2. Some reference fixes
    * The invalid DOI you noted. 
    * Reference ambiguity (M. Liang vs Man Liang, to fix make sure the name is identical in the bib file)
    * In the BMI reference, Eric Hutton's second middle initial should be capitalized.

Thanks for your thoughts on reviewers.

**Comment by amoodie** [comment] 2021-06-11 22:19
Alright, should be all good to go now. Just released v2.0.0, which is the version to review. :+1:

**Comment by kbarnhart** [comment] 2021-06-11 22:40
Sounds good. I've started reaching out to reviewers over email and when confirmed will add them here.

**Comment by kbarnhart** [comment] 2021-06-18 14:29
@amoodie a quick update. I'm presently reaching out to reviewers over email. @zsylvester has kindly agreed to provide a review.

I'll work to find one or two more reviewers (two or three total) and then start the review issue.

**Comment by kbarnhart** [comment] 2021-06-18 14:30
@whedon add @zsylvester as reviewer

**Comment by whedon** [comment] 2021-06-18 14:30
OK, @zsylvester is now a reviewer

**Comment by kbarnhart** [comment] 2021-06-23 17:24
@jhnienhuis has kindly agreed to provide a review. I will add him as a reviewer and then start the review issue so the reviewers can start their reviews. 

I plan to find one more reviewer for this submission. I will add them manually to the review once they have agreed to contribute a review.

**Comment by kbarnhart** [comment] 2021-06-23 17:24
@whedon add @jhnienhuis as reviewer

**Comment by whedon** [comment] 2021-06-23 17:24
OK, @jhnienhuis is now a reviewer

**Comment by kbarnhart** [comment] 2021-06-23 17:25
@whedon start review

**Comment by whedon** [comment] 2021-06-23 17:25
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3398.

**Comment by kbarnhart** [comment] 2021-06-23 17:25
I have reopened the issue and will close it once I find the final reviewer.

**Comment by arfon** [comment] 2021-06-24 09:51
@whedon generate pdf

**Comment by whedon** [comment] 2021-06-24 09:51
PDF failed to compile for issue #3345 with the following error: 
```
 Error producing PDF.
! Illegal parameter number in definition of \@xs@arg@i.
<to be read again> 
                   q
l.350 }

Looks like we failed to compile the PDF

```

**Comment by kbarnhart** [comment] 2021-08-30 17:51
Looks like I never closed this issue. Closing.

**Closed by kbarnhart** 2021-08-30 17:51 UTC
Labels: pre-review, Python
