### ISSUE TITLE
[REVIEW]: autoplotly: An R package for automatic generation of interactive visualizations for statistical results

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#657] opened 2018-03-29 19:23 UTC
**Submitting author:** @terrytangyuan (<a href="http://orcid.org/0000-0001-5243-233X">Yuan Tang</a>)
**Repository:** <a href="https://github.com/terrytangyuan/autoplotly" target ="_blank">https://github.com/terrytangyuan/autoplotly</a>
**Version:** v0.1.1
**Editor:** @arfon
**Reviewer:** @chlalanne, @corybrunson
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.1221391" target="_blank">10.5281/zenodo.1221391</a>

## Status

[![status](http://joss.theoj.org/papers/857f1efeca788008e34825c89080b7ff/status.svg)](http://joss.theoj.org/papers/857f1efeca788008e34825c89080b7ff)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/857f1efeca788008e34825c89080b7ff"><img src="http://joss.theoj.org/papers/857f1efeca788008e34825c89080b7ff/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/857f1efeca788008e34825c89080b7ff/status.svg)](http://joss.theoj.org/papers/857f1efeca788008e34825c89080b7ff)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/terrytangyuan/autoplotly" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@chlalanne & @corybrunson, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @arfon know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/terrytangyuan/autoplotly">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.1)?
- [x] **Authorship:** Has the submitting author (@terrytangyuan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/terrytangyuan/autoplotly">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.1)?
- [x] **Authorship:** Has the submitting author (@terrytangyuan) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by arfon** [comment] 2018-03-29 19:24
@chlalanne, @corybrunson - please carry out your review in this issue by updating the checklist above and giving feedback in this issue. The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Any questions/concerns please let me know.

**Comment by terrytangyuan** [comment] 2018-03-29 19:27
Thanks @arfon. Do you know why the references do not show up in the compiled PDF?

**Comment by arfon** [comment] 2018-03-29 19:50
@terrytangyuan - I think this is because they're not being cited directly. (You can read how to do that [here](http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html))

**Comment by arfon** [comment] 2018-03-29 20:30
@whedon generate pdf

**Comment by whedon** [comment] 2018-03-29 20:30
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by corybrunson** [comment] 2018-04-13 12:46
@terrytangyuan i have a question that i don't think is appropriate as an issue on the submitted repo. It may just reflect my lack of knowledge about software licenses.

**autoplotly** is licensed under Apache 2.0,  which is [described as incompatible with GPLv3 (and v2) in this direction](https://www.apache.org/licenses/GPL-compatibility.html). Since **ggplot2** and **ggfortify** are licensed under GPLv2, this seems to present a problem. Can you address that?

**Comment by terrytangyuan** [comment] 2018-04-13 16:05
@corybrunson Thanks for taking the time to review! I just responded your issues. I've listed out the TODOs below:

- [ Move blogpost to package vignette (with `eval = FALSE` in .Rmd file)] 
- [ Add community guidelines to ggfortify and autoplotly repos] 
- [ Change autoplotly license to GPLv2]
- [ Add DOI to ggplot2 book citation] 

I'll work on them soon.

**Comment by terrytangyuan** [comment] 2018-04-13 16:09
@corybrunson Note that I am not adding a LICENSE file to the repo though since they are usually not required for R packages. This is a Github rendering issue and I believe they are working on the fix. I will fix the license in DESCRIPTION file only.

**Comment by terrytangyuan** [comment] 2018-04-13 19:55
@corybrunson Just finished all the TODOs. Could you review again? Thanks!

**Comment by corybrunson** [comment] 2018-04-13 20:47
@whedon generate pdf

**Comment by whedon** [comment] 2018-04-13 20:47
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-04-13 20:47
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00657/joss.00657/10.21105.joss.00657.pdf)

**Comment by corybrunson** [comment] 2018-04-13 20:53
@terrytangyuan Great! Everything looks and works good for me. I have one final suggestion for the README: Now that a vignette is included, the development version might better be installed via:

    devtools::install_github("terrytangyuan/autoplotly", build_vignettes = TRUE)

**Comment by corybrunson** [comment] 2018-04-13 20:55
@arfon i have concluded my review and recommend acceptance.

**Comment by arfon** [comment] 2018-04-14 12:03
@corybrunson - excellent. Thanks!

@chlalanne - when do you think you might be able to complete your review by?

**Comment by chlalanne** [comment] 2018-04-19 08:00
Sorry for the delay. I somewhat messed up with GH notifications. The package looks great and is working out of the box for me. I reviewed the vignette and the test suite, and they look ok to me. 

@terrytangyuan I only have a couple a minor comments:

1. You cited SO as a possible placeholder for reporting issues or seeking help (`ISSUE_TEMPLATE.md`); maybe you should also indicate that users need to provide a minimal reproducible example, per SO policy, to prevent questions being closed quickly.
2. You do not mention `plotly::ggplotly()`, which provides similar facilities but without the `ggfortify` backend. I would have thought that it would perhaps fit in the last paragraph of you `paper.md` file.

@arfon I am done with the review and I am happy with the project as it stands.

**Comment by arfon** [comment] 2018-04-19 10:15
⚡️thanks @chlalanne.

@terrytangyuan - please take a look at @chlalanne's feedback above.

**Comment by terrytangyuan** [comment] 2018-04-19 13:04
Thanks everyone! I've addressed your comments.

**Comment by arfon** [comment] 2018-04-19 16:05
Great! @terrytangyuan - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by terrytangyuan** [comment] 2018-04-19 18:37
@arfon Here it is: [![DOI](https://zenodo.org/badge/116608209.svg)](https://zenodo.org/badge/latestdoi/116608209)

**Comment by terrytangyuan** [comment] 2018-04-19 18:43
@whedon generate pdf

**Comment by whedon** [comment] 2018-04-19 18:43
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-04-19 18:44
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00657/joss.00657/10.21105.joss.00657.pdf)

**Comment by terrytangyuan** [comment] 2018-04-19 18:53
@arfon Please hold off on the publishing. I've resolving some minor issues with the Rmarkdown generation. Will ping you when ready. BTW, just curious - if I update paper.md going forward, would it automatically update the paper?

**Comment by terrytangyuan** [comment] 2018-04-19 19:25
@whedon generate pdf

**Comment by whedon** [comment] 2018-04-19 19:25
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-04-19 19:25
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00657/joss.00657/10.21105.joss.00657.pdf)

**Comment by terrytangyuan** [comment] 2018-04-19 19:51
@arfon All issues fixed now. See DOI in my comments above (you can also find it in project README). Thanks for everyone’s time!

**Comment by arfon** [comment] 2018-04-20 00:10
@whedon set 10.5281/zenodo.1221391 as archive

**Comment by whedon** [comment] 2018-04-20 00:10
OK. <a href="http://dx.doi.org/10.5281/zenodo.1221391" target="_blank">10.5281/zenodo.1221391</a> is the archive.

**Comment by arfon** [comment] 2018-04-20 00:11
> BTW, just curious - if I update paper.md going forward, would it automatically update the paper?

No, it wouldn't update on the final JOSS site but @whedon can always compile the latest version for you here.

**Closed as completed** 2018-04-20 00:22 UTC
Labels: accepted, review, recommend-accept, published
