### ISSUE TITLE
[REVIEW]: walkr: MCMC Sampling from Non-Negative Convex Polytopes

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#61] opened 2016-09-12 04:47 UTC
**Submitting author:** @andyyao95 (<a href="http://orcid.org/0000-0003-3898-8782">Andy  Yao</a>)
**Repository:** <a href="https://github.com/andyyao95/walkr" target ="_blank">https://github.com/andyyao95/walkr</a>
**Version:** v0.3.4
**Editor:** @karthik 
**Reviewer:** @dgrtwo 
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.400944" target="_blank">10.5281/zenodo.400944</a>

## Status

[![status](http://joss.theoj.org/papers/71b0689984d98a4ecc39b5e906ba0c71/status.svg)](http://joss.theoj.org/papers/71b0689984d98a4ecc39b5e906ba0c71)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/71b0689984d98a4ecc39b5e906ba0c71"><img src="http://joss.theoj.org/papers/71b0689984d98a4ecc39b5e906ba0c71/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/71b0689984d98a4ecc39b5e906ba0c71/status.svg)](http://joss.theoj.org/papers/71b0689984d98a4ecc39b5e906ba0c71)
```

**Reviewers and authors**: Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue
in the <a href="https://github.com/andyyao95/walkr" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers)
in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice
versa will create corresponding breadcrumb trails in the link target.)
### Conflict of interest
- [ ] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andyyao95/walkr">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v0.3.3)?
### Functionality
- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper

Paper PDF: [10.21105.joss.00061.pdf](https://github.com/openjournals/joss-reviews/files/470581/10.21105.joss.00061.pdf)
- [ ] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment] 2016-09-12 04:53
Hi @andyyao95. Currently the paper doesn't compile properly as you're not actually citing any of the references in the paper. Could you actually cite the entries in your `paper.bib` (e.g. [@kannan]) in the body of the paper?

**Comment by andyyao95** [comment] 2016-09-12 20:36
Hi Arfon,

Thank you so much, I used the reference for a longer version of the paper
instead (my bad). I just updated the paper.bib and paper.md to properly
cite all the references.

Let me know if you have any other questions. Thanks!

Andy

**Comment by arfon** [comment] 2016-09-13 19:00
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by arfon** [comment] 2016-09-21 16:19
@whedon commands

**Comment by whedon** [comment] 2016-09-21 16:19
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by arfon** [comment] 2016-09-21 16:19
@whedon assign @jakevdp as editor

**Comment by whedon** [comment] 2016-09-21 16:19
OK, the editor is @jakevdp

**Comment by jakevdp** [comment] 2016-09-21 16:31
I contacted Neal Thomas, author of R2OpenBUGS, to see if he's interested in reviewing.

**Comment by jakevdp** [comment] 2016-09-23 13:46
Neal was not interested, nor were a couple other R/Bayesian folks. Still reaching out to some...

**Comment by karthik** [comment] 2016-09-23 15:24
@jakevdp You might ask @drgtwo if he's interested and has the time.

**Comment by jakevdp** [comment] 2016-09-29 15:00
Hi folks,
I'm completely striking out finding a reviewer for this. To be entirely honest, I accepted this thinking it was a Python package. I'm finding I don't have enough ties to the Rstats community to find an appropriate person/someone who knows me well enough to not blow me off.

Is there a way to re-assign this to another editor? I'm frankly out of ideas.

**Comment by arfon** [comment] 2016-09-29 16:36
@karthik - would you be able to take this one?

**Comment by karthik** [comment] 2016-09-29 18:02
Sure. Assign it to me. Will handle on Friday when I'm back. 






On Thu, Sep 29, 2016 at 6:36 PM +0200, "Arfon Smith" <notifications@github.com> wrote:












@karthik - would you be able to take this one?

**Comment by arfon** [comment] 2016-09-29 18:12
@whedon assign @karthik as editor

**Comment by whedon** [comment] 2016-09-29 18:12
OK, the editor is @karthik

**Comment by karthik** [comment] 2016-10-18 20:40
Quick update that I am still working to find reivewers for this submission.

**Comment by arfon** [comment] 2016-11-08 21:23
> Quick update that I am still working to find reviewers for this submission.

Any update on this @karthik?

**Comment by andyyao95** [comment] 2016-11-21 01:46
Hi @karthik, 

I am wondering if there is any update from the reviewers. Please let me know if anything can be done on my end to faciliate the process. 

Thanks!
Andy

**Comment by karthik** [comment] 2016-11-21 19:49
Hi @andyyao95, Apologies for the delay but two folks I contacted declined the invitation to review. I'm still seeking out other reviewers. If you have any suggestions for people I should contact, please mention it in this thread or drop me a note (`karthik.ram at berkeley edu`).

**Comment by dgrtwo** [comment] 2016-11-21 20:38
I volunteer to review this. I'll have it done by Saturday.

I'm sorry the process has taken so long!

**Comment by andyyao95** [comment] 2016-11-21 20:46
@karthik  @dgrtwo Thank you two so much! I look forward to hearing back from you guys. 

Best,
Andy

**Comment by andyyao95** [comment] 2016-12-06 23:57
Hi @dgrtwo . 

I just wanted to check with you where the package is in the reviewing process. Thanks a ton!

Best,
Andy

**Comment by karthik** [comment] 2016-12-07 04:37
@whedon assign @dgrtwo as reviewer

**Comment by whedon** [comment] 2016-12-07 04:37
OK, the reviewer is @dgrtwo

**Comment by karthik** [comment] 2016-12-13 18:28
@dgrtwo Hi Dave, can you update this thread when you get a chance? Thanks!

**Comment by arfon** [comment] 2017-01-08 03:27
> @dgrtwo Hi Dave, can you update this thread when you get a chance? Thanks!

Friendly new year reminder @dgrtwo 😁

**Comment by arfon** [comment] 2017-02-05 00:42
:wave @dgrtwo - are you still able to review this submission for JOSS? If not, we can look for another reviewer.

**Comment by masalmon** [comment] 2017-02-16 12:12
@arfon just noticed this from the CRANberries feed https://cran.r-project.org/web/packages/walkr/index.html

**Comment by masalmon** [comment] 2017-02-16 12:13
The reason for removal from CRAN is "Archived on 2017-02-16 as check problems were not corrected despite reminders."

**Comment by andyyao95** [comment] 2017-02-17 12:02
@arfon @masalmon  Hi. Very sorry about this. There was a minor error in compiling the package vignette on CRAN. I missed the reminder as it was in another email. 

I've updated the package (same content, small vignette fix). I'll let you guys know when CRAN updates it. Thanks!

**Comment by masalmon** [comment] 2017-02-17 12:05
@andyyao95 great I had just copied this here in case you were MIA :wink: cool that you could solve the error!

**Comment by andyyao95** [comment] 2017-02-24 08:02
It's back on CRAN [now.](https://cran.r-project.org/web/packages/walkr/index.html) (also updated on github.) Thank you guys for your patience. Let me know if anything else is needed in the review process. 

Looking forward to hearing back, and have a nice day!

**Comment by arfon** [comment] 2017-03-12 19:49
:wave: @dgrtwo - are you still able to review this submission?

@andyyao95 - I think we might need to find an alternative reviewer here.

**Comment by dgrtwo** [comment] 2017-03-12 19:57
@arfon Sorry, this completely slipped my mind again :( I'll do it immediately.

**Comment by dgrtwo** [comment] 2017-03-16 15:20
After review I'm recommending **acceptance**; my only issues (about GitHub/CRAN differences and DOIs) were resolved in [this issue](https://github.com/andyyao95/walkr/issues/2). My other note is that the version is now **0.3.4** (I don't know where that should change in the submission).

Overall this is a great package and I've been impressed as I've played with the mathematical sampling. I particularly like the detail and figures in the vignette and am impressed with the test coverage. paper.md covers the software's uses well.

I greatly appreciate your patience in this unusually long process, as well as Andy's quick response to feedback!

## Reviewer questions
### Conflict of interest
- [X] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).
### General checks
- [X] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andyyao95/walkr">repository url</a>?
- [X] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [X] **Version:** Does the release version given match the GitHub release (v0.3.3)?
### Functionality
- [X] **Installation:** Does installation proceed as outlined in the documentation?
- [X] **Functionality:** Have the functional claims of the software been confirmed?
- [X] **Performance:** Have any performance claims of the software been confirmed?
### Documentation
- [X] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [X] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [X] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [X] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [X] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [X] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
### Software paper

Paper PDF: [10.21105.joss.00061.pdf](https://github.com/openjournals/joss-reviews/files/470581/10.21105.joss.00061.pdf)
- [X] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [X] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [X] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment] 2017-03-18 00:45
> I greatly appreciate your patience in this unusually long process, as well as Andy's quick response to feedback!

👍  thanks @dgrtwo!

@andyyao95 - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by karthik** [comment] 2017-03-18 21:45
Thanks @dgrtwo!

@arfon Getting caught up here but glad the review is in.

**Comment by andyyao95** [comment] 2017-03-20 12:09
Hi @arfon. Here it is: https://doi.org/10.5281/zenodo.400944 

Let me know if this is okay! Thanks for all the help.

**Comment by arfon** [comment] 2017-03-20 12:57
@whedon set 10.5281/zenodo.400944 as archive

**Comment by whedon** [comment] 2017-03-20 12:57
OK. <a href="http://dx.doi.org/10.5281/zenodo.400944" target="_blank">10.5281/zenodo.400944</a> is the archive.

**Comment by arfon** [comment] 2017-03-20 13:06
Many thanks for the review @dgrtwo and for editing this one @karthik ✨ 

@andyyao95 - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00061 ⚡️ 🚀 💥

**Closed by arfon** 2017-03-20 13:06 UTC
Labels: accepted, review

**Comment by andyyao95** [comment] 2017-03-20 13:11
Hi @arfon @dgrtwo and @karthik, thanks so much for the help in the process. Really appreciate everything and glad that the review was successful.

**Comment by arfon** [comment] 2017-03-20 13:22
@davidkane9 - https://github.com/openjournals/joss-papers/raw/master/joss.00061/10.21105.joss.00061.pdf _is_ the full JOSS paper. Please take a look at the author guidelines [here](http://joss.theoj.org/about#author_guidelines).

**Comment by davidkane9** [comment] 2017-03-20 13:33
Ah, yes. Read that so long ago that I had forgotten it!

;-)
