### ISSUE TITLE
[REVIEW]: QuasinormalModes.jl: A Julia package for computing1 discrete eigenvalues of second order ODEs

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4077] opened 2022-01-20 18:27 UTC
**Submitting author:** @lucass-carneiro (<a href="http://orcid.org/0000-0001-6764-1812">Lucas Timotheo Sanches</a>)
**Repository:** https://github.com/lucass-carneiro/QuasinormalModes.jl/
**Branch with paper.md** (empty if default branch): master
**Version:** v1.1.0
**Editor:** @pdebuyl
**Reviewers:** @JamieBamber, @cescalara
**Archive:**  10.5281/zenodo.6478503

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55/status.svg)](https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55"><img src="https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55/status.svg)](https://joss.theoj.org/papers/d3e2bd41441f58c77be1ca5e6c749d55)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lucass-carneiro/QuasinormalModes.jl/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@JamieBamber & @cescalara, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @pdebuyl know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @JamieBamber
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/lucass-carneiro/QuasinormalModes.jl/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lucass-carneiro/QuasinormalModes.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lucass-carneiro) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @cescalara
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/lucass-carneiro/QuasinormalModes.jl/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lucass-carneiro/QuasinormalModes.jl/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lucass-carneiro) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2022-01-20 18:27
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @JamieBamber, @cescalara it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2022-01-20 18:27
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (487.7 files/s, 59287.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Julia                           14            364            179           1525
Markdown                         7            156              0            373
TOML                             2             92              1            363
SVG                              2              0             10            253
YAML                             3              3              0             85
-------------------------------------------------------------------------------
SUM:                            28            615            190           2599
-------------------------------------------------------------------------------


Statistical information for the repository '21c49dede83d2d1f3883f10a' was
gathered on 2022/01/20.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment] 2022-01-20 18:27
PDF failed to compile for issue #4077 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by pdebuyl** [comment] 2022-01-20 18:29
@whedon generate pdf from branch paper

**Comment by whedon** [comment] 2022-01-20 18:29
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2022-01-20 18:30
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04077/joss.04077/10.21105.joss.04077.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04077/joss.04077/10.21105.joss.04077.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment] 2022-01-31 08:53
@JamieBamber @cescalara gentle reminder for the review. Also, don't hesitate to ask if there is any issue with installation.

**Comment by whedon** [comment] 2022-02-03 18:27
:wave: @cescalara, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment] 2022-02-03 18:27
:wave: @JamieBamber, please update us on how your review is going (this is an automated reminder).

**Comment by cescalara** [comment] 2022-02-04 17:56
Hi @lucass-carneiro,

Thanks for your work on `QuasinormalModes.jl`. I started the review today, here are my questions/comments:

- At the moment it is not clear which dependencies are needed to run the tests/docs asopposed to the core code. The latest recommendation is to use separate `Project.toml` files inside `tests/` and `docs` to handle this - see https://pkgdocs.julialang.org/v1/creating-packages/#Adding-tests-to-the-package for more info. 

- There are logging statements available in Julia such as `@info` and `@warn` that have a lot of advantages over a call to `println()` - see https://docs.julialang.org/en/v1/stdlib/Logging/. These could be used when not using throwing exceptions, e.g. [here]( https://github.com/lucass-carneiro/QuasinormalModes.jl/blob/f22d12304b247415df94483fc4f7355fb8fa0393/src/eigenvalue_computing/compute_eigenvalues.jl#L37).

- I noticed that the docs and example scripts are out of sync, e.g. I need to add some calls to `BigFloat()` in when constructing problems in the Schwarzschild example to avoid an error. A nice way to avoid manually updating both is to use [Literate.jl](https://fredrikekre.github.io/Literate.jl/v2/) to convert your scripts to doc notebooks that are actually run when the docs are built, so outputs will also be displayed for users to compare with.

- Can you provide the code used to make the benchmark plots shown in the paper? This would make it easier for me to check the performance claims. It could also be useful to have it in the repo, as an example or test.

- Could you add some guidelines on a good workflow for ensuring enough iterations in the AIM algorithm when applying this method generally? Is it enough just to check the final output from `computeEigenvalues()`? 

- In the paper, some in-text citations have parentheses around them. I think you can just remove the square brackets to fix this. 

- More superficial suggestions:
  - It would be nice to have "oscillator" spelt correctly throughout the code/docs.
  - Also FYI, the Julia style guide for function naming is lowercase with underscores (https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/), but I don't think this is necessary for JOSS.

I hope this is useful and am happy to discuss more.

**Comment by lucass-carneiro** [comment] 2022-02-08 17:56
Hi @cescalara,

Thank you for your review and comments. They were all very helpful and have improved the quality of the package. Here is a brief list of changes made in the "paper" and "gh-pages" branches to address your comments:

1. Both the documentation and the tests have now their own `Project.toml` and `Manifest.toml` files with their dependencies tracked.
2. I have found no other place in the code that outputs logging-like messages with `println` throughout the code and replaced the spot you indicated with `@warn`. I still use `println` in places where I want to format the output a certain way and `error` where appropriate.
3. The documentation is now synced with the examples. I have also made the package loading step of the examples a little bit more explicit in the documentations. `Literate.jl` seems a great tool, but (at least for now) I thought it better to keep tracking things manually in order to address other issues more quickly, since integrating `Literate.jl`'s workflow with the existing structure would require some effort.
4. The benchmark data, as well as the source code necessary to generate it and the plots that are included in the paper are now in the repository [here](https://github.com/lucass-carneiro/QuasinormalModes.jl/tree/paper/benchmark). I have included a small `README.md` file with instructions on how to generate new benchmarks.
5. I have added a new section in the documentation with general tips, workflow guidelines and how to choose parameters in the AIM [here](https://lucass-carneiro.github.io/QuasinormalModes.jl/org/#Computing-eigenvalues-and-general-workflow-guidelines).
6. About the citations, are you referring to the act that all citations have parenthesis around them? If so, I thought that this style was accepted in JOSS since i have obtained it from [here](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).
7. "Oscillator" is now spelt correctly throughout the code and source file names.
8. I will consider changing the names from camel to snake case, however since this is a major API change It will probably take some time to change everything and I'm not sure that the review is a good period for that type of overhaul.

**Comment by pdebuyl** [comment] 2022-02-11 13:44
Thanks @cescalara for the review so far!

@lucass-carneiro JOSS appreciates to see the best practices for a specific field or language but the choice of camel case vs snake case is not relevant for the review :-)

**Comment by pdebuyl** [comment] 2022-02-25 10:45
Hi @JamieBamber any update on your side?

**Comment by cescalara** [comment] 2022-02-28 12:45
Hi @lucass-carneiro,

I have been through your response and changes to the code, thanks a lot for taking my comments on board. I confirm that I was able to run your benchmark example and produce equivalent plots to those shown in the paper, so I haved checked off the box regarding performance claims. I also think the added documentation is very helpful. I add a few more minor comments/replies below. 

* When using `computeEigenvalues` in the Schwarzschild numerical example, I get an `NLSolve.SolverResults` output as explained in the docs. Most fields in the output are self-explanatory, but it might be nice to have a example of what the output values could be for users to compare to. I notice that the Inf-norm is a large number and not sure if this is cause for concern in this case (although I admit this may be more obvious to a reviewer with expertise in these methods).

* You might consider using [deploydocs](https://juliadocs.github.io/Documenter.jl/v0.9/lib/public.html#Documenter.deploydocs) so that you docs track different versions/releases of the software.

> About the citations, are you referring to the act that all citations have parenthesis around them? If so, I thought that this style was accepted in JOSS since i have obtained it from here.

This is a really minor point, but I meant that for citations that are part of the sentence (e.g. line 40 in your paper) one usually drops the parentheses.

**Comment by lucass-carneiro** [comment] 2022-03-09 14:34
@editorialbot generate pdf from branch paper

**Comment by cescalara** [comment] 2022-03-09 15:26
Hi @lucass-carneiro, 

Thanks again for taking all the comments on board. 

> There are links in REDME.md in master that point to the stable and development versions of the docs, although the stable link is not working. I suspect that when I tag the next release version, Documenter.jl will auto generate the documentation for the new version and create the stable link. I suspect it did not do so now because I have triggered it by simple pushes to master that contained only preexisting tags.

That sounds right, although it should be able to pick up existing tags. If there are still any issues after tagging your new release, you can always just clear out the `gh-pages` branch and rerun the action (at least this has worked for me).

> I have removed parenthesis around the citations that are part of a sentence. I tried to get whedon to compile a new preview but it did not seem to work, I don't know why. Maybe @pdebuyl needs to issue the command? In any case, it is minor change but I think it is best to update the paper preview.

No worries, this really isn't a big deal.

> do you think that including the SolverResults output in the documentations for the examples and briefly going over what the parameters are would help?

That would be great, I think then I can check all the boxes!

**Comment by pdebuyl** [comment] 2022-03-09 19:44
Hi @lucass-carneiro I did not consider that @JamieBamber might not read his notifications from GitHub, which happens not so unfrequently with JOSS reviewers. It was the case and he confirmed today that he would review. Sorry for the delay about this!

**Comment by pdebuyl** [comment] 2022-03-09 19:46
@editorialbot set paper as branch

**Comment by pdebuyl** [comment] 2022-03-09 19:47
@editorialbot generate pdf

**Comment by pdebuyl** [comment] 2022-03-09 21:03
Regarding the citations, there is a mismatched curly brace at https://github.com/lucass-carneiro/QuasinormalModes.jl/blob/paper/paper/paper.bib#L131 so the bibtex parsing fails.

**Comment by lucass-carneiro** [comment] 2022-03-12 04:18
Hi @cescalara 

I have made a few additions both of code examples and documentation to the package. Since I think all of these changes are important to the package as a whole, the have been pushed directly to `master`.

1. There are two new examples, [here](https://github.com/lucass-carneiro/QuasinormalModes.jl/blob/master/examples/harmonic_oscillator_roots_and_poles.jl) and [here](https://github.com/lucass-carneiro/QuasinormalModes.jl/blob/master/examples/schwarzschild_roots_and_poles.jl). These examples show how the user is not bound to use `NLsolve.jl` and is in fact free to choose any root finding method they wish. In this particular case, I'm using [`RootsAndPoles.jl`](https://github.com/fgasdia/RootsAndPoles.jl). These new examples are referenced multiple times across the documentation, when appropriate. There is also a new `README.md` file in the examples folder and a `Projec.toml` and `Manifest.toml` file as well in order to keep track of example dependencies separately and clearly.
2. There is a new note marked in blue at the bottom of the page [here](https://lucass-carneiro.github.io/QuasinormalModes.jl/dev/org/#Computing-eigenvalues-and-general-workflow-guidelines) giving advice on how to find initial guesses for physics problem where one might have no idea where to start. I have decided to add this advice even tough you didn't ask for it directly as I realized that this particular topic was missing from the rest of the documentation.
3. There is a new section [here](https://lucass-carneiro.github.io/QuasinormalModes.jl/dev/schw/#Interpreting-SolverResults-output) that deals with interpreting `SolverResult` objects and a brief discussion about the large inf-norm. To summarize, my advice in these cases is to always double check with a different root finding method. In the Schwarzschild case, `RootsAndPoles.jl` is also able to find the same root by a completely different method that does not rely on polishing. which indicates that the value is in fact a root of the quantization condition and a quasinormal mode candidate. Note that in the harmonic oscillator example, `NLsolve.jl` converges by both criteria, probably because this example is substantially simpler than the Schwarzschild quasinormal modes.

Regarding changes made to the `paper` branch:

1. @pdebuyl I have fixed the paper compilation issues and tested the compilation locally using the docker image. For good measure, I have decided to also include the generated PDF. About @JamieBamber's review, don't worry about the delay. It is good that you managed to get a hold of him and that he is able to do the review. I have no trouble waiting.
2. I have added a few people to the `Acknowledgements` section of the paper.

**Comment by cescalara** [comment] 2022-03-13 09:48
Hi @lucass-carneiro,

Thank you for the further additions, I think these together help to show the subtleties of using your package in a robust way. I confirm the new examples run without issue and that I can reproduce the results shown in the documentation.  

From my side I think I can conclude the review and I look forward to the thoughts of @JamieBamber.

**Comment by lucass-carneiro** [comment] 2022-03-14 17:49
@cescalara Thank your review, work and suggestions. I wish you all the best!

**Comment by JamieBamber** [comment] 2022-03-16 17:15
@lucass-carneiro 
Apologies for the delay in my review. The work looks very impressive. I agree with the comments of @cescalara, and I only had a few minor additional comments:

1.  You discuss the need to carefully refine the results to distinguish true eigenvalues from spurious ones, and to find others not discovered from that x_0. In your research work have you developed a systematic method or code to do this, and if so could it be included in the repository? 

2.  In the Schwarzschild BH example after seeing the output list of candidate frequencies found from the analytic problem I immediately wanted to plot a graph to see what they look like and compare with the known plots of Schwarzschild QNM frequencies. Hence, I was wondering if it might be a good idea to add such a plotting feature to that example, so that users can see the results visually and not merely from a list of numbers, as well as a comparison plot of the true QNM frequencies to visually demonstrate the method works?

3. There are a few minor typos in the documentation, such as using "Weather" instead of "Whether" at the bottom of the "Complete Example: Schwarzschild Quasinormal Modes" page. 

4. Why did you chose the AIM method for your code over the alternatives? 

5. How does the time scaling and error convergence of this code compare to the existing alternatives (where comparable) or non-AIM methods?

**Comment by pdebuyl** [comment] 2022-03-31 21:54
Thank you very much @JamieBamber for the review!

@lucass-carneiro the review is positive as far as the checklist is concerned. It would be good to reply to the comment by @JamieBamber to proceed though.

**Comment by lucass-carneiro** [comment] 2022-03-31 21:59
Thank you for the review @JamieBamber. 

@pdebuyl thanks for the remainder and ping. I have been very swamped by other task these last few days and have not found the time yer to respond adequately to Jamie's review yet but I will do so on the following days. Thank you for your patience.

**Comment by lucass-carneiro** [comment] 2022-04-06 04:01
Hello @JamieBamber. Once again, I apologize my long delay in answering your questions. As I have said, I was swamped with other duties and did not find the time to answer you properly.

In regards to your comments:

1. So far I have not coded any automatic solution for finding `x_0`. As I've mentioned in the docs, I usually start halfway through in the compactifyied domain (to me this usually means `x_0 = 0.5`) and start perturbing this parameter from there. In practice, I never found the need to deviate much further from this value, as `x_0` speeds up (or slows down) the convergence of the mode and does not change the set of eigenvalues obtained, at least from a theoretical standpoint. In order to develop a systematic way of fine tuning `x_0`, the user could take, for instance, the time required to find a certain mode and choose `x_0` such as to minimize this time. This is not a difficult thing to do, but again, for most users and practical purposes unnecessary for good usage of the method.
2. It is very easy to plot the obtained eigenvalues, as they are simple Julia arrays. I have not included such functionality because plot aesthetics are a highly subjective topic so I have chosen to give users data instead of ready made plots. Nevertheless, I also think that a plot of the modes would be of interest. That is why I have added a new section in the documentation that can be found [here](https://lucass-carneiro.github.io/QuasinormalModes.jl/dev/schw/#Computing-high-\\ell-quasinormal-modes). The code used in this example is an excerpt of a code that I'm currently using (together with collaborators) in a paper that compares the AIM with pseudo-spectral methods for several bosonic and fermionic Schwarzschild perturbations. We have found so far that even for large ``\ell`` values the results computed with both methods agree to machine precision (when using `BigFloats` for the computations) and also agree with available literature values. We are also in the processes of discovering and cross-comparing several modes not listed in existing references. Initial guesses in these computations were produced using the analytic formula that yields the Schwarzschild QNMs for large ``\ell`` and the list of modes can be found [here](https://github.com/lucass-carneiro/QuasinormalModes.jl/blob/master/examples/high_l_Schwarzschild/qnm_2022-04-05%2017:49:10_s_0.dat)
3. Noted. I have combed the file and fixed a few other typos.
4. In my opinion, the main advantage of the AIM over other methods is it's flexibility and generality. It's formulated in such a way that it abstracts away the specific features of problems and presents a general solution to the second order ODE of interest. I have written the package in a way that attempts to expose that abstraction to the user: Give me your ODE coefficients and I shall give you eigenvalues. It does not matter if you are trying to find the modes of an extreme BH or if your eigenvalues appears inside a complicated function in one of the ODE's coefficients. The method works regardless of such details. In contrast, let us look at another popular method of solving the same problem: Leaver's continued fraction method. This method is based upon finding a continued fraction expression from the ODE of interest and searching for roots of said fraction to determine the problem's eigenvalues. The difficulty lies in the construction of the continued fraction: To do so, one must derive a recurrence relation for series expansion coefficients which may have a varying number of terms. Each problem, generates a uniquely different recurrence relation and it's hard to generalize this and abstract away certain problem details. Furthermore, the method needs to be supplemented with additional techniques in the case of an extreme black hole (see [this paper](https://arxiv.org/abs/1409.7440)). These requirements make it unsuitable for a general solver. Another popular candidates are pseudo-spectral methods, which discretize the derivative operators and transforms the problem into a matrix-generalized eigenvalue problem. This transformation is straightforward if the eigenvalue being sought is a liner or polynomial function. It is not possible (at least to my knowledge) to pose a generalized eigenvalue problem using a spectral method if the eigenvalue is any other type of function. If for instance the eigenvalue being sought appears inside a spheroidal harmonic, pseudo-spectral methods are not an option. The AIM does not care in general for what your ODE coefficients look like. You simple need to be able to evaluate them inside your compactifyied domain. As I intended to have a general eigenvalue solver, the AIM was a natural candidate.
5. That is a question that is difficult to answer. The AIM is a relatively new method (circa 2003) and only very recently (see [this paper](https://arxiv.org/pdf/2003.06730.pdf)) things like success and failure conditions and why the method actually works robustly were understood formally. As the field progresses I intend to keep up with such developments and keep the underlying math in the package up to date. That being said, I prefer not to make any specific claims about the method's convergence rates in comparison to other methods as they will probably be wrong. It can be shown empirically, as I have, that the method does converge but that in some cases it oscillates and never converges (see the paper I've indicated). Nevertheless, the conditions for success and failure are now understood and the robustness of the method can be mathematically proven. I might one day attempt to make such comparisons but that would be the subject of an entirely new work.

**Comment by pdebuyl** [comment] 2022-04-09 11:55
Thank you @lucass-carneiro for the reply.

@JamieBamber are you happy with the replies and minor changes to the repository?

I see that all the checkboxes are ticked, so is the review done from your side?

**Comment by JamieBamber** [comment] 2022-04-20 15:36
@lucass-carneiro Thank you for your responses, I think they do very much answer my questions. I think I would then consider the review done from my end.

**Comment by pdebuyl** [comment] 2022-04-20 17:58
Thanks @JamieBamber for confirming your acceptance!

@lucass-carneiro I'll proceed soon to the next editorial steps https://joss.readthedocs.io/en/latest/editing.html#after-reviewers-recommend-acceptance

**Comment by lucass-carneiro** [comment] 2022-04-22 19:21
@pdebuyl As per the instructions, I have tagged a new release (v1.1.0) and archived it in Zenodo. Here is the [DOI](https://doi.org/10.5281/zenodo.6478503).

I have also move the paper from the `paper` branch to the `master` branch and deleted the `paper` branch.

**Comment by pdebuyl** [comment] 2022-05-04 19:12
@editorialbot check references

**Comment by pdebuyl** [comment] 2022-05-04 19:13
@editorialbot set master as branch

**Comment by pdebuyl** [comment] 2022-05-04 19:16
@editorialbot generate pdf

**Comment by pdebuyl** [comment] 2022-05-19 13:49
@editorialbot set v1.1.0 as version

**Comment by pdebuyl** [comment] 2022-05-19 13:50
@editorialbot set  10.5281/zenodo.6478503 as archive

**Comment by pdebuyl** [comment] 2022-05-19 14:00
@lucass-carneiro can you edit the metadata of the zenodo archive so that it matches the title and author list of the article?

Also, can you spell out "Journal of Open Source Software" in the bibliography for Stein 2019? Apart for the "J" of "Journal", I don't think that the words can be shortened.

I only ran into one problem while testing the software, it is that I had to explicitly install SymEngine after having installed QuasiNormalModes. It would make sense to make it a run-time dependency but I don't know enough about Julia packaging to know if this is normal or not.

**Comment by lucass-carneiro** [comment] 2022-05-19 18:57
@pdebuyl 
* I have edited the Zenodo archive metadata to match the paper information.
* JOSS is now spelt without abbreviations in the Stein 2019 citation.
* If you are trying to run the tests or examples, activate the project environment using the `--project` flag. Since the tests and examples track their dependencies separately from the main package, everything should work fine without the need to manually download `SymEngine`. If the user is running outside of the `project` environment (which is often the case) and trying to define an analytic problem then `SymEngine` will need to be manually added by the user, even tough it is explicitly defined as a dependency of the main package. There are ways to automate this. If the user is using a `Pluto` notebook for instance, `using` statements will trigger an automatically installation if the packages are not found in the local registry.

**Comment by lucass-carneiro** [comment] 2022-05-20 19:11
@pdebuyl FYI, I have updated the paper to correct an issues where benchmark figures were missing and added new thanks to contributors

**Comment by pdebuyl** [comment] 2022-05-23 12:58
@editorialbot generate pdf

**Comment by pdebuyl** [comment] 2022-05-23 12:58
@editorialbot check references

**Comment by lucass-carneiro** [comment] 2022-05-23 19:54
@pdebuyl I have removed the extraneous citation. Thanks for pointing it out.

**Comment by pdebuyl** [comment] 2022-05-24 13:44
@editorialbot recommend-accept

**Comment by lucass-carneiro** [comment] 2022-05-25 14:43
@arfon Merged! Thanks for the corrections.

**Comment by arfon** [comment] 2022-05-25 14:45
@editorialbot recommend-accept

**Comment by arfon** [comment] 2022-05-25 16:19
@editorialbot accept

**Comment by arfon** [comment] 2022-05-25 16:29
@JamieBamber, @cescalara – many thanks for your reviews here and to @pdebuyl for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@lucass-carneiro – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Closed by arfon** 2022-05-25 16:29 UTC
Labels: accepted, review, Julia, recommend-accept, published
