### ISSUE TITLE
[REVIEW]: PsiRESP: calculating RESP charges with Psi4

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4100] opened 2022-01-26 18:02 UTC
**Submitting author:** @lilyminium (<a href="http://orcid.org/0000-0002-6095-6704">Lily Wang</a>)
**Repository:** https://github.com/lilyminium/psiresp
**Branch with paper.md** (empty if default branch): 
**Version:** 0.3.2
**Editor:** @pdebuyl
**Reviewers:** @ptmerz, @hannahbrucemacdonald
**Archive:** 10.5281/zenodo.6501898

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0/status.svg)](https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0"><img src="https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0/status.svg)](https://joss.theoj.org/papers/e9da64635833d70c0efe66da34b682b0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/lilyminium/psiresp" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@ptmerz, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @pdebuyl know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @ptmerz
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/lilyminium/psiresp">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lilyminium/psiresp">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lilyminium) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @hannahbrucemacdonald
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/lilyminium/psiresp">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/lilyminium/psiresp">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@lilyminium) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2022-01-26 18:03
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @ptmerz it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2022-01-26 18:03
Wordcount for `paper.md` is 1317

**Comment by whedon** [comment] 2022-01-26 18:03
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.27 s (348.3 files/s, 126263.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          47           1357           1617           4955
TeX                              3             49              0            813
XML                              1              0              0            586
YAML                            10             67             56            534
reStructuredText                11            300            308            510
Markdown                        12            145              0            410
Jupyter Notebook                 3              0          22442            160
Bourne Shell                     3              5              8             41
DOS Batch                        1              8              1             27
make                             1              7              8             20
TOML                             1              0              0              4
CSS                              1              0              0              3
JSON                             1              0              0              1
-------------------------------------------------------------------------------
SUM:                            95           1938          24440           8064
-------------------------------------------------------------------------------


Statistical information for the repository '1330ea95e6d8730261fd24a0' was
gathered on 2022/01/26.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Lily Wang                       34         25388          17499          100.00

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Lily Wang                  7889           31.1          2.3                9.33
```

**Comment by whedon** [comment] 2022-01-26 18:03
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1002/jcc.21787 is OK
- 10.25080/Majora-629e541a-00e is OK
- 10.1021/ct200196m is OK
- 10.1002/jcc.540161106 is OK
- 10.1021/ja00074a030 is OK
- 10.1021/j100142a004 is OK
- 10.1039/c0cp00111b is OK
- 10.1093/nar/gkm887 is OK
- 10.1038/s42004-020-0291-4 is OK
- 10.1002/qua.26035 is OK
- 10.1002/jcc.540050204 is OK
- 10.1063/1.1740588 is OK
- 10.1002/(SICI)1096-987X(20000130)21:2<132::AID-JCC5>3.0.CO;2-P is OK
- 10.1002/jcc.540141013 is OK
- 10.1021/jp0667442 is OK
- 10.1021/ja00049a045 is OK
- 10.1063/5.0059356 is OK
- 10.1002/wcms.1491 is OK
- 10.5281/zenodo.5601736 is OK
- 10.1063/5.0005188 is OK
- 10.1002/jcc.540110311 is OK
- 10.1107/S0021889883010985 is OK
- 10.5281/zenodo.4107869 is OK
- 10.1002/wcms.93 is OK
- 10.1063/1.1747632 is OK
- 10.1007/BF00549096 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2022-01-26 18:03
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04100/joss.04100/10.21105.joss.04100.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04100/joss.04100/10.21105.joss.04100.pdf) :page_facing_up: :point_left:

**Comment by pdebuyl** [comment] 2022-01-26 18:07
@ptmerz @hannahbrucemacdonald thanks for accepting to review for JOSS! Make sure to accept the invitation to the reviewers group and to have a look at the reviewer guidelines linked to at the top of this review page.

The review process will happen in this issue page, so questions to the author or to me can be added as comments here.

**Comment by hannahbrucemacdonald** [comment] 2022-01-26 23:07
Hey @pdebuyl  - I think I was missed off at the top as a reviewer, do I need this to get an editable checklist?

thanks!

**Comment by pdebuyl** [comment] 2022-01-27 08:08
Hi @hannahbrucemacdonald indeed, I started the review without adding you as a reviewer in the pre-review stage. Sorry about this. I'll add you and duplicate the the checklist.

**Comment by pdebuyl** [comment] 2022-01-27 08:08
@whedon add @hannahbrucemacdonald as reviewer

**Comment by whedon** [comment] 2022-01-27 08:09
OK, @hannahbrucemacdonald is now a reviewer

**Comment by pdebuyl** [comment] 2022-01-27 08:09
@whedon reinvite @hannahbrucemacdonald

**Comment by whedon** [comment] 2022-01-27 08:09
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by pdebuyl** [comment] 2022-01-27 08:09
@whedon commands

**Comment by whedon** [comment] 2022-01-27 08:10
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by pdebuyl** [comment] 2022-01-27 08:10
@whedon re-invite @hannahbrucemacdonald as reviewer

**Comment by whedon** [comment] 2022-01-27 08:10
The reviewer already has a pending invite.

@hannahbrucemacdonald please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by ptmerz** [comment] 2022-01-28 18:39
Hi @lilyminium, I started the review today. I didn't have time yet to review the package in all details, so I won't comment on it yet, but it definitely looks to be in great shape!

I did review the paper already, and I think it's very well written. A few things I noted:
* The author instructions (https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) ask to start the paper with "a summary of the high-level functionality of your software for a non-specialist reader". This section is missing in your paper.
* I think the Statement of Need section could be split into two sections. Most of this section (from the second paragraph on) actually describes the functionality of the software and isn't a statement of need, so this could be split off in a new section titled "Functionality" or something similar.
* I think you could extend the Statement of Need section to include some real-world use cases. You are doing a great job at explaining the existing packages, and how your package improves upon them, so it would be interesting to add some real-world examples of what these improvements can achieve (or make easier) compared to the existing solutions.
* You are repeatedly adding citations for the same concepts or methods in the different sections. I think that adding citations at the first mentioning is enough and could improve the readability of the remaining text, but maybe @pdebuyl can chime in if there are some editorial recommendations regarding this.

**Comment by lilyminium** [comment] 2022-01-28 23:53
Thanks for your feedback, @ptmerz! I have opened a PR updating the paper at https://github.com/lilyminium/psiresp/pull/68 -- does that  address your comments?

**Comment by ptmerz** [comment] 2022-01-31 15:26
Yes, the changes in the PR look great, thanks! 👍

**Comment by lilyminium** [comment] 2022-02-02 11:51
@whedon generate pdf

**Comment by whedon** [comment] 2022-02-02 11:52
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04100/joss.04100/10.21105.joss.04100.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04100/joss.04100/10.21105.joss.04100.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment] 2022-02-09 18:03
:wave: @ptmerz, please update us on how your review is going (this is an automated reminder).

**Comment by pdebuyl** [comment] 2022-02-11 13:45
Hi @ptmerz and @hannahbrucemacdonald thanks for the review so far!

**Comment by ptmerz** [comment] 2022-02-18 18:47
Two comments regarding version:

* @lilyminium and @pdebuyl: The version given in the first comment of this review is v0.2.4. The version we are reviewing is 0.3.1. I think this was fixed in the pre-review, but this change doesn't seem to have been carried over.
* @lilyminium: The version string of the readthedocs documentation *document title* (the bit that appears in the tab) is 0.1-unstable.

**Comment by lilyminium** [comment] 2022-02-20 05:07
Thanks for pointing that out, @ptmerz! The [latest](https://psiresp.readthedocs.io/en/latest/) docs now properly specify the version as `psiresp v0.3.1+8.g4147f7c.dirty documentation` and `stable` will update on the next release :-)

**Comment by ptmerz** [comment] 2022-02-22 21:42
I thoroughly enjoyed reviewing the package and the paper. Congratulations on a great job @lilyminium!

I am convinced the package will be useful to the community. It addresses a very common problem in molecular simulations. It is feature-rich, very well documented, intuitive to use, and follows Python research software best practices.

The paper is well written and clearly outlines both the need for the software and it's functionality.

All my raised issues have been minor, and most have already been taken care of. I have ticked all review boxes above, since the last remaining issues are extremely minor and I definitely would not see them as blocking issues. Note that I have already ticked the "Community Guidelines" tickbox since the guidelines are about to be introduced in https://github.com/lilyminium/psiresp/pull/70.

I think the software and the paper are a great fit for JOSS and I can confidently recommend it for acceptance.

**Comment by pdebuyl** [comment] 2022-02-25 10:32
Thank you @ptmerz for the review!

**Comment by pdebuyl** [comment] 2022-02-25 10:35
@whedon generate pdf

**Comment by pdebuyl** [comment] 2022-02-25 10:38
@editorialbot generate pdf

**Comment by pdebuyl** [comment] 2022-02-25 10:45
@hannahbrucemacdonald there has been feedback from @lilyminium in reply to your issue and in PR https://github.com/lilyminium/psiresp/pull/70

**Comment by lilyminium** [comment] 2022-02-27 22:57
@editorialbot generate pdf

**Comment by hannahbrucemacdonald** [comment] 2022-02-28 16:50
Hey, sorry for being slow, but I've ticked everything on the list. Really nice work and a nice paper! Well done @lilyminium

**Comment by pdebuyl** [comment] 2022-02-28 21:05
Thank you @hannahbrucemacdonald for the review!

@lilyminium I'll finalize the review by next week, I am off this week.

**Comment by lilyminium** [comment] 2022-03-01 05:00
Thank you @ptmerz and @hannahbrucemacdonald for the reviews and especially your helpful suggestions that made the library much better -- and thank you @pdebuyl for looking after this :-)

**Comment by pdebuyl** [comment] 2022-03-08 14:11
Hi @lilyminium I have some issues with the pip install, I'll get back to you when it is solved. It is not an issue with PsiRESP per se indeed, but given the choice I always try pip first and the postgresql routines in qcfractal are not portable.

**Comment by lilyminium** [comment] 2022-03-10 17:53
@pdebuyl rats, that's annoying. I think QCFractal does have some notes somewhere that installation by pip is not optimal; perhaps it's related. Which architecture are you on? Do you find that it works with conda? I just ask because the `conda install psiresp` package should functionally do a `pip install psiresp`, followed by conda installing the remaining dependencies.

**Comment by pdebuyl** [comment] 2022-03-10 18:10
I use debian. Googling postgresql initdb resulted in interesting finds about debian (and Ubuntu I believe) being different w.r.t. postgresql setup. I'll try once more and if it doesn't work go the conda route.

**Comment by pdebuyl** [comment] 2022-03-25 13:35
I ended up using the conda install. The install page makes it explicit that it is easier but I had a package resolution conflict as well by doing `conda install -c conda-forge psiresp`. I used the file `test_env.yml` in the end and that worked.

The install instructions also state that it is possible to install with `python setup.py install` (after the dependencies have been installed). That made an "egg" installed that did not bring the data. Could you change that part to recommend `pip install .` instead? That worked ok (with conda-installed environment).

**Comment by pdebuyl** [comment] 2022-03-25 13:37
@editorialbot generate pdf

**Comment by pdebuyl** [comment] 2022-03-25 13:37
@editorialbot check references

**Comment by pdebuyl** [comment] 2022-03-25 13:41
Please fix the invalid DOI

**Comment by pdebuyl** [comment] 2022-03-25 13:43
Please verify whether the version number in the top-comment of this page is the good one and publish the reviewed version of psiresp on zenodo. Let me know if you need assistance about this.

**Comment by pdebuyl** [comment] 2022-03-25 13:43
@editorialbot generate pdf

**Comment by pdebuyl** [comment] 2022-03-25 14:31
References:
- Would you have a reference (link to documentation or homepage of the code if there is no paper) for amber and gaussian?
- Can you clean the entry for rdkit?
- for schauperl 2020 there is an article number 44

**Comment by lilyminium** [comment] 2022-03-28 02:27
@editorialbot generate pdf

**Comment by lilyminium** [comment] 2022-03-28 02:27
@editorialbot check references

**Comment by lilyminium** [comment] 2022-03-28 02:29
@pdebuyl yikes, would you recall what the package conflict was? Was it anything to do with `qcfractal`? I'm trying to reproduce on Ubuntu but haven't found anything yet so far.

> The install instructions also state that it is possible to install with python setup.py install (after the dependencies have been installed). That made an "egg" installed that did not bring the data. Could you change that part to recommend pip install . instead? That worked ok (with conda-installed environment).

Thanks, done. Sorry, I was under the impression they were functionally the same thing.

> Please fix the invalid DOI

I think that's supposed to be `10.1002/(SICI)1096-987X(20000130)21:2<132::AID-JCC5>3.0.CO;2-P`, I'm not sure if the bot strips punctuation when it checks. I believe that is what I have in the `paper.bib` file and it is valid: [https://doi.org/10.1002/(SICI)1096-987X(20000130)21:2<132::AID-JCC5>3.0.CO;2-P](https://doi.org/10.1002/(SICI)1096-987X(20000130)21:2<132::AID-JCC5>3.0.CO;2-P)

Here it is in the master branch currently: https://github.com/lilyminium/psiresp/blob/86c1ebf228869ef835933ae5d9bcaff48f0d3d59/paper/paper.bib#L248

> Would you have a reference (link to documentation or homepage of the code if there is no paper) for amber and gaussian?

I think these are already in the paper and cited -- I did clean up the AMBER citation as it was not showing all authors, and change it to 2021. So far as I can tell these are the desired citations.

They are cited in the passages here -- I removed subsequent citations.

> distributed by the AmberTools package (Case et al., 2020).
> It supports quantum chemistry jobs using both the Gaussian (Frisch et al., 2016) 

> Can you clean the entry for rdkit?

Do you mean cleaning up the author vs user names? I am happy to, but I'm pretty new to this and not sure if I should -- the entry for RDKit comes from this [zenodo entry](https://zenodo.org/record/4107869) and has a reasonably unambiguous Bibtex entry / requested citation already. Would that mess anything up for them?

> for schauperl 2020 there is an article number 44

Thanks -- I've added this as a `pages = {44}`. This seems to be the most common way to represent this in bibtex, where there's apparently not a canonical field. Please let me know if it should be something else.

**Comment by lilyminium** [comment] 2022-03-28 02:30
The version reviewed should be 0.3.1, which I've put up on Zenodo here: https://zenodo.org/record/6388137

**Comment by pdebuyl** [comment] 2022-03-28 13:28
Ok, I retried:

```
conda create -n tmpenv python=3
conda activate tmpenv
conda install -c conda-forge psiresp
conda install notebook
```

Installing psiresp triggered Python 3.8 to be selected.

Running example `01_examples_resp_single_server.ipynb` returns

``` py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [5], in <cell line: 1>()
----> 1 from qcfractal import FractalSnowflakeHandler
      3 server = FractalSnowflakeHandler()
      4 print(server)

File /opt/miniconda3/envs/tmpenv/lib/python3.8/site-packages/qcfractal/__init__.py:5, in <module>
      1 """
      2 Main init function for qcfractal
      3 """
----> 5 from . import interface
      6 # Handle versioneer
      7 from .extras import get_information

File /opt/miniconda3/envs/tmpenv/lib/python3.8/site-packages/qcfractal/interface/__init__.py:5, in <module>
      1 """
      2 DQM Client base folder
      3 """
----> 5 from . import collections, data, models, util
      6 # Add imports here
      7 from .client import FractalClient

File /opt/miniconda3/envs/tmpenv/lib/python3.8/site-packages/qcfractal/interface/collections/__init__.py:6, in <module>
      1 """
      2 Python init for QCPortal collections
      3 """
      5 from .collection_utils import collection_factory, collections_name_map, list_known_collections, register_collection
----> 6 from .dataset import Dataset
      7 from .generic import Generic
      8 from .gridoptimization_dataset import GridOptimizationDataset

File /opt/miniconda3/envs/tmpenv/lib/python3.8/site-packages/qcfractal/interface/collections/dataset.py:12, in <module>
      8 import pandas as pd
     10 from qcelemental import constants
---> 12 from ..models import ComputeResponse, KeywordSet, Molecule, ObjectId, ProtoModel
     13 from ..statistics import wrap_statistics
     14 from ..visualization import bar_plot, violin_plot

File /opt/miniconda3/envs/tmpenv/lib/python3.8/site-packages/qcfractal/interface/models/__init__.py:5, in <module>
      1 """
      2 Either pull in QCEl models or local models
      3 """
----> 5 from . import rest_models
      6 from .common_models import (AutodocBaseSettings, KeywordSet, Molecule, ObjectId, OptimizationSpecification, ProtoModel,
      7                             QCSpecification)
      8 from .gridoptimization import GridOptimizationInput, GridOptimizationRecord

File /opt/miniconda3/envs/tmpenv/lib/python3.8/site-packages/qcfractal/interface/models/rest_models.py:6, in <module>
      1 """
      2 Models for the REST interface
      3 """
      4 from typing import Any, Dict, List, Optional, Tuple, Union
----> 6 from pydantic import Schema, constr, validator
      8 from qcelemental.util import get_base_docs
     10 from .common_models import KeywordSet, Molecule, ObjectId, ProtoModel

ImportError: cannot import name 'Schema' from 'pydantic' (/opt/miniconda3/envs/tmpenv/lib/python3.8/site-packages/pydantic/__init__.cpython-38-x86_64-linux-gnu.so)
```

**Comment by pdebuyl** [comment] 2022-03-28 13:34
The reference "jakalian2000" is not cited if I understand correctly, could you thus remove it from the bib file, as well as other non-cited entries?

**Comment by pdebuyl** [comment] 2022-03-28 13:37
rdkit appears as
```
Landrum, G., Tosco, P., Kelley, B., sriniker, gedeck, Ric, Vianello, R., NadineSchneider, Dalke,204
A., N, D., Cole, B., Kawashima, E., Turk, S., Swain, M., AlexanderSavelyev, Cosgrove,205
D., Vaucher, A., Wójcikowski, M., Probst, D., ... Jensen, J. H. (2020). Rdkit/rdkit:206
2020_09_1 (Q3 2020) release (Version Release_2020_09_1) [Computer software]. Zenodo.207
https://doi.org/10.5281/zenodo.4107869
``` 

the ` (Version Release_2020_09_1)` is not necessary, the "version" entry is duplicate with the title (only one could be kept). The `[Computer software]` part is apparently from our bibtex style, sorry about it.

**Comment by pdebuyl** [comment] 2022-03-28 13:40
Regarding Gaussian and Amber, those seem indeed to be the recommended citations, sorry as well. It is a bit weird from them but whatever :-)

**Comment by pdebuyl** [comment] 2022-03-28 13:40
@editorialbot set 0.3.1 as version

**Comment by lilyminium** [comment] 2022-03-28 14:07
@editorialbot check references

**Comment by pdebuyl** [comment] 2022-03-28 14:34
Can you let me know when the plain conda install is working?

Apart from that, all is fine from my point of view, thanks for the updates!

**Comment by pdebuyl** [comment] 2022-04-15 07:58
Hi @lilyminium is the problem solved?

**Comment by lilyminium** [comment] 2022-04-15 16:13
@pdebuyl I added a new build with better pins as mentioned in https://github.com/openjournals/joss-reviews/issues/4100#issuecomment-1080704696, but that means that conda just ignores this new build in favour of the old ones without the pins, and therefore keeps pulling up the old version of qcfractal. I submitted a patch to update pins on the earlier builds https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/249 but that repository seems to move quite slowly, so it has not been reviewed yet.

In the mean time, I updated the installation notes on the PsiRESP to recommend people use mamba (which does not inexplicably favour old qcfractal) or specify their own pins: https://psiresp.readthedocs.io/en/latest/installation.html

That seems to be the only real solution for now, unfortunately.

**Comment by pdebuyl** [comment] 2022-04-19 14:16
`Solving environment: ...`

I'll provide an update but so far conda and mamba are slow.

**Comment by lilyminium** [comment] 2022-04-20 00:41
Thanks @pdebuyl. I didn't find mamba so bad, but `conda` can take forever -- so far as I can tell that's out of my control. I think adding the `--debug` flag can give you low level information on what it's doing.

**Comment by pdebuyl** [comment] 2022-04-22 13:10
Hi @lilyminium 

Status: I could install with `mamba install -n tmpenv3.9 -c conda-forge psiresp==0.3.1 "qcfractal>0.15"`. I understand that psiresp is especially complex to install as it relies on quite elaborate packages that are not otherwise bundled.

I have only two requests before confirming the paper:
1. When running the examples, the user learns about the dependency on psi4 or mdanalysis, has to install and restart the kernel. Can you mention those dependencies visibly at the top of the example file?
2. The example "04_example_rest_minimal.ipynb" is not running because of missing input files.

**Comment by lilyminium** [comment] 2022-04-23 15:28
Hi @pdebuyl, I've done the first change! Unfortunately with regards to the second, that's because I added that example as a response to this review. `04_example_rest_minimal.ipynb` is not actually in version 0.3.1 of the repository, but the next release 0.4.0. That's why the input files are also missing, as they were created specifically for the example.

I looked into a bit and I can't patch a release I've already put on pip or conda -- however, I could make a new 0.3.2 that includes those examples as the only change from 0.3.1, and update the version in this review?

**Comment by pdebuyl** [comment] 2022-04-26 13:25
HI @lilyminium yes, a 0.3.2 release with only the minimal fixes to be able to run the examples properly would be totally ok.

**Comment by lilyminium** [comment] 2022-04-29 17:16
Great @pdebuyl, I've made a version 0.3.2 and put it on Zenodo here: https://zenodo.org/record/6501898 :)

**Comment by pdebuyl** [comment] 2022-05-03 21:47
@editorialbot set 0.3.2 as version

**Comment by pdebuyl** [comment] 2022-05-03 21:47
@editorialbot set 10.5281/zenodo.6501898 as archive

**Comment by pdebuyl** [comment] 2022-05-03 21:48
@editorialbot recommend-accept

**Comment by pdebuyl** [comment] 2022-05-04 07:38
There can be only one ISSN per bib entry. You have to pick one of "online" or "print" only.

**Comment by lilyminium** [comment] 2022-05-04 10:30
Ohh, thanks for that. I've gone through them now :)

**Comment by pdebuyl** [comment] 2022-05-04 10:47
@editorialbot recommend-accept

**Comment by kyleniemeyer** [comment] 2022-05-04 15:09
Congratulations @lilyminium on your article's publication in JOSS!

Many thanks to @ptmerz and @hannahbrucemacdonald for reviewing this, and @pdebuyl for editing.

**Closed by kyleniemeyer** 2022-05-04 15:09 UTC
Labels: accepted, review, TeX, Shell, Python, recommend-accept, published
