### ISSUE TITLE
[REVIEW]: CVtreeMLE: Efficient Estimation of Mixed Exposures using Data Adaptive Decision Trees and Cross-Validated Targeted Maximum Likelihood Estimation in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4181] opened 2022-02-18 19:52 UTC
**Submitting author:** @blind-contours (<a href="http://orcid.org/0000-0002-5515-6307">David McCoy</a>)
**Repository:** https://github.com/blind-contours/CVtreeMLE
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0-joss
**Editor:** @osorensen
**Reviewers:** @GaryBAYLOR, @cpalmer718, @wleoncio
**Archive:** 10.5281/zenodo.7651354

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0/status.svg)](https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0"><img src="https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0/status.svg)](https://joss.theoj.org/papers/e3f631afd3bbcd60ed5d965ce26a39b0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/blind-contours/CVtreeMLE" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@GaryBAYLOR & @cpalmer718, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @osorensen know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @GaryBAYLOR
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/blind-contours/CVtreeMLE">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/blind-contours/CVtreeMLE">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@blind-contours) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @cpalmer718
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/blind-contours/CVtreeMLE">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/blind-contours/CVtreeMLE">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@blind-contours) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2022-02-18 19:52
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @GaryBAYLOR, @cpalmer718 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2022-02-18 19:53
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.26 s (186.7 files/s, 31606.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               39            832           1214           2592
HTML                             1             35              2           1020
Markdown                         3            125              0            872
TeX                              2             55              0            631
Rmd                              2            241            425            180
YAML                             2             12              0             57
-------------------------------------------------------------------------------
SUM:                            49           1300           1641           5352
-------------------------------------------------------------------------------


Statistical information for the repository '3c477f102d988190661a0dcd' was
gathered on 2022/02/18.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment] 2022-02-18 19:53
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1515/ijb-2015-0013 is OK
- 10.2202/1557-4679.1217 is OK
- 10.1111/j.1541-0420.2011.01685.x is OK
- 10.1002/sim.5907 is OK
- 10.1007/978-3-319-65304-4_14 is OK
- 10.1007/978-1-4419-9782-1 is OK
- 10.1007/978-3-319-65304-4 is OK
- 10.2202/1557-4679.1356 is OK
- 10.1111/rssb.12362 is OK
- 10.1111/biom.13375 is OK
- 10.21105/joss.02526 is OK
- 10.5281/zenodo.1342293 is OK
- 10.5281/zenodo.3558313 is OK
- 10.5281/zenodo.3698329 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2022-02-18 19:53
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04181/joss.04181/10.21105.joss.04181.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04181/joss.04181/10.21105.joss.04181.pdf) :page_facing_up: :point_left:

**Comment by GaryBAYLOR** [comment] 2022-03-02 05:10
@osorensen I reviewed the paper and have the following comments. I will take another look after these issues are resolved. Thanks!

Why two licenses https://github.com/blind-contours/CVtreeMLE/issues/2
The package cannot be found in CRAN https://github.com/blind-contours/CVtreeMLE/issues/3
Improve function documentation https://github.com/blind-contours/CVtreeMLE/issues/4
Lightweight editing of the JOSS paper https://github.com/blind-contours/CVtreeMLE/issues/5
Comments on the paper https://github.com/blind-contours/CVtreeMLE/issues/6
Remove R code that are no longer needed https://github.com/blind-contours/CVtreeMLE/issues/7
Comments on README file https://github.com/blind-contours/CVtreeMLE/issues/8
Non reproducible results https://github.com/blind-contours/CVtreeMLE/issues/9

**Comment by cpalmer718** [comment] 2022-03-12 16:32
Hi @osorensen I'm ready to post the review, but I can't edit the checklist message. I'm logged in, and I tried the invitation link but it said it couldn't find an invitation. Can you reinvite me? I apologize if this was (quite likely) because I waited too long to click the link.

**Comment by osorensen** [comment] 2022-03-12 18:29
Thanks for reaching out @cpalmer718. I hope @openjournals/dev can help us with this issue.

**Comment by osorensen** [comment] 2022-03-12 18:31
Or perhaps you could try running the following comment in this issue, @cpalmer718: `@editorialbot generate my checklist`. This should generate a new checklist, which you can edit.

**Comment by cpalmer718** [comment] 2022-03-12 18:34
@editorialbot generate my checklist

**Comment by cpalmer718** [comment] 2022-03-12 18:35
@osorensen oooh excellent, thank you

**Comment by osorensen** [comment] 2022-03-12 18:38
Glad it worked @cpalmer718. Then just use this checklist rather than the one at the top.

**Comment by cpalmer718** [comment] 2022-03-12 21:13
Extended comments/issue links:

- practical test coverage around 4.47%: https://github.com/blind-contours/CVtreeMLE/issues/10
- contribution link broken: https://github.com/blind-contours/CVtreeMLE/issues/8
- I concur about function documentation: https://github.com/blind-contours/CVtreeMLE/issues/4
- package is not on CRAN, as mentioned above; but also the devel version instructions don't work either because there's no `devel` branch. `main` installation with install_github works fine though: https://github.com/blind-contours/CVtreeMLE/issues/11
- vignette needs reworking and editing: https://github.com/blind-contours/CVtreeMLE/issues/12
- additional comments about JOSS paper: https://github.com/blind-contours/CVtreeMLE/issues/5
- runtime performance guidelines: https://github.com/blind-contours/CVtreeMLE/issues/13
- linting: https://github.com/blind-contours/CVtreeMLE/issues/14

**Comment by cpalmer718** [comment] 2022-03-12 21:14
Thanks for having me @osorensen _et al._! Hope it goes well, and I'd be happy to take a second look.

**Comment by osorensen** [comment] 2022-03-13 14:16
Thanks a lot for your review, @cpalmer718. Please notify us when these issues have been resolved, @blind-contours, and don't hesitate to reach out if I can be of any help.

**Comment by blind-contours** [comment] 2022-03-17 18:49
Hi Team, thank you so much for your review and sorry for my delayed response. I'm preparing for my qualifying exam currently. I will begin making edits based on your suggestions soon. Again, thank you for the thorough review, this was extremely helpful!

**Comment by osorensen** [comment] 2022-05-25 06:03
@blind-contours, could you please update us on how it's going with addressing the issues raised by the reviewers?

**Comment by osorensen** [comment] 2022-06-10 04:49
@blind-contours, can you please update us on how it is going with addressing the points raised by the reviewers?

**Comment by osorensen** [comment] 2022-06-19 18:01
@openjournals/joss-eics I have not been able to get in touch with the submitting author @blind-contours, despite repeated attempts. The last response is on 17 March and none of the issues opened by the reviewers in the source repository appear to have been addressed. Could you please consider if this submission should be rejected, with an opportunity to resubmit? I have also searched extensively for the author's e-mail address, but not been able to find it.

Furthermore, the manuscript claims that "The CVtreeMLE package has been made publicly available both via GitHub and the Comprehensive R Archive Network." However, I am not able to find the package on the [Comprehensive R Archive Network](https://cran.r-project.org/).

**Comment by blind-contours** [comment] 2022-06-19 18:52
@osorensen -- sorry for the delay. I've started addressing the issues made by @cpalmer718. My email address is david_mccoy@berkeley.edu, I will add it to the readme and update the link to my bio page. I wasn't able to get the package on CRAN because the SL3 dependency is not on CRAN so I am removing that section of the manuscript and updating the READme. Thank you for your review of this package, I will be responding to issues this week.

**Comment by osorensen** [comment] 2022-06-19 20:18
Thanks @blind-contours. Please keep us updated about the progress.

**Comment by osorensen** [comment] 2022-07-09 16:35
@blind-contours, could you please update us on how it is going addressing the issues opened by the reviewers? It would also be nice if you could give an approximate estimate of how long you expect it will take to resolve the issues.

**Comment by blind-contours** [comment] 2022-07-13 16:56
Hi @osorensen, I have responded to issue #5 and #6 in regards to the JOSS paper submission. Generally, I have added details to elaborate on more abstruse terms and moved parts of different sections around to better match organization. Hopefully these edits meet the reviewers comments but please let me know if there are any other suggestions. The current paper.md is the most updated draft.

**Comment by blind-contours** [comment] 2022-07-13 17:00
Issues #1 and #3 have been resolved - this is regarding CVtreeMLE not being available on CRAN. I've simply removed this from the documentation and download is only available off github as the package currently relies on SL3 for ensemble machine learning. In the future, I can update code to use tidymodels or HAL9001 nonparametric estimators which will allow for CRAN submission but for now this is not available given SL3 is not on CRAN.

**Comment by blind-contours** [comment] 2022-07-13 17:03
I am currently cleaning the existing code to pass linting tests and updating documentation to meet reviewer comments #7, #4, and #14. I expect all issues to be resolved by August 1st.

**Comment by osorensen** [comment] 2022-07-13 17:12
Thanks @blind-contours! It's absolutely fine that this takes some time, but please give a new update on the progress in the beginning of August.

**Comment by blind-contours** [comment] 2022-07-28 20:19
@osorensen et. al., I have made significant changes to the package in response to the JOSS issues page. I have given responses to each and made updates to the package accordingly. I'm still making some small changes but for the most part I believe the new updates are a major improvement in the package given the issues raised by reviewers. This is the first major package I have created so I really appreciate the thorough review. Please let me know what additional changes you would like to see after reviewing what I have already done. Thanks again - really appreciate the time and effort.

**Comment by osorensen** [comment] 2022-07-29 04:11
Thanks a lot for the work, @blind-contours. Could you please update your review checklists based on these latest modifications, @cpalmer718 and @GaryBAYLOR? Please let me know if you have any further questions.

**Comment by osorensen** [comment] 2022-08-21 04:39
👋 @cpalmer718 and @GaryBAYLOR, could you please consider whether the updates made by @blind-contours address your points raised in the reviews, and update your review checklists accordingly?

**Comment by cpalmer718** [comment] 2022-08-21 11:45
Hi @osorensen @blind-contours the package is much improved, and substantial effort has been put into addressing my comments. I'll summarize the following remaining notes:

- the only potentially tough one is that `@import {package}` statements are causing huge bloat to the package namespace. I'd recommend removing all of them, but if you can't avoid it for sl3 for some reason, at least remove it for partykit and especially ggplot2
- the contributions link in the readme still points to nothing
- the paper needs minor editing:
  - there are subject/verb agreement issues (e.g. `Newer mixture methods [...] is biased by`), specifically in the summary
  - I'd recommend splitting the summary text into at least two paragraphs. content is good but it's hard to read as a big block
- markdown in both readme and the vignette has some formatting issues:
  - vignette header text rendered as `## Marginal Results` 
  - assorted links and references in readme render strangely
  - license text in readme and in quote block and in actual license file all differ by year
  - one instance of the license seems to preemptively claim 2023, which isn't a common convention
- consolidate .gitignore files into a single, top-level entry
- remove .DS_Store from repo
  
These are all quite minor, and beyond that I am content.

**Comment by osorensen** [comment] 2022-08-21 13:20
Thanks @cpalmer718!

**Comment by osorensen** [comment] 2022-08-21 13:22
On the occasion, I'd also like to ask @blind-contours about the prospects of submitting this package to CRAN. Although not a strict requirement for publishing in JOSS, it definitely would be an advantage.

**Comment by blind-contours** [comment] 2022-08-25 17:52
Thank you @cpalmer718! As per your first point, I'm looking to reduce the bloat. I am still learning the intricacies of namespaces - are there particular packages you see that are only used via library()? I'll work on your additional comments. Really appreciate your thorough review! It's been a great learning experience.

**Comment by blind-contours** [comment] 2022-08-25 17:59
I would like to get this package on CRAN. The major issue is the ensemble machine learning used to estimate the data adaptive parameter and the nuisance parameters. Because SL3 - the ensemble machine learning package I use, is not on CRAN, and I can't really make it optional while keeping the statistical properties of the estimates, I would need to use a package that is on CRAN and does a type of Super Learning. I believe I can substitute SL3 for tidymodels. So my plan is, once this package is on JOSS (hopefully) to create a new branch for development of transferring the machine learning functions to use tidymodels - this would require a lot of restructuring of the package but would make it available on CRAN.

**Comment by osorensen** [comment] 2022-08-26 08:58
Another example I found while browsing source code. In `simulate_mixture_cube.R` you have the line

```
    dplyr::mutate(rcat = Hmisc::rMultinom(probs, 1))
 ```

but you also write 

```
#' @importFrom Hmisc rMultinom
```

Again, since you use the qualifier `Hmisc::`, the `@importFrom` should be removed here.

**Comment by blind-contours** [comment] 2022-08-26 16:31
@osorensen - thanks so much for the clarification. I think I get it now and will do more research. I'll remove these packages from the namespace.

**Comment by GaryBAYLOR** [comment] 2022-08-28 01:00
@blind-contours I have updated some issues as well as adding a few new issues I detected. I will take time to look at issue #6 and #8 I raised previously given you have updated them.

* updated issues https://github.com/blind-contours/CVtreeMLE/issues/4,  https://github.com/blind-contours/CVtreeMLE/issues/5
* added a few new issues: https://github.com/blind-contours/CVtreeMLE/issues/17, https://github.com/blind-contours/CVtreeMLE/issues/18, https://github.com/blind-contours/CVtreeMLE/issues/19, https://github.com/blind-contours/CVtreeMLE/issues/20

**Comment by osorensen** [comment] 2022-11-02 05:00
@GaryBAYLOR, could you please update us on how it's going addressing the issues raised by the reviewers?

**Comment by blind-contours** [comment] 2022-11-04 21:21
I’ve made some big updates to the package. Currently passes everything with no notes, warnings or errors but it appears something is failed the check with GitHub Linux which I’m trying to figure out. I think it’s just the parallel processing in the vignette on Linux. I think I’ve responded to everything else. Let me know if I can do anything else.

**Comment by osorensen** [comment] 2022-11-05 08:34
Thanks for responding @blind-contours, and sorry @GaryBAYLOR that I wrongly tagged you.

**Comment by osorensen** [comment] 2022-11-05 08:35
@blind-contours, if you think most of the issues raised by the reviewers have been resolved, please tag them with `@username` in the respective issues in the source repository.

**Comment by osorensen** [comment] 2022-12-02 13:28
👋  @GaryBAYLOR and @cpalmer718, could you please check if the points raised in your reviews have now been addressed?

**Comment by cpalmer718** [comment] 2022-12-13 15:59
@osorensen There are still no contributing guidelines and the corresponding link in the readme is broken. I'm fine with the paper at this point, effort has obviously been put in here.

**Comment by osorensen** [comment] 2022-12-13 17:51
Thanks a lot @cpalmer718.

@blind-contours, could you please fix the two remaining issues pointed out by @cpalmer718 and report here when done?

**Comment by osorensen** [comment] 2023-01-02 10:53
> Thanks a lot @cpalmer718.
> 
> @blind-contours, could you please fix the two remaining issues pointed out by @cpalmer718 and report here when done?

@blind-contours, could you please update us on this one?

@GaryBAYLOR could you please update us on how it's going with your review?

**Comment by blind-contours** [comment] 2023-01-04 04:32
@osorensen I have added contributing guidelines and the corresponding link now maps to my website. Package should pass with no notes, warnings, or errors. I'm still making small changes to the vignette and general code streamlining but I think I've responded to all the comments/suggestions at this point. Thank you!

**Comment by osorensen** [comment] 2023-01-04 08:16
Thanks @blind-contours. @cpalmer718 could you please let us know if this addresses you concerns, and update the review checklist if it does?

**Comment by osorensen** [comment] 2023-01-04 20:42
👋 @SaranjeetKaur @calebsjin, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The review of this submission has been going on for a while and the authors has addressed a number of issues, but we have lost contact with one of the reviewers. We would hence very much appreciate the opinion of one or two additional reviewers.

**Comment by cpalmer718** [comment] 2023-01-05 18:41
@osorensen I see the markdown file in the repo, which is good, but the links to it in the readme are broken: e.g. should be `https://github.com/blind-contours/CVtreeMLE/blob/main/contributing.md` but instead is `https://github.com/blind-contours/%20CVtreeMLE/blob/main/CONTRIBUTING.md` (note floating space). Additionally, the article citation in the markdown readme seems to be malformed.

Regardless, I see the contributing doc, so while the above should be fixed, I'll check the thing off. I'm sorry this has languished.

**Comment by osorensen** [comment] 2023-01-05 19:11
Thanks you very much for checking this @cpalmer718, and also for your patience and your thorough review. 

@blind-contours, could you please fix the issues mentioned by @cpalmer718.

**Comment by blind-contours** [comment] 2023-01-05 19:44
Thanks @cpalmer718 I have fixed the issue with the contributing link and have simply removed the citation for now until we get our paper on Arxiv which should happen soon. I will update the readme with the JOSS citation and Arxiv citation once complete.

**Comment by osorensen** [comment] 2023-01-06 07:23
:wave: @tkmamidi, @FrancisXL2019, would any of you be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

The review of this submission has been going on for a while and the authors has addressed a number of issues, but we have lost contact with one of the reviewers. We would hence very much appreciate the opinion of one or two additional reviewers.

**Comment by osorensen** [comment] 2023-01-09 08:08
@blind-contours, just to let you know, since I'm not getting a response from @GaryBAYLOR, I'm trying to find at least another reviewer for this submission.

**Comment by osorensen** [comment] 2023-01-10 08:12
@editorialbot add @wleoncio as reviewer

**Comment by wleoncio** [comment] 2023-01-10 10:18
@editorialbot generate my checklist

**Comment by osorensen** [comment] 2023-01-12 05:17
Perfect, thanks @skiptoniam!

**Comment by osorensen** [comment] 2023-01-12 05:17
@editorialbot add @skiptoniam as reviewer

**Comment by skiptoniam** [comment] 2023-01-13 02:05
@editorialbot generate my checklist

**Comment by osorensen** [comment] 2023-01-18 09:22
Thanks for your review @wleoncio! Looking forward to your response, @blind-contours.

**Comment by blind-contours** [comment] 2023-01-25 22:32
@osorensen I've responded to @wleoncio issues and made updates to the package accordingly. There are still some things I can update moving forward to make installation easier but it should be better now.

**Comment by osorensen** [comment] 2023-01-29 20:56
Thanks @blind-contours. When you have time, please let us know if this addresses you concerns, @wleoncio.

**Comment by wleoncio** [comment] 2023-01-30 13:59
Hi @osorensen,

I think we've made some progress, issues [24](https://github.com/blind-contours/CVtreeMLE/issues/24) and [25](https://github.com/blind-contours/CVtreeMLE/issues/25) are taken care of, and [23](https://github.com/blind-contours/CVtreeMLE/issues/23) and [26](https://github.com/blind-contours/CVtreeMLE/issues/26) may be left as future improvements.

Regarding [27](https://github.com/blind-contours/CVtreeMLE/issues/27), however, I'd like to hear back from @blind-contours once more about the possibility of further reducing test times.

**Comment by wleoncio** [comment] 2023-01-31 05:12
Dear @osorensen,

Happy to report all my concerns with this submission have been addressed.

**Comment by osorensen** [comment] 2023-01-31 05:24
Thanks a lot for your review @wleoncio!

**Comment by osorensen** [comment] 2023-01-31 05:25
@wleoncio could you then please also check the missing boxes in your review checklist a bit further up in this thread?

**Comment by osorensen** [comment] 2023-01-31 05:26
👋 @skiptoniam could you please update us on how it's going with your review?

**Comment by blind-contours** [comment] 2023-02-08 21:52
Is there anything else I can do to help expedite this review process?

**Comment by osorensen** [comment] 2023-02-09 04:18
> Is there anything else I can do to help expedite this review process?

I'm afraid not, but since we now have two reviewers approving the package, if we don't hear back from @GaryBAYLOR or @skiptoniam within two weeks, I'll move forward with accepting the submission.

**Comment by GaryBAYLOR** [comment] 2023-02-12 01:22
Hi @osorensen, thank you for your patience in waiting for my review results. I checked all previous open issues and added a new one today, all of which have now been addressed by the author with the exception of only this one:  https://github.com/blind-contours/CVtreeMLE/issues/2.After this is addressed, I am good on my end.

Refer to https://github.com/blind-contours/CVtreeMLE/issues?q=is%3Aissue+is%3Aclosed for all closed issues.

**Comment by blind-contours** [comment] 2023-02-12 02:02
I just addressed this issue related to the license: https://github.com/blind-contours/CVtreeMLE/issues/2

**Comment by GaryBAYLOR** [comment] 2023-02-12 02:40
@osorensen, all open issues on my end have been addressed.

**Comment by osorensen** [comment] 2023-02-12 03:09
Thank you very much @GaryBAYLOR

**Comment by osorensen** [comment] 2023-02-13 12:06
@editorialbot generate pdf

**Comment by osorensen** [comment] 2023-02-13 12:06
@editorialbot check references

**Comment by blind-contours** [comment] 2023-02-16 19:43
New PDF is compiled and in the package with these edits.

**Comment by blind-contours** [comment] 2023-02-17 02:19
The only last thing is getting the package to install on Windows via github actions, I keep getting this error: 
 
cannot open file 'C:\Users\RUNNER~1\AppData\Local\Temp\RtmpoZc4PS\xshell1a402bd4033': Permission denied

I can't find a solution to this - have any of the reviewers seen this Windows error before? I'd just like this to show green checks on all operating systems per reviewers requests.

**Comment by wleoncio** [comment] 2023-02-17 05:19
Doesn't ring a bell, but notice how the installation of TinyTeX also doesn't go smoothly.

Perhaps updating your r-lib setup versions (see template [here](https://github.com/r-lib/actions/tree/v2-branch/examples#standard-ci-workflow)) helps. The new versions may even allow you to remove some manual installation commands from your YAML as well (namely, TinyTeX and the package dependencies).

**Comment by osorensen** [comment] 2023-02-17 06:39
@editorialbot generate pdf

**Comment by osorensen** [comment] 2023-02-17 06:43
@editorialbot check references

**Comment by osorensen** [comment] 2023-02-17 06:46
@blind-contours; in the references list, Keil et al. (2019) is listed as an arXiv preprint, but the doi points me to a paper in Environmental Epidemiology. Could you please correct this reference?

**Comment by blind-contours** [comment] 2023-02-17 18:43
Fixed.

**Comment by osorensen** [comment] 2023-02-17 20:12
@editorialbot generate pdf

**Comment by osorensen** [comment] 2023-02-17 20:12
@editorialbot check references

**Comment by osorensen** [comment] 2023-02-17 20:14
@blind-contours, at this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with recommending acceptance of the submission.

**Comment by osorensen** [comment] 2023-02-17 20:15
@editorialbot generate pdf

**Comment by blind-contours** [comment] 2023-02-17 21:26
@osorensen 

I've created a new release at https://github.com/blind-contours/CVtreeMLE/releases/tag/v1.0-joss 

and a Zenodo archive of that release at https://zenodo.org/record/7651354

The DOI for that release is 10.5281/zenodo.7651354

**Comment by osorensen** [comment] 2023-02-18 07:43
@editorialbot set 10.5281/zenodo.7651354 as archive

**Comment by osorensen** [comment] 2023-02-18 07:43
@editorialbot set v1.0 as version

**Comment by osorensen** [comment] 2023-02-18 07:45
@cpalmer718 and @GaryBAYLOR, I want to thank both of you for your incredibly useful and thorough reviews, which have helped improve this submission a lot. Also thanks for your patience in the process.

Thanks to @wleoncio for coming in and give an additional review, which makes sure that this submission now has really good quality.

**Comment by osorensen** [comment] 2023-02-18 07:45
@editorialbot recommend-accept

**Comment by GaryBAYLOR** [comment] 2023-02-18 16:38
@osorensen I'm glad to see the paper is now accepted, and it's my pleasure to participate in the review process! Congratulations! @blind-contours

**Comment by blind-contours** [comment] 2023-02-18 16:50
@wleoncio, @cpalmer718 , @GaryBAYLOR , @osorensen - thank you all for the time you have spent reviewing and improving this package. This is my first piece of software that operationalizes a statistical method I created and I have just learned so much! Really appreciate the support.

**Comment by Kevin-Mattheus-Moerman** [comment] 2023-02-21 13:27
@blind-contours I am the AEiC for this track and here to help process the last steps. I've checked the archive and paper and have some minor comments that need your attention: 

On the archive: 
- [ ] The version tag on your repository is called `v1.0-joss`, while here and on ZENODO it is listed as `v1.0`. These need to match. Please check if you can either: rename the release on GitHub to match `v1.0` OR update the version here (I can do this) and on ZENODO to match `v1.0-joss`. 
- [ ] The ZENODO listed license (currently listed as ` Creative Commons Attribution 4.0 International`) should match the software license which is the MIT license. 

On the paper: 
- [ ] Check/fix `heterogenous` -> `heterogeneous`

**Comment by blind-contours** [comment] 2023-02-21 16:36
Hi @Kevin-Mattheus-Moerman, I've changed the version on ZENODO to v1.0-joss and changed the license to MIT. I've also made and pushed the fix for heterogeneous in the paper and updated the affiliations. Let me know if you need anything else.

**Comment by Kevin-Mattheus-Moerman** [comment] 2023-02-21 17:15
@editorialbot set v1.0-joss as version

**Comment by Kevin-Mattheus-Moerman** [comment] 2023-02-21 17:24
@editorialbot generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment] 2023-02-21 17:38
@editorialbot accept

**Comment by Kevin-Mattheus-Moerman** [comment] 2023-02-21 21:58
Congratulations on this publication @blind-contours !

Thanks for editing @osorensen! 

And a special thanks to the reviewers: @GaryBAYLOR, @cpalmer718, @wleoncio !

**Closed by Kevin-Mattheus-Moerman** 2023-02-21 21:58 UTC
Labels: accepted, review, TeX, R, recommend-accept, published, Track: 2 (BCM)
