### ISSUE TITLE
[REVIEW]: PERFORM: A Python package for developing reduced-order models for reacting fluid flows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3428] opened 2021-06-28 20:23 UTC
**Submitting author:** @cwentland0 (<a href="http://orcid.org/0000-0002-8500-569X">Christopher Wentland</a>)
**Repository:** https://github.com/cwentland0/perform
**Branch with paper.md** (empty if default branch): paper
**Version:** v0.2.1
**Editor:** @kyleniemeyer
**Reviewers:** @Himscipy, @kyleniemeyer
**Archive:** 10.5281/zenodo.7302346

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/690515fb80b2e2c5d7635084159f2cae/status.svg)](https://joss.theoj.org/papers/690515fb80b2e2c5d7635084159f2cae)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/690515fb80b2e2c5d7635084159f2cae"><img src="https://joss.theoj.org/papers/690515fb80b2e2c5d7635084159f2cae/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/690515fb80b2e2c5d7635084159f2cae/status.svg)](https://joss.theoj.org/papers/690515fb80b2e2c5d7635084159f2cae)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/cwentland0/perform" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@clemaitre58 & @Himscipy, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @kyleniemeyer know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/cwentland0/perform">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@cwentland0) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2021-06-28 20:23
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @clemaitre58, @Himscipy it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-06-28 20:23
PDF failed to compile for issue #3428 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment] 2021-06-28 20:24
👋 Hello @cwentland0 @clemaitre58 @Himscipy we will perform the actual review in this issue. Thanks!

**Comment by kyleniemeyer** [comment] 2021-06-28 20:24
@whedon generate pdf from branch paper

**Comment by whedon** [comment] 2021-06-28 20:24
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-06-28 20:24
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03428/joss.03428/10.21105.joss.03428.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03428/joss.03428/10.21105.joss.03428.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment] 2021-07-12 20:23
:wave: @clemaitre58, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment] 2021-07-12 20:23
:wave: @Himscipy, please update us on how your review is going (this is an automated reminder).

**Comment by Himscipy** [comment] 2021-07-28 21:29
@kyleniemeyer, I am unable to check mark the actions in the reviewers checklist.

**Comment by danielskatz** [comment] 2021-07-28 21:45
@whedon re-invite @Himscipy as reviewer

**Comment by whedon** [comment] 2021-07-28 21:45
The reviewer already has a pending invite.

@himscipy please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by Himscipy** [comment] 2021-07-29 15:53
@danielskatz,
I clicked the link but it say's the invitation has expired.

**Comment by danielskatz** [comment] 2021-07-29 15:59
@whedon re-invite @Himscipy as reviewer
let's try again

**Comment by whedon** [comment] 2021-07-29 15:59
OK, the reviewer has been re-invited.

@himscipy please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by danielskatz** [comment] 2021-07-29 15:59
@whedon re-invite @Himscipy as reviewer

**Comment by whedon** [comment] 2021-07-29 15:59
The reviewer already has a pending invite.

@himscipy please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by cwentland0** [comment] 2021-07-29 17:42
@kyleniemeyer A question, since I'm unfamiliar with software journal reviews in general, especially so when I first submitted this back in April. There have been some significant changes to the code in a couple branches that will soon be merged, including general expansions of capabilities and some class names which were explicitly mentioned in the paper. Should I update the paper to reflect these changes once they're merged (or at the very least, remove any specific references to class names, which was a naive mistake on my part)? I understand the reviewers may have already looked over the paper, but I figure these changes would be mostly superficial, and would not change the bulk of its content. I know there's usually some back and forth with editing, I just don't want to waste any of the reviewers' time.

**Comment by kyleniemeyer** [comment] 2021-07-29 17:48
@cwentland0 good question - this is always tough when software continues to evolve while under review. Minor edits to the paper are fine, especially if you summarize the changes in here for us.

Larger edits to the software, that change capabilities and would essentially require a re-review, should probably wait, so that the version mentioned with a JOSS article is actually the version reviewed.

**Comment by cwentland0** [comment] 2021-07-29 17:59
Maybe "significant changes" was a little overblown on my part. To be more specific, the changes will add two more classes of ROM methods, which would amount to adding two more sub-bullet points under the current "ROMs" bullet point on page 3. Would you consider that a larger edit?

**Comment by kyleniemeyer** [comment] 2021-07-29 18:14
@cwentland0 that sounds ok to me

**Comment by cwentland0** [comment] 2021-07-29 18:15
Great, thanks for the help!

**Comment by Himscipy** [comment] 2021-08-29 19:47
👋🏼  Hi @cwentland0 , Thank you for submitting the paper+ software to JOSS. The developed package will really a nice addition to the scientific community both for research and academic purpose. 
I am currently reviewing your code base, one thing which I caught my attention is that "testing" of any sort is missing in the code base. Tests plays a crucial role for any software package and is one of the essential components in the JOSS submissions acceptance criteria, therefore I would like to recommend that you add these testing procedures to the code base. Thank you.

**Comment by cwentland0** [comment] 2021-08-30 14:37
@Himscipy thank you for taking the time to review the code. You're right, I haven't implemented anything in the way of rigorous unit or regression tests, I've only provided a few pre-set cases to ensure base functionality of the solver and few ROMs. I'll get to work on a better testing framework.

**Comment by kyleniemeyer** [comment] 2021-10-13 19:55
@cwentland0 understood, thanks for the update!

**Comment by cwentland0** [comment] 2021-12-06 17:53
Hi all, just wanted to give an update. I have put together a fairly thorough testing framework of unit, integration, and regression tests which can be found in the `tests/` directory. Instructions for manually running the tests have been included in the `README`. Additionally, I have added continuous integration via GitHub Actions, which automatically executes unit and integration tests and reports code coverage via the Coveralls API. Regression tests are run nightly and aren't included in the code coverage. Hopefully this covers the testing requirement.

Additionally, I have made minor changes to the paper to a) sanitize it of any specific mention of class names, since those might change and evolve over time, and b) add a citation for a recent paper that has used PERFORM. No other substantive changes were made to the paper. I had to make a Zenodo DOI for the repository to make the code citeable for collaborators, I think I recall that this can be substituted for the JOSS paper DOI in the event of acceptance?

Thank you for your patience!

**Comment by cwentland0** [comment] 2021-12-06 17:53
@whedon generate pdf from branch paper

**Comment by whedon** [comment] 2021-12-06 17:53
```
Attempting PDF compilation from custom branch paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-12-06 17:54
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03428/joss.03428/10.21105.joss.03428.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03428/joss.03428/10.21105.joss.03428.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment] 2022-01-21 23:19
@cwentland0 thanks for the update! (And sorry it took so long for me to get back to this.) Yes, we will use the Zenodo DOI of the repo, though you will also get one for the paper itself.

@Himscipy can you possibly take another look at the updates, to see if your issues are now satisfied?

@clemaitre58 are you still able to review this submission?

**Comment by Himscipy** [comment] 2022-02-14 04:25
Hi 👋  @kyleniemeyer,

I have completed my review checklist for PERFORM. 
@cwentland0 PERFORM software tool is a great addition to the research and engineering teaching community. 

Best,
Himanshu Sharma

**Comment by kyleniemeyer** [comment] 2022-03-16 15:11
Hello @clemaitre58, are you able to review this submission?

@Himscipy thanks for your feedback!

**Comment by cwentland0** [comment] 2022-04-13 19:29
Just checking in, is there anything I can do to help with your review @clemaitre58 ? Happy to answer any questions or resolve any issues.

**Comment by kyleniemeyer** [comment] 2022-05-05 19:17
@cwentland0 unfortunately it looks like we might need to find another reviewer. I will send out a few requests.

**Comment by kyleniemeyer** [comment] 2022-05-05 19:18
Hello @tupi @dlagrava @ctdegroot would any of you be available to review this submission for JOSS? It's been under review for a while now, with one complete review. Thanks!

**Comment by dlagrava** [comment] 2022-05-11 12:57
@kyleniemeyer  hope you are well. I am currently super busy, so I won't be able to do the review. Sorry!

**Comment by ctdegroot** [comment] 2022-05-24 15:53
Hi All,

Apologies for the late reply, however, I am currently on parental leave and cannot help on this one.
Cheers,

Chris

**Comment by arfon** [comment] 2022-08-05 19:59
:wave: @kyleniemeyer – a friendly bump to identify a second reviewer here.

**Comment by cwentland0** [comment] 2022-08-15 14:40
@kyleniemeyer Just checking in again, happy to look through the reviewer list to suggest a second reviewer, let me know how I can help.

**Comment by kyleniemeyer** [comment] 2022-08-15 17:48
I will go ahead and do the second review for this one, which I should be able to get to this week.

**Comment by kyleniemeyer** [comment] 2022-08-15 17:48
@editorialbot add me as reviewer

**Comment by kyleniemeyer** [comment] 2022-08-15 17:48
@editorialbot remove @clemaitre58 as reviewer

**Comment by kyleniemeyer** [comment] 2022-08-15 17:49
@editorialbot generate my checklist

**Comment by cwentland0** [comment] 2022-08-31 13:54
Hi @kyleniemeyer , do you think you'll be able to get to this this week? I only ask because a collaborator is asking to reference the paper if it's finished this week. Otherwise I'll just ask them to cite the Zenodo DOI, so no worries either way!

**Comment by kyleniemeyer** [comment] 2022-09-02 12:17
@cwentland0 sorry, I have not been able to get to this, and don't think I realistically will until at least the holiday on Monday.

**Comment by cwentland0** [comment] 2022-10-20 18:13
Just quickly updated a reference that has since been formally published, and added a new reference that used PERFORM and has been added to arXiv.

**Comment by cwentland0** [comment] 2022-10-20 18:13
@whedon generate pdf from branch paper

**Comment by cwentland0** [comment] 2022-10-20 18:14
@editorialbot generate pdf from branch paper

**Comment by cwentland0** [comment] 2022-10-20 18:14
@editorialbot commands

**Comment by cwentland0** [comment] 2022-10-20 18:15
@editorialbot set paper as branch

**Comment by cwentland0** [comment] 2022-10-20 18:15
@editorialbot generate pdf

**Comment by cwentland0** [comment] 2022-10-20 18:18
@editorialbot generate pdf

**Comment by kyleniemeyer** [comment] 2022-10-21 18:07
Hi @cwentland0, sorry for my (extreme) delay here. I was able to install and run the package, including the tests and examples.

A few comments:
- Your testing approach is not very standard—have you considered setting things up to work with a standard tool like pytest? This would allow automated running of tests. (You can also specify the additional optional/testing requirement of TensorFlow in the `setup.py` file.)
- Related, but some indication that the regression tests are going to take a while would be nice...
- Regarding the command-line interface, have you considered allowing users to specify the input file, rather than requiring them to have a rigid directory/file-naming structure?
- The Python community has moved away from using `setup.py` with `setuptools` to `pyproject.toml` as the standard. I realize you submitted this a while ago, but moving forward you should probably switch to that system.

**Comment by cwentland0** [comment] 2022-10-21 18:55
Hey @kyleniemeyer no worries, thank you for reviewing! Addressing your comments:

- I remember looking into `nose`, `pytest`, and `unittest`, and ended up opting for `unittest` since it seemed the simplest. I can look into using `nose` if that would be considered more standard? From what I can tell that would require less rewriting of the original testing code.
- I apologize for the long regression tests, I will definitely add in a warning when it asks for confirmation to run them!
- Command line input file specification definitely crossed my mind, I can add that in very simply while leaving the current setup as the default if the user doesn't supply an input file path.
- Looks like adding `pyproject.toml` would be fairly simple from a cursory overview. From what I can tell, though, `pyproject.toml` does not permit an editable install like `pip install -e`. Since the idea for PERFORM is that folks can easily expand the code, it would still need an editable install, but from what I'm reading it seems like they can coexist.

I can get the last three things done today, if you would like the tests to be rewritten with `pytest` that will take a bit longer.

**Comment by kyleniemeyer** [comment] 2022-10-22 13:09
@cwentland0 

> I remember looking into nose, pytest, and unittest, and ended up opting for unittest since it seemed the simplest. I can look into using nose if that would be considered more standard? From what I can tell that would require less rewriting of the original testing code.

I think that `pytest` is probably the widest used right now, and is what I would consider the modern "standard". From my understanding folks have moved away from `nose`, actually. To be compatible with `pytest`, you just have to have your test files and the classes/functions inside that start with the word "test", essentially, which shouldn't require *too* much work. 
But, I 

> I apologize for the long regression tests, I will definitely add in a warning when it asks for confirmation to run them! Command line input file specification definitely crossed my mind, I can add that in very simply while leaving the current setup as the default if the user doesn't supply an input file path.



> Looks like adding pyproject.toml would be fairly simple from a cursory overview. From what I can tell, though, pyproject.toml does not permit an editable install like pip install -e. Since the idea for PERFORM is that folks can easily expand the code, it would still need an editable install, but from what I'm reading it seems like they can coexist.

You actually can still use a `pyproject.toml` approach with an editable install: https://www.python.org/dev/peps/pep-0660/

**Comment by cwentland0** [comment] 2022-10-30 21:16
I've merged the changes for the latter three points into the main branch (including replacing `setup.py` with `pyproject.toml`). For now I'm going to keep using `unittest` but will consider using `pytest` moving forward. Please let me know if there's anything else you'd like me to address!

**Comment by kyleniemeyer** [comment] 2022-11-02 18:56
@cwentland0 looks good! My only last comment is that *technically* those changes should probably warrant a small version change, like to 0.1.1

**Comment by cwentland0** [comment] 2022-11-08 02:59
Just updated the `pyproject.toml` and made a tagged release. Actually updated to 0.2.1, as I labelled the last release as 0.2, I just wasn't careful to update it in the setup.py then!

**Comment by kyleniemeyer** [comment] 2022-11-08 03:12
@cwentland0 great! at this point please archive the repository (e.g., on Zenodo) and provide the DOI here.

FYI, moving forward, you might consider encoding the version number in a file (e.g., `_version.py`) and then have `pyproject.toml` read that in dynamically.

**Comment by cwentland0** [comment] 2022-11-08 03:15
The Zenodo DOI is:
10.5281/zenodo.7302346

**Comment by kyleniemeyer** [comment] 2022-11-08 03:23
@editorialbot set 10.5281/zenodo.7302346 as archive

**Comment by kyleniemeyer** [comment] 2022-11-08 03:23
@editorialbot set v0.2.1 as version

**Comment by kyleniemeyer** [comment] 2022-11-08 03:23
@editorialbot recommend-accept

**Comment by kyleniemeyer** [comment] 2022-11-08 03:31
@cwentland0 just a few last changes for the paper: could you add the arXiv DOIs for the two arXiv citations? 10.48550/arXiv.2003.07798 and 10.48550/arXiv.2209.06957

No need to update the Zenodo archive

**Comment by cwentland0** [comment] 2022-11-08 03:54
arXiv citations have been updated on the paper branch

**Comment by kyleniemeyer** [comment] 2022-11-08 03:56
@editorialbot generate pdf

**Comment by kyleniemeyer** [comment] 2022-11-08 03:59
@editorialbot accept

**Comment by kyleniemeyer** [comment] 2022-11-08 04:04
Congratulations @cwentland0 on your article's publication in JOSS! And thanks for your patience during this process.

Many thanks to @Himscipy for reviewing.

**Closed by kyleniemeyer** 2022-11-08 04:05 UTC
Labels: accepted, review, Python, recommend-accept, published, Track: 3 (PE)

**Comment by cwentland0** [comment] 2022-11-08 04:08
Thank you so much @Himscipy and @kyleniemeyer for all your time and patience!
