### ISSUE TITLE
[PRE REVIEW]: bayesGARCH: Bayesian Estimation of the GARCH(1,1) Model with Student-t Innovations in R

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#148] opened 2016-12-26 02:51 UTC
**Submitting author:** @ArdiaD (<a href="http://orcid.org/0000-0003-2823-782X">David Ardia</a>)
**Repository:** <a href="https://github.com/ArdiaD/bayesGARCH" target ="_blank">https://github.com/ArdiaD/bayesGARCH</a>
**Version:** 2.0.2
**Editor:** Pending
**Reviewer:** Pending

**What this issue is for**

Thanks for submitting your paper to JOSS @ArdiaD. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2016-12-26 02:51
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment] 2016-12-29 22:42
@noamross - is this a good candidate for rOpenSci?

**Comment by noamross** [comment] 2016-12-29 23:32
Thanks for checking.  We don't do statistical methods packages; our [**scope**](https://github.com/ropensci/onboarding/blob/master/policies.md#package-fit) is limited to data access, extraction, manipulation and facilitating reproducible workflows.

**Comment by arfon** [comment] 2017-01-04 11:40
👋  @pboesu - would you be willing to review this submission for JOSS?

**Comment by pboesu** [comment] 2017-01-05 17:05
Hi @arfon , I'm happy to review this one, but I will not be able to get started with the review until mid-January. So if there are other (or additional) willing reviewers I'm happy to for them to have a go first.

**Comment by pboesu** [comment] 2017-01-05 17:11
Hi @arfon, @ArdiaD, 
as in #147 this appears to be a duplicate of an article already published. This time in the R Journal: https://journal.r-project.org/archive/2010-2/RJournal_2010-2_Ardia+Hoogerheide.pdf

**Comment by arfon** [comment] 2017-01-05 17:23
> Hi @arfon, @ArdiaD,
as in #147 this appears to be a duplicate of an article already published. This time in the R Journal: https://journal.r-project.org/archive/2010-2/RJournal_2010-2_Ardia+Hoogerheide.pdf

Good catch @pboesu. @ArdiaD - is there a reason why you've submitted to JOSS when this (and #147) appears to have been published already?

**Comment by ArdiaD** [comment] 2017-01-05 17:52
See my comments on GitHub.

Btw, this is not a good catch; nothing has been hidden, as in both JOSS abstract, the various publications are cited…

I guess I misunderstood the goal of JOSS, as I thought this was for package DOI and not in conflict with R journal of JSS.

**Comment by pboesu** [comment] 2017-01-05 18:19
@ArdiaD JOSS issues crossref DOIs for the software meta papers, but uses zenodo or figshare DOIs for the code archives. The latter are easily obtained without the need for a JOSS submission e.g. by using the existing integration between github and zenodo: https://guides.github.com/activities/citable-code/

**Comment by ArdiaD** [comment] 2017-01-05 18:22
I see; then please accept my apologizes and close both submissions. Thanks again for your time and feedback.

**Comment by arfon** [comment] 2017-01-05 20:31
> Btw, this is not a good catch; nothing has been hidden, as in both JOSS abstract, the various publications are cited…

Yes, totally agreed. My apologies for a poor choice of language here @ArdiaD. 

As @pboesu suggested, you might like to look at the Zenodo/GitHub integration that we use a lot here: https://guides.github.com/activities/citable-code/

**Comment by ArdiaD** [comment] 2017-01-05 21:26
Thanks, this is now done for both packages. So I guess you can remove both submissions. 
@arfon No worries, this is my mistake.
@pboesu Thanks for your help.

**Comment by ArdiaD** [comment] 2017-01-05 21:54
@arfon short question. I have other packages for which I would like to have a DOI. Can I first create a DOI via Zenodo, and then submit to JOSS, or should I submit directly to JOSS? NB: these packages have not been published elsewhere.

**Comment by arfon** [comment] 2017-01-05 22:56
> Can I first create a DOI via Zenodo, and then submit to JOSS, or should I submit directly to JOSS? NB: these packages have not been published elsewhere.

Generally we recommend authors make the archive DOI (with Zenodo) at _the end_ of the JOSS review process because there are usually changes required as part of the review (which should be captured in the archive).

**Closed** 2017-01-05 23:07 UTC
Labels: pre-review
