### ISSUE TITLE
[REVIEW]: yadg: yet another datagram

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4166] opened 2022-02-15 00:50 UTC
**Submitting author:** @PeterKraus (<a href="http://orcid.org/0000-0002-4359-5003">Peter Kraus</a>)
**Repository:** https://github.com/dgbowl/yadg
**Branch with paper.md** (empty if default branch): 
**Version:** v4.0.0
**Editor:** @galessiorob
**Reviewers:** @aozorahime, @1mikegrn, @pythonpanda2
**Archive:** 10.5281/zenodo.6413504

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3/status.svg)](https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3"><img src="https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3/status.svg)](https://joss.theoj.org/papers/88a0f9f20c0719d399fbbae73df0a5a3)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/dgbowl/yadg" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@aozorahime, @pythonpanda2 & @1mikegrn, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @galessiorob know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @aozorahime
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/dgbowl/yadg">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dgbowl/yadg">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@PeterKraus) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @1mikegrn
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/dgbowl/yadg">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dgbowl/yadg">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@PeterKraus) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @pythonpanda2
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/dgbowl/yadg">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [ ] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [ ] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [ ] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/dgbowl/yadg">repository url</a>?
- [ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Contribution and authorship:** Has the submitting author (@PeterKraus) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [ ] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [ ] **Installation:** Does installation proceed as outlined in the documentation?
- [ ] **Functionality:** Have the functional claims of the software been confirmed?
- [ ] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [ ] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [ ] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [ ] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [ ] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [ ] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [ ] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2022-02-15 00:50
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @aozorahime, @1mikegrn it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2022-02-15 00:50
Wordcount for `paper.md` is 1191

**Comment by whedon** [comment] 2022-02-15 00:50
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=4.54 s (29.7 files/s, 133925.8 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
JSON                            34              0              0         596261
Python                          67           1203           2252           6820
reStructuredText                21            245            360            587
SVG                              2              2              2            349
YAML                             7              9             20            224
TeX                              1             21              0            205
Markdown                         2             23              0             70
TOML                             1              0              0              6
-------------------------------------------------------------------------------
SUM:                           135           1503           2634         604522
-------------------------------------------------------------------------------


Statistical information for the repository '546042009554621630cac07e' was
gathered on 2022/02/15.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Kraus                            1            74             73            0.48
Kraus, Peter                    16          3924           1935           19.10
Nicolas Vetsch                   1           544              0            1.77
Peter Kraus                     29          3410           1290           15.32
Vetsch, Nicolas                  2          1940            169            6.87
krpe                            88          6880           4842           38.21
vetschn                         44          2983           2617           18.25

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Kraus, Peter               6626          168.9          3.0                2.81
Nicolas Vetsch              544          100.0          0.9                6.25
Peter Kraus                 336            9.9          5.5               12.50
Vetsch, Nicolas            2764          142.5          1.4                6.22
vetschn                       5            0.2          3.2                0.00
```

**Comment by whedon** [comment] 2022-02-15 00:50
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1038/s41586-020-2649-2 is OK
- 10.33774/chemrxiv-2021-mh17g is OK
- 10.1002/cctc.202001132 is OK
- 10.1186/1471-2105-13-115 is OK
- 10.3847/1538-3881/aabc4f is OK
- 10.1007/s11244-020-01380-2 is OK
- 10.1038/sdata.2016.18 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2022-02-15 00:51
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04166/joss.04166/10.21105.joss.04166.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04166/joss.04166/10.21105.joss.04166.pdf) :page_facing_up: :point_left:

**Comment by galessiorob** [comment] 2022-02-21 19:34
👋 @aozorahime, @1mikegrn, @pythonpanda2

Thanks again for volunteering to review this paper. Could you please update us in your ETA? Also, let me know if you have any questions ion the criteria or the process. 🙇‍♀️

**Comment by 1mikegrn** [comment] 2022-02-21 23:26
Hi everyone 👋🏻 @galessiorob I'm hoping to get my initial review at least started today, hopefully finished as well.

**Comment by 1mikegrn** [comment] 2022-02-22 00:37
Overall I feel like this is a very well put together package - most of my critiques are minor things like unused imports and whatnot. I don't have any major concerns for which I would expect any sort of revision. 👍🏻 I also noticed that there's some CI/CD built in from gitlab, I don't use gitlab so I didn't verify any of that, but I was able to easily install the package and run the test suite in a generic docker container, so I'd call it close enough 🤷🏻‍♂️.

**Comment by aozorahime** [comment] 2022-02-22 02:37
Hi, i am doing this right now. hopefully can finish it tonight or tomorrow @galessiorob

**Comment by PeterKraus** [comment] 2022-02-22 05:58
> Overall I feel like this is a very well put together package - most of my critiques are minor things like unused imports and whatnot. I don't have any major concerns for which I would expect any sort of revision. 👍🏻 I also noticed that there's some CI/CD built in from gitlab, I don't use gitlab so I didn't verify any of that, but I was able to easily install the package and run the test suite in a generic docker container, so I'd call it close enough 🤷🏻‍♂️.

We've moved the package from our internal gitlab server back to github fairly recently. The gitlab repo is now archived and only the main repo on here is used. I forgot to remove the gitlab CI files after the migration. The github actions now replicate the CI functionality (with testing of every PR on Windows and Linux), including a docs deployment after every commit to master. If you have any suggestions how to improve this, I'm all ears!

**Comment by pythonpanda2** [comment] 2022-02-26 16:50
I will start taking a look at this latest on monday.

**Comment by pythonpanda2** [comment] 2022-02-26 16:58
@galessiorob I don't think I am able to work on the checklist. Please let me know if I have been removed from the review service or if my service is no longer required ?

**Comment by galessiorob** [comment] 2022-03-01 17:50
@editorialbot list reviewers

**Comment by galessiorob** [comment] 2022-03-01 17:51
@editorialbot commands

**Comment by galessiorob** [comment] 2022-03-01 17:52
@editorialbot add @pythonpanda2  as reviewer

**Comment by galessiorob** [comment] 2022-03-01 17:53
@whedon add @pythonpanda2 as reviewer

**Comment by galessiorob** [comment] 2022-03-01 17:55
@arfon running into some issues trying to re-add `pythonpanda2` as a reviewer so they can work on their checklist

**Comment by galessiorob** [comment] 2022-03-01 20:47
@editorialbot add @pythonpanda2 to reviewers

**Comment by galessiorob** [comment] 2022-03-01 20:48
@pythonpanda2 could you try again and let me know if the issue persists, please? We'd really appreciate to have your review 🙏

**Comment by pythonpanda2** [comment] 2022-03-03 17:36
@galessiorob  Not sure if this is an issue due to Safari. I still cannot select the tick option in check list. I am going to try again in Firefox.

**Comment by pythonpanda2** [comment] 2022-03-04 01:32
@galessiorob I am not able to get the checklist sorted out even after switching to Firefox. I am just going to go ahead and start the review. Thanks a lot for your patience.

**Comment by galessiorob** [comment] 2022-03-04 02:23
@pythonpanda2 thank you!

**Comment by galessiorob** [comment] 2022-03-04 02:25
@kyleniemeyer could you help us troubleshoot please?

**Comment by kyleniemeyer** [comment] 2022-03-04 21:27
@galessiorob @pythonpanda2  I think the issue is that since we switched to the new editorialbot infrastructure, the checklists at the top no longer work (@arfon is that right?)

Instead, @pythonpanda2 can you comment `@editorialbot generate my checklist` ? This will generate one for you that you can edit.

**Comment by pythonpanda2** [comment] 2022-03-07 21:48
https://github.com/dgbowl/yadg/issues/43

**Comment by pythonpanda2** [comment] 2022-03-12 02:04
@PeterKraus   

https://github.com/dgbowl/yadg/issues/45

https://github.com/dgbowl/yadg/issues/46

**Comment by PeterKraus** [comment] 2022-03-14 08:45
Alright, I'm losing my mind trying to get the conference proceedings formatted properly for https://github.com/dgbowl/yadg/issues/45. @galessiorob, @kyleniemeyer does either of you know how to do this? The following bibtex doesn't seem to work well:

```
@inproceedings{Draxl2020,
  title = {{FAIRmat [Presentation]}},
  author = {Draxl, Claudia},
  crossref = {nfdiconf:20},
  langid = {german},
  howpublished = {https://www.dfg.de/download/pdf/foerderung/programme/nfdi/nfdi_konferenz_2020/fairmat_abstract.pdf},
  file = {C\:\\Users\\krpe\\Zotero\\storage\\5AXGYX4G\\fairmat_abstract.pdf}
}

@proceedings{nfdiconf:20,
  title = {{2. NFDI Conference}},
  publisher = {{Deutsche Forschungsgemeinschaft}},
  venue = {online},
  month = jul,
  year = {2020},
  langid = german
}
```

The title of the conference gets pulled out properly, but `publisher` and `howpublished` do not.

**Comment by PeterKraus** [comment] 2022-03-14 12:45
@editorialbot generate pdf

**Comment by pythonpanda2** [comment] 2022-03-14 13:21
Thank you @PeterKraus 

I think my part is done @galessiorob

**Comment by PeterKraus** [comment] 2022-03-14 16:08
@pythonpanda2 I think there are a couple unticked/unchecked items wrt. documentation. The testing/CI is done via github actions, and the example usage is now included in a short section in the paper, and it will be added to the docs. See:
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.6351210.svg)](https://doi.org/10.5281/zenodo.6351210)

**Comment by galessiorob** [comment] 2022-03-16 01:53
@editorialbot generate pdf

**Comment by galessiorob** [comment] 2022-03-16 02:21
Hi @PeterKraus,

We're almost at the finish line! I put together a few edit suggestions and typo corrections in this [PR](https://github.com/dgbowl/yadg/pull/49). Please merge as much as you like, and after that, we'll review once more and start the publishing process.

**Comment by galessiorob** [comment] 2022-04-05 00:08
@editorialbot generate pdf

**Comment by galessiorob** [comment] 2022-04-05 00:14
@PeterKraus 🙈 I am very sorry I missed this question. I apologize for the delay and hope you have more upcoming talks where you can point the audience to your paper. I'm a Chemical Engineer and this paper is awesome! I'm sure it'll be very well received.

The next thing we need from you is to deposit your software in Zenodo and post the DOI here and the most recent version. After that, we can set the final version, generate a final proof, and have an Editor in Chief do the publishing.

@aozorahime @pythonpanda2 @1mikegrn Thank you so much for lending your expertise and reviewing this paper 🚀

**Comment by PeterKraus** [comment] 2022-04-05 07:13
Hi @galessiorob, no worries about the delay. Glad you like the paper/software! I have uploaded all published versions of yadg to https://doi.org/10.5281/zenodo.5894822 (with version 4.0.0 being https://doi.org/10.5281/zenodo.6413504). We're working on getting v4.1.0 out, which will have some of the suggestions from reviewers merged in, but it's not ready yet as we need to finish a couple of features. Do I need to add the DOIs to the paper, or are the links here enough?

**Comment by galessiorob** [comment] 2022-04-05 16:19
Great! I _think_ the links are enough, but I'll ask the editor in chief.

**Comment by galessiorob** [comment] 2022-04-05 16:19
@editorialbot set v4.0.0 as version

**Comment by galessiorob** [comment] 2022-04-05 16:20
@editorialbot recommend-accept

**Comment by galessiorob** [comment] 2022-04-05 16:24
@editorialbot set 10.5281/zenodo.6413504 as archive

**Comment by galessiorob** [comment] 2022-04-05 16:31
@PeterKraus mind taking a look at these formatting errors, please?

**Comment by PeterKraus** [comment] 2022-04-06 06:04
@editorialbot generate pdf

**Comment by PeterKraus** [comment] 2022-04-06 06:09
@galessiorob I think that's done. I've also changed one of the references (lines 129-131) to the published version of the preprint. It doesn't have the page numbers or volume yet, but it has DOI so I'm guessing it's fine. Thanks for your help!

**Comment by galessiorob** [comment] 2022-04-06 13:58
@editorialbot recommend-accept

**Comment by galessiorob** [comment] 2022-04-08 16:36
@kyleniemeyer I'm having trouble figuring out this error. Could you help us, please? 🙏

**Comment by kyleniemeyer** [comment] 2022-04-08 17:35
@galessiorob sorry, I'm not sure either! The paper header looks alright to me. @openjournals/dev any ideas what's going on here? The paper author/affiliations block is:
```yaml
authors:
  - name: Peter Kraus^[corresponding author] 
    orcid: 0000-0002-4359-5003
    affiliation: 1 
  - name: Nicolas Vetsch
    affiliation: 1
  - name: Corsin Battaglia
    affiliation: 1
affiliations:
 - name: |
      Empa - Swiss Federal Laboratories for Materials Science and Technology,
      Überlandstrasse 129, 8600 Dübendorf
      Switzerland
   index: 1
```

**Comment by danielskatz** [comment] 2022-04-08 17:38
maybe change the affil entry to a single line:
```
 - name: Empa - Swiss Federal Laboratories for Materials Science and Technology, Überlandstrasse 129, 8600 Dübendorf, Switzerland
```
?
I'm not sure about the pipe character or the multiline affiliation

**Comment by PeterKraus** [comment] 2022-04-09 15:44
@editorialbot generate pdf

**Comment by PeterKraus** [comment] 2022-04-12 05:49
@galessiorob Hi, could we try again?

**Comment by galessiorob** [comment] 2022-04-14 23:14
@editorialbot recommend-accept

**Comment by galessiorob** [comment] 2022-04-14 23:19
Woohoo! Congrats @PeterKraus

**Comment by arfon** [comment] 2022-04-20 21:03
@PeterKraus – I've made a couple of minor edits here, could you please merge the PR? https://github.com/dgbowl/yadg/pull/53

**Comment by PeterKraus** [comment] 2022-04-21 06:00
@editorialbot generate pdf

**Comment by arfon** [comment] 2022-04-21 09:05
@editorialbot accept

**Comment by arfon** [comment] 2022-04-21 09:13
@aozorahime, @1mikegrn, @pythonpanda2 – many thanks for your reviews here and to @galessiorob for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@PeterKraus – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Closed by arfon** 2022-04-21 09:13 UTC
Labels: accepted, review, TeX, Python, recommend-accept, published
