### ISSUE TITLE
[PRE REVIEW]: Scyland3D: Processing 3D landmarks 

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1153] opened 2019-01-03 21:35 UTC
**Submitting author:** @ybayle (<a href="http://orcid.org/0000-0002-5143-2335">Yann Bayle</a>)
**Repository:** <a href="https://github.com/ybayle/Scyland3D" target ="_blank">https://github.com/ybayle/Scyland3D</a>
**Version:** v1.0.0
**Editor:** @Kevin-Mattheus-Moerman
**Reviewers:** @r-barnes

**Author instructions**

Thanks for submitting your paper to JOSS @ybayle. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@ybayle if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-01-03 21:35
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @Kevin-Mattheus-Moerman it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@Kevin-Mattheus-Moerman) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-01-03 21:35
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by arfon** [comment] 2019-01-03 21:35
:wave: @Kevin-Mattheus-Moerman - the submitting author suggested you as the handling editor.

**Comment by whedon** [comment] 2019-01-03 21:35
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01153/joss.01153/10.21105.joss.01153.pdf)

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-01-04 09:16
@whedon assign @Kevin-Mattheus-Moerman as editor

**Comment by whedon** [comment] 2019-01-04 09:16
OK, the editor is @Kevin-Mattheus-Moerman

**Comment by ybayle** [comment] 2019-01-04 11:08
From the JOSS suggested list of reviewers, we suggest to the editor, these people:
- @ryancoleman for the geometry keyword 
- @ngoldbaum for the 3D keyword
- @r-barnes for the evolutionary biology keywords

**Comment by ybayle** [comment] 2019-01-04 11:34
@whedon generate pdf

**Comment by whedon** [comment] 2019-01-04 11:34
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-01-04 11:35
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01153/joss.01153/10.21105.joss.01153.pdf)

**Comment by r-barnes** [comment] 2019-01-09 05:53
@ybayle : I haven't reviewed for JOSS before, but I'm generally game to give it a go. From a quick glance at your repository I don't see the evolutionary biology tie-in; however, I do a fair amount of computational science, so this likely wouldn't prevent me from reviewing it.

**Comment by ybayle** [comment] 2019-01-09 18:47
> 
> 
> @ybayle : I haven't reviewed for JOSS before, but I'm generally game to give it a go. From a quick glance at your repository I don't see the evolutionary biology tie-in; however, I do a fair amount of computational science, so this likely wouldn't prevent me from reviewing it.

Thanks! 
@Kevin-Mattheus-Moerman, do you agree to add @r-barnes as the first reviewer?

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-01-10 11:48
@whedon add @r-barnes as reviewer

**Comment by whedon** [comment] 2019-01-10 11:48
OK, @r-barnes is now a reviewer

**Comment by fberio** [comment] 2019-01-11 18:35
> 
> 
> @ybayle : I haven't reviewed for JOSS before, but I'm generally game to give it a go. From a quick glance at your repository I don't see the evolutionary biology tie-in; however, I do a fair amount of computational science, so this likely wouldn't prevent me from reviewing it.

@r-barnes We designed the functions for an evo-devo project but indeed, this is a global method that can be used for many research topics. We did not focus on Evolution in the description but the code was designed to help with 3D landmarks handling.

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-01-12 08:18
@fberio if you can suggest more reviewers great. I'll look for some more too.

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-01-12 08:36
@cleardusk @patrikhuber @anilbas @JuliaWinchester would you be interested in reviewing this work for the [Journal of Open Source Software (JOSS)](http://joss.theoj.org/about)? The https://joss.readthedocs.io/en/latest/reviewer_guidelines.html focuses on the software and a [short paper](https://github.com/openjournals/joss-papers/blob/joss.01153/joss.01153/10.21105.joss.01153.pdf). The review process (here is an example https://github.com/openjournals/joss-reviews/issues/1148) takes place on GitHub in a dedicated issue that I'll open once we have sufficient reviewers. Let me know if you have questions.

**Comment by patrikhuber** [comment] 2019-01-12 10:05
@Kevin-Mattheus-Moerman I can't currently do a full review according to your reviewer guidelines, but I've looked at the paper & repo and I'd be happy to leave a paragraph or two of review comments.

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-01-12 13:51
@patrikhuber thanks that would be great

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-01-31 14:48
@cleardusk @anilbas @JuliaWinchester would you be interested in reviewing this work for the Journal of Open Source Software (JOSS)? The [review process](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) focuses on the software and a short paper. The review process (here is an example #1148) takes place on GitHub in a dedicated issue that I'll open once we have sufficient reviewers. Let me know if you have questions.

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-01-31 14:48
@patrikhuber you can paste those paragraphs here if you like, thanks.

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-02-10 08:40
> @patrikhuber you can paste those paragraphs here if you like, thanks.

Any feedback you can share is greatly appreciated.

**Comment by patrikhuber** [comment] 2019-02-10 17:12
@Kevin-Mattheus-Moerman Apologies for a bit of a delay. Here goes my review:

### Overview

It seems to me that in general, this software is for a very, _**very**_ limited use case (which of course isn't necessarily bad!). Basically, the main thing it does:
1) Reads `.pts` landmarks from a software called "Landmark software (v3.6)" and converts them to a `.csv` format
2) It can mirror and re-order those landmarks while converting them. The mirroring potentially seems like it can be a bit tricky (see more below).

### Comments/questions:

* The Readme needs a better introduction in my opinion. It states

> Scyland3D is a Python tool for converting 3D raw landmark and semilandmark coordinates to a usable format for geometric morphometric analyses

but if you're not from _exactly_ that field, you're going to have a hard time discerning if the tool is useful or not, because "3D raw landmarks" is such a large field. I am not from the author's field directly but "geometric morphometric analysis" looks like it is in fact what I know by the term shape analysis, which is a really broad field, with thousands of different landmark formats. And Sciland3D seems only for one specific task in one very particular field (or perhaps even one particular lab or commercial software), without much broader applicability, I think. At least for me as a computer vision researcher, having worked with statistical shape models a lot, I had a hard time figuring out what this exactly is and does.

* The PDF and repo don't explain or introduce what "semilandmarks" are. I've worked with facial landmark points for many years and don't believe I've come across this term. Also no example seems to make use of them, as far as I can tell. Some explanation here would be really great.

* The Readme mentions `.pts` files but not what they are or where they're coming from. We have `.pts` files too in the facial landmarks community and they are something completely different (e.g. see https://github.com/patrikhuber/eos/blob/master/examples/data/image_0010.pts).
The PDF says they're ".pts files, exported by the Landmark software (v3.6)" but it also doesn't help much - please add a link/reference to that "Landmark software (v3.6)" or even better, to the format definition as well.

To sum that part up, I think there's way more context needed, and the name "Scyland3D: Processing 3D landmarks" may also be too general.

### Specific comments regarding the paper (PDF):

* The abstract says "convert them to a usable format". Why would the pts files be a less usable format than csv files? I believe that might be the wrong motivation or the motivation is just misstated. Both formats are probably useful, but data conversion is part of our daily jobs so we just want to to be as easy, painless and error-free as possible.

* I believe "ie" should have periods, i.e. (no pun intended... :-) ) "i.e.". Also I wouldn't italicise it but I'm not sure whether that's perhaps just personal preference. Italicising is for emphasising and what you want to emphasise there is _in situ_ and not the "i.e." :-) (see e.g. https://english.stackexchange.com/questions/3911/correct-spelling-italicization-of-e-g-i-e)

* _"Few free software solutions allow digitizing 3D landmarks and semilandmarks [...]"_: What do you mean with that? Store them to the disk? I think again what you probably mean is few ready-made scripts exist that convert between all these many formats?

* _"checks and reports [...] Consistency of folder and file names"_ In what way does it check that, what naming scheme does it expect?

* _"checks and reports [...] Precision of landmark and semilandmark coordinates export by the Landmark software."_ - I can't find anything about that in the code?

* _"mirrored objects have reverted bending"_ What do you mean with blending here?

### Specifically with regards to the code:

* How useful is the mirroring? For it to be useful, you usually have to mirror the original data too (in your case e.g. the teeth point-cloud), in the same way. Furthermore it seems to me that e.g. in the example given in Figure 1, this only works if the landmarks are placed in a symmetric way in the first place (i.e. if 1 is the "mirror-point" of 7, etc.).

* The code could use more documentation in general. A tiny bit longer function documentation, but also in-code comments. Code should be either self-explanatory and need no comments (best case) or have appropriate comments, where needed.

* Here it says something about a comparison "up to epsilon": https://github.com/ybayle/Scyland3D/blob/1d219d40a8327515d936b94a2d1d4ce7060c0f16/Scyland3D.py#L80
But in the following code, I can't find any comparison up to an epsilon, only equality checks. It may very well be that I don't read the code correctly and I haven't run it either but it kind of reinforces my point from above about documentation.

* https://github.com/ybayle/Scyland3D/blob/1d219d40a8327515d936b94a2d1d4ce7060c0f16/Scyland3D.py#L106-L107
It would be nice to know here what's "good" about one link and "wrong" about one link. There seem to be some peculiarities at play here, and even a StackOverflow answer with most upvotes and comments like "This one should be marked as the correct answer." that apparently has gotten something important wrong. Let us know about it please, and also again, please put comments in that function and let us know which ones were/are the tricky bits.
From what I can see, that function (`reverse_z`) is actually one of *the* main contributions of the proposed submission.

Some of those comments might be a bit picky but in particular because I don't think this contribution is particularly big, it is even more important that the small thing that *is* contributed is as useful as possible and can be used by people being assured it doesn't have any bugs, or if they do need to check something, the code should be documented clearly enough to make it easy.

**Comment by r-barnes** [comment] 2019-02-18 22:33
Sorry about the delay. Whedon invited me to join the github and this resulted in an unbelievable amount of spam. I think I've finally got my settings such that I'll see this conversation and not the rest. @Kevin-Mattheus-Moerman : Do I now evaluate the work based on [this](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html) and [this](https://joss.readthedocs.io/en/latest/review_criteria.html)? (In my mind there was some kind of standard form with checkboxes and spaces for comments.)

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-02-18 22:59
@whedon start review

**Comment by whedon** [comment] 2019-02-18 22:59
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1262. Feel free to close this issue now!

**Closed** 2019-02-18 23:37 UTC
Labels: Python, TeX, pre-review

**Comment by patrikhuber** [comment] 2019-02-19 00:09
Hi @Kevin-Mattheus-Moerman,
Shall I copy&paste my review over to the review thread? It might be more appropriate there?

Best wishes,
Patrik
