### ISSUE TITLE
[REVIEW]: stabm: Stability Measures for Feature Selection

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3010] opened 2021-02-04 18:41 UTC
**Submitting author:** @bommert (<a href="http://orcid.org/0000-0002-1005-9351">Andrea Bommert</a>)
**Repository:** <a href="https://github.com/bommert/stabm" target ="_blank">https://github.com/bommert/stabm</a>
**Version:** v1.2.0
**Editor:** @marcosvital
**Reviewer:** @mcavs, @clauswilke, @osorensen
**Archive:** <a href="https://doi.org/10.5281/zenodo.4648087" target="_blank">10.5281/zenodo.4648087</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/80566e3da78bdd36a2dbca1217fb8f32/status.svg)](https://joss.theoj.org/papers/80566e3da78bdd36a2dbca1217fb8f32)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/80566e3da78bdd36a2dbca1217fb8f32"><img src="https://joss.theoj.org/papers/80566e3da78bdd36a2dbca1217fb8f32/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/80566e3da78bdd36a2dbca1217fb8f32/status.svg)](https://joss.theoj.org/papers/80566e3da78bdd36a2dbca1217fb8f32)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/bommert/stabm" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mcavs & @clauswilke & @osorensen, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @marcosvital know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bommert/stabm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bommert) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bommert/stabm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bommert) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/bommert/stabm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@bommert) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2021-02-04 18:41
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mcavs, @clauswilke, @osorensen it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-02-04 18:41
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (309.3 files/s, 34419.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               19            299            508           1533
TeX                              2             27              0            263
Markdown                         2             23              0            120
YAML                             2             23              0             95
Rmd                              2             29             67             18
-------------------------------------------------------------------------------
SUM:                            27            401            575           2029
-------------------------------------------------------------------------------


Statistical information for the repository 'd1a59aec2d8fdc1255ae7055' was
gathered on 2021/02/04.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment] 2021-02-04 18:42
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment] 2021-02-04 18:42
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10115-006-0040-8 is OK
- 10.1155/2017/7907163 is OK
- 10.1007/978-3-030-64583-0_19 is OK
- 10.1016/j.csda.2019.106839 is OK
- 10.1109/IRI.2012.6303031 is OK
- 10.1007/978-3-319-25226-1_7 is OK
- 10.5169/seals-266450 is OK
- 10.2307/1932409 is OK
- 10.1093/bioinformatics/btl400 is OK
- 10.1109/icdmw.2009.32 is OK
- 10.2331/suisan.22.531 is OK
- 10.1007/978-3-319-46227-1_28 is OK
- 10.1007/978-3-030-46150-8_20 is OK
- 10.1109/tpami.2010.34 is OK
- 10.1109/ictai.2013.63 is OK
- 10.1109/tcbb.2011.47 is OK
- 10.2202/1544-6115.1307 is OK
- 10.18637/jss.v031.i02 is OK
- 10.1016/j.softx.2020.100526 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by marcosvital** [comment] 2021-02-04 18:44
Dear @bommert: your manuscript will be reviewed in this issue, and you can reply any comments and suggestions that the reviewers might address right here.

**Comment by marcosvital** [comment] 2021-02-04 18:45
@mcavs, @clauswilke and @osorensen: thank you again for for accepting review this submission for JOSS.

Even if you are not starting the review right now, please accept the invite, as it has an expiration date (there is a link under Reviewer instructions & questions and you should also get an email notification). Furthermore, please check the instructions and checklists above, and let me know if you need any assistance.

You can also tag @bommert if you need to ask specific questions about the submission or to address any changes that might be necessary in the submitted paper or in the repository.

**Comment by marcosvital** [comment] 2021-02-04 18:46
@bommert, I see your paper have a co-author. If this person have a GitHub profile and wants to participate, you can tag the profile any time you want.

**Comment by bommert** [comment] 2021-02-04 21:23
The co-author is @mllg .

**Comment by bommert** [comment] 2021-02-05 16:02
I have added my phd thesis, that was just published today, as a reference. I hope that is okay.

**Comment by bommert** [comment] 2021-02-05 16:03
@whedon generate pdf

**Comment by whedon** [comment] 2021-02-05 16:03
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: :point_left:

**Comment by bommert** [comment] 2021-02-05 16:05
@whedon check references

**Comment by whedon** [comment] 2021-02-05 16:06
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10115-006-0040-8 is OK
- 10.1155/2017/7907163 is OK
- 10.1007/978-3-030-64583-0_19 is OK
- 10.1016/j.csda.2019.106839 is OK
- 10.17877/DE290R-21906 is OK
- 10.1109/IRI.2012.6303031 is OK
- 10.1007/978-3-319-25226-1_7 is OK
- 10.5169/seals-266450 is OK
- 10.2307/1932409 is OK
- 10.1093/bioinformatics/btl400 is OK
- 10.1109/icdmw.2009.32 is OK
- 10.2331/suisan.22.531 is OK
- 10.1007/978-3-319-46227-1_28 is OK
- 10.1007/978-3-030-46150-8_20 is OK
- 10.1109/tpami.2010.34 is OK
- 10.1109/ictai.2013.63 is OK
- 10.1109/tcbb.2011.47 is OK
- 10.2202/1544-6115.1307 is OK
- 10.18637/jss.v031.i02 is OK
- 10.1016/j.softx.2020.100526 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by osorensen** [comment] 2021-02-09 14:59
@bommert 

This is related to the following point on the reviewer checklist:

> Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

While I think the package is well documented and has good examples, they are all very simple. It might hence be difficult for someone without too much experience in the field to actually understand the real-world analysis problems which can be solved with this package. I think it would be useful if you could add one or more slightly extended examples of analysis tasks which `stabm` can help solved. Perhaps this could be put on a separate analysis page. 

Here are some ideas that came to my mind while reading through the package documentation, but feel free to choose something else:

- Use `stabm` to assess the stability of variable selection algorithms, like the lasso (`glmnet::glmnet`). You could show a small example where the lasso is fit on a number of simulated datasets coming from the same distribution, and the stability of the selected set of variables computed. See, e.g., https://doi.org/10.1002/gepi.20623 or https://doi.org/10.1111/j.1467-9868.2010.00740.x for related methods.

- Perhaps you could also use `stabm` to assess the stability of cluster solutions? For example, you could use `stats::kmeans` to partition a dataset into a fixed number of clusters, and then repeat this either for random splits of the datasets or for multiple datasets from the same distribution. Something like this is often used to check if a clustering is stable with respect to random variations in the dataset (e.g., https://elifesciences.org/articles/52677).

**Comment by clauswilke** [comment] 2021-02-09 20:41
I agree with @osorensen. Specifically, the one vignette provided with the package is rather short. I would suggest expanding this vignette or adding additional ones to provide a little more substance.

The other comment I have is regarding community guidelines. You have one brief sentence in the Readme, but I think it would be a good idea to expand on that a little bit, and maybe add explicit contributing and code of conduct documents.

**Comment by bommert** [comment] 2021-02-10 09:01
Thank you for your comments! I will work on them in the next days.

**Comment by mllg** [comment] 2021-02-10 09:47
https://github.com/bommert/stabm/pull/11 adds a simple feature selection example to the vignette. I've decided to use a simple regression tree here because the `rpart` package ships with R as a recommended package.

**Comment by mllg** [comment] 2021-02-15 09:22
> The other comment I have is regarding community guidelines. You have one brief sentence in the Readme, but I think it would be a good idea to expand on that a little bit, and maybe add explicit contributing and code of conduct documents.

Both done in https://github.com/bommert/stabm/commit/9bad1c8a2a72884fe34ccd21fb90baa69053aa74.

**Comment by bommert** [comment] 2021-02-15 17:47
We have extended the vignette with a feature selection and a clustering example. The extended vignette has been merged into the master.

**Comment by clauswilke** [comment] 2021-02-15 17:52
Thanks for making the requested changes. I have no further comments.

**Comment by whedon** [comment] 2021-02-18 18:41
:wave: @mcavs, please update us on how your review is going (this is an automated reminder).

**Comment by mcavs** [comment] 2021-02-19 18:41
Hi @marcosvital, I am agree with @osorensen and @clauswilke. 

I think an illustrative example is needed. Other than that, I have no further comments. 

Very clear and fluent manuscript!

**Comment by mllg** [comment] 2021-02-20 05:05
I've added a reference to the checkmate package in the paper, hope that's okay for everyone.

@whedon generate pdf

@whedon check references

**Comment by mllg** [comment] 2021-02-20 05:07
I propose that we do a CRAN release and update the reviewed version accordingly before proceeding.

**Comment by mllg** [comment] 2021-02-20 05:08
@whedon generate pdf

**Comment by mllg** [comment] 2021-02-20 05:08
@whedon check references

**Comment by whedon** [comment] 2021-02-20 05:09
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment] 2021-02-20 05:09
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10115-006-0040-8 is OK
- 10.1155/2017/7907163 is OK
- 10.1007/978-3-030-64583-0_19 is OK
- 10.1016/j.csda.2019.106839 is OK
- 10.17877/DE290R-21906 is OK
- 10.1109/IRI.2012.6303031 is OK
- 10.1007/978-3-319-25226-1_7 is OK
- 10.5169/seals-266450 is OK
- 10.2307/1932409 is OK
- 10.1093/bioinformatics/btl400 is OK
- 10.1109/icdmw.2009.32 is OK
- 10.2331/suisan.22.531 is OK
- 10.1007/978-3-319-46227-1_28 is OK
- 10.1007/978-3-030-46150-8_20 is OK
- 10.1109/tpami.2010.34 is OK
- 10.1109/ictai.2013.63 is OK
- 10.1109/tcbb.2011.47 is OK
- 10.2202/1544-6115.1307 is OK
- 10.18637/jss.v031.i02 is OK
- 10.1016/j.softx.2020.100526 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mllg** [comment] 2021-02-20 05:12
@whedon generate pdf

**Comment by mllg** [comment] 2021-02-20 05:13
@whedon check references

**Comment by whedon** [comment] 2021-02-20 05:13
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment] 2021-02-20 05:13
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10115-006-0040-8 is OK
- 10.1155/2017/7907163 is OK
- 10.1007/978-3-030-64583-0_19 is OK
- 10.1016/j.csda.2019.106839 is OK
- 10.17877/DE290R-21906 is OK
- 10.1109/IRI.2012.6303031 is OK
- 10.1007/978-3-319-25226-1_7 is OK
- 10.5169/seals-266450 is OK
- 10.2307/1932409 is OK
- 10.1093/bioinformatics/btl400 is OK
- 10.1109/icdmw.2009.32 is OK
- 10.2331/suisan.22.531 is OK
- 10.1007/978-3-319-46227-1_28 is OK
- 10.1007/978-3-030-46150-8_20 is OK
- 10.1109/tpami.2010.34 is OK
- 10.1109/ictai.2013.63 is OK
- 10.1109/tcbb.2011.47 is OK
- 10.2202/1544-6115.1307 is OK
- 10.18637/jss.v031.i02 is OK
- 10.1016/j.softx.2020.100526 is OK
- 10.32614/RJ-2017-028 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mllg** [comment] 2021-02-20 05:16
@whedon generate pdf

**Comment by whedon** [comment] 2021-02-20 05:17
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03010/joss.03010/10.21105.joss.03010.pdf) :page_facing_up: :point_left:

**Comment by bommert** [comment] 2021-02-20 14:32
@mcavs: We have added a feature selection and a clustering example in the vignette (bommert/stabm@c4e4101b6fb66a8fb236aafc041a69745d951f54). Do these examples meet the need for illustrative examples?

**Comment by danielskatz** [comment] 2021-03-05 14:52
👋 @marcosvital - just a ping on this, since it seems so close to be ready to publish...

**Comment by mllg** [comment] 2021-03-29 11:39
@marcosvital Is there anything we can do to complete the review?

**Comment by marcosvital** [comment] 2021-03-29 17:52
Dear @bommert and @mllg, I'm very sorry for the long absence. I'll carry on with our final steps towards publication, ok?

**Comment by marcosvital** [comment] 2021-03-29 21:59
@whedon set 1.1.4 as version

**Comment by whedon** [comment] 2021-03-29 21:59
OK. 1.1.4 is the version.

**Comment by marcosvital** [comment] 2021-03-29 22:01
@bommert and @mllg, the manuscript looks great, so we are almost ready to go. But first, you will need archive the last release of the package (on Zenodo, figshare, or other) if you already didn't do this. After that, just let me know the archive DOI.

**Comment by mllg** [comment] 2021-03-30 20:00
Thanks @marcosvital.

We have released a new version to CRAN today (v1.2.0) which includes all the improvements requested by the reviewers and uploaded the same version to Zenodo: http://doi.org/10.5281/zenodo.4648087

**Comment by marcosvital** [comment] 2021-03-31 10:14
Thanks, @mllg!

**Comment by marcosvital** [comment] 2021-03-31 10:15
@whedon set v1.2.0 as version

**Comment by whedon** [comment] 2021-03-31 10:15
OK. v1.2.0 is the version.

**Comment by marcosvital** [comment] 2021-03-31 10:16
@whedon set 10.5281/zenodo.4648087 as archive

**Comment by whedon** [comment] 2021-03-31 10:16
OK. <a href="https://doi.org/10.5281/zenodo.4648087" target="_blank">10.5281/zenodo.4648087</a> is the archive.

**Comment by marcosvital** [comment] 2021-03-31 10:17
@whedon accept

**Comment by whedon** [comment] 2021-03-31 10:17
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment] 2021-03-31 10:19
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2170

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2170, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by whedon** [comment] 2021-03-31 10:19
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1007/s10115-006-0040-8 is OK
- 10.1155/2017/7907163 is OK
- 10.1007/978-3-030-64583-0_19 is OK
- 10.1016/j.csda.2019.106839 is OK
- 10.17877/DE290R-21906 is OK
- 10.1109/IRI.2012.6303031 is OK
- 10.1007/978-3-319-25226-1_7 is OK
- 10.5169/seals-266450 is OK
- 10.2307/1932409 is OK
- 10.1093/bioinformatics/btl400 is OK
- 10.1109/icdmw.2009.32 is OK
- 10.2331/suisan.22.531 is OK
- 10.1007/978-3-319-46227-1_28 is OK
- 10.1007/978-3-030-46150-8_20 is OK
- 10.1109/tpami.2010.34 is OK
- 10.1109/ictai.2013.63 is OK
- 10.1109/tcbb.2011.47 is OK
- 10.2202/1544-6115.1307 is OK
- 10.18637/jss.v031.i02 is OK
- 10.1016/j.softx.2020.100526 is OK
- 10.32614/RJ-2017-028 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by kthyng** [comment] 2021-03-31 15:36
@whedon accept deposit=true

**Comment by whedon** [comment] 2021-03-31 15:39
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment] 2021-03-31 15:41
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2173
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.03010](https://doi.org/10.21105/joss.03010)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kthyng** [comment] 2021-03-31 15:52
Congrats on your new publication @bommert! Thanks to editor @marcosvital and reviewers @mcavs, @clauswilke, and @osorensen for your time, hard work, and expertise!!

**Closed by kthyng** 2021-03-31 15:52 UTC
Labels: R, TeX, accepted, published, recommend-accept, review

**Comment by whedon** [comment] 2021-03-31 16:04
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.03010/status.svg)](https://doi.org/10.21105/joss.03010)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.03010">
  <img src="https://joss.theoj.org/papers/10.21105/joss.03010/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.03010/status.svg
   :target: https://doi.org/10.21105/joss.03010
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.03010/status.svg)](https://doi.org/10.21105/joss.03010)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Comment by mllg** [comment] 2021-03-31 18:14
Thanks everyone!

**Comment by bommert** [comment] 2021-04-01 07:34
Thank you!
