### ISSUE TITLE
[PRE REVIEW]: pyHoops: A Python package for advanced basketball data analytics

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1784] opened 2019-10-04 16:12 UTC
**Submitting author:** @alessandroBombelli (<a href="http://orcid.org/0000-0001-7889-9552">Alessandro Bombelli</a>)
**Repository:** <a href="https://github.com/alessandroBombelli/pyHoops" target ="_blank">https://github.com/alessandroBombelli/pyHoops</a>
**Version:** v1.5
**Editor:** @danielskatz
**Reviewers:** @mado89, @ctsilva

**Author instructions**

Thanks for submitting your paper to JOSS @alessandroBombelli. **Currently, there isn't an JOSS editor assigned** to your paper.

@alessandroBombelli if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-10-04 16:12
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-10-04 16:12
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-10-04 16:12
Failed to discover a valid open source license.

**Comment by whedon** [comment] 2019-10-04 16:12
PDF failed to compile for issue #1784 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:135:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon.rb:87:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:36:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/lib/whedon/processor.rb:36:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-efe915e61673/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by kyleniemeyer** [comment] 2019-10-04 16:14
Hello @alessandroBombelli, thanks for your interest in JOSS. Before we proceed, during my review of your submission, I could not find the research application of your software. While useful for folks in basketball, I don't quite see where someone would cite this in the academic literature (not an explicit requirement, but one way we think about whether software has a research use).

Can you clarify this, per one of our submission requirements?
> The software should have an **obvious** research application.

**Comment by danielskatz** [comment] 2019-10-04 16:26
https://github.com/alessandroBombelli/pyHoops/pull/46 should fix the immediate paper building process

**Comment by alessandroBombelli** [comment] 2019-10-04 16:57
> Hello @alessandroBombelli, thanks for your interest in JOSS. Before we proceed, during my review of your submission, I could not find the research application of your software. While useful for folks in basketball, I don't quite see where someone would cite this in the academic literature (not an explicit requirement, but one way we think about whether software has a research use).
> 
> Can you clarify this, per one of our submission requirements?
> 
> > The software should have an **obvious** research application.

Dear @kyleniemeyer, apologies if the research application is not clear. I agree that, at a first glance, the obvious research application might not be as straight-forward as in other cases. On the other hand, a strong interest in data analytics applied to sports has been growing in recent years, as testified by ad-hoc conferences (MIT Sloan Sports Analytics Conference) and journals (Journal of Sports Sciences). To this avail, the research application of this work is the possibility to compute a set of team performance indices (per player and per lineup) to be used, as example, to infer lineup performances in future games. Knowing how different lineups perform against different opposing lineups (e.g., "tall", or "fast" lineups), can be used as part of a decision-making process to improve performances of a team. In addition, a sufficiently comprehensive database retrieved via pyHoops (e.g., a full season), can be used as the input for a prediction model (e.g., random forest) to assess what are the features (lineup- or player-specific) more crucial for a team's success. I hope this answers your question. I am willing to elaborate more if the answer is not satisfactory. Thank you!

**Comment by danielskatz** [comment] 2019-10-04 17:06
I can take

**Comment by alessandroBombelli** [comment] 2019-10-04 17:22
> [alessandroBombelli/pyHoops#46](https://github.com/alessandroBombelli/pyHoops/pull/46) should fix the immediate paper building process

Dear @danielskatz, sorry for the issue. but it is my first time here and, as such, I am not familiar with the formatting. I followed the example provided in the guidelines but thought that, being a single author, the distinction between affiliation and affiliations was not necessary. I fixed the issue now. Please let me know otherwise.
Thank you very much

**Comment by kyleniemeyer** [comment] 2019-10-04 17:49
@danielskatz thanks for volunteering—did you mean to close the issue?

**Comment by kyleniemeyer** [comment] 2019-10-04 17:50
@alessandroBombelli ok, so I think it would help to revise your article to better describe the research applications of the software, so this is clear to reviewers (and readers), focusing specifically on the types of research questions/problems this helps answer. 

What you are describing to me sounds more like what a basketball team might use, but not an academic researcher writing a publication (for example)—but I may still be misunderstanding.

**Comment by danielskatz** [comment] 2019-10-04 19:08
@whedon generate pdf

**Comment by whedon** [comment] 2019-10-04 19:08
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-10-04 19:09
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01784/joss.01784/10.21105.joss.01784.pdf)

**Comment by danielskatz** [comment] 2019-10-04 19:26
I've suggested more changes in https://github.com/alessandroBombelli/pyHoops/pull/48 - after merging this, you can enter ```@whedon generate pdf``` as a new comment here to regenerate the paper.

**Comment by kyleniemeyer** [comment] 2019-10-04 19:29
@whedon assign @danielskatz as editor

**Comment by whedon** [comment] 2019-10-04 19:29
OK, the editor is @danielskatz

**Comment by danielskatz** [comment] 2019-10-07 16:45
@alessandroBombelli - do you have suggestions for reviewers?  They can be from [this list of potential reviewers](https://bit.ly/joss-reviewers) (please start at the bottom of the list), or individuals who are not on this list; if so, please mention their GitHub handles here.

**Comment by alessandroBombelli** [comment] 2019-10-08 15:17
@whedon generate pdf

**Comment by whedon** [comment] 2019-10-08 15:17
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-10-08 15:17
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01784/joss.01784/10.21105.joss.01784.pdf)

**Comment by alessandroBombelli** [comment] 2019-10-08 15:18
> I've suggested more changes in [alessandroBombelli/pyHoops#48](https://github.com/alessandroBombelli/pyHoops/pull/48) - after merging this, you can enter `@whedon generate pdf` as a new comment here to regenerate the paper.

@danielskatz, I slightly modified references because I realized two of them were not correctly compiled. In one case, there was a @ missing. In the other case, where I am citing a website, I am not sure what the problem is. I am using the same citation type I would use in a classic LaTeX file, where I know it should work. On the other hand, I am not very familiar with the integration of the .md file with the .bib file, so I have little control on what is going wrong. Could you please help me with that? Thanks!

**Comment by alessandroBombelli** [comment] 2019-10-08 15:19
> > I've suggested more changes in [alessandroBombelli/pyHoops#48](https://github.com/alessandroBombelli/pyHoops/pull/48) - after merging this, you can enter `@whedon generate pdf` as a new comment here to regenerate the paper.
> 
> @danielskatz, I slightly modified references because I realized two of them were not correctly compiled. In one case, there was a @ missing. In the other case, where I am citing a website, I am not sure what the problem is. I am using the same citation type I would use in a classic LaTeX file, where I know it should work. On the other hand, I am not very familiar with the integration of the .md file with the .bib file, so I have little control on what is going wrong. Could you please help me with that? Thanks!

@danielskatz never mind, it is fixed now. Sorry for the confusion

**Comment by alessandroBombelli** [comment] 2019-10-08 15:22
> @alessandroBombelli - do you have suggestions for reviewers? They can be from [this list of potential reviewers](https://bit.ly/joss-reviewers) (please start at the bottom of the list), or individuals who are not on this list; if so, please mention their GitHub handles here.

Dear @danielskatz, I checked the list and I think @mado89 should be a good match. No preference for the second reviewer instead.

**Comment by danielskatz** [comment] 2019-10-08 15:23
Perhaps you can suggest some other people not on the list?  Maybe from other types of sport analytics?

**Comment by danielskatz** [comment] 2019-10-08 15:29
👋 @mado89 - would you be willing to review this submission for JOSS?

**Comment by danielskatz** [comment] 2019-10-08 15:37
👋 @ctsilva - would you (or someone in your group) be willing to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

If not, could you suggest some others in the field of software and sports analytics who might be suitable?

**Comment by mado89** [comment] 2019-10-08 15:40
@danielskatz I can do it. But I might need some time (and maybe a gentle reminder in 1.5 weeks) as I am quite busy this and next week.

**Comment by danielskatz** [comment] 2019-10-08 15:41
Thanks @mado89 - we won't start until I find another reviewer, but I'll put you into the system for now, and I will be sure to remind you again once things start, or it's been a little time :)

**Comment by danielskatz** [comment] 2019-10-08 15:41
@whedon assign @mado89 as reviewer

**Comment by alessandroBombelli** [comment] 2019-10-08 15:46
@whedon generate pdf

**Comment by whedon** [comment] 2019-10-08 15:47
PDF failed to compile for issue #1784 with the following error: 

 Error reading bibliography ./pyHoops_references.bib (line 18, column 3):
unexpected "p"
expecting space, ",", white space or "}"
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by alessandroBombelli** [comment] 2019-10-08 15:48
@whedon generate pdf

**Comment by whedon** [comment] 2019-10-08 15:48
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-10-08 15:49
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01784/joss.01784/10.21105.joss.01784.pdf)

**Comment by alessandroBombelli** [comment] 2019-10-08 15:50
@whedon generate pdf

**Comment by whedon** [comment] 2019-10-08 15:50
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-10-08 15:51
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01784/joss.01784/10.21105.joss.01784.pdf)

**Comment by mado89** [comment] 2019-10-24 18:19
What are the requirements for the reviewer? I might know a guy who knows somebody working in the industry  (sport data)Sent from my mobile devicePlease excuse briefness and typos

-------- Original message --------

**Comment by danielskatz** [comment] 2019-10-27 17:31
The reviewer should be familiar with open source, ideally with the domain and language of the software, and should not be conflicted with the authors

**Comment by danielskatz** [comment] 2019-10-30 06:38
👋 @ctsilva - thanks for agreeing by email to review

**Comment by danielskatz** [comment] 2019-10-30 06:38
@whedon add @ctsilva as reviewer

**Comment by whedon** [comment] 2019-10-30 06:38
OK, @ctsilva is now a reviewer

**Comment by danielskatz** [comment] 2019-10-30 06:39
@whedon start review

**Comment by whedon** [comment] 2019-10-30 06:39
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1845. Feel free to close this issue now!

**Comment by alessandroBombelli** [comment] 2019-10-30 12:36
> As a quick update, I am still working on finding another review, partially by private email. Any more suggestions are also welcome.

Dear @danielskatz sorry for the late reply. Thanks for the efforts in finding suitable reviewers. I really appreciated

**Closed** 2019-11-06 11:44 UTC
Labels: Jupyter Notebook, Python, TeX, pre-review
