### ISSUE TITLE
[REVIEW]: SleepPy: A python package for sleep analysis from accelerometer data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1663] opened 2019-08-19 20:37 UTC
**Submitting author:** @elyiorgos (<a href="http://orcid.org/0000-0003-3371-8935">Yiorgos Christakis</a>)
**Repository:** <a href="https://github.com/elyiorgos/sleeppy" target ="_blank">https://github.com/elyiorgos/sleeppy</a>
**Version:** 0.2.21
**Editor:** @lheagy
**Reviewers:** @eskofier, @ikarosilva, @nhejazi
**Archive:** <a href="https://doi.org/10.5281/zenodo.3572581" target="_blank">10.5281/zenodo.3572581</a>

## Status

[![status](https://joss.theoj.org/papers/fad54455272cbb33a611cfb93b758480/status.svg)](https://joss.theoj.org/papers/fad54455272cbb33a611cfb93b758480)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fad54455272cbb33a611cfb93b758480"><img src="https://joss.theoj.org/papers/fad54455272cbb33a611cfb93b758480/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fad54455272cbb33a611cfb93b758480/status.svg)](https://joss.theoj.org/papers/fad54455272cbb33a611cfb93b758480)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/elyiorgos/sleeppy" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@eskofier & @ikarosilva, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @lheagy know.

✨ **Please try and complete your review in the next two weeks** ✨ 

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/elyiorgos/sleeppy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.2.21
- [x] **Authorship:** Has the submitting author (@elyiorgos) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [ ] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/elyiorgos/sleeppy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.2.21
- [x] **Authorship:** Has the submitting author (@elyiorgos) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/elyiorgos/sleeppy">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** 0.2.21
- [x] **Authorship:** Has the submitting author (@elyiorgos) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment] 2019-08-19 20:37
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @eskofier, @ikarosilva it looks like you're currently assigned to review this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2019-08-19 20:37
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-08-19 20:38
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01663/joss.01663/10.21105.joss.01663.pdf)

**Comment by lheagy** [comment] 2019-08-20 04:07
Thank you @eskofier and @ikarosilva for being willing to review! Above there is a checklist to help guide your review. Please feel free to open issues on the [target repository](https://github.com/elyiorgos/sleeppy) with comments or suggestions for improvement in the submission and link them here by mentioning `openjournals/joss-reviews#1663` in the issue text. 

If you are able to complete your review in the next two weeks, that would be much appreciated. Please let me know if you have any questions along the way. Thanks again!

**Comment by Kevin-Mattheus-Moerman** [comment] 2019-09-11 10:23
@eskofier, @ikarosilva thanks again for your help with this review. Can you please give us an indication as to when you can work on/finalize this review? Thanks.

**Comment by eskofier** [comment] 2019-09-11 14:17
Hi Kevin,

What exactly are we supposed to do? I have not seen any review instructions or the likes?

Best regards,
Bjoern



-sent from mobile office-

**Comment by ikarosilva** [comment] 2019-09-17 12:26
Hi @lheagy,

Posting here per per our discussion on conflict of interest waiver. I have worked with Dr. Patel for several months and  a year on a team at a start up in 2015. I hold him at a very high regards and as a trusted colleague. We also have a few publications in press. While I don't believe our relationship should affect my ability to review this work, I would like to disclose this information in spirit of full transparency.

**Comment by lheagy** [comment] 2019-09-23 15:07
Thanks for your disclosure @ikarosilva. You are welcome to contribute to the review, but please leave the check-box for the conflict of interest unckecked. I will try to find one more reviewer to contribute to the review.

**Comment by lheagy** [comment] 2019-09-23 15:07
:wave: @eskofier, when do you anticipate that you will have time to take a look at this review? Thanks!

**Comment by eskofier** [comment] 2019-09-23 15:27
I am on it!

Best regards,
Bjoern



-sent from mobile office-

**Comment by lheagy** [comment] 2019-09-23 16:38
:wave: @nhejazi, would you be willing to join this review?

**Comment by nhejazi** [comment] 2019-09-23 18:11
Sure, would be happy to provide a review!

**Comment by lheagy** [comment] 2019-09-23 18:14
@whedon add @nhejazi as reviewer

**Comment by whedon** [comment] 2019-09-23 18:14
OK, @nhejazi is now a reviewer

**Comment by lheagy** [comment] 2019-09-23 18:16
Many thanks @nhejazi! I have added a checklist to the main issue thread above to help guide your review. Please let me know if you have any questions!

**Comment by nhejazi** [comment] 2019-09-29 04:20
@elyiorgos, the `sleeppy` package looks interesting, thanks for submitting the paper to JOSS! After going through the reviewer checklist, there are a few outstanding items that I'd like to bring your attention:

* The package requires a statement about contribution guidelines. A simple approach for doing this includes adding a section "Contributing" to the `README` that links to a more complete document (e.g., `CONTRIBUTING.md`), giving those interested in adding to the package information on how best to do so.
* From an examination of the package source, it appears that there are no unit tests included in the package. There are several frameworks for writing such tests, including [`unittest`](https://docs.python.org/2/library/unittest.html), [`nose2`](https://github.com/nose-devs/nose2), and [`pytest`](https://pytest.readthedocs.io/en/latest/). Such tests are critical for ensuring software integrity as development continues. If I missed a note about tests or they are located elsewhere, feel free to point this out also.

**Comment by elyiorgos** [comment] 2019-09-29 19:17
Hello Nima!

Thank you for your comments!

In the current sleeppy github repo there should be an existing
CONTRIBUTING.md file that outlines the ways in which any interested party
can contribute if they would like to. If that file needs more fleshing out
I'm happy to update it. I'm also happy to add a link to the README.md file
to make it easier to find if that is a suitable and helpful addition.

With regards to a testing suite, there is a demo module with a demo.py file
that runs the full suite of analyses on demo data, generates reports to be
compared to the expected output(from a visual point of view), and also
performs assertion tests on the expected clinical endpoints calculated by
the package. My understanding in talking with the editor pre-submission was
that those would suffice, however, I fully understand the importance of
more robust testing, and am more than happy to create a suite of more
conventional unit tests testing the many specific pieces of functionality
leveraged by the package.

When you get a chance let me know your thoughts on both accounts, and I'll
get right on it! Thank you again!

Wishing you all the best,
Yiorgos Christakis

**Comment by nhejazi** [comment] 2019-10-01 02:24
Hi Yiorgos ---

Thanks for your quick reply and for pointing out the items that I missed. The included `CONTRIBUTING.md` file looks good to me --- please do link to it from the `README.md` though as this will make it much easier for interested users to find the document. Also, you're right that formal unit tests are technically not necessary to pass the JOSS review, that is, the checks currently included in the `demo.py` file appear sufficient. I will check off the testing item as it appears that the included checks do satisfy the requirement; however, I'd still strongly encourage adding unit tests in the style of whichever framework you prefer in the future as this will go a long way towards ensuring reproducibility as changes to the core software are made (possibly by contributors). Once such tests are set up, you may also consider looking into leveraging existing continuous integration services to ensure that your tests are run upon each commit / PR (you could also set this up with the existing `demo.py` and perhaps check that key numerical results are consistent between commits / PRs). Happy to check off the remaining item about contributions as well after the `README.md` is updated. Almost there!

Cheers,
Nima

**Comment by elyiorgos** [comment] 2019-10-02 14:07
Hi Nima,

Thanks for taking a look at what I mentioned. I went ahead and updated the
the README to include a link to the contributions document. I completely
agree with your testing point, robust unit testing and integration tests
for the project are at the top of our to do list in terms of development.
Thanks again for your help and responsiveness! We're very excited!

Best,
Yiorgos

**Comment by lheagy** [comment] 2019-10-04 18:58
Many thanks @nhejazi for your speedy review! 

@elyiorgos: if you are able to include a test suite, that would be preferable for publication. Although having examples run does act as a test, that really is the bare minimum.

**Comment by lheagy** [comment] 2019-10-04 19:01
:wave: Just checking in @eskofier. How are things going? In order to check-off the boxes for the review, you will need to have accepted the JOSS invitation: https://github.com/openjournals/joss-reviews/invitations. Please let me know if you have any questions. Thanks for your work on this!

**Comment by ikarosilva** [comment] 2019-10-06 22:34
Hi Guys, sorry for the delay. 
Update my review list. My feedback:

1) I did not see any unit tests (am I missing something)? Would be nice to have a standard unit test folder that uses python unit test frameworks (nose etc).

2) Please avoid the use of wild imports such as:

from sleeppy.sleep import *
Instead, limit the scope of your import to only those functions/classes necessary. 

3)

**Comment by eskofier** [comment] 2019-10-07 21:28
Dear all,

I took a look at this with my senior PhD student Stefan Gradl (github: gradlman, also CCed). Feedback:

-> the code looks well documented where needed
-> we could not really test the code because of its programming in python 2.7. I don’t have a 2.7 installation anymore, neither does Stefan or most people in my lab (except 1). Stefan tried to get the code running for half a day by downloading old packages or searching for compatible ones, but without success. As Python 2.7 will not be supported anymore after the end of this year [1, 2], we decided to not try further.

[1] https://pythonclock.org
[2] https://www.anaconda.com/end-of-life-eol-for-python-2-7-is-coming-are-you-ready/

Please let us know how to proceed.

Best regards,
Bjoern Eskofier
-- 
Prof. Bjoern Eskofier, Ph.D.

FAU Sandbox: find out more about our newest FAU student startup & innovation program at www.sandbox.fau.de 

Heisenberg professorship of the DFG
Digital Sports and Health Group
Machine Learning and Data Analytics Lab
Department of Computer Science
Faculty of Engineering
Friedrich-Alexander University Erlangen-Nuernberg (FAU)
Carl-Thiersch-Strasse 2b, 91052 Erlangen, Germany

Adjunct Member, Faculty of Medicine
Speaker, Central Institute of Healthcare Engineering
Friedrich-Alexander University Erlangen-Nuernberg (FAU)
Henkestraße 91, 91052 Erlangen

I-net: http://www.mad.cs.fau.de
Phone: +49 9131 85-27297
Email: bjoern.eskofier@fau.de

**Comment by elyiorgos** [comment] 2019-10-08 19:36
Hello all,

I'll try to address things in order, though forgive me if I miss something.

@nhejazi Thank you for your quick feedback, and quick responses!

@lheagy With regards to a testing suite, without getting into any unnecessary details, the research project that helped spawn the package is currently being overhauled from a testing point of view, which will eventually require the addition of a full testing suite to the package, though this may take some time as other pipelines take priority.

@ikarosilva Thank you for your comments! I'll be sure to fix the wild import you showed, as well as any other similar instance across the package. As far as testing goes, the demo folder provides dummy data that can be automatically run through the package, producing reports and clinical endpoints for one night's sleep. When the demo is run, there are assertion tests that run through the produced endpoints and confirm that they match the expected output. I realize this is more of a full package integration test, and a full suite of unit tests in addition to that is desirable to verify that the package functions perform as expected, though as I mentioned above that may take some time. As written, the package does meet the _minimum_ testing requirements for publication, though I understand if that causes you(or others) to have reservations in your review.

@eskofier I'm sorry to hear you had difficulty getting the package to install and run. Assuming you have access to an apple computer, python 2.7 should be built-in and the sleeppy package can simply be pip-installed. The pip installation is written in such a way that it installs all required dependencies with the correct versions, which should be all you need to be able to run the demo/test from inside the python interpreter (more detailed run directions are available in the readme). I'm happy to provide any assistance beyond that if necessary, please let me know.

A conversion of the package to python 3 will soon be in the works (for exactly the reasons you mentioned), but will take a back seat to fleshing out testing, so the timeline for that will be somewhat more extended. Our choice of python 2.7 was related to the fact that the package wasn't developed in a vacuum, but had to be integrated with a large existing project code base that had python 2.7 dependencies. 

Please let me know if there are any more questions or comments, and thank you all for your help evaluating the package.

Best,
Yiorgos Christakis

**Comment by eskofier** [comment] 2019-10-08 19:51
Hi,

pip install did not work on an apple computer

Bjoern$ pip install sleeppy
Collecting sleeppy
  ERROR: Could not find a version that satisfies the requirement sleeppy (from versions: none)
ERROR: No matching distribution found for sleeppy


Manual install did not work

error: Setup script exited with error: library dfftpack has Fortran sources but no Fortran compiler found
(as well as several other errors)


Sorry, but I do not have time to mess with technology. I have a couple of hours of work ahead of me and it’s 10p


Viele Grüße
Bjoern

**Comment by yiorg** [comment] 2019-10-11 15:54
Hi Bjoern,

I understand your frustration, and I'm sorry this is adding to an already demanding schedule. My guess is that since your laptop is probably rather new and you yourself use python 3, it's likely that the default python environment is python 3, so when you run a normal pip command like you showed above, it tries to pull a distribution for python 3 and can't find one. I actually ran into the same issue on my personal laptop, but if you run `pip2 install sleeppy` it _should_ download and set up without a hitch. On my personal I had to run `sudo pip2 install sleeppy` due to a permissions error. After that, if you choose to run it from the python interpreter, just make sure that when starting python in the command line you run python2 as opposed to just python. Again that _should_ work, but if not please let me know. If necessary I'm more than happy to set up a call/chat with either you or your colleague to sort things out. Thank you again for agreeing to review the package, and for your feedback.

Best,
Yiorgos

**Comment by eskofier** [comment] 2019-10-12 21:24
Hi Yiorgos,

Did not work :/ When I run:

$ pip2 install sleeppy
-bash: pip2: command not found

Also:

$ pip3 install sleeppy
Collecting sleeppy
  ERROR: Could not find a version that satisfies the requirement sleeppy (from versions: none)
ERROR: No matching distribution found for sleeppy

Like before 

$ pip install sleeppy
Collecting sleeppy
  ERROR: Could not find a version that satisfies the requirement sleeppy (from versions: none)
ERROR: No matching distribution found for sleeppy

What should we try next?

Viele Grüße
Bjoern

**Comment by elyiorgos** [comment] 2019-10-14 15:29
Hi Bjoern,

Are you able to run python 2 from the command line with the command `python2`? If so you can install pip2 by running the following:

This will get you what you need to download pip
`wget https://bootstrap.pypa.io/get-pip.py`

This will install pip for python 2
 `sudo python2 get-pip.py`

This will install pip for python 3
`sudo python3 get-pip.py`

Now if you call pip, or pip3, you will get pip for python 3, and if you call pip2, you'll get pip for python 2. From there running `pip2 install sleeppy` should work.

If running `python2` doesn't work for you for whatever reason, let me know and we can continue from there.

Best,
Yiorgos

**Comment by lheagy** [comment] 2019-10-14 16:59
@elyiorgos and @eskofier: If getting up and running locally is proving to be challenging, then I would recommend that @elyiorgos set up an example that runs on [binder](http://mybinder.org). You will need to specify an environment.yml file that contains the dependencies, and binder will install those for you and give you a sandbox computational environment to run the code. See for example this demo repository: https://github.com/binder-examples/python-conda_pip. 

Creating a binder demonstrates that the software can be installed, and doesn't mess with @elyiorgos's software environment. 

Please let me know if you run into any challenges getting up and running with binder.

**Comment by eskofier** [comment] 2019-10-14 20:45
> Are you able to run python 2 
Yes, that works.


> wget https://bootstrap.pypa.io/get-pip.py
Doesn’t work:
-bash: wget: command not found


Viele Grüße
Bjoern

Social Media: find out more about

FAU Sandbox
www.sandbox.fau.de
https://twitter.com/FauSandbox
https://www.instagram.com/fausandbox
https://www.linkedin.com/company/fau-sandbox
https://www.facebook.com/FAUSandbox

MaD Lab
www.mad.tf.fau.de
https://twitter.com/fau_mad_lab
https://twitter.com/bjoerneskofier
www.linkedin.com/in/bjoerneskofier
https://de-de.facebook.com/FAU.MaD.Lab

**Comment by yiorg** [comment] 2019-10-15 21:39
@lheagy Thank you for the suggestion, that seems like the best way forward. I'll get working on it as soon as possible and share it here once I have it up and running!

Best, 
Yiorg

**Comment by elyiorgos** [comment] 2019-10-24 15:16
@lheagy @eskofier Thank you for your patience guys, the binder example is up and running! It's accessible from the readme in the demo section, but the following link should work as well: 

https://mybinder.org/v2/gh/elyiorgos/sleeppy/master?filepath=example_notebook%2Fexample.ipynb

The environment may take a little while to set up (5-10 minutes maybe), but the version of the demo I have posted has all the data preloaded, so that portion should run quickly. In the results folders the pdfs that are generated don't open in browser for me (no idea why), but if you download them to local you can see them just fine.

Let me know if you have any issues, thanks again!
Yiorg

**Comment by lheagy** [comment] 2019-11-05 16:48
:wave: Hi @eskofier, just checking in. Have you had a chance to check out the binder link posted above? This should give you an environment where you can run the examples and play with the code-base.

**Comment by eskofier** [comment] 2019-11-05 20:01
Hi, I will try to have a look the next few days.

Viele Grüße
Bjoern

**Comment by eskofier** [comment] 2019-11-13 10:48
Dear all,

I tried the demo, but got stuck - I am copying in the output of the Notebook below, and also provide a screenshot what happens when I "Simply copy the url above, and replace /example.ipynb with /demo to load the demo folder.“. How should we proceed?

—————> Notebook output:

Example sleeppy usage: running the demo
This short tutorial serves to confirm that sleeppy installs and runs correctly.
In [1]:

# We first import the demo from sleeppy.
import sleeppy.tests as demo
In [2]:

# next we get the current working directory
import os
print(os.getcwd())
/home/jovyan/example_notebook

In [*]:

# The next step is to run the demo and provide the current working directory as the results directory
demo.run_demo(binder_demo=True)
Please provide a path to a results directory:    /Users/Bjoern/Desktop/Joss

Your previous entry was not appropriate.
It should follow a format similar to /home/jovyan/example_notebook
Please provide a path to a results directory:    

Now you can go to the generated results and explore sleeppy's outputs
Simply copy the url above, and replace /example.ipynb with /demo to load the demo folder.


—————> End notebook output


Viele Grüße
Bjoern

**Comment by elyiorgos** [comment] 2019-11-13 15:00
Hi Bjoern,

Thanks for giving it a shot! The demo failed because the directory you provided wasn't the current working directory. Since the binder environment is one hosted online, if you provide a local directory  it fails and prompts you to use a directory with the proper format and location (usually `/home/jovyan/example_notebook`). That's the reason the current working directory is printed in the previous statement, so it can be copy pasted easily as input.

So just to be 100% clear, when you run the demo and it prompts you with:

 Please provide a path to a results directory:

You should just copy the current working directory printed above, (likely: /home/jovyan/example_notebook)
and continue with that.

Let me know if you have any more issues, thank you!

Best,
Yiorgos

**Comment by eskofier** [comment] 2019-11-13 21:38
Dear All,

This worked, the results are partially unclear though - the pdf don’t work?
Could you provide an a bit more in-depth insight into what happens during the demo, what the input data is and what is outputtet.
Also, the python version issue remains. What is the opinion of the editor and the other reviewer on this?

Viele Grüße
Bjoern

**Comment by elyiorgos** [comment] 2019-11-13 22:54
Hi Bjoern,

Happy to hear it worked!

With respect to the pdf's I think I had mentioned somewhere in an earlier message in the thread that for some reason the pdf's aren't viewable in browser, to see them you have to download them locally unfortunately.  

In terms of what happens during the demo/during any given run of the package I would refer you to the readme (or the paper itself) for a more detailed description of what's going on in general, but in short:

- The input data is Geneactiv accelerometer data collected from the wrist location (in either .csv or .bin form, the demo data is 24 hours of sample data in .bin format)
- The output data is a set of quantitative clinical measures related to sleep in csv format, as well as visual reports showcasing those clinical measures both per 24 hour window, and across the entire recording (For the demo there's only a single day's worth).
- The calculation of clinical measures is achieved by the running of several published algorithms (implemented here as methods within the sleeppy class, or as separate classes). These include the calculation of major rest period(the window during which the person is in bed for the night), the calculation of an activity feature (used as an input to sleep/wake classification), the classification of each minute of data to either sleep or wake, and a regime for on-body detection.

With respect to versioning I will chime in and say that the python 3 implementation is essentially finished (barring some validation and documentation of some of the implemented updates), the python 2 implementation will be retired, but frozen, and a more comprehensive and thorough testing suite will accompany the python 3 version (using pytest as a framework). 

I hope that helped clear things up, please let me know if you have any more questions. Thank you!

Best,
Yiorgos

**Comment by elyiorgos** [comment] 2019-11-26 21:04
Hi all, just checking in to see if there's anything missing or anything I can clear up. Thanks again for taking the time. For those of you celebrating Thanksgiving soon I hope you enjoy the break!

Best,
Yiorgos

**Comment by eskofier** [comment] 2019-11-26 21:07
Dear other reviewers and editor,

I did ask about the version issue - if the others don‘t see this as problematic, Ineould be OK with accepting overall. 

Best regards,
Bjoern



-sent from mobile office-

**Comment by lheagy** [comment] 2019-12-03 23:56
Thanks @eskofier! Have you had a chance to take a look at the check-boxes in the main issue description? If you are satisfied with their current state, could you please tick off the boxes under your name? If you are unable to check the boxes, you might need to accept the invitation at: https://github.com/openjournals/joss-reviews/invitations

**Comment by eskofier** [comment] 2019-12-04 09:53
Hi,

I just read through all the boxes and I would tick them all off if I could - how do I do that (on an iPhone)? I just spent 15 minutes searching and trying. 

Best regards,
Bjoern



-sent from mobile office-

**Comment by lheagy** [comment] 2019-12-06 23:33
Thanks @eskofier, with your written confirmation, I can tick them off for you.

**Comment by lheagy** [comment] 2019-12-06 23:34
@whedon generate pdf

**Comment by whedon** [comment] 2019-12-06 23:34
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-12-06 23:35
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01663/joss.01663/10.21105.joss.01663.pdf)

**Comment by yiorg** [comment] 2019-12-09 20:07
Thank you everyone! 

From what I can tell the article proof looks good. Please let me know about any next steps on our end. 

Best,
Yiorgos

**Comment by lheagy** [comment] 2019-12-09 20:50
@whedon check references

**Comment by whedon** [comment] 2019-12-09 20:50
```
Attempting to check references...
```

**Comment by whedon** [comment] 2019-12-09 20:51
```Reference check summary:

OK DOIs

- 10.1152/japplphysiol.00421.2014 is OK
- 10.1371/journal.pone.0142533 is OK
- 10.1371/journal.pone.0160644 is OK
- 10.1093/sleep/15.5.461 is OK
- 10.1038/s41598-018-31266-z is OK
- 10.5281/zenodo.1051064 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by elyiorgos** [comment] 2019-12-12 16:58
Hi @lheagy, 

Based on the above passing I went ahead and made a new release (0.2.21) and archived it at zenodo with DOI: 10.5281/zenodo.3572581

I made sure the title of the archive matches the title of the paper and that the authors of the archive match the authors of the paper.

Please let me know if everything looks good and if there's anything else for me to take care of. Thank you!

Best,
Yiorgos

**Comment by lheagy** [comment] 2019-12-16 18:55
Excellent, thanks @elyiorgos! and apologies for my delay - I was at the AGU conference last week and was a bit overloaded.  

This looks good. Many thanks @eskofier, @ikarosilva, @nhejazi for your review 🎉

**Comment by lheagy** [comment] 2019-12-16 18:55
@whedon set 10.5281/zenodo.3572581 as archive

**Comment by whedon** [comment] 2019-12-16 18:55
OK. <a href="https://doi.org/10.5281/zenodo.3572581" target="_blank">10.5281/zenodo.3572581</a> is the archive.

**Comment by lheagy** [comment] 2019-12-16 18:58
@whedon set 0.2.21 as version

**Comment by whedon** [comment] 2019-12-16 18:58
OK. 0.2.21 is the version.

**Comment by lheagy** [comment] 2019-12-16 18:59
:wave: @openjournals/joss-eics, this submission is ready fo final checks!

**Comment by arfon** [comment] 2019-12-18 14:39
@whedon accept

**Comment by whedon** [comment] 2019-12-18 14:39
```
Attempting dry run of processing paper acceptance...
```

**Comment by whedon** [comment] 2019-12-18 14:40
```Reference check summary:

OK DOIs

- 10.1152/japplphysiol.00421.2014 is OK
- 10.1371/journal.pone.0142533 is OK
- 10.1371/journal.pone.0160644 is OK
- 10.1093/sleep/15.5.461 is OK
- 10.1038/s41598-018-31266-z is OK
- 10.5281/zenodo.1051064 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2019-12-18 14:40
Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/1182

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/1182, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by arfon** [comment] 2019-12-18 14:54
@whedon accept deposit=true

**Comment by whedon** [comment] 2019-12-18 14:54
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment] 2019-12-18 14:55
🐦🐦🐦 👉 [Tweet for this paper](https://twitter.com/JOSS_TheOJ/status/1207313464504524801) 👈 🐦🐦🐦

**Comment by whedon** [comment] 2019-12-18 14:55
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/1183
1. Wait a couple of minutes to verify that the paper DOI resolves [https://doi.org/10.21105/joss.01663](https://doi.org/10.21105/joss.01663)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? notify your editorial technical team...

**Comment by arfon** [comment] 2019-12-18 15:20
@eskofier, @ikarosilva, @nhejazi - many thanks for your reviews here and to @lheagy for editing this submission ✨ 

Also, special congratulations to @lheagy for editing her final JOSS paper. Thanks for all of efforts @lheagy making JOSS the success it is!

@elyiorgos - your paper is now accepted into JOSS :zap::rocket::boom:

**Comment by arfon** [comment] 2019-12-18 15:23
I'm going to keep this issue upon for a while until the PDF is resolving on GitHub pages...

**Comment by arfon** [comment] 2019-12-18 16:00
> I'm going to keep this issue upon for a while until the PDF is resolving on GitHub pages...

Update - looks like this is working now.

**Comment by whedon** [comment] 2019-12-18 16:00
:tada::tada::tada: Congratulations on your paper acceptance! :tada::tada::tada:

If you would like to include a link to your paper from your README use the following code snippets:

```
Markdown:
[![DOI](https://joss.theoj.org/papers/10.21105/joss.01663/status.svg)](https://doi.org/10.21105/joss.01663)

HTML:
<a style="border-width:0" href="https://doi.org/10.21105/joss.01663">
  <img src="https://joss.theoj.org/papers/10.21105/joss.01663/status.svg" alt="DOI badge" >
</a>

reStructuredText:
.. image:: https://joss.theoj.org/papers/10.21105/joss.01663/status.svg
   :target: https://doi.org/10.21105/joss.01663
```
This is how it will look in your documentation:

[![DOI](https://joss.theoj.org/papers/10.21105/joss.01663/status.svg)](https://doi.org/10.21105/joss.01663)

**We need your help!**

Journal of Open Source Software is a community-run journal and relies upon volunteer effort. If you'd like to support us please consider doing either one (or both) of the the following:

- Volunteering to review for us sometime in the future. You can add your name to the reviewer list here: https://joss.theoj.org/reviewer-signup.html
- Making a small donation to support our running costs here: https://numfocus.org/donate-to-joss

**Closed by arfon** 2019-12-18 16:00 UTC
Labels: accepted, review
