### ISSUE TITLE
[PRE REVIEW]: `hopit`: An R Package for Analysis of Reporting Behavior Using Generalized Ordered Probit Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1481] opened 2019-05-30 19:37 UTC
**Submitting author:** @MaciejDanko (<a href="http://orcid.org/0000-0002-7924-9022">Maciej J. Dańko</a>)
**Repository:** <a href="https://github.com/MaciejDanko/hopit" target ="_blank">https://github.com/MaciejDanko/hopit</a>
**Version:** 0.9.2.9000
**Editor:** @alexhanna
**Reviewers:** @soodoku, @mkearney

**Author instructions**

Thanks for submitting your paper to JOSS @MaciejDanko. **Currently, there isn't an JOSS editor assigned** to your paper.

@MaciejDanko if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-05-30 19:37
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-05-30 19:37
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-05-30 19:37
PDF failed to compile for issue #1481 with the following error: 

 Error producing PDF.
! LaTeX Error: File `float.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.253 ^^M

Looks like we failed to compile the PDF

**Comment by kyleniemeyer** [comment] 2019-05-30 19:37
Hi @alexhanna, this submission looks up your alley. Do you have the bandwidth to edit this submission?

**Comment by kyleniemeyer** [comment] 2019-05-30 19:41
Hi @MaciejDanko, our automated system is having some trouble compiling your paper—I think it is the (attempted) inclusion of the `float` package, and then using the LaTeX figure commands in the Markdown paper. Can you instead try to use Markdown figure commands?

@arfon, can you comment on whether this *should* be possible? I know we have been working on supporting fully LaTeX-based submissions, if that is necessary for what the author wants.

**Comment by arfon** [comment] 2019-05-30 20:20
> @arfon, can you comment on whether this should be possible? I know we have been working on supporting fully LaTeX-based submissions, if that is necessary for what the author wants.

If possible, we strongly prefer people to use standard Markdown syntax here for including figures.

e.g. `Figures can be included like this: ![Example figure.](figure.png)`

**Comment by MaciejDanko** [comment] 2019-05-31 05:29
Thank you for your quick response,
paper.md is written in the standard Markdown syntax now

**Comment by MaciejDanko** [comment] 2019-05-31 08:28
Dear all,
Thank you for your quick response
I removed LaTeX style from md file.
The problem is that the last figure appears now after acknowledgements.
Best wishes,
Maciej
________________________________________

**Comment by alexhanna** [comment] 2019-05-31 16:48
@whedon generate pdf

**Comment by whedon** [comment] 2019-05-31 16:48
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-05-31 16:49
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01481/joss.01481/10.21105.joss.01481.pdf)

**Comment by kyleniemeyer** [comment] 2019-05-31 17:04
@MaciejDanko great, thanks! @alexhanna I'll leave this in your hands now.

**Comment by kyleniemeyer** [comment] 2019-05-31 17:05
@whedon assign @alexhanna as editor

**Comment by whedon** [comment] 2019-05-31 17:05
OK, the editor is @alexhanna

**Comment by MaciejDanko** [comment] 2019-05-31 18:50
I checked the paper proof and found that there is a problem with figure 3 caption.
The md code looks OK, I don't know why there is a problem.

**Comment by MaciejDanko** [comment] 2019-06-08 06:12
... I think this is Whedon's problem, I could generate the pdf without mistakes.
Anyway, I shortened the caption of the figure 3 and added additional blank lines
Could you check if it works now?

**Comment by arfon** [comment] 2019-06-08 18:55
@whedon generate pdf

**Comment by whedon** [comment] 2019-06-08 18:55
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-06-08 18:55
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01481/joss.01481/10.21105.joss.01481.pdf)

**Comment by arfon** [comment] 2019-06-08 19:00
@MaciejDanko - you had a typo in your `paper.md` which I've fixed in https://github.com/MaciejDanko/hopit/pull/5

**Comment by MaciejDanko** [comment] 2019-06-08 20:35
I don't know why I didn't notice the typos. 
Thank you very much! 
paper.md is updated now.

**Comment by arfon** [comment] 2019-06-08 20:47
@whedon generate pdf

**Comment by whedon** [comment] 2019-06-08 20:47
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-06-08 20:48
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01481/joss.01481/10.21105.joss.01481.pdf)

**Comment by MaciejDanko** [comment] 2019-06-08 21:43
Proof checked. No problems found. Thank you.

**Comment by MaciejDanko** [comment] 2019-06-14 14:10
**@alexhanna** - I looked at the reviewers list. Here are my suggestions:

soodoku
Tgerke
benmarwick
lebebr01
mariacuellar
vincentarelbundock
mkearney

**Comment by alexhanna** [comment] 2019-06-16 16:08
Thanks.

@soodoku
@Tgerke
@benmarwick
@lebebr01
@mariacuellar
@vincentarelbundock
@mkearney

We need two reviewers for this submission. Would any of you be willing to review?

**Comment by soodoku** [comment] 2019-06-16 19:17
Sure.

**Comment by vincentarelbundock** [comment] 2019-06-16 19:19
I'm also happy to take a look, but I'll be travelling for work, so unlikely to get to this before about 3 weeks.

**Comment by mkearney** [comment] 2019-06-16 21:15
I'd be willing to review as well.

**Comment by alexhanna** [comment] 2019-06-17 15:53
I'll assign @soodoku and @mkearney based on availability, then. Thanks all.

**Comment by alexhanna** [comment] 2019-06-17 15:53
@whedon assign @soodoku as reviewer

**Comment by whedon** [comment] 2019-06-17 15:54
OK, the reviewer is @soodoku

**Comment by alexhanna** [comment] 2019-06-17 15:54
@whedon add @mkearney as reviewer

**Comment by whedon** [comment] 2019-06-17 15:54
OK, @mkearney is now a reviewer

**Comment by alexhanna** [comment] 2019-06-17 15:54
@whedon start review

**Comment by whedon** [comment] 2019-06-17 15:54
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1508. Feel free to close this issue now!

**Closed** 2019-06-17 17:43 UTC
Labels: C++, R, TeX, pre-review
