### ISSUE TITLE
[REVIEW]: Dune-MMesh: The Dune Grid Module for Moving Interfaces

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3959] opened 2021-11-29 22:29 UTC
**Submitting author:** @samuelburbulla (<a href="http://orcid.org/0000-0002-2566-9777">Samuel Burbulla</a>)
**Repository:** https://github.com/samuelburbulla/dune-mmesh/
**Branch with paper.md** (empty if default branch): feature/paper
**Version:** v1.3.2
**Editor:** @diehlpk
**Reviewers:** @krober10nd, @vijaysm
**Archive:** 10.5281/zenodo.6705603

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0/status.svg)](https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0"><img src="https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0/status.svg)](https://joss.theoj.org/papers/fd01af083a08d06dcfe64c8b13ddd0e0)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/samuelburbulla/dune-mmesh/" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@krober10nd & @ @vijaysm, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @diehlpk know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @krober10nd
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/samuelburbulla/dune-mmesh/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/samuelburbulla/dune-mmesh/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@samuel.burbulla) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @ @vijaysm
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/samuelburbulla/dune-mmesh/">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/samuelburbulla/dune-mmesh/">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@samuel.burbulla) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2021-11-29 22:29
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @krober10nd, @ @vijaysm it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-11-29 22:29
PDF failed to compile for issue #3959 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment] 2021-11-29 22:29
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.82 s (888.3 files/s, 230731.9 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C/C++ Header                   601          24036          17975         120957
C++                             25            487            242           1865
Python                          21            551            563           1024
make                             2            110             72            959
Markdown                         3            132              0            597
GLSL                            12             83            111            446
Jupyter Notebook                 6              0           1283            423
reStructuredText                34            208          16214            282
CMake                           19             57             17            241
YAML                             3             15              4            103
DOS Batch                        1              8              1             26
TOML                             1              0              0              3
-------------------------------------------------------------------------------
SUM:                           728          25687          36482         126926
-------------------------------------------------------------------------------


Statistical information for the repository '1203757d924ee5f3b5784485' was
gathered on 2021/11/29.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Maximilian Hörl                  3           599            143            0.38
Samuel                          18           665            216            0.45
Samuel Burbulla                286        179458          12786           98.77
Timo Koch                        4            12             15            0.01
dedner                          16           586            161            0.38

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Maximilian Hörl             374           62.4         21.2               18.45
Samuel Burbulla          167150           93.1          5.8               11.71
Timo Koch                     5           41.7          5.6                0.00
dedner                      171           29.2         17.2                2.34
```

**Comment by diehlpk** [comment] 2021-11-29 22:29
@whedon generate pdf from branch feature/paper

**Comment by whedon** [comment] 2021-11-29 22:29
```
Attempting PDF compilation from custom branch feature/paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-11-29 22:30
PDF failed to compile for issue #3959 with the following error: 
```
 [WARNING] Citeproc: citation vijaysm not found
Error producing PDF.
! Undefined control sequence.
\hyper@@link ->\let \Hy@reserved@a 
                                   \relax \@ifnextchar [{\hyper@link@ }{\hyp...
l.348 }

Looks like we failed to compile the PDF

```

**Comment by diehlpk** [comment] 2021-11-29 22:30
@whedon generate pdf from branch feature/paper

**Comment by whedon** [comment] 2021-11-29 22:30
```
Attempting PDF compilation from custom branch feature/paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-11-29 22:31
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03959/joss.03959/10.21105.joss.03959.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03959/joss.03959/10.21105.joss.03959.pdf) :page_facing_up: :point_left:

**Comment by vijaysm** [comment] 2021-12-07 18:09
@diehlpk I can't seem to edit the review checkboxes. Perhaps my username didn't get authorized ? I see that there are two "@" symbols there, which is possibly causing an issue.

**Comment by danielskatz** [comment] 2021-12-07 18:29
@whedon re-invite @vijaysm as reviewer

see if this helps

**Comment by whedon** [comment] 2021-12-07 18:29
OK, the reviewer has been re-invited.

@vijaysm please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by vijaysm** [comment] 2021-12-07 18:48
@danielskatz Thanks, that worked!

**Comment by diehlpk** [comment] 2021-12-07 20:11
> @whedon re-invite @vijaysm as reviewer
> 
> see if this helps

@danielskatz Thanks for your support. I have the final exam week and was not so quick.

**Comment by whedon** [comment] 2021-12-13 22:29
:wave: @krober10nd, please update us on how your review is going (this is an automated reminder).

**Comment by diehlpk** [comment] 2022-01-01 23:51
Hi @vijaysm and @krober10nd how is your review going?

**Comment by krober10nd** [comment] 2022-01-02 00:02
Hey @diehlpk im on a holiday until the 6 of January then will continue where we left off. I tried a number of ways to install the package to no avail on my personal laptop. I can try with another OS and see if I have better luck. I’ve posted issues on the repository.

**Comment by vijaysm** [comment] 2022-01-03 17:23
@diehlpk Happy new year! I got caught up with some holiday travel as well. I'll document the installation and usage procedures and start an issue page as needed this coming week. Will try to finish up the review in the next two weeks.

**Comment by krober10nd** [comment] 2022-01-09 21:27
@samuel.burbulla I have tried on a different clean laptop and OS and encountered the same error as I noted in your repo. The program appears to install but I cannot import or run any of the examples. I look forward to @vijaysm for help here. 

I cannot procced further with the review of this software if I cannot install correctly...

**Comment by vijaysm** [comment] 2022-01-12 16:37
@krober10nd My installation tries on my macbook have not been successful. The errors are related to OpenMP includes and I think you have already raised this issue. I haven't had the time to fully debug the issue.

I am also going to try on either a Fedora or an Ubuntu machine this week. I'll let you know how the installation proceeds. @samuel.burbulla

**Comment by diehlpk** [comment] 2022-01-18 03:11
@samuel.burbulla could you please have a look?

**Comment by samuelburbulla** [comment] 2022-01-21 10:12
Hi @vijaysm,
as you mentioned, we discussed this issue in [#2](https://github.com/samuelburbulla/dune-mmesh/issues/2) and I proposed the following solution:

````
1. brew install libomp
2. export CXXFLAGS="-lomp -L/opt/homebrew/Cellar/libomp/13.0.0/lib/"
````

Somehow, CMake finds the package OpenMP and sets OPENMP_FOUND, but afterwards the compiler does not find the `<omp.h>` header. I just cross checked this behaviour on my Mac both with and without OpenMP, but unfortunately I am not able to reproduce the issue.

**Comment by vijaysm** [comment] 2022-01-26 12:04
I apologize for the delay. I have been unwell and plan to restart my review next week. I will update more soon. @diehlpk @samuelburbulla

**Comment by samuelburbulla** [comment] 2022-01-26 14:38
I created a notebook on Google Colab where I was able to install dune-mmesh and run a short example:

https://colab.research.google.com/drive/1CB8HohQ0gE2LU0PET-N2bTnElzRILBbR?usp=sharing

Maybe this is useful for testing code? At least, you might compare your setup with this one.
Unfortunately, the usability there is a bit unhandy in my opinion, and it takes its time to compile everything when starting a new runner.

Remark that in the meantime I uploaded a new package 1.3.1.post1 where I updated the version requirement of dune-fem to 2.8.0.6. Compared to version 2.8.0.5 some things regarding OMP have been fixed, maybe this already fixes your errors with omp.

**Comment by vijaysm** [comment] 2022-02-11 21:10
I had no success in getting the installation working on my Ubuntu (18.04) workstation either. I am unsure whether it was due to my CMake version not being up to the requirement. However, I'm going to try to see if I can get a clean environment on a Docker container with Ubuntu-latest to run your commands from the notebook to see if I can make progress. I apologize that this has taken more time than expected. I will document what I see and get back to you.

On a separate note, I would advise some form of simplification to the installation procedure. I understand that `pip install dune-mmesh` is as simple as it gets, but the installation has failed in more than one architecture. The errors seen should be better documented, and architecture-specific instructions if possible should be posted on the readthedocs page to help users get started easily.

**Comment by diehlpk** [comment] 2022-03-07 02:33
@krober10nd, @vijaysm could you please try again to install the software?

**Comment by vijaysm** [comment] 2022-03-08 17:11
It took me couple of iterations, but I think I have dune-mmesh successfully installed now in a Docker container. It may be simple to document this explicitly in your README for someone wanting to get started.
```
Steps to install Dune-MMesh on Ubuntu 20.04

1) docker run -it ubuntu:latest
2) apt update
3) apt install g++ cmake python3 python3-pip libboost-dev libopenmpi3 git
4) pip install dune-mmesh
```
I can now clone the repository and play with the examples locally. I have the image with dune-mmesh installed but have not had the time to experiment with the scripts. Meanwhile, any updates to the documentation for better procedures to install the library will be helpful, especially given the number of underlying dependencies.

**Comment by krober10nd** [comment] 2022-03-08 23:10
Okay. I've tried the identical set of steps and it's failed on my end although I don't have Ubuntu to test on. The fact that it's been this challenging to install is not a good sign. How are other users using this code? Can this be simplified?

**Comment by diehlpk** [comment] 2022-03-09 14:51
@samuelburbulla What about proving some Docker image with the latest stable version or master for testing the code?

**Comment by diehlpk** [comment] 2022-03-09 14:51
Or at least a Docker file with the installation instructions?

**Comment by diehlpk** [comment] 2022-03-15 14:20
@samuel.burbulla could you please respond to the comments above?

**Comment by samuelburbulla** [comment] 2022-03-16 08:43
@vijaysm Thanks a lot for trying again and posting your Docker setup steps.

High appreciation for all of your feedback and your suggestions!

I agree that the installation is not yet clear enough, in particular regarding the large list of dependencies. So far, essentially people were using Dune-MMesh who had a working setup of DUNE on their system already, or a system which was preconfigured in that manner.

Reducing the requirements would be favourable, but is not easy, as many of them are implicit requirements of DUNE or dune-fem. I will try to make more of the dependencies optional (e.g. MPI is optional on the master already), but many of them will remain and are not installable via pip.

Following the setup of @vijaysm I added a more verbose description to the README.md and to the installation page. I think this makes things more clear and provides a simpler entry point. Can you have a look?

@diehlpk I would like to avoid providing a Docker image that has to be updated in the future. Do you think the updated documentation (including the docker setup) is sufficient?

@krobner10nd Have you tried to use the Docker setup with the ubuntu image? This is working on my Mac. And can you try following the steps I added for an installation on MacOS? This is how I use it on my Mac.

**Comment by diehlpk** [comment] 2022-03-16 15:29
> @diehlpk I would like to avoid providing a Docker image that has to be updated in the future. Do you think the updated documentation (including the docker setup) is sufficient?

I think a Docker image is not necessary, however, a Docker file like posted by @vijaysm and some instructions how to run it would be good.

**Comment by samuelburbulla** [comment] 2022-03-17 17:45
Update: There is now a Dockerfile which builds a running container with preconfigured Dune-MMesh.
````
docker build -t mmesh \
  https://raw.githubusercontent.com/samuelburbulla/dune-mmesh/master/scripts/Dockerfile
docker run -it mmesh
````
This also works now on the Mac with its ARM architecture.

**Comment by diehlpk** [comment] 2022-03-18 22:03
> Update: There is now a Dockerfile which builds a running container with preconfigured Dune-MMesh.
> 
> ```
> docker build -t mmesh \
>   https://raw.githubusercontent.com/samuelburbulla/dune-mmesh/master/scripts/Dockerfile
> docker run -it mmesh
> ```
> 
> This also works now on the Mac with its ARM architecture.

@samuelburbulla That sounds good. You might want to add that to the README.md and documentation. Maybe you can write that if one just wants to test and play with your code, the Docker approach is the easiest way. Just put the commands how to run the docker image and possibly execute one example. 

After that you can write that people, who want to implement new features or run heavier examples, should install the code and provide the install instructions.

**Comment by diehlpk** [comment] 2022-03-28 17:45
Hi @samuelburbulla any news?

**Comment by diehlpk** [comment] 2022-03-28 17:46
HI @vijaysm and @krober10nd could you solve the installation issues?

**Comment by vijaysm** [comment] 2022-04-16 20:04
Just an update: I should be able to finish up the review in the next couple of days. @diehlpk @samuelburbulla

**Comment by krober10nd** [comment] 2022-04-21 14:28
@diehlpk sure I can try this weekend, although I have left several more general issues and thoughts to consider on the github page for this package and paper that have yet to be addressed.

**Comment by samuelburbulla** [comment] 2022-04-21 16:23
@diehlpk I had a look at the issues of @krober10nd.
Apart from that I am awaiting the feedback of @vijaysm about the installation/examples.

**Comment by diehlpk** [comment] 2022-04-25 17:19
> I unfortunately cannot finish my review this week or next. I'm on travel due to a death in the family. Not in a state of mind to complete this before early May.

Sorry to hear about your lost. Please take your time.

**Comment by krober10nd** [comment] 2022-04-30 13:08
@diehlpk I was able to install it finally and verified some more aspects of the paper. 

I would like to @samuelburbulla to iterate a couple times on the paper following my issues I've posted on his repo as I believe several aspects of the paper can be improved.

**Comment by diehlpk** [comment] 2022-05-11 18:14
@samuelburbulla Please let us know once you finished these edits.

**Comment by krober10nd** [comment] 2022-05-14 14:51
I am okay with recommending this article provided the article is edited and improved.

**Comment by vijaysm** [comment] 2022-05-16 02:56
My return back to work took a little longer than anticipated. I'll be able to finish the review this week.

**Comment by samuelburbulla** [comment] 2022-05-16 09:07
> @samuelburbulla Please let us know once you finished these edits.

I finished the edits addressed by @krober10nd.

**Comment by samuelburbulla** [comment] 2022-05-23 11:06
Thanks @vijaysm for your helpful comments! I will try to address your points below, and will make the changes right away on the feature/paper branch.

1. In the introduction section (L.8-L.12), you mention that both 2d and 3d meshes are supported using CGAL interface. However, you immediately talk about adaptivity or remeshing only in 2d with no mention of 3d. Is this intentional or an oversight? I noticed the same in L.51-L.52.

I must briefly mention that the introduction has changed somewhat due to comments from @krober10nd. However, the statement is still present and intended. The CGAL wrapper and the interface grid are fully implemented in 3d, but remeshing in 3d is not supported (yet). This is because removing vertices is not supported by the underlying CGAL Triangulation_3 class and more thought needs to be given to this.

2. In Figure 1, CGAL representations and DUNE numbering differ, and this is marked clearly. However, I only see face numbering for CGAL and no edge numbering in the 3D-Tet figure. I see that you mention in the text that CGAL doesn't provide one, but DUNE does? It would help to better clarify the legend and text.

Yes, DUNE does explicitly require a numbering of the edges. For instance, this can be relevant when defining finite-element spaces with Dofs at edges. I added a clarification to the article and extended the caption.

3. L.37: What do you mean by "Dune intersections" here? Are these referring to the interface intersection on a given mesh? Clarify or perhaps rephrase.

The term ‘Dune intersection’ means “Intersection of a mesh entity of codimension 0 with a neighboring element or with the domain boundary.” Clearly this needs to be clarified, and I added the definition to the article.

4. What are the light gray lines in the left figure of Figure 4? Is this a 2d or a 3d domain? It is confusing. Please clarify.

The gray and black lines each show a 2d triangulation. The gray triangulation is transformed by the blue vertex shifts into to black triangulation. I added a clarification to the caption of the figure.

5. L.56-57: To prevent degeneracy of cells, do you run mesh optimizations or smoothing procedures? Is this part of the remeshing routines? If yes, please expand accordingly. And if you do, are you using Dune or CGAL for it?

We apply no mesh optimizations or smoothing, just the remeshing procedures described thereafter in section “Adaptation”. As this is our own implementation, we use neither Dune nor CGAL. In L.58 I now refer explicitly to the adaptation section and within this section, I now elaborate on how we mark cells exactly.

6. L.64: "inavoidable" -> "unavoidable"

Corrected.

7. Suggestion: It might be worthwhile to show the objective error as a function of grid adaptation alongside the solution as well. Perhaps as a second row (subfigure). This will show how the error remains bounded or monotonically decreasing as the moving boundary problem is adaptively resolved.

I am not quite sure if I understand correctly what you suggest. In the moving example, I can plot the L2-Error between the numerical solution and the exact solution over time. This results in the following plot and shows that error increases over time as one would expect for such kind of time-dependent problems, I guess? So, where do you expect a bounded or monotonically decreasing error?

![Screenshot 2022-05-23 at 12 53 33](https://user-images.githubusercontent.com/34940349/169806107-41e44f2d-aba9-4f58-9158-fdb4d399d984.png)

**Comment by vijaysm** [comment] 2022-05-28 00:11
I have been trying to run the examples but have not had luck so far. I have been able to compile and link the tests without any issues. However, running the tests does not yield any output whatsoever. For example, `test-grid-2d` and `test-femadaptation` under dune/mmesh/test just sit at 100% CPU usage even after 2 hours. Are these supposed to take this long?

**Comment by vijaysm** [comment] 2022-06-06 02:52
@samuelburbulla So looks like the `.msh` files were just lfs references and so after I installed `git-lfs` as well, was able to git pull cleanly and get the full files. My further tries to run the examples still fail. I will open an issue in the repo related to this where we can further discuss and debug the issue.

**Comment by vijaysm** [comment] 2022-06-06 03:39
> I am not quite sure if I understand correctly what you suggest. In the moving example, I can plot the L2-Error between the numerical solution and the exact solution over time. This results in the following plot and shows that error increases over time as one would expect for such kind of time-dependent problems, I guess? So, where do you expect a bounded or monotonically decreasing error?

I meant that for any fixed point in time, adapting the mesh to the interface should produce a numerical solution that is much more accurate than the un-adapted one. Hence, my question was about plotting such an error convergence as a function of the adaptation levels/iterates, which I expect to decrease monotonically. The figure you shared above, in my understanding, is a time-dependent error, which has the temporal error component in addition to the spatial error due to moving interfaces. This certainly may not be monotone depending on how the temporal error propagates (immaterial of how well you adapt spatially).

**Comment by samuelburbulla** [comment] 2022-06-10 19:16
Of course, for any point in time we can compare the non-adapted solution to the adapted one, and the latter is always lower. 
For the moving example this looks like this:

<img width="444" alt="Screenshot 2022-06-10 at 20 52 52" src="https://user-images.githubusercontent.com/34940349/173134607-028e4360-555b-4dd9-a73c-a086ae09d719.png">

Probably I have to clarify one point: We do not adapt the mesh _to_ the interface, but actually move the corresponding interface edges. Therefore, there are no adaptation levels/iterates that reduce the error at the interface, it is already minimal. The adaptation of the mesh only happens next to the interface, but does not influence the discontinuity at the interface. Does that clear up the question?

**Comment by vijaysm** [comment] 2022-06-15 17:16
> Probably I have to clarify one point: We do not adapt the mesh to the interface, but actually move the corresponding interface edges. Therefore, there are no adaptation levels/iterates that reduce the error at the interface, it is already minimal. The adaptation of the mesh only happens next to the interface, but does not influence the discontinuity at the interface. Does that clear up the question?

Yes. That was exactly what I was asking. Thanks for clarifying this point. Perhaps this should also be mentioned in the paper as I had the impression that the grid adapts at the interface as well.

**Comment by samuelburbulla** [comment] 2022-06-20 14:03
There is now a Docker image in the GitHub Container registry:
````
docker run -it ghcr.io/samuelburbulla/dune-mmesh:master
````

Thanks for clarifying, I added a sentence to the paper that we actually move the interface edges.

**Comment by vijaysm** [comment] 2022-06-21 06:06
@diehlpk I have completed my review and am satisfied with the state of the paper and the software. @samuelburbulla has been very responsive and addressed all my comments and questions. I recommend the paper be published in JOSS.

**Comment by diehlpk** [comment] 2022-06-22 21:13
@krober10nd, @vijaysm thanks for finishing the review.

**Comment by diehlpk** [comment] 2022-06-22 21:14
@editorialbot check references

**Comment by diehlpk** [comment] 2022-06-22 21:15
> ```
> Reference check summary (note 'MISSING' DOIs are suggestions that need verification):
> 
> OK DOIs
> 
> - 10.5281/zenodo.3706994 is OK
> 
> MISSING DOIs
> 
> - 10.1016/j.camwa.2020.06.007 may be a valid DOI for title: The DUNE framework: Basic concepts and recent developments
> - 10.1007/978-3-319-91545-6_25 may be a valid DOI for title: A Finite-Volume Tracking Scheme for Two-Phase Compressible Flow
> 
> INVALID DOIs
> 
> - None
> ```

@@samuel.burbulla please add the missing DOIs.

**Comment by diehlpk** [comment] 2022-06-22 21:17
@editorialbot generate pdf from branch feature/paper

**Comment by diehlpk** [comment] 2022-06-22 21:18
@editorialbot set feature/paper as branch

**Comment by diehlpk** [comment] 2022-06-22 21:27
From the editorial perspective please do the following changes:

*` University of Stuttgart 2 University of Warwick` -> please add the city and country 

* `we will try to follow the general Dune approach and separate the adaptation into two stages.`

I assume that 1. Mark and 2. Adapt are the two stages. I would recommend to use Stage 1: Mark and Stage 2: Adapt to make it more clear.

After adding the missing DOIs and these two changes, we can proceed accepting the paper.

**Comment by samuelburbulla** [comment] 2022-06-23 06:47
@diehlpk Thanks for your feedback. I edited the paper according to your comments.

**Comment by diehlpk** [comment] 2022-06-23 10:33
@editorialbot check references

**Comment by diehlpk** [comment] 2022-06-23 10:40
@samuelburbulla thanks for editing the paper.

Please do the following finalize the acceptance 

- [ ] generate a new version, including all changes made during the review and post the new version here.
- [ ] upload this version to Zenodo or FigShare and post the DOI here. Note the title and the authors have to match with the psper.

**Comment by samuelburbulla** [comment] 2022-06-24 11:06
I made a new release, v1.3.2, including all changes of the review and uploaded a new PyPI package.

The version is now published via Zenodo with DOI: 10.5281/zenodo.6705603

**Comment by diehlpk** [comment] 2022-06-24 11:21
@editorialbot set 10.5281/zenodo.6705603 as archive

**Comment by diehlpk** [comment] 2022-06-24 11:21
@editorialbot set v1.3.2 as version

**Comment by diehlpk** [comment] 2022-06-24 11:23
@editorialbot recommend-accept

**Comment by Kevin-Mattheus-Moerman** [comment] 2022-06-25 13:50
- I checked the archive meta-data and all looks good. 
- I checked the version tag for the review and archive and verified they match
- I proofread the paper and have the following comments: 
- [ ] Should `dune-fem` have capital letters? 
- [ ] `Use Partial Differential Equations (PDEs)` to introduce the acronym `PDEs`
- [ ] Check throughout for `Adaption`, this probably should read `Adaptation`
- [ ] Instead of `occur, e.g., in mixed-dimensional PDEs` I would recommend `occur, for example, in mixed-dimensional PDEs`

Please consider the above and update the paper here by calling `@editorialbot generate pdf`

**Comment by samuelburbulla** [comment] 2022-06-27 07:25
Thanks a lot @Kevin-Mattheus-Moerman for the detailed comments. I updated the paper accordingly.

**Comment by samuelburbulla** [comment] 2022-06-27 07:25
@editorialbot generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment] 2022-06-27 07:43
@editorialbot accept

**Comment by Kevin-Mattheus-Moerman** [comment] 2022-06-27 08:47
@samuelburbulla congratulations on this JOSS publication!

Thanks @diehlpk for editing this one! 

And special thanks to @krober10nd and @vijaysm for your review efforts!! :tada:

**Closed by Kevin-Mattheus-Moerman** 2022-06-27 08:47 UTC
Labels: accepted, review, C++, C, CMake, recommend-accept, published
