### ISSUE TITLE
[PRE REVIEW]: A coupled model for the accumulation of cosmogenic radionuclides during shore platform development

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3689] opened 2021-09-03 21:49 UTC
**Submitting author:** @mdhurst1 (<a href="http://orcid.org/0000-0002-9822-076X">Martin Hurst</a>)
**Repository:** https://github.com/mdhurst1/Rocky-Profile-Model/
**Branch with paper.md** (empty if default branch): 
**Version:** v1.0.0
**Editor:** @kbarnhart
**Reviewers:** Pending
**Managing EiC:** Kyle Niemeyer

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/90f36a61502bebea6312c11143585b87/status.svg)](https://joss.theoj.org/papers/90f36a61502bebea6312c11143585b87)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/90f36a61502bebea6312c11143585b87"><img src="https://joss.theoj.org/papers/90f36a61502bebea6312c11143585b87/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/90f36a61502bebea6312c11143585b87/status.svg)](https://joss.theoj.org/papers/90f36a61502bebea6312c11143585b87)
```

**Author instructions**

Thanks for submitting your paper to JOSS @mdhurst1. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @kbarnhart.

@mdhurst1 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2021-09-03 21:49
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-09-03 22:03
PDF failed to compile for issue #3689 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by kyleniemeyer** [comment] 2021-09-03 22:14
Hi @mdhurst1, thanks for your interest in JOSS! Unfortunately we do not have any editors available to handle your submission right now, so I'm going to put this on our waitlist. As soon as an editor in this area becomes open, we will get it assigned. In the meantime, if you can suggest any reviewers, that would be helpful.

@arfon can you fix the URL in the database to be just `https://github.com/mdhurst1/Rocky-Profile-Model/`? I don't think including the branch works for whedon.

**Comment by kyleniemeyer** [comment] 2021-09-03 22:15
@whedon check repository

**Comment by whedon** [comment] 2021-09-03 22:15
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.10 s (775.5 files/s, 130537.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C++                             28           1425           1913           3778
MATLAB                          10            488            439           1700
Python                          29            715            732           1359
C/C++ Header                     8            188            240            312
YAML                             3              0              0              7
Bourne Shell                     1              0              0              2
-------------------------------------------------------------------------------
SUM:                            79           2816           3324           7158
-------------------------------------------------------------------------------


Statistical information for the repository '3fdf560b314d31bcc07dda01' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Jenny Shadrick                 242          5691           1306           30.46
Lovleen Acharya Chow             1             1              1            0.01
Martin Hurst                   157          8732           4512           57.66
hironorimatsumoto                1            12              7            0.08
lovleenac                        1           144             29            0.75
martin                           2          2006              0            8.73
mdhurst1                        11           271            257            2.30

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Jenny Shadrick             3929           69.0         23.5               32.65
Lovleen Acharya Chow          1          100.0         16.1                0.00
Martin Hurst               1914           21.9         24.2               26.38
lovleenac                   124           86.1         15.2               11.29
mdhurst1                   4798         1770.5         20.4               27.80
```

**Comment by whedon** [comment] 2021-09-03 22:15
Failed to discover a valid open source license.

**Comment by kyleniemeyer** [comment] 2021-09-03 22:16
@whedon generate pdf from branch JOSS-Paper

**Comment by whedon** [comment] 2021-09-03 22:16
```
Attempting PDF compilation from custom branch JOSS-Paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-09-03 22:17
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03689/joss.03689/10.21105.joss.03689.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03689/joss.03689/10.21105.joss.03689.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment] 2021-09-03 22:17
@mdhurst1 also, it looks like your submission is missing an open-source license. Please select one and add as a plaintext `LICENSE` file to the repository.

**Comment by kbarnhart** [comment] 2021-09-07 19:19
@kyleniemeyer I can confirm that I don't have the bandwidth right now to take this on. I did take a really quick look and it seems like this is missing some major elements. I thought I'd chime in quickly to provide that feedback to @mdhurst1 and co-authors so they could consider this input as they wait for an editor to be available. 

Martin - it looks like this is presently missing the following elements:
- Usage instructions (and installation instructions are pretty minimal). 
- API level documentation 
- Tests

I'd take a quick look at the review criteria, which has some additional info
https://joss.readthedocs.io/en/latest/review_criteria.html

I also find looking at the repositories of accepted papers to get a sense of what documentation and/or tests look like in them.

**Comment by arfon** [comment] 2021-09-09 07:33
Thanks @kbarnhart. @mdhurst1 – I'm going to mark this submission as paused for now to give you a change to incorporate @kbarnhart's initial feedback.

**Comment by kbarnhart** [comment] 2021-09-10 13:56
@arfon thanks! I suspect I'll be able to take on another paper by the time this is unpaused. So I'm going to assign myself.

**Comment by kbarnhart** [comment] 2021-09-10 13:56
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment] 2021-09-10 13:56
OK, the editor is @kbarnhart

**Comment by mdhurst1** [comment] 2021-09-15 11:16
> @mdhurst1 also, it looks like your submission is missing an open-source license. Please select one and add as a plaintext `LICENSE` file to the repository.

@kyleniemeyer @kbarnhart there is a license file in the JOSS-paper branch. I was under the impression I could prepare everything for this submission on a branch and then will pull request on completion of the review process if it goes to publication. I think a number of the issues highlighted here might be because you have not been looking at the branch?

**Comment by mdhurst1** [comment] 2021-09-15 11:18
> @kyleniemeyer I can confirm that I don't have the bandwidth right now to take this on. I did take a really quick look and it seems like this is missing some major elements. I thought I'd chime in quickly to provide that feedback to @mdhurst1 and co-authors so they could consider this input as they wait for an editor to be available.
> 
> Martin - it looks like this is presently missing the following elements:
> 
> * Usage instructions (and installation instructions are pretty minimal).
> * API level documentation
> * Tests
> 
> I'd take a quick look at the review criteria, which has some additional info
> https://joss.readthedocs.io/en/latest/review_criteria.html
> 
> I also find looking at the repositories of accepted papers to get a sense of what documentation and/or tests look like in them.

Same for this, detailed usage instructions, documentation and example runs have been put together on the branch for the paper. See https://github.com/mdhurst1/Rocky-Profile-Model/tree/JOSS-Paper

I did look and hopefully addressed all of the journal's criteria.

**Comment by mdhurst1** [comment] 2021-09-15 11:19
Apologies for the delay in responding, I made the submissino the day before taking some holiday.

**Comment by kbarnhart** [comment] 2021-09-15 18:38
@mdhurst1 I've conferred with others on the joss editorial board. 
- Please put the license file on the default branch. It is important that it be there at the start of the review. 
- The other content is OK to stay on a development branch while this is considered by JOSS. I will make sure to direct the reviewers to consider this branch. 

Looking at the JOSS-Paper branch and the documentation, I still don't see anything regarding tests. If they are there, please point me in the right direction with a link. 

See [this part of the JOSS documentation](https://joss.readthedocs.io/en/latest/review_criteria.html#tests)

> Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.
> 
> Good: An automated test suite hooked up to continuous integration (GitHub Actions, Circle CI, or similar)
> OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
> Bad (not acceptable): No way for you, the reviewer, to objectively assess whether the software works

A few other comments I would strongly recommend addressing along with adding tests. These are issues I expect would come up quickly during the review. 

- I'd expect the documentation to provide some more detailed information regarding how the parameters outlined [here](https://rocky-profile-model.readthedocs.io/en/joss-paper/user-guide/configuration-options/) are used by the model to evolve the topography. Because the documentation is supposed to be somewhat stand-alone, just referring to the original publications for the RCM and RoBoCoP doesn't quite cut it. I don't think you need to fully reproduce all the equations in those papers, but another documentation page that summarizes the two models that are being coupled here would be important. 
- Second, there are some aspects of the configuration options that look like they could use a quick revise (units, comment about the reference frame). I'd also recommend stating what format is expected for the SeaLevelFilename.

If you have any questions or clarifications, please let me know. Once these issues are addressed I will unpause this and start looking for reviewers.

**Comment by kbarnhart** [comment] 2021-09-22 14:13
@mdhurst1 I wanted to let you know I'll be in the field with very limited internet access from Sept 24 through Sept 30. If you have any questions for me during that time, I'll respond when I return.

**Comment by kbarnhart** [comment] 2021-10-05 16:41
@mdhurst1 I wanted to check in and see if you had any questions about my above comments. Please let me know if you plan to make these changes and what you expect the timeframe will be. 

Thanks!

**Comment by mdhurst1** [comment] 2021-11-02 12:24
Hi @kbarnhart, apologies for the delay in pushing this along. I have tried to provide some initial answers to the points raised above but still have some work to do:
- The JOSS branch has now been merged to master so licence situation should be fine.
- This includes an example test that I think conforms with "OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)".
- I will work on some additional docs to explain the model components more clearly this week.
- I am working on the configuration options section too and will provide some further guidance for this.

**Comment by kbarnhart** [comment] 2021-11-02 19:49
@mdhurst1 thanks for the update, sounds good. Give me another ping (here or over email) once those remaining items are done and I'll check out all the changes at once.

**Comment by kbarnhart** [comment] 2021-12-21 20:57
@mdhurst1 just a quick ping to see what the status of this is.

**Comment by arfon** [comment] 2022-04-24 19:59
@kbarnhart – I propose we close this review and re-invite a submission if/when @mdhurst1 is able to make these changes. What do you think?

**Comment by kbarnhart** [comment] 2022-04-25 02:15
Works for me. I followed up my prior message via email and haven't heard back in a while.

**Closed** 2022-04-25 02:15 UTC
Labels: pre-review, paused, Shell, Makefile, C++

**Comment by arfon** [comment] 2022-04-25 07:37
@editorialbot reject

**Comment by mdhurst1** [comment] 2022-04-25 12:55
Thanks folks, happy with this and will resubmit in the summer once I can
get everything in order. Sorry for the hassle.

Martin

**Comment by kbarnhart** [comment] 2022-04-25 14:54
@mdhurst1 no worries! Feel free to reach out to me if you have any questions as you prepare to resubmit.
