### ISSUE TITLE
[PRE REVIEW]: AnyPyTools: A Python package for reproducible research with the AnyBody Modeling System.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1099] opened 2018-11-27 12:17 UTC
**Submitting author:** @melund (<a href="http://orcid.org/0000-0001-9920-4051">Morten Enemark Lund</a>)
**Repository:** <a href="https://github.com/AnyBody-Research-Group/AnyPyTools" target ="_blank">https://github.com/AnyBody-Research-Group/AnyPyTools</a>
**Version:** 1.0.0
**Editor:** @trallard
**Reviewers:** @tonygon, @marcopus, @acolum

**Author instructions**

Thanks for submitting your paper to JOSS @melund. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@melund if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2018-11-27 12:17
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @trallard it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@trallard) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2018-11-27 12:17
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-11-27 12:17
PDF failed to compile for issue #1099 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse': (tmp/1099/docs/paper/paper.md): found unexpected document indicator while scanning a quoted scalar at line 2 column 8 (Psych::SyntaxError)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:377:in `parse_stream'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:325:in `parse'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:252:in `load'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:473:in `block in load_file'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `open'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/psych.rb:472:in `load_file'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/bin/whedon:52:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c44264c87f39/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by arfon** [comment] 2018-11-27 12:17
👋 @trallard - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment] 2018-11-27 12:19
@melund - I think this OR should fix your paper: https://github.com/AnyBody-Research-Group/AnyPyTools/pull/55

**Comment by melund** [comment] 2018-11-27 12:40
Thanks, @arfon. I merged AnyBody-Research-Group/AnyPyTools#55 

@whedon generate pdf

**Comment by melund** [comment] 2018-11-27 12:41
@whedon generate pdf

**Comment by whedon** [comment] 2018-11-27 12:41
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-11-27 12:42
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01099/joss.01099/10.21105.joss.01099.pdf)

**Comment by melund** [comment] 2018-11-27 13:58
@whedon generate pdf

**Comment by whedon** [comment] 2018-11-27 13:58
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-11-27 13:58
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01099/joss.01099/10.21105.joss.01099.pdf)

**Comment by melund** [comment] 2018-11-27 20:30
@trallard Most of the review can probably be handled by someone who knows Python/GitHub/OpenSource.

But having reviewers with knowledge on multibody musculoskeletal modeling and the [AnyBody Modeling System](https://www.anybodytech.com/software/ams/) is probably also required.

So here are a few suggestions on reviewers who have used the AnyBody Modeling System, and have some Python and GitHub/Git experience. 

1. [Antonio Gonzales Marin](https://www.linkedin.com/in/antonio-gonzales-marin-817245115/) (@tonygon). Research Scientist at the German Aerospace Center (DLR)

2. [Marco Antonio Marra](https://www.linkedin.com/in/marcoantoniomarra/) (@marcopus) Assistant Professor at University of Twente

**Comment by trallard** [comment] 2018-11-28 14:34
👋 Hi @melund thanks for the submission. Since you suggested me as an editor I will be performing the editorial duties for this submission. If you have any questions over the review process please feel free to ping me. 

Let's start by pinging some suitable reviewers with Python and biomechanics expertise. We can start the review once two or more of them accept the request to review.

--- 
Dear reviewers,

@tonygon as suggested: Antonio, are you able to and interested in taking on this review?
@marcopus as suggested: Marco, are you able to and interested in taking on this review?
@moorepants: Jason, are you able to and interested in taking on this review?
@nirum: Niru, are you able to and interested in taking on this review?
@acolum: Alyssa, are you able to and interested in taking on this review?


**Title**: AnyPyTools: A Python package for reproducible research with the AnyBody Modeling System.
**Summary**: AnyPyTools is a toolkit for working with the AnyBody Modeling System (AMS) from Python. It enables reproducible research with the AnyBody Modeling System and bridges the gap to the whole ecosystem of open source scientific Python.
**Topic**: reproducible science, musculoskeletal modelling
**Article proof**: [https://github.com/openjournals/joss-papers/blob/joss.01099/joss.01099/10.21105.joss.01099.pdf](https://github.com/openjournals/joss-papers/blob/joss.01099/joss.01099/10.21105.joss.01099.pdf)
**Submitting author**: @melund 
**Repository**: [https://github.com/AnyBody-Research-Group/AnyPyTools](https://github.com/AnyBody-Research-Group/AnyPyTools)

**Comment by marcopus** [comment] 2018-11-28 14:42
Hi Tania, I am willing to review this. Thanks, Marco

Il giorno mer 28 nov 2018 alle ore 15:34 Tania Allard <
notifications@github.com> ha scritto:

**Comment by tonygon** [comment] 2018-11-28 14:49
> wave Hi @melund thanks for the submission. Since you suggested me as an editor I will be performing the editorial duties for this submission. If you have any questions over the review process please feel free to @ me.
> 
> Let's start by pinging some suitable reviewers with Python and biomechanics expertise. We can start the review once two or more of them accept the request to review.
> 
> Dear reviewers,
> 
> @tonygon as suggested: Antonio, are you able to and interested in taking on this review?
> @marcopus as suggested: Marco, are you able to and interested in taking on this review?
> @moorepants: Jason, are you able to and interested in taking on this review?
> @nirum: Niru, are you able to and interested in taking on this review?
> @acolum: Alyssa, are you able to and interested in taking on this review?
> 
> **Title**: AnyPyTools: A Python package for reproducible research with the AnyBody Modeling System.
> **Summary**: AnyPyTools is a toolkit for working with the AnyBody Modeling System (AMS) from Python. It enables reproducible research with the AnyBody Modeling System and bridges the gap to the whole ecosystem of open source scientific Python.
> **Topic**: reproducible science, musculoskeletal modelling
> **Article proof**: https://github.com/openjournals/joss-papers/blob/joss.01099/joss.01099/10.21105.joss.01099.pdf
> **Submitting author**: @melund
> **Repository**: https://github.com/AnyBody-Research-Group/AnyPyTools

@trallard 
I'm able and interested to take the review.

**Comment by trallard** [comment] 2018-11-28 14:52
Thanks for the quick response @tonygon. I'll wait and see if anyone else can review before jumping into the formal review

**Comment by trallard** [comment] 2018-11-28 14:53
@whedon  assign @tonygon as reviewer

**Comment by trallard** [comment] 2018-11-28 14:55
@whedon add @marcopus as reviewer

**Comment by whedon** [comment] 2018-11-28 14:55
OK, @marcopus is now a reviewer

**Comment by trallard** [comment] 2018-11-28 14:56
@whedon assign @tonygon as reviewer

**Comment by whedon** [comment] 2018-11-28 14:57
OK, the reviewer is @tonygon

**Comment by trallard** [comment] 2018-11-28 14:57
@whedon add @marcopus as reviewer

**Comment by whedon** [comment] 2018-11-28 14:57
OK, @marcopus is now a reviewer

**Comment by acolum** [comment] 2018-11-28 16:59
Hi Tania,
I'm also able and interested to take the review.
Thanks,
Alyssa

**Comment by trallard** [comment] 2018-11-29 08:35
@whedon add @acolum as reviewer

**Comment by whedon** [comment] 2018-11-29 08:35
OK, @acolum is now a reviewer

**Comment by trallard** [comment] 2018-11-29 08:36
Awesome, thanks for agreeing to review this submission @acolum 

We can now move onto the review for this submission  🎊🎊

**Comment by trallard** [comment] 2018-11-29 08:36
@whedon start review

**Comment by whedon** [comment] 2018-11-29 08:36
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1108. Feel free to close this issue now!

**Closed** 2018-11-29 08:36 UTC
Labels: Python, pre-review
