### ISSUE TITLE
[PRE REVIEW]: Limarka: making possible Brazilian students writing dissertation and thesis with Markdown

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#136] opened 2016-12-09 11:51 UTC
**Submitting author:** @edusantana (<a href="http://orcid.org/0000-0002-9165-9438">Eduardo Alexandre</a>)
**Repository:** <a href="https://github.com/abntex/limarka" target ="_blank">https://github.com/abntex/limarka</a>
**Version:** v0.5.2
**Editor:** @acabunoc
**Reviewer:** @alanlivio

**What this issue is for**

Thanks for submitting your paper to JOSS @edusantana. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2016-12-09 11:51
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment] 2016-12-09 11:52
👋 @acabunoc - would you be willing to edit this submission for JOSS?

**Comment by acabunoc** [comment] 2016-12-09 16:39
Yes! I can take a look next week

**Comment by edusantana** [comment] 2016-12-10 13:48
Thank you @acabunoc 

I don't know if it's a problem, but the code, test, documentation, and examples are all writen in Portuguese.

**Comment by arfon** [comment] 2016-12-12 15:15
@whedon assign @acabunoc as editor

**Comment by whedon** [comment] 2016-12-12 15:15
OK, the editor is @acabunoc

**Comment by acabunoc** [comment] 2017-01-08 03:03
Sorry for the delay here! 

@rgaiacs, would you be interested in being a reviewer for JOSS and reviewing this paper? Review guidelines can be found here: http://joss.theoj.org/about#reviewer_guidelines

Also, @edusantana do you have any potential reviewers you can suggest (someone close to the domain & speaks Portuguese)? It's nice to have multiple reviewers, and I'm not sure which of current reviewers knows Portuguese.

**Comment by edusantana** [comment] 2017-01-08 09:35
@whedon list editors

**Comment by whedon** [comment] 2017-01-08 09:35
Current JOSS editors:

```
@acabunoc
@arfon
@arokem
@biorelated
@cMadan
@danielskatz
@jakevdp
@karthik
@katyhuff
@Kevin-Mattheus-Moerman
@kyleniemeyer
@labarba
@mgymrek
@pjotrp
@tracykteal
```

**Comment by edusantana** [comment] 2017-01-08 09:42
@whedon list reviewers

**Comment by whedon** [comment] 2017-01-08 09:42
Here's the current list of JOSS reviewers: https://github.com/openjournals/joss/blob/master/docs/reviewers.csv

**Comment by edusantana** [comment] 2017-01-08 09:48
Since limarka is intended to make possible to write scientific work (according to Brazilian's rules) I think these reviewers would be interested:

@jsta : because of reproducible science and scientific writing tools
@richardlitt : because of computer science, computational linguistics, data science 

@acabunoc I can deliver translations to English of important parts of documentation.

**Comment by edusantana** [comment] 2017-01-08 09:50
I do have a question, can I have the paper on a different repository just for it? I put it on a different branch, but that doesn't look good to me.

**Comment by acabunoc** [comment] 2017-01-09 00:17
Thanks @edusantana! If you're willing to provide an English translation, that would help a lot for finding reviewers. If @jsta, @RichardLitt or @rgaiacs are interested, reply with a quick ✋  -- otherwise, feel free to ignore this issue :)

For the paper, it's usually on the master branch in the main repo. Sometimes it's on a permanent branch based off the reviewed version. I'll defer to @arfon on whether or not having the paper in a completely separate repo is okay.

**Comment by arfon** [comment] 2017-01-10 01:07
> For the paper, it's usually on the master branch in the main repo. Sometimes it's on a permanent branch based off the reviewed version. I'll defer to @arfon on whether or not having the paper in a completely separate repo is okay.

@edusantana - the paper needs to be in the repository being reviewed. Is there an reason this can't be in a `docs` or `paper` folder on the `master` branch?

**Comment by edusantana** [comment] 2017-01-11 12:55
@arfon  I did not have a `docs` folder, I use wiki for documentation, but I will create one now. And the paper will be there.

**Comment by edusantana** [comment] 2017-01-16 13:20
@acabunoc I have translated the README.md and CONTRIBUTING.md files to english. You can see them at `v0.6.3-english` branch: https://github.com/abntex/limarka/tree/v0.6.3-english

The paper was also included in this version of code. It's DOI is https://doi.org/10.5281/zenodo.247247. The version of the software is now `v0.6.4` instead of `v0.5.2` and described on the issue description.

You can ask whatever you need for the review.

**Comment by edusantana** [comment] 2017-01-16 14:53
It's now `v0.6.5`, with API documentation.
DOI: https://doi.org/10.5281/zenodo.247387

**Comment by edusantana** [comment] 2017-01-23 01:19
@acabunoc I'm using wiki as documentation, if you need that in English as well, I can make it happen, but takes time. Do you need any section translated?

**Comment by acabunoc** [comment] 2017-01-24 16:55
Hi @edusantana! I think that will depend on the reviewer  -- I'll spend some time later to see if I find some other possible reviewers.  Thanks for all your work here! Let me know if you think of anyone else (doesn't have to be listed as a current reviewer for JOSS)

**Comment by edusantana** [comment] 2017-01-24 17:57
Hi @acabunoc, I have sent a few emails making the invitation.

**Comment by alanlivio** [comment] 2017-01-24 18:06
Hello @acabunoc and @edusantana.
I'm interested in review the Eduardo's paper.
I'm a PhD student at Puc-Rio Brazil and my research interests are in multimedia authoring and documents.
How I proceed to review?

**Comment by acabunoc** [comment] 2017-01-24 18:10
Thanks @alanlivio! 🎉  I'll assign you as reviewer and get the review started. Review guidelines can be found here: http://joss.theoj.org/about#reviewer_guidelines

Do you read Portuguese? If so, @edusantana may not have to translate as much 😄

**Comment by acabunoc** [comment] 2017-01-24 18:10
@whedon assign @alanlivio as reviewer

**Comment by whedon** [comment] 2017-01-24 18:10
OK, the reviewer is @alanlivio

**Comment by acabunoc** [comment] 2017-01-24 18:10
@whedon start review

**Comment by whedon** [comment] 2017-01-24 18:10
You didn't say the magic word! Try this:

```
@whedon start review magic-word=bananas
```

**Comment by acabunoc** [comment] 2017-01-24 18:10
@whedon start review magic-word=bananas

**Comment by whedon** [comment] 2017-01-24 18:10
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/169. Feel free to close this issue now!

**Comment by acabunoc** [comment] 2017-01-24 18:11
@alanlivio & @edusantana the review is now in #169! I'll close this. Let me know if you have any questions :)

**Comment by edusantana** [comment] 2017-01-24 18:12
@acabunoc yes, he does. He is a Brazilian.

**Closed by acabunoc** 2017-01-24 18:11 UTC
Labels: pre-review

**Comment by edusantana** [comment] 2017-01-24 18:13
@acabunoc the tag version is wrong.
