### ISSUE TITLE
[PRE REVIEW]: MicrobiomeR:  An R Package for Simplified and Standardized Microbiome Analysis Workflows

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1288] opened 2019-02-28 20:31 UTC
**Submitting author:** @grabear (<a href="http://orcid.org/0000-0001-8096-0180">Robert Gilmore</a>)
**Repository:** <a href="https://github.com/vallenderlab/MicrobiomeR" target ="_blank">https://github.com/vallenderlab/MicrobiomeR</a>
**Version:** 0.5.1
**Editor:** @lpantano
**Reviewers:** @CosteaPaul 

**Author instructions**

Thanks for submitting your paper to JOSS @grabear. **Currently, there isn't an JOSS editor assigned** to your paper.

@grabear if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-02-28 20:31
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-02-28 20:31
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-02-28 20:31
PDF failed to compile for issue #1288 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1288 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:50:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment] 2019-02-28 20:32
👋 @pjotrp - the author requested you (or someone from your group) as editor - ok? 
Of course, some work is needed on the paper first...

**Comment by danielskatz** [comment] 2019-02-28 20:34
👋 @grabear - I don't see the paper part of your submission.  Take a look at the [author submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html), specifically [What should my paper contain?](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain) and [Example paper and bibliography](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography)

**Comment by grabear** [comment] 2019-02-28 21:01
Hi, I put the paper in a separate folder under inst/paper/ @danielskatz

**Comment by danielskatz** [comment] 2019-02-28 21:08
@whedon generate pdf from inst/paper

**Comment by whedon** [comment] 2019-02-28 21:08
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-02-28 21:08
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by danielskatz** [comment] 2019-02-28 21:12
thanks - I see some issues with the figure, the table, and the references.  You can make changes to the paper.md and paper.bib, then use the same command I used (as a new comment here) to regenerate until you are satisfied with the generated proof.

**Comment by danielskatz** [comment] 2019-02-28 21:13
In the meantime, @pjotrp and his group can figure out who will edit this, I think.

**Comment by grabear** [comment] 2019-02-28 21:17
@danielskatz Thank you!  I'll work on it.

**Comment by grabear** [comment] 2019-02-28 21:18
@whedon commands

**Comment by whedon** [comment] 2019-02-28 21:18
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by grabear** [comment] 2019-02-28 21:25
@whedon generate pdf from branch joss-review from inst/paper

**Comment by whedon** [comment] 2019-02-28 21:25
```
Attempting PDF compilation from custom branch joss-review from inst/paper . Reticulating splines etc...
```

**Comment by grabear** [comment] 2019-02-28 21:31
@sdhutchins working on tweaking the paper!

**Comment by pjotrp** [comment] 2019-02-28 22:51
Yes, I'll ask for an editor.

**Comment by lpantano** [comment] 2019-03-01 13:46
@whedon assign @lpantano as editor

**Comment by whedon** [comment] 2019-03-01 13:46
OK, the editor is @lpantano

**Comment by grabear** [comment] 2019-03-01 16:15
@whedon generate pdf from inst/paper branch joss-review

**Comment by whedon** [comment] 2019-03-01 16:15
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-01 16:16
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by lpantano** [comment] 2019-03-01 17:55
Hi @grabear,

let me know when you can figure out the format issue, I will look into possible reviewers in the meantime.

Looking forward to working together in the process.

Cheers

**Comment by grabear** [comment] 2019-03-01 18:14
Hello @lpantano!  I'll be working on it this afternoon!  I just need to play around with whedon a little.  

Looking forward to it as well :+1:

**Comment by grabear** [comment] 2019-03-01 19:47
@whedon generate pdf from branch joss-review inst/paper

**Comment by whedon** [comment] 2019-03-01 19:47
```
Attempting PDF compilation from custom branch joss-review inst/paper. Reticulating splines etc...
```

**Comment by grabear** [comment] 2019-03-01 19:54
@pjotrp @lpantano @danielskatz Any idea what I should do with @whedon when I'm generating the pdf on a separate branch and in a folder that's not on the top level?

**Comment by danielskatz** [comment] 2019-03-01 19:55
👋 @arfon ?

**Comment by grabear** [comment] 2019-03-01 19:56
Part of the problem is that I always protect my master and dev-master branches, so it makes it a bit more complicated for me to edit.  I can always change the permissions temporarily, but that's not ideal.

**Comment by grabear** [comment] 2019-03-01 21:34
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-01 21:35
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-01 21:36
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by lpantano** [comment] 2019-03-01 21:52
sorry @grabear that is not working with two of the conditions (other branch and other location), hopefully, somebody who knows the backend infrastructure can help. I will reach somebody if @arfon doesn't chime in.

At least the figure now. seems right. :)

Thanks!

**Comment by grabear** [comment] 2019-03-01 21:54
@lpantano It seems to be working now!  It's finding the paper, so no complaints.  :)

**Comment by grabear** [comment] 2019-03-01 21:55
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-01 21:55
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-01 21:55
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-01 21:56
@whedon check references

**Comment by whedon** [comment] 2019-03-01 21:56
```
Attempting to check references...
```

**Comment by whedon** [comment] 2019-03-01 21:56
```Reference check summary:

OK DOIs

- http://doi.org/10.1371/journal.pcbi.1005404 is OK

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0061217 may be missing for title: phyloseq: An R package for reproducible interactive analysis and graphics of microbiome census data
- https://doi.org/10.1038/nmeth.f.303 may be missing for title: QIIME allows analysis of high-throughput community sequencing data.
- https://doi.org/10.1093/nar/gks1219 may be missing for title: The SILVA ribosomal RNA gene database project: improved data processing and web-based tools.
- https://doi.org/10.1093/nar/gkt1209 may be missing for title: The SILVA and “All-species Living Tree Project (LTP)” taxonomic frameworks.

INVALID DOIs

- None
```

**Comment by grabear** [comment] 2019-03-01 22:09
@whedon check references from branch joss-review

**Comment by whedon** [comment] 2019-03-01 22:09
```
Attempting to check references...
```

**Comment by whedon** [comment] 2019-03-01 22:10
```Reference check summary:

OK DOIs

- http://doi.org/10.1371/journal.pcbi.1005404 is OK

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0061217 may be missing for title: phyloseq: An R package for reproducible interactive analysis and graphics of microbiome census data
- https://doi.org/10.1038/nmeth.f.303 may be missing for title: QIIME allows analysis of high-throughput community sequencing data.
- https://doi.org/10.1093/nar/gks1219 may be missing for title: The SILVA ribosomal RNA gene database project: improved data processing and web-based tools.
- https://doi.org/10.1093/nar/gkt1209 may be missing for title: The SILVA and “All-species Living Tree Project (LTP)” taxonomic frameworks.

INVALID DOIs

- None
```

**Comment by grabear** [comment] 2019-03-01 22:10
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-01 22:10
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-01 22:11
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-01 22:37
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-01 22:37
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-01 22:38
PDF failed to compile for issue #1288 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0    207      0 --:--:-- --:--:-- --:--:--   207
Error producing PDF.
! Misplaced \noalign.
\hline ->\noalign 
                  {\ifnum 0=`}\fi \hrule \@height \arrayrulewidth \futurelet...
l.386 \hline

Looks like we failed to compile the PDF

**Comment by grabear** [comment] 2019-03-01 23:03
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-01 23:03
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-01 23:04
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-01 23:09
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-01 23:09
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-01 23:10
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-01 23:12
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-01 23:12
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-01 23:13
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-01 23:23
@lpantano @sdhutchins I think I have the table, diagram, and DOIs in a good place.

Thoughts?

**Comment by lpantano** [comment] 2019-03-01 23:54
Thanks!

I think looks good, the only think is that some DOIs have the `https` and other not. Can you  normalize  that?

**Comment by lpantano** [comment] 2019-03-01 23:58
Hi @CosteaPaul,

@brainstorm mentioned to me that you could be a good reviewer for this paper, Do you think you would have time for this? It would be great!

**Comment by sdhutchins** [comment] 2019-03-02 00:16
I think it looks good, @grabear! I would only say perhaps the diagram's height could be decreased while keeping the same scale. It looks good as it is though.

**Comment by grabear** [comment] 2019-03-02 03:27
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-02 03:27
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-02 03:27
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-04 17:07
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-04 17:07
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-04 17:08
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-04 17:11
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-04 17:11
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-04 17:11
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-04 17:18
@lpantano @sdhutchins Made some changes!

**Comment by grabear** [comment] 2019-03-04 17:18
@whedon check references

**Comment by whedon** [comment] 2019-03-04 17:19
```
Attempting to check references...
```

**Comment by whedon** [comment] 2019-03-04 17:19
```Reference check summary:

OK DOIs

- http://doi.org/10.1371/journal.pcbi.1005404 is OK

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0061217 may be missing for title: phyloseq: An R package for reproducible interactive analysis and graphics of microbiome census data
- https://doi.org/10.1038/nmeth.f.303 may be missing for title: QIIME allows analysis of high-throughput community sequencing data.
- https://doi.org/10.1093/nar/gks1219 may be missing for title: The SILVA ribosomal RNA gene database project: improved data processing and web-based tools.
- https://doi.org/10.1093/nar/gkt1209 may be missing for title: The SILVA and “All-species Living Tree Project (LTP)” taxonomic frameworks.

INVALID DOIs

- None
```

**Comment by CosteaPaul** [comment] 2019-03-04 18:30
@lpantano this looks like fun :).
Would be happy to help with reviewing, though I have no idea how this is supposed to work.

**Comment by lpantano** [comment] 2019-03-04 18:35
Thank you,  @CosteaPaul !

We have some guidelines here:

https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

For now, I will move this to review, that will close this issue and open a new one where the review process will happen. Our friend whedon, will help you with the requirements to review the paper. When the new issue is open, there will be some guidelines. I will follow up there.

Thanks so much!

**Comment by lpantano** [comment] 2019-03-04 18:35
@whedon assign @CosteaPaul  as reviewer

**Comment by whedon** [comment] 2019-03-04 18:35
OK, the reviewer is @CosteaPaul

**Comment by lpantano** [comment] 2019-03-04 22:37
Hi @grabear,

I see there are some issues with the DOI links , let me know when you  solve this and we can move this to under review.

Thanks!

**Comment by grabear** [comment] 2019-03-04 22:48
@lpantano All of those DOI's are not missing.  I copied an pasted those during my first check, so Idk why they are considered "Missing" or "may be missing".  

I just updated an F1000 DOI, but only because they release a second version of that paper.  I also checked all of the other ones and they are working links..

**Comment by lpantano** [comment] 2019-03-04 22:51
Hi,
Weird, When I click on the PDF link it lands on a broken web page.  Did you try to use the link of the PDF, maybe there is something wrong on the latex code that breaks the link?

`https://doi.org/https://doi.org/10.1038/nmeth.f.303` This url is malformed. 

Cheers

**Comment by grabear** [comment] 2019-03-04 22:56
@whedon generate pdf from branch joss-review

**Comment by whedon** [comment] 2019-03-04 22:56
```
Attempting PDF compilation from custom branch joss-review. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-04 22:57
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

**Comment by grabear** [comment] 2019-03-04 23:00
@whedon check references

**Comment by whedon** [comment] 2019-03-04 23:00
```
Attempting to check references...
```

**Comment by whedon** [comment] 2019-03-04 23:00
```Reference check summary:

OK DOIs

- http://doi.org/10.1371/journal.pcbi.1005404 is OK

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0061217 may be missing for title: phyloseq: An R package for reproducible interactive analysis and graphics of microbiome census data
- https://doi.org/10.1038/nmeth.f.303 may be missing for title: QIIME allows analysis of high-throughput community sequencing data.
- https://doi.org/10.1093/nar/gks1219 may be missing for title: The SILVA ribosomal RNA gene database project: improved data processing and web-based tools.
- https://doi.org/10.1093/nar/gkt1209 may be missing for title: The SILVA and “All-species Living Tree Project (LTP)” taxonomic frameworks.

INVALID DOIs

- None
```

**Comment by grabear** [comment] 2019-03-04 23:02
@whedon check references from branch joss-review

**Comment by whedon** [comment] 2019-03-04 23:02
```
Attempting to check references...
```

**Comment by whedon** [comment] 2019-03-04 23:02
```Reference check summary:

OK DOIs

- http://doi.org/10.1371/journal.pcbi.1005404 is OK

MISSING DOIs

- https://doi.org/10.1371/journal.pone.0061217 may be missing for title: phyloseq: An R package for reproducible interactive analysis and graphics of microbiome census data
- https://doi.org/10.1038/nmeth.f.303 may be missing for title: QIIME allows analysis of high-throughput community sequencing data.
- https://doi.org/10.1093/nar/gks1219 may be missing for title: The SILVA ribosomal RNA gene database project: improved data processing and web-based tools.
- https://doi.org/10.1093/nar/gkt1209 may be missing for title: The SILVA and “All-species Living Tree Project (LTP)” taxonomic frameworks.

INVALID DOIs

- None
```

**Comment by grabear** [comment] 2019-03-04 23:05
> [ point_right Check article proof page_facing_up point_left ](https://github.com/openjournals/joss-papers/blob/joss.01288/joss.01288/10.21105.joss.01288.pdf)

Not really sure what's going on with whedon's reference check, but the DOIs should be correct now.  Sorry about that!

**Comment by arfon** [comment] 2019-03-05 10:50
> @whedon check references from branch joss-review

I'm afraid @whedon only knows how to check references for the `master` or default branch of your repository.

**Comment by lpantano** [comment] 2019-03-05 12:48
Thank you, @arfon. I think is fine since the links work now. I will start the review process.

@whedon start review

**Comment by pjotrp** [comment] 2019-03-05 13:21
Whedon needs separate lines

**Comment by pjotrp** [comment] 2019-03-05 13:21
@whedon start review

**Comment by whedon** [comment] 2019-03-05 13:21
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1299. Feel free to close this issue now!

**Closed** 2019-03-05 13:26 UTC
Labels: CSS, R, TeX, pre-review
