### ISSUE TITLE
[PRE REVIEW]: hmis: A python tool to visualize and analyze HMIS data

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#383] opened 2017-08-28 14:11 UTC
**Submitting author:** @mattbellis (<a href="http://orcid.org/0000-0002-6353-6043">Matthew Bellis</a>)
**Repository:** <a href="https://github.com/mattbellis/hmis" target ="_blank">https://github.com/mattbellis/hmis</a>
**Version:** 1.0
**Editor:** @leeper
**Reviewer:** @alexhanna

**Author instructions**

Thanks for submitting your paper to JOSS @mattbellis. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@mattbellis if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://github.com/openjournals/joss/blob/master/docs/reviewers.csv) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2017-08-28 14:11
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @leeper it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by arfon** [comment] 2017-08-28 14:13
👋 @leeper - the submitting author suggested you as an editor

**Comment by mattbellis** [comment] 2017-08-28 18:46
Ben Marwick (benmarwick) has listed his research as having a social sciences bent, as well as reproducible science, two things that this software package aims to improve upon. 

As far as we can tell, there is no real research being done with the HMIS data and from the folks in the homelessness support community with whom we have been working, this is in part because 1) they're not particularly trained to do this and 2) the data is not in a form that one can easily use standard data science tools (R or python). This code tries to rectify the latter, but this also means that there might not be any easily identifiable reviewers.  

Hope this helps!

**Comment by leeper** [comment] 2017-08-29 17:19
@mattbellis Thanks for this. It looks within-scope and I have found a reviewer. A new issue to handle the review process will be initialized momentarily.

**Comment by leeper** [comment] 2017-08-29 17:19
@whedon assign @alexhanna as reviewer

**Comment by whedon** [comment] 2017-08-29 17:19
OK, the reviewer is @alexhanna

**Comment by leeper** [comment] 2017-08-29 17:20
I've confirmed that this submission has:

 - [x] An OSI approved license (GPL)
 - [x] A description of the software and its research applications
 - [x] Is in scope for this journal

@whedon start review magic-word=bananas

**Comment by leeper** [comment] 2017-08-29 17:21
@whedon start review magic-word=bananas

**Comment by whedon** [comment] 2017-08-29 17:21
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/384. Feel free to close this issue now!

**Closed** 2017-08-29 17:21 UTC
Labels: pre-review
