### ISSUE TITLE
[REVIEW]: HydDown: A Python package for calculation of hydrogen (or other gas) pressure vessel filling and discharge

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3695] opened 2021-09-06 09:50 UTC
**Submitting author:** @andr1976 (<a href="http://orcid.org/0000-0003-0475-323X">Anders Andreasen</a>)
**Repository:** <a href="https://github.com/andr1976/HydDown" target ="_blank">https://github.com/andr1976/HydDown</a>
**Version:** v0.16.2
**Editor:** @fraukewiese
**Reviewer:** @mefuller, @bocklund
**Archive:** <a href="https://doi.org/10.5281/zenodo.5547917" target="_blank">10.5281/zenodo.5547917</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25/status.svg)](https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25"><img src="https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25/status.svg)](https://joss.theoj.org/papers/0eed2a25a99589ed8dcdc785c890fb25)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/andr1976/HydDown" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@mefuller & @bocklund, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @fraukewiese know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @mefuller
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/andr1976/HydDown">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andr1976/HydDown">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@andr1976) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @bocklund
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/andr1976/HydDown">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/andr1976/HydDown">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@andr1976) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2021-09-06 09:50
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @mefuller, @bocklund it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-09-06 09:50
Wordcount for `paper.md` is 1179

**Comment by whedon** [comment] 2021-09-06 09:50
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.06 s (866.9 files/s, 96677.7 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          14            393            129           1786
TeX                              3            106            171           1289
YAML                            32             19             42            981
Markdown                         4            356              0            855
TOML                             1              0              0              6
DOS Batch                        1              0              0              1
-------------------------------------------------------------------------------
SUM:                            55            874            342           4918
-------------------------------------------------------------------------------


Statistical information for the repository 'd0c999d5d8a51340c134c0b7' was
gathered on 2021/09/06.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Anders Andreasen                 8            21             16            0.52
andr1976                       113          4707           2408           99.48

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
andr1976                   2308           49.0          3.1                3.99
```

**Comment by whedon** [comment] 2021-09-06 09:50
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.5154096 is OK
- 10.1016/j.psep.2016.10.008 is OK
- 10.3390/safety4010011 is OK
- 10.1299/jtst.2.180 is OK
- 10.1299/jtst.3.241 is OK
- 10.1021/i260011a004 is OK
- 10.1016/j.ijhydene.2014.03.028 is OK
- 10.1021/ie4033999 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/mcse.2007.55  is OK
- 10.25080/majora-92bf1922-00a is OK
- 10.1016/j.ijhydene.2021.04.037 is OK
- 10.1016/j.ces.2015.01.019 is OK
- 10.1002/aic.690480223 is OK
- 10.1016/j.psep.2019.10.035 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2021-09-06 09:51
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03695/joss.03695/10.21105.joss.03695.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03695/joss.03695/10.21105.joss.03695.pdf) :page_facing_up: :point_left:

**Comment by fraukewiese** [comment] 2021-09-06 09:53
@bocklund @mefuller – This is the review thread for the paper. All of our communications will happen here from now on.

Please read the "Reviewer instructions & questions" in the first comment above.

Both reviewers have checklists at the top of this thread (in that first comment) with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, the reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention #3625 so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for the review process to be completed within about 4-6 weeks but please make a start well ahead of this as JOSS reviews are by their nature iterative and any early feedback you may be able to provide to the author will be very helpful in meeting this schedule.

**Comment by mfleschutz** [comment] 2021-09-06 15:21
😀@fraukewiese, you probably mean #3695 in

> ...When doing so, please mention #3625 ...

**Comment by fraukewiese** [comment] 2021-09-07 13:14
Absolutely! #3695, sorry for that, I have corrected it.

**Comment by fraukewiese** [comment] 2021-09-14 11:28
@mefuller @bocklund : If you have any questions about the review do not hesitate to ask :)

**Comment by mefuller** [comment] 2021-09-14 11:47
@fraukewiese would you please send me a new invite? I cannot edit the checklist and am getting an error that my invitation expired. Thanks

**Comment by danielskatz** [comment] 2021-09-14 12:36
@whedon re-invite @mefuller as reviewer

**Comment by whedon** [comment] 2021-09-14 12:36
OK, the reviewer has been re-invited.

@mefuller please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by whedon** [comment] 2021-09-20 09:50
:wave: @mefuller, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment] 2021-09-20 09:50
:wave: @bocklund, please update us on how your review is going (this is an automated reminder).

**Comment by mefuller** [comment] 2021-09-20 15:33
@whedon  I've worked through installation, some basic functionality testing (although only superficially), and have thoroughly examined and edited the documentation for the software

**Comment by whedon** [comment] 2021-09-20 15:33
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by bocklund** [comment] 2021-09-28 19:34
@andr1976: I finished making my first pass on HyDown. I was able to use the Streamlit app online. It looks great. Your documentation looks very detailed and seems to demonstrate the power of HydDown very well. I have opened a few issues to be fixed. Issues blocking my acceptance in the checklist:

- [ ] **Installation** https://github.com/andr1976/HydDown/issues/63
- [ ] **Functionality** https://github.com/andr1976/HydDown/issues/64
- [ ] **Automated tests** automated tests seem to exist, but instructions for running them do not. Tracked by https://github.com/andr1976/HydDown/issues/65. Validation/manual tests clearly exist, but I was not able to run them (same error as https://github.com/andr1976/HydDown/issues/64)


Non-blocking issues:

- [ ] Improving the usage flow in the documentation for `pip` users https://github.com/andr1976/HydDown/issues/59

**Comment by andr1976** [comment] 2021-09-28 21:49
@bocklund  thanks for commenting, really appreciated. I have updated the setup to include dependencies, fixed input.yml, updated manual/documentation, including guidelines for running tests. I wanted to create a separate PR with you as reviewer, however one of my workflows/actions kept pushing to main (by mistake) when pushing to a seprate branch, so it didn't really work as intended. No all the fixes have already been merged to main.

**Comment by bocklund** [comment] 2021-09-30 16:11
@fraukewiese all the acceptance-blocking issues that I identified have been completed and I'm happy to recommend that HydDown be accepted to JOSS.

**Comment by mefuller** [comment] 2021-10-01 05:02
@fraukewiese I am also satisfied with the submission in its present for and recommend acceptance

**Comment by andr1976** [comment] 2021-10-02 22:22
@fraukewiese , if/when you accept the paper for publication, I would like to make a new release to the python package index, which includes the improvements made by the reviewers, before the paper is published

**Comment by andr1976** [comment] 2021-10-04 14:46
@fraukewiese, I have made a new release (0.16.2 on github) accompanied with an updated PyPi package. The new release includes the improvments suggested by the reviewers (and some fixes here and there)  as well as another proofreding round made by the company department language secretary. So I am good to go from here if you are

**Comment by fraukewiese** [comment] 2021-10-05 09:11
@mefuller and @bocklund : Thank you very much for your thorough review!

**Comment by fraukewiese** [comment] 2021-10-05 09:11
@whedon generate pdf

**Comment by whedon** [comment] 2021-10-05 09:12
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03695/joss.03695/10.21105.joss.03695.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03695/joss.03695/10.21105.joss.03695.pdf) :page_facing_up: :point_left:

**Comment by fraukewiese** [comment] 2021-10-05 09:12
@whedon check references

**Comment by whedon** [comment] 2021-10-05 09:12
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5281/zenodo.5154096 is OK
- 10.1016/j.psep.2016.10.008 is OK
- 10.3390/safety4010011 is OK
- 10.1299/jtst.2.180 is OK
- 10.1299/jtst.3.241 is OK
- 10.1021/i260011a004 is OK
- 10.1016/j.ijhydene.2014.03.028 is OK
- 10.1021/ie4033999 is OK
- 10.1109/mcse.2011.37 is OK
- 10.1038/s41586-020-2649-2 is OK
- 10.1038/s41592-019-0686-2 is OK
- 10.1109/mcse.2007.55  is OK
- 10.25080/majora-92bf1922-00a is OK
- 10.1016/j.ijhydene.2021.04.037 is OK
- 10.1016/j.ces.2015.01.019 is OK
- 10.1002/aic.690480223 is OK
- 10.1016/j.psep.2019.10.035 is OK
- 10.5281/zenodo.5517697 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by fraukewiese** [comment] 2021-10-05 10:39
@andr1976 
Could you please correct the following in the article:
Typo in Line 56 "come" instead of "comes"
The link in this Reference does not work: API. (2014). Pressure-relieving and Depressuring Systems, API Standard 521 (API Standard 521, Sixth Edition, January). American Petroleum Institute. ISBN: 5925731107

**Comment by fraukewiese** [comment] 2021-10-05 10:41
@andr1976 
Then, could you
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with accepting the submission.

**Comment by andr1976** [comment] 2021-10-05 13:29
@fraukewiese : 

The manuscript has been revised accordingly and the ISBN no has been removed. 

The latest tagged release https://github.com/andr1976/HydDown/releases/tag/v0.16.2
Achived here: https://doi.org/10.5281/zenodo.5547917
yesterday, i.e. the small corrections just made to the manuscript are not reflected, but the software is the same. I have checked metadata and removed mefuller as author including an anonynous dummy user that I have used for a workflow/github action.

**Comment by andr1976** [comment] 2021-10-05 13:29
@whedon generate pdf

**Comment by whedon** [comment] 2021-10-05 13:30
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03695/joss.03695/10.21105.joss.03695.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03695/joss.03695/10.21105.joss.03695.pdf) :page_facing_up: :point_left:

**Comment by fraukewiese** [comment] 2021-10-06 06:13
@whedon set v0.16.2 as version

**Comment by fraukewiese** [comment] 2021-10-06 06:16
@andr1976 : The title of the archive should match the title of your paper. Please adapt that, the we can move forward :)

**Comment by whedon** [comment] 2021-10-06 16:31
OK. <a href="https://doi.org/10.5281/zenodo.5547917" target="_blank">10.5281/zenodo.5547917</a> is the archive.

**Comment by fraukewiese** [comment] 2021-10-06 16:33
@whedon recommend-accept

**Comment by whedon** [comment] 2021-10-06 16:33
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2646

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2646, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true
```

**Comment by kyleniemeyer** [comment] 2021-10-06 17:17
Hi @andr1976, I am doing some final checks before accepting.

In the third paragraph and in the Acknowledgments section, you have a few instances of consecutive citations. In cases like this, please use the citation format like `[@author1:2001; @author2:2001]` to have them combined in a single citation like "(Author1 et al., 2001; Author2 et al., 2002)".

You also have one or two instances where the `@author:2001` format (i.e., without brackets) would be more appropriate, to put the author name(s) in the text like "Author et al. (2001)". I'm specifically looking at "please refer to (Shafig et al., 2020)."  in the statement of need section and "from (Haque et al., 1992)" in the caption of Figure 2.

Please update these and let me know—thanks!

**Comment by andr1976** [comment] 2021-10-06 19:43
@kyleniemeyer thanks for improving the reference style of the paper, much appreciated. I did a final proof-reading myself, but don't have anything to add/correct.  Also a big thanks to editor @fraukewiese, reviewers @mefuller and @bocklund 👍 you rock!, and another big thanks to @arfon and entire team behind joss - I think this model for reviewing papers could be adapted by other journals (although single/double blind is a challenge though) - it is very constructive and productive.

**Comment by kyleniemeyer** [comment] 2021-10-06 20:09
@whedon generate pdf

**Comment by whedon** [comment] 2021-10-06 20:11
```
Doing it live! Attempting automated processing of paper acceptance...
```

**Comment by whedon** [comment] 2021-10-06 20:12
🚨🚨🚨 **THIS IS NOT A DRILL, YOU HAVE JUST ACCEPTED A PAPER INTO JOSS!** 🚨🚨🚨

 Here's what you must now do:

0. Check final PDF and Crossref metadata that was deposited :point_right: https://github.com/openjournals/joss-papers/pull/2647
1. Wait a couple of minutes, then verify that the paper DOI resolves [https://doi.org/10.21105/joss.03695](https://doi.org/10.21105/joss.03695)
2. If everything looks good, then close this review issue.
3. Party like you just published a paper! 🎉🌈🦄💃👻🤘

 Any issues? Notify your editorial technical team...

**Comment by kyleniemeyer** [comment] 2021-10-06 20:19
Congrats @andr1976 on your article's publication in JOSS!

Many thanks to @mefuller and @bocklund for reviewing this, and @fraukewiese for editing.

**Closed by kyleniemeyer** 2021-10-06 20:19 UTC
Labels: accepted, review, TeX, Python, recommend-accept, published
