### ISSUE TITLE
[PRE REVIEW]: Python Sorted Containers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1223] opened 2019-01-31 11:38 UTC
**Submitting author:** @grantjenks (<a href="http://orcid.org/0000-0001-5010-405X">Grant Jenks</a>)
**Repository:** <a href="https://github.com/grantjenks/python-sortedcontainers" target ="_blank">https://github.com/grantjenks/python-sortedcontainers</a>
**Version:** v2.1.0
**Editor:** @jasonclark
**Reviewers:** @djmitche

**Author instructions**

Thanks for submitting your paper to JOSS @grantjenks. The JOSS editor Pending, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@grantjenks if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-01-31 11:38
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-01-31 11:38
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-01-31 11:38
PDF failed to compile for issue #1223 with the following error: 

 /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `block in find': No such file or directory - tmp/1223 (Errno::ENOENT)
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `collect!'
	from /app/vendor/ruby-2.4.4/lib/ruby/2.4.0/find.rb:43:in `find'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/lib/whedon/processor.rb:57:in `find_paper_paths'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:47:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-c5f29247288e/bin/whedon:113:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by danielskatz** [comment] 2019-01-31 14:11
This software looks useful, even though there's a problem compiling the paper.  You can make changes to the source, then enter ```@whedon compile pdf``` as a new comment here to try to fix it.

Another issue I have is that it's not clear to me that this is research software according to the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html):
> JOSS publishes articles about research software. This definition includes software that: solves complex modeling problems in a scientific context (physics, mathematics, biology, medicine, social science, neuroscience, engineering); supports the functioning of research instruments or the execution of research experiments; extracts knowledge from large data sets; offers a mathematical library, or similar.

Can you help me understand this?

**Comment by grantjenks** [comment] 2019-02-02 01:12
Regarding the guidelines, I think it fits under:

```
supports the functioning of research instruments or the execution of research experiments
```

But I may be wrong. I had JOSS suggested to me by the creator of IPython. And I received a GitHub Issue asking how to cite the project. Consider some of the users:

* Zipline, an algorithmic trading library from Quantopian
* Angr, a binary analysis platform from UC Santa Barbara
* Trio, an async I/O library
* Dask Distributed, a distributed computation library supported by Continuum Analytics
* Astropy, a community Python library for astronomy

Does that satisfy?

Also, I looked through GitHub issues trying to understand how the PDF is generated:

* https://github.com/openjournals/joss/issues/370
* https://github.com/openjournals/joss/issues/379
* https://github.com/openjournals/whedon
* https://gist.github.com/mhucka/5ecb18aa2fd088c055de07366f70135e
* https://github.com/openbases/builder-pdf

But I was unable to reproduce the problem. (Maybe those links will be useful for a future visitor). There seems to be a "paper.md" file that is missing. Is that something I generate? I'm happy to accommodate, just not sure what's necessary. I could see how the project README may not be as useful for a paper as say the [Performance Comparison](http://www.grantjenks.com/docs/sortedcontainers/performance.html), [Implementation Details](http://www.grantjenks.com/docs/sortedcontainers/implementation.html), or [Performance at Scale](http://www.grantjenks.com/docs/sortedcontainers/performance-scale.html) materials.

**Comment by arfon** [comment] 2019-02-03 03:07
Hi @grantjenks - please take a look at the [submission guidelines](https://joss.readthedocs.io/en/latest/submitting.html) and prepare a `paper.md` and `paper.bib` file and include them in your repository (https://github.com/grantjenks/python-sortedcontainers). Once you've uploaded them, Whedon (the robot here) will be able to compile the paper.

In your paper, please be sure to address each of the points listed in the section [what should my paper contain?](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain).

**Comment by arfon** [comment] 2019-02-04 12:42
> I _think_ that's fine, but want to hear from @arfon before we go on.

👍 I think that's OK too. Please go ahead and prepare a paper to accompany this submission @grantjenks.

**Comment by danielskatz** [comment] 2019-02-25 13:30
I'll mark this as paused until then - please let us know when you are ready to proceed.

**Comment by grantjenks** [comment] 2019-02-25 15:34
Sorry for the delay. February has been a busy month. It’s on the schedule for early March.

**Comment by grantjenks** [comment] 2019-03-05 22:34
I published the paper.md and paper.bib files this morning. I believe I covered each of the requirements as to "What should my paper contain?" It is ready to be un-paused. I believe that was pre-review. Let me see if I can get whedon to compile the PDF.

**Comment by grantjenks** [comment] 2019-03-05 22:35
@whedon compile pdf

**Comment by kyleniemeyer** [comment] 2019-03-06 22:33
@whedon compile pdf

**Comment by kyleniemeyer** [comment] 2019-03-06 22:34
@arfon looks like @whedon isn't responding in here?

**Comment by danielskatz** [comment] 2019-03-06 22:35
@whedon generate pdf

**Comment by whedon** [comment] 2019-03-06 22:35
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-06 22:36
PDF failed to compile for issue #1223 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:83:in `check_fields': Paper YAML header is missing expected fields: affiliations (RuntimeError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:69:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by grantjenks** [comment] 2019-03-07 01:30
Ooops, updated paper.

**Comment by grantjenks** [comment] 2019-03-07 01:30
@whedon generate pdf

**Comment by whedon** [comment] 2019-03-07 01:30
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-07 01:30
PDF failed to compile for issue #1223 with the following error: 

 /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:117:in `parse_affiliations': undefined method `each' for nil:NilClass (NoMethodError)
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:103:in `parse_authors'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon.rb:73:in `initialize'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:55:in `prepare'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.4.0/bundler/gems/whedon-01ece1d1d135/bin/whedon:116:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `load'
	from /app/vendor/bundle/ruby/2.4.0/bin/whedon:23:in `<main>'

**Comment by grantjenks** [comment] 2019-03-07 01:36
Hi all, I'm not sure what you want for "affiliations". I was not attending college when I developed the project. But I can put where I graduated. Should I put my company? Please advise.

**Comment by arfon** [comment] 2019-03-07 11:20
@grantjenks - you can have an affiliation of 'None', but the YAML header of the paper needs to match this example: https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography

**Comment by grantjenks** [comment] 2019-03-07 19:34
Ok, try 2.

**Comment by grantjenks** [comment] 2019-03-07 19:34
@whedon generate pdf

**Comment by whedon** [comment] 2019-03-07 19:34
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-03-07 19:34
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01223/joss.01223/10.21105.joss.01223.pdf)

**Comment by labarba** [comment] 2019-03-13 00:48
Looks like we're ready to get this submission into review now!

@jasonclark — from a first look, I'd like to assign this to you. Hope that you can find a couple of reviewers and steer this one!

**Comment by labarba** [comment] 2019-03-16 14:35
@whedon assign @jasonclark as editor

**Comment by jasonclark** [comment] 2019-03-17 14:39
Hi, @grantjenks. I'll be working through the editing. Thanks for your work so far.

**Comment by jasonclark** [comment] 2019-03-17 14:45
Hi, @djmitche. Would you have time to review this software in the next 2 weeks? It's more of a software library implementation and your software testing background perspective would be really helpful. cc @grantjenks

**Comment by djmitche** [comment] 2019-03-17 21:15
Happy to.

**Comment by jasonclark** [comment] 2019-03-18 16:19
Thanks, @djmitche! I'll set up the review and assign you. cc @grantjenks

**Comment by jasonclark** [comment] 2019-03-18 16:22
@whedon assign @reviewer as reviewer

**Comment by whedon** [comment] 2019-03-18 16:23
OK, the reviewer is @reviewer

**Comment by jasonclark** [comment] 2019-03-18 16:24
@whedon unassign @djmitche  as reviewer

**Comment by jasonclark** [comment] 2019-03-18 16:24
@whedon assign @djmitche as reviewer

**Comment by whedon** [comment] 2019-03-18 16:25
OK, the reviewer is @djmitche

**Comment by jasonclark** [comment] 2019-03-18 16:27
@whedon start review magic-word=bananas

**Comment by whedon** [comment] 2019-03-18 16:28
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1330. Feel free to close this issue now!

**Comment by jasonclark** [comment] 2019-03-18 16:30
@djmitche the review is set up at https://github.com/openjournals/joss-reviews/issues/1330. cc @grantjenks

**Closed** 2019-03-20 10:14 UTC
Labels: Python, Shell, pre-review
