### ISSUE TITLE
[REVIEW]: Text detection in screen images with a Convolutional Neural Network

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#235] opened 2017-04-11 05:09 UTC
**Submitting author:** @domoritz (<a href="http://orcid.org/0000-0002-3110-1053">ROBYN DOMINIK MORITZ</a>)
**Repository:** <a href="https://github.com/domoritz/label_generator" target ="_blank">https://github.com/domoritz/label_generator</a>
**Version:** v1.1
**Editor:** @arfon
**Reviewer:** @ekolve
**Archive:** <a href="http://dx.doi.org/10.5281/zenodo.821196" target="_blank">10.5281/zenodo.821196</a>

## Status

[![status](http://joss.theoj.org/papers/d2821f933fc95337202393e84189f4d9/status.svg)](http://joss.theoj.org/papers/d2821f933fc95337202393e84189f4d9)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d2821f933fc95337202393e84189f4d9"><img src="http://joss.theoj.org/papers/d2821f933fc95337202393e84189f4d9/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d2821f933fc95337202393e84189f4d9/status.svg)](http://joss.theoj.org/papers/d2821f933fc95337202393e84189f4d9)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/domoritz/label_generator" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/domoritz/label_generator">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.1)?
- [x] **Authorship:** Has the submitting author (@domoritz) made major contributions to the software?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by whedon** [comment] 2017-04-11 05:09
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @ekolve it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by ekolve** [comment] 2017-05-03 16:28
I followed all the steps in the README to install on AWS. I am using Ubuntu 14.04 and when I run this:
`python label_gen.py read-s3 escience.washington.edu.viziometrics acl_anthology/pdf/C08-1099.pdf acl_anthology`

I get the following message:
Usage:
`  main.py read-s3 S3-IN-BUCKET S3-FILE S3-OUT-BUCKET S3-PATH [--use-ramdisk] [--debug] [--dbg-image]
  main.py read FILE PATH [--debug] [--dbg-image]
  main.py (-h | --help)
  main.py --version`

**Comment by domoritz** [comment] 2017-05-03 16:38
@ekolve Thanks for doing the review! It looks like `label_gen.py` now expects two buckets. I'm looking into it.

**Comment by ekolve** [comment] 2017-05-03 17:39
Running this command:
` parallel --resume -j +6 --no-run-if-empty --eta --joblog /tmp/par.log python label_gen.py read-s3 escience.washington.edu.viziometrics acl_anthology/pdf/{} escience.washington.edu.viziometrics acl_anthology --dbg-image :::: acl_papers.txt`

I get several 403 Forbidden errors.  This was caused by me not having permission to the the s3 output bucket.  It would probably be a good idea to specify in the example that the user must supply their own output bucket they have write permission to.

**Comment by ekolve** [comment] 2017-05-03 17:43
A few documentation requests:
Specify the platform - I assumed Ubuntu 14.04 because that is what PDF figures requires, but it would be good for people to see this documented here.

I had to install the following additional apt packages:
software-properties-common # to get the add-apt-repository utility
python-dev
liblapack-dev libblas-dev gfortran # scipy dependencies - installed from requirements.txt

Not necessarily, specific to your code, but I had to run:
`pip install awscli --force-reinstall --upgrade`
to resolve an issue with aws + botocore.session followed by `aws configure`

**Comment by ekolve** [comment] 2017-05-03 17:50
It would also be a good idea to either freeze your requirements.txt or at least pin the packages to a major version (e.g. scipy >=1.12, < 1.13).  That way if a package deprecates something you are depending on in a new version users will be able to install.

**Comment by domoritz** [comment] 2017-05-03 17:51
Okay, first step was to get pdffigures working again. The api changed a bit (pdffigures now generates only a single json file) so I had to change the label generator code a bit but local generation works again now. 

```
python label_gen.py read papers/1504.01101.pdf /tmp --debug                                                                                       1265ms
DEBUG:root:Run pdffigures /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:Finished. Now look for the JSON and generate labels.
DEBUG:root:Found 4 figures
DEBUG:root:Render image /tmp/img/1504.01101-Figure-0.png from /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:Render image /tmp/img/1504.01101-Figure-0-2x.png from /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:generate label /tmp/text-masked/1504.01101-Figure-0-label.png
DEBUG:root:Render image /tmp/img/1504.01101-Figure-1.png from /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:Render image /tmp/img/1504.01101-Figure-1-2x.png from /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:generate label /tmp/text-masked/1504.01101-Figure-1-label.png
DEBUG:root:Render image /tmp/img/1504.01101-Figure-2.png from /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:Render image /tmp/img/1504.01101-Figure-2-2x.png from /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:generate label /tmp/text-masked/1504.01101-Figure-2-label.png
DEBUG:root:Render image /tmp/img/1504.01101-Figure-3.png from /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:Render image /tmp/img/1504.01101-Figure-3-2x.png from /Users/domoritz/Developer/vision/label_generator/papers/1504.01101.pdf
DEBUG:root:generate label /tmp/text-masked/1504.01101-Figure-3-label.png
```

I'm looking at S3 now.

**Comment by domoritz** [comment] 2017-05-03 18:07
> Specify the platform - I assumed Ubuntu 14.04 because that is what PDF figures requires, but it would be good for people to see this documented here.

Done

> It would also be a good idea to either freeze your requirements.txt or at least pin the packages to a major version (e.g. scipy >=1.12, < 1.13). That way if a package deprecates something you are depending on in a new version users will be able to install.

Done

The last remaining issue are the changes in AWS. The problem seems to be that a) I didn't document that you need to write to a bucket that you have write access to and b) that the `label_gen.py` arguments are not correct in the instructions, right?

**Comment by ekolve** [comment] 2017-05-03 18:13
Correct.  I am running the parallel task now and it seems to be running fine.

**Comment by domoritz** [comment] 2017-05-03 18:37
I don't have access to an AWS machine right now but I fixed the command in the readme and everything seems to be working fine on my local machine.

**Comment by domoritz** [comment] 2017-05-03 19:16
That's great. I fixed the command in the readme and everything seems to be working fine on my local machine. I also added a note to the readme that the commands were the ones I used to extract the figures and generate the labels that you can also just download from S3 (as described in the readme). I think the relevant part of those instructions is that you can use it to understand how you can generate the text masks for papers that I have not processed yet. 

After the upgrades I did today, I think the code and docs are at a point where we can do that.

**Comment by domoritz** [comment] 2017-05-03 19:17
Thank you for the review and the suggestions to improve the docs and code @ekolve!

**Comment by ekolve** [comment] 2017-05-04 00:22
I am getting an error running the find_bad.py command:
`python find_bad.py read-s3 escience.washington.edu.viziometrics acl_anthology/json > anthology_bad.txt`
Run 0 of 1

ERROR:root:Not a json file acl_anthology/json/

This might be coming from boto.

**Comment by domoritz** [comment] 2017-05-04 03:12
Looks like boto has changed its behavior. I'm asking boto to enumerate all the files in a directory and they now also list the directory itself. Strange but not a big problem. Fixed in https://github.com/domoritz/label_generator/commit/d2a7eb54e93898df005a416807d65f3993b3912c

**Comment by ekolve** [comment] 2017-05-05 20:01
I am getting an error running this command:
` python label_gen.py read testdata/paper.pdf /tmp/test --dbg-image --debug`

DEBUG:root:Run pdffigures /home/erick/label_generator/testdata/paper.pdf
DEBUG:root:Finished. Now look for the JSON and generate labels.
Traceback (most recent call last):
  File "label_gen.py", line 193, in <module>
    arguments['--dbg-image'], False)
  File "label_gen.py", line 94, in run_local
    with open(json_file) as fh:
IOError: [Errno 2] No such file or directory: '/tmp/test/json/paper.json'

I am using the latest code from master.

**Comment by domoritz** [comment] 2017-05-05 21:32
Did you rebuild pdffigures?

**Comment by ekolve** [comment] 2017-05-08 22:11
I am trying to re-run the label generation:
`parallel --resume -j +6 --no-run-if-empty --eta --joblog /tmp/par.log python label_gen.py read-s3 escience.washington.edu.viziometrics acl_anthology/pdf/{} escience.washington.edu.viziometrics acl_anthology --dbg-image :::: acl_papers.txt
`
And I am getting this error:
  File "label_gen.py", line 190, in <module>
    arguments['--use-ramdisk'], arguments['--dbg-image'])
  File "label_gen.py", line 162, in run_s3
    files = run_local(target, dirpath, debug_image, True)
  File "label_gen.py", line 94, in run_local
    with open(json_file) as fh:
IOError: [Errno 2] No such file or directory: '/tmp/tmpyVYzU7/A83-1016.json'

over and over again.

**Comment by domoritz** [comment] 2017-05-10 16:34
I just tested `python label_gen.py read testdata/paper.pdf /tmp/test --dbg-image --debug` and get

```
DEBUG:root:Run pdffigures /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:Finished. Now look for the JSON and generate labels.
DEBUG:root:Found 6 figures
DEBUG:root:Render image /tmp/test/img/paper-Figure-0.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:Render image /tmp/test/img/paper-Figure-0-2x.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:generate label /tmp/test/text-masked/paper-Figure-0-label.png
DEBUG:root:Render image /tmp/test/img/paper-Figure-1.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:Render image /tmp/test/img/paper-Figure-1-2x.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:generate label /tmp/test/text-masked/paper-Figure-1-label.png
DEBUG:root:Render image /tmp/test/img/paper-Figure-2.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:Render image /tmp/test/img/paper-Figure-2-2x.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:generate label /tmp/test/text-masked/paper-Figure-2-label.png
DEBUG:root:Render image /tmp/test/img/paper-Figure-3.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:Render image /tmp/test/img/paper-Figure-3-2x.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:generate label /tmp/test/text-masked/paper-Figure-3-label.png
DEBUG:root:Render image /tmp/test/img/paper-Figure-4.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:Render image /tmp/test/img/paper-Figure-4-2x.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:generate label /tmp/test/text-masked/paper-Figure-4-label.png
DEBUG:root:Render image /tmp/test/img/paper-Figure-5.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:Render image /tmp/test/img/paper-Figure-5-2x.png from /Users/domoritz/Developer/vision/label_generator/testdata/paper.pdf
DEBUG:root:generate label /tmp/test/text-masked/paper-Figure-5-label.png
```

I suspect that you get the second error because of permission issues on S3, which I consider outside the scope of this review. When running over S3 data, the code always just calls the same method that is used for local generation (https://github.com/domoritz/label_generator/blob/master/label_gen.py#L162).

**Comment by ekolve** [comment] 2017-05-10 21:16
Looks like I am getting an error from pdffigures:

Running this pdf: X98-1018.pdf

pdffigures/pdffigures -j /tmp/tmp70kZSJ/X98-1018 /tmp/tmp70kZSJ/X98-1018.pdf

Gives this output:
Body text appears to be encoded as graphics, skipping (use -i to parse these kinds of documents)
Running pdffigures version 1.0.6

**Comment by domoritz** [comment] 2017-05-10 21:21
Interesting. I think this should only be a warning. Does it crash the
script?

**Comment by ekolve** [comment] 2017-05-10 21:23
It doesn't crash the script, but pdffigures doesn't write anything out so there is no json to read which causes the code to failure a few lines later.

**Comment by ekolve** [comment] 2017-05-10 21:24
Actually, hold on - i am seeing JSON - let me look at this a little more.

**Comment by ekolve** [comment] 2017-05-10 21:28
Okay, I not sure what is going on with pdffigures, but this is what I am seeing:

`pdffigures/pdffigures -j /tmp/X98-1018 /tmp/X98-1018.pdf.pdf`

works - I get a file in /tmp/X98-1018.json

If i run:

`mkdir /tmp/foo`
`pdffigures/pdffigures -j /tmp/foo/X98-1018 /tmp/X98-1018.pdf.pdf`

no json file gets placed in /tmp/foo

**Comment by domoritz** [comment] 2017-05-10 21:48
Yeah, I can confirm. The directory needs to exist. 

```
pdffigures/pdffigures -j /tmp/json/test ./testdata/paper.pdf
```

Only works if `tmp/json` exists.

**Comment by domoritz** [comment] 2017-05-10 21:52
Running 

```
python label_gen.py read testdata/paper.pdf /tmp/test --dbg-image
```

Works even when only `/tmp` exists and it generates the labels correctly for me. I'm using pdffigures version 1.0.6.

Again, thank you so much for putting the effort into testing the label generator thoroughly. I'm at a conference so please excuse the slow replies lately.

**Comment by ekolve** [comment] 2017-05-10 22:33
Could you try the pdf that I was using?

**Comment by domoritz** [comment] 2017-05-10 23:06
> Could you try the pdf that I was using?

Sure! Can you send me a link to the file or the S3 location?

**Comment by domoritz** [comment] 2017-05-10 23:09
Found it: https://s3-us-west-2.amazonaws.com/escience.washington.edu.viziometrics/acl_anthology/pdf/X98-1018.pdf

**Comment by domoritz** [comment] 2017-05-10 23:15
Ahh, yes. That was a bug. The problem was that pdffigures doesn't create a JSON file when it couldn't extract any figures from the paper. 

Fixed in https://github.com/domoritz/label_generator/commit/8c665df0ec37f249818455b7c100fdec5440605e. I just added a check for whether the JSON file exists.

**Comment by ekolve** [comment] 2017-05-19 18:19
I am going to try and train the network - I pulled down all the data that I generated using the parallel command from s3. Now I have a directory acl_anthology with three directories inside of it: img, json, text-masked.  Which directory of images do I use to train the network?

**Comment by domoritz** [comment] 2017-05-19 20:39
@ekolve I think the main contribution of my code (and what others are using it for) is the label generation. IMHO, you don't necessarily need to do the training because I just use darknet and these days better models exist.

**Comment by ekolve** [comment] 2017-05-19 23:40
Okay, that sounds good.

The only remaining points I have to verify are: Community guidelines and Automated Tests.

Could you add a section to the README to satisfy community guidelines (description for how to contribute, etc.)?

For automated tests, I am able to run the example label_gen.py you have in the README, but I don't necessarily know if my output is what is expected.  Could you provide some way to verify that its correct?

**Comment by domoritz** [comment] 2017-05-20 17:16
Thank you! I'll do that today. For intimated tests, I should probably add a
test that runs a full image generation on Travis and compares the outputs.

**Comment by domoritz** [comment] 2017-05-22 05:46
I've added some guidelines and set up basic tests on travis. As a basic test, compare your output of `python label_gen.py read testdata/paper.pdf /tmp/test --dbg-image` with the content of [`testoutput`](https://github.com/domoritz/label_generator/tree/master/testoutput). I also created a new [tag 1.2](https://github.com/domoritz/label_generator/releases/tag/1.2).

**Comment by domoritz** [comment] 2017-06-02 18:03
@ekolve Let me know if there is anything else to do. Again, thanks for the thorough review!

**Comment by ekolve** [comment] 2017-06-06 00:00
lgtm, want me to close out the issue?

**Comment by domoritz** [comment] 2017-06-06 00:03
@ekolve Can you check the last boxes in this issue?

@jakevdp What happens next?

**Comment by domoritz** [comment] 2017-06-25 17:37
Ping @ekolve @jakevdp

**Comment by arfon** [comment] 2017-06-29 08:28
@domoritz - At this point could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by domoritz** [comment] 2017-06-29 18:17
Thanks @arfon. The DOI is https://doi.org/10.5281/zenodo.821196.

**Comment by arfon** [comment] 2017-07-04 06:49
@whedon set 10.5281/zenodo.821196 as archive

**Comment by whedon** [comment] 2017-07-04 06:49
OK. <a href="http://dx.doi.org/10.5281/zenodo.821196" target="_blank">10.5281/zenodo.821196</a> is the archive.

**Comment by arfon** [comment] 2017-07-04 06:50
Thanks @domoritz. 

> How will we make sure that the doi links to the code on GitHub instead of the uploaded file on Zenodo?

Your paper (and the JOSS website) link directly to GitHub. I don't know about the Zenodo linking sorry other than I think they include links to the GitHub repository in their metadata for the DOI.

**Comment by domoritz** [comment] 2017-07-04 06:58
Sounds good. Thanks for moving this forward @arfon!

**Comment by arfon** [comment] 2017-07-04 07:04
@ekolve - many thanks for your review here.

@domoritz - your paper is now accepted into JOSS and your DOI is http://dx.doi.org/10.21105/joss.00235 ⚡️ 🚀 💥

**Closed by arfon** 2017-07-04 07:04 UTC
Labels: accepted, review

**Comment by domoritz** [comment] 2017-07-04 07:30
Thank you @arfon and @jakevdp for finding reviewers and finalizing the acceptance and @ekolve for the review!
