### ISSUE TITLE
[REVIEW]: ResumableFunctions: C# sharp style generators for Julia.

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#400] opened 2017-09-11 10:54 UTC
**Submitting author:** @benlauwens (<a href="http://orcid.org/0000-0003-0761-6265">Ben Lauwens</a>)
**Repository:** <a href="https://github.com/BenLauwens/ResumableFunctions.jl.git" target ="_blank">https://github.com/BenLauwens/ResumableFunctions.jl.git</a>
**Version:** v0.1.0
**Editor:** @danielskatz
**Reviewer:** @gasagna
**Archive:** <a href="https://doi.org/10.5281/zenodo.1039345" target="_blank">10.5281/zenodo.1039345</a>

## Status

[![status](http://joss.theoj.org/papers/889b2faed426b978ee705689c8f8440b/status.svg)](http://joss.theoj.org/papers/889b2faed426b978ee705689c8f8440b)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/889b2faed426b978ee705689c8f8440b"><img src="http://joss.theoj.org/papers/889b2faed426b978ee705689c8f8440b/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/889b2faed426b978ee705689c8f8440b/status.svg)](http://joss.theoj.org/papers/889b2faed426b978ee705689c8f8440b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/BenLauwens/ResumableFunctions.jl.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer questions

@gasagna, please carry out your review in this issue by updating the checklist below (please make sure you're logged in to GitHub). The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines. Any questions/concerns please let @danielskatz know.

### Conflict of interest

- [x] As the reviewer I confirm that I have read the [JOSS conflict of interest policy](https://github.com/openjournals/joss/blob/master/COI.md) and that there are no conflicts of interest for me to review this work.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](http://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/BenLauwens/ResumableFunctions.jl.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v0.1.0)?
- [x] **Authorship:** Has the submitting author (@benlauwens) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by whedon** [comment] 2017-09-11 10:55
Hello human, I'm @whedon. I'm here to help you with some common editorial tasks for JOSS. @gasagna it looks like you're currently assigned as the reviewer for this paper :tada:.

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As as reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all JOSS reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by danielskatz** [comment] 2017-09-11 10:57
@gasagna - this is ready for you to review.

An informal guideline is that we would like your review in 2 weeks, but sooner (or later) are also ok.

Please carry out your review in this issue by updating the checklist above (please make sure you're logged in to GitHub)

The reviewer guidelines are available here: http://joss.theoj.org/about#reviewer_guidelines

Please avoid lengthy details of difficulties in this review thread. Instead, please create a new issue in the target repository and link to those issues (especially acceptance-blockers) in this review thread. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

Any questions/concerns, please let me know.

Thanks!!

**Comment by gasagna** [comment] 2017-09-23 10:39
@whedon commands

**Comment by whedon** [comment] 2017-09-23 10:39
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the reviewer of this submission
@whedon assign @username as reviewer

# List the GitHub usernames of the JOSS editors
@whedon list editors

# List of JOSS reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Open the review issue
@whedon start review
```

:construction: **Important** :construction:

This is all quite new. Please make sure you check the top of the issue after running a @whedon command (you might also need to refresh the page to see the issue update).

**Comment by gasagna** [comment] 2017-09-23 10:56
It seems I am unable to edit directly the checklist above. Am I supposed to fork this and make pull requests?

**Comment by danielskatz** [comment] 2017-09-23 11:24
The only time I've heard of this problem, it was when someone tried to check a box when they were not logged in.

So, please be sure you are logged in when you try to check a box.  (I know you were when you commented, but perhaps you were not initially?)

Also, when you say "edit the checklist", do you really mean check a box?  You should be able to do that, but you should not able to make other changes to the checklist.

Let me know if either of these clear up the problem.

**Comment by gasagna** [comment] 2017-09-29 15:05
No, sorry, I can't really check the boxes. I am logged in. Tried two different browsers as well.

**Comment by danielskatz** [comment] 2017-09-29 15:10
@arfon - any thoughts on this?  I haven't seen this before, and you are probably the GitHub expert :)

**Comment by arfon** [comment] 2017-10-01 10:35
> No, sorry, I can't really check the boxes. I am logged in. Tried two different browsers as well.

Looks like the API command to give you access must have failed silently. @gasagna - can you visit this URL (logged in): https://github.com/openjournals and accept the invite. You should then be able to update the check list.

**Comment by gasagna** [comment] 2017-10-02 08:01
Sorry, still unable to check the boxes after the invite.

**Comment by arfon** [comment] 2017-10-02 08:35
> Sorry, still unable to check the boxes after the invite.

OK, I officially give up. Please copy and paste the checklist content into a separate comment in this thread and work through it here.

**Comment by gasagna** [comment] 2017-10-03 05:33
**Conflict of interest**

- [x] As the reviewer I confirm that I have read the JOSS conflict of interest policy and that there are no conflicts of interest for me to review this work.

**Code of Conduct**

- [x] I confirm that I read and will adhere to the JOSS code of conduct.

**General checks**
- [ ] Repository: Is the source code for this software available at the repository url?
- [ ]  License: Does the repository contain a plain-text LICENSE file with the contents of an OSI approved software license?
- [ ]  Version: Does the release version given match the GitHub release (v0.1.0)?
- [ ]  Authorship: Has the submitting author (@BenLauwens) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?

**Functionality**
- [ ]  Installation: Does installation proceed as outlined in the documentation?
- [ ]  Functionality: Have the functional claims of the software been confirmed?
- [ ]  Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

**Documentation**

- [ ]  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ]  Installation instructions: Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ]  Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [ ]  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ]  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?
- [ ]  Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Software paper**

- [ ]  Authors: Does the paper.md file include a list of authors with their affiliations?
- [ ]  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [ ]  References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?

**Comment by danielskatz** [comment] 2017-10-09 12:27
Hi @gasagna - How is this going?

(Note: I copied your 2 checkmarks from your comment above into the main list at the top of the issue, and I'm happy to continue to do this as you make progress, so that someone who looks at this later can see the status at the top.)

**Comment by gasagna** [comment] 2017-10-09 16:41
Hi Daniel, 

I have completed my review, and I have pointed out minor issues that @BenLauwens should address (see unchecked boxes above). These are mostly documentation improvement suggestions.

I will wait for the author to fix these and then check the remaining boxes.

**Comment by danielskatz** [comment] 2017-10-09 19:36
thanks!

**Comment by danielskatz** [comment] 2017-10-16 01:03
@gasagna - it looks like @BenLauwens has made some changes and plans to make one more.  Perhaps you can update some of the boxes?

And @BenLauwens, please let us know when the other change has been made.

**Comment by danielskatz** [comment] 2017-10-23 22:05
Hi @BenLauwens - just checking on this...  Is there any update?

**Comment by BenLauwens** [comment] 2017-10-24 06:40
Hi @danielskatz. I updated the documentation as proposed by @gasagna and I modified one line of code so that the behaviour of the iterator created by an `@resumable function` is in line with the already existing iterators in Julia. 
One issue remains that is documented both in the README and the tutorial. Parametrised `@resumable functions` are not supported yet. The implementation of this feature is straightforward but tedious. I am using a supporting package Macrotools to do the heavy work but this package has not yet released a version that supports the 'where' clause (in master this is already supported). This is however a minor feature and ResumableFunctions are perfectly working without it.

**Comment by danielskatz** [comment] 2017-10-24 09:57
@gasagna - what do you think?

**Comment by gasagna** [comment] 2017-10-29 19:42
I think this is OK. There are a few missing checks in my reviews, but these are not blocking acceptance. Just additional edits to the docs that the author might wish to add.

**Comment by danielskatz** [comment] 2017-10-30 12:40
@gasagna - we do want to see all the boxes checked before we accept.  For example, for performance, the description is
> If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

So please check off everything you can, and if you don't feel you can check something off, please explain what you think is needed in order that you could do so.

**Comment by gasagna** [comment] 2017-10-30 13:45
@danielskatz The text in italic in my check list explains it already. My comments are suggestions to improve the docs that the author might wish to take into account. These are not acceptance-blocking.

**Comment by danielskatz** [comment] 2017-10-30 13:50
Thanks @gasagna, but as I said, we will not move ahead until all boxes are checked.  Can I suggest that rather than altering the list, you check the items (since you say that they are not blockers) and make the comments in italics issues that you open in the author's package?

Remember that if this was a normal review (where you could check the boxes on the top of the issue), you would not be able to edit the checklist, just check the boxes or leave the empty.

**Comment by gasagna** [comment] 2017-10-30 14:00
Done! All boxes have been checked, and an issue has been opened in the repo, as you suggested.

**Comment by danielskatz** [comment] 2017-10-30 14:21
@arfon - Please go ahead with the acceptance process now

**Comment by arfon** [comment] 2017-10-30 18:50
@BenLauwens - please merge this PR with some minor changes to your paper and bibtex https://github.com/BenLauwens/ResumableFunctions.jl/pull/8 

Then, could you make an archive of the reviewed software in Zenodo/figshare/other service and update this thread with the DOI of the archive? I can then move forward with accepting the submission.

**Comment by BenLauwens** [comment] 2017-10-30 20:18
@arfon 
I have just merged the changes and created a new release.
DOI: 10.5281/zenodo.1039345

**Comment by arfon** [comment] 2017-10-30 20:35
@whedon set 10.5281/zenodo.1039345 as archive

**Comment by whedon** [comment] 2017-10-30 20:35
OK. <a href="http://dx.doi.org/10.5281/zenodo.1039345" target="_blank">10.5281/zenodo.1039345</a> is the archive.

**Comment by arfon** [comment] 2017-10-30 21:06
@gasagna - many thanks for your review and to @danielskatz for editing this submission ✨ 

@BenLauwens - your paper is now accepted into JOSS and your DOI is https://doi.org/10.21105/joss.00400 ⚡️ 🚀 💥

**Closed by arfon** 2017-10-30 21:06 UTC
Labels: accepted, review
