### ISSUE TITLE
[PRE REVIEW]: GraphColoring: A Java package for solving the graph coloring problem

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1733] opened 2019-09-16 15:54 UTC
**Submitting author:** @shah314 (<a href="http://orcid.org/0000-0002-3770-1391">Shalin S Shah</a>)
**Repository:** <a href="https://github.com/shah314/graphcoloring" target ="_blank">https://github.com/shah314/graphcoloring</a>
**Version:** v1.1
**Editor:** @jedbrown
**Reviewers:** HaoZeke

**Author instructions**

Thanks for submitting your paper to JOSS @shah314. **Currently, there isn't an JOSS editor assigned** to your paper.

@shah314 if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-09-16 15:54
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```


**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-09-16 15:54
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by kthyng** [comment] 2019-09-16 15:54
Hi @VivianePons! Could you edit this submission?

**Comment by whedon** [comment] 2019-09-16 15:54
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01733/joss.01733/10.21105.joss.01733.pdf)

**Comment by kthyng** [comment] 2019-09-16 15:57
@jedbrown Can you edit this submission?

**Comment by shah314** [comment] 2019-09-16 16:01
@whedon generate pdf

**Comment by whedon** [comment] 2019-09-16 16:01
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-09-16 16:02
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01733/joss.01733/10.21105.joss.01733.pdf)

**Comment by jedbrown** [comment] 2019-09-17 15:46
@whedon assign jedbrown as editor

**Comment by whedon** [comment] 2019-09-17 15:47
OK, the editor is jedbrown

**Comment by jedbrown** [comment] 2019-09-17 15:52
@shah314 Could you please add a comparison with existing graph coloring capability (why would a practitioner use this software instead of others, and when should they choose others?) and address [community guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines) and automated testing?

**Comment by shah314** [comment] 2019-09-17 16:14
@whedon generate pdf

**Comment by whedon** [comment] 2019-09-17 16:14
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-09-17 16:14
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01733/joss.01733/10.21105.joss.01733.pdf)

**Comment by shah314** [comment] 2019-09-17 16:16
@whedon generate pdf

**Comment by whedon** [comment] 2019-09-17 16:16
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-09-17 16:17
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01733/joss.01733/10.21105.joss.01733.pdf)

**Comment by shah314** [comment] 2019-09-17 16:21
@jedbrown Thank you. I am working on it. About community guidelines, where do I add them? I think the repository is open for anyone to contribute and add issues, pull requests etc. I will add tests in a day or two.

**Comment by jedbrown** [comment] 2019-09-17 16:58
Usually people say something about support channels and expectations in their README and add [CONTRIBUTING.md](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors) and possibly a code of conduct. See also the [Community tab](https://github.com/shah314/graphcoloring/community) for your project.

**Comment by shah314** [comment] 2019-09-17 17:43
@jedbrown I have added community guidelines, a code of conduct and a test case to test the code. Since this is java code, it has to be compiled, so a Java compiler is a requirement. I have added a tests folder and a test.sh script which will compile the code and run a test. Please see if you are able to run this script. I also added a README to the tests folder.

**Comment by shah314** [comment] 2019-09-17 18:42
@jedbrown I have also made some changes to the paper with some motivation on why a heuristic might be preferred to an exact algorithm (like branch and cut).

**Comment by jedbrown** [comment] 2019-09-17 21:14
Thanks. In terms of comparison, I was thinking in terms of existing software such as [ColPack](https://cscapes.cs.purdue.edu/coloringpage/software.htm), the classic MINPACK methods ([largest first](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/MatOrderings/MATCOLORINGLF.html#MATCOLORINGLF), [smallest last](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/MatOrderings/MATCOLORINGSL.html#MATCOLORINGSL), and [incidence degree](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/MatOrderings/MATCOLORINGID.html#MATCOLORINGID) -- available in PETSc, for example), and implementations of parallel methods such as [Jones-Plassmann](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/MatOrderings/MATCOLORINGJP.html) and [Bozdag's greedy method](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/MatOrderings/MATCOLORINGGREEDY.html). Does your implementation outperform these? Is it significant because it's more convenient for a Java caller? These are the sort of questions that you can answer in your documentation and paper.

**Comment by shah314** [comment] 2019-09-17 22:41
@jedbrown Thanks. As far as I can see, ColPack does not publish benchmarks on publicly available data sets. The other references you cited all use their own data which are not publicly available. The paper I have cited uses publicly available benchmarks (like fpsol, myciel and queen) which can be verified easily. So, I'm not sure how to compare. I will keep looking. Thanks.

**Comment by jedbrown** [comment] 2019-09-17 22:50
These are open source packages that implement graph coloring as part of solving higher level problems. It should be straightforward to run on existing data sets. (Thousands of people use these implementations every day, but I have not seen their results on the benchmarks you mention.)

Note that your CMU link has an invalid certificate. Perhaps you can ask the owners to fix that.

**Comment by shah314** [comment] 2019-09-18 20:55
@jedbrown I'm trying to run the algorithms you mentioned on PETSc. I was able to set up PETSc and configure and build it. But I am unable to figure out how to invoke it and run these algorithms. When I go to the src directory and try to build them using make, it does not work because there is only a lib target. Any help?

**Comment by shah314** [comment] 2019-09-19 06:47
@whedon generate pdf

**Comment by whedon** [comment] 2019-09-19 06:47
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-09-19 06:47
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01733/joss.01733/10.21105.joss.01733.pdf)

**Comment by shah314** [comment] 2019-09-19 06:50
@jedbrown I was able to use ColPack to see how the largest first, smallest last and the incidence degree algorithms do on my instances. I have the results at the bottom of the git README. I have also included a summary of the comparison in the paper. Thanks.

**Comment by shah314** [comment] 2019-09-19 15:20
Also, if you are unable to download individual instance files from the CMU site, try downloading the tar file. I have also uploaded the instances tar file on my repository: https://github.com/shah314/graphcoloring/blob/master/instances.tar

**Comment by shah314** [comment] 2019-09-20 16:51
@whedon generate pdf

**Comment by whedon** [comment] 2019-09-20 16:51
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-09-20 16:52
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01733/joss.01733/10.21105.joss.01733.pdf)

**Comment by shah314** [comment] 2019-09-20 21:05
@whedon generate pdf

**Comment by whedon** [comment] 2019-09-20 21:05
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-09-20 21:06
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01733/joss.01733/10.21105.joss.01733.pdf)

**Comment by shah314** [comment] 2019-09-20 21:07
@whedon generate pdf

**Comment by whedon** [comment] 2019-09-20 21:08
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-09-20 21:08
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01733/joss.01733/10.21105.joss.01733.pdf)

**Comment by shah314** [comment] 2019-09-20 21:11
I have fixed the invalid certificate error for the CMU link.

**Comment by shah314** [comment] 2019-09-20 22:14
@whedon @hausen and @gabrielspadon could be reviewers.

**Comment by shah314** [comment] 2019-09-26 16:01
Any further thoughts, @jedbrown ?

I have made some changes to the code and added tests. I am now passing in the file name to the code, so there is no need for the data.col to exist in the current directory. 

Please do a git pull and review and verify the changes.

**Comment by jedbrown** [comment] 2019-09-30 04:09
@shah314 Thanks for your diligence in comparing with ColPack. I just remembered that NetworkX also has coloring algorithms, though I don't think they are any better than those in ColPack.

In your README, it just says "compile the code". I think it would be helpful to list the command to run to do that. From the tests, you evidently use the following, which gives some warnings with OpenJDK-12.

```
$ javac *.java
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

Could you comment on the expected execution-time performance of the algorithm? For example, packages like ColPack are used to color graphs with millions of vertices in a setup step for a solver. (They are usually computing a distance-2 coloring, though distance-1 colorings are used in a related context to expose parallelism.)

You have a lot of HTML inlined into your markdown files. Is that deliberate to overcome some perceived limitation of markdown?

Would you be willing to add automated testing to your repository, or at least streamline the testing procedure so that there is one command to run at the top level that reports success/failure?

I'll look for reviewers in the meantime.

**Comment by shah314** [comment] 2019-09-30 17:34
The compilation warning is because the code does not use generics. I think it is completely harmless.

About execution time, there are several parameters in Constants.java which can be used to control the run time. For instance, one could disable local search, or reduce the number of iterations and get a much better run time. On the inithx.i.3 instance with 621 vertices, this algorithm takes 2 seconds (without local search) and ColPack takes 45 milliseconds. But if the goal is to get a good enough coloring as fast as possible, the algorithm could be changed. I have mentioned this on the git README.

I mainly use HTML for the results tables, and to change the properties of text. It just makes it more readable when viewed on a browser.

I have added testall.sh which runs both the heuristics and the backtracking algorithms. It compiles the code, and runs both algorithms on an instance with a known chromatic number (queen9_9).

Thanks @jedbrown

**Comment by jedbrown** [comment] 2019-09-30 18:58
Editing compile-time constants is a poor interface for a potential application. It would be *much* better to have a configurable public interface with examples. I'm not personally familiar with Java documentation practices, but it's very common for JOSS submissions to have API documentation plus tutorials written with tools like Sphinx or Doxygen. If you want the package to be used, it would be very worthwhile to create such documentation. As a lighter weight alternative, you could just write markdown files with example calling procedures.

Regarding HTML, Markdown has its own lighter weight syntax for the formatting that I've noticed. This isn't that important, but is disruptive when reading the text files directly (e.g., after cloning) and adds a layer of uncertainty for a potential contributor to determine whether to introduce inconsistency by using markdown or to reproduce via HTML to satisfy some unknown requirement (such as that it be copy-pastable into a literal HTML file).

On testing, you added the following to `tests/README.md`, but it is not mentioned in the top-level `README.md`.
> Please run <b>testall.sh</b> to run all tests.

It doesn't say how to run them (and `testall.sh` is not executable). This kind of documentation should be really explicit. It also helps for tests to have explicit PASS/FAIL reports. There shouldn't be any interpretation left to the user. Perhaps you could write some tests using JUnit, for example, which would formalize what we mean by automated tests. The following is better than nothing, but is not deterministic and it's left to the reader to interpret whether the result is a pass.
```
$ bash testall.sh 
mkdir: cannot create directory ‘testing1’: File exists
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Reading Graph...
Computing Clique...
Maximum Clique Size Found: 9
Vertices in the Clique:
40 13 49 67 4 31 76 58 22 

104 milliseconds (excluding I/O).
15 coloring found using DSatur.
Applying Iterated Greedy Improvement...
Found Better Coloring - 13
Found Better Coloring - 12
Found Better Coloring - 11
Applying Local Search...
Final Coloring of graph possible with 11 colors.
Colors of Vertices: 
8 2 6 9 11 1 4 5 10 5 10 11 7 2 3 8 6 1 9 4 3 10 1 6 2 11 7 6 1 7 5 3 4 10 8 2 4 8 10 11 7 9 5 3 6 11 9 1 3 8 2 6 10 4 2 7 8 4 6 10 11 1 3 10 11 2 1 9 8 3 4 5 1 3 4 8 5 11 7 2 9 Reading Graph...
Computing Clique...
Maximum Clique Size Found: 9
Vertices in the Clique:
22 13 49 67 4 31 76 58 40 

108 milliseconds (excluding I/O).
Trying to color graph with 9 colors...
Trying to color graph with 10 colors...
Trying to color graph with 11 colors...
Trying to color graph with 12 colors...
Trying to color graph with 13 colors...
Trying to color graph with 14 colors...

14 coloring found! Exiting...
```

**Comment by shah314** [comment] 2019-09-30 23:24
@jedbrown I think I have addressed all of your suggestions.

The code now has several command line arguments that can be passed in. I have mentioned this in both README.md files in the tests as well as the root directories.

I have added an "automatedtests.sh" file that will output if the tests passed for both heuristics as well as the backtracking algorithms.

I created a parameters.md file that explains all the parameters that can be passed in.

About the shell scripts being not executable, I have mentioned that the user needs to run a "chmod u+x *.sh" to run the shell scripts. This is the only way I see how to do this. I don't think git propagates the permissions when a file is uploaded.

**Comment by jedbrown** [comment] 2019-10-05 17:00
I don't understand what environment you're on that can't commit mode changes, but it's fully supported by Git; here's an example PR:
https://github.com/shah314/graphcoloring/pull/2
Edit: I see you merged this, but the docs talking about using `chmod` should also be updated.

I also demonstrated more idiomatic markdown formatting [here](https://github.com/jedbrown/graphcoloring/blob/jed/markdown/parameters.md), to be compared with the [HTML-in-markdown](https://github.com/shah314/graphcoloring/blob/master/parameters.md). The "for heuristics" and "for backtracking" parts should be organized more clearly. Which options apply to which executable?

I think we should talk about whether a standalone executable is the primary research utility. In my research world, a potential user would vastly prefer to call a library, passing the data in-memory, versus write it to file and call a standalone executable. If you strongly believe that standalone is the only use case that needs to be supported, we can take it to review and get opinions of reviewers, but I think there is high likelihood that they will want an in-memory interface. I see from `Tests.java` that there is a library interface (though perhaps still file-based and certainly clunky by putting numbers into strings to be parsed), but there is no API documentation. It believe it is standard to write API docs using Javadoc. The resulting generated documentation could be published using GitHub pages, for example.

When called as a library, it must be possible (and preferably default) to print nothing to the screen. Imagine, for example, that someone writes a NetworkX binding to your library and using it becomes an option to their graph coloring interfaces.

In a command-line interface, one would normally expect `--help` to give more detailed usage information. I believe it is standard (also in Java) to use a command-line parsing library such as [Apache CLI](https://commons.apache.org/proper/commons-cli/) or [args4j](http://args4j.kohsuke.org/), which helps provide useful diagnostics and improve reliability.

I'm not familiar with Java community standards, but you should investigate how a command-line utility is normally packaged/distributed. If successful, your software may find it into distribution repositories such as Debian/Ubuntu, Homebrew, and Anaconda. It makes sense to research and choose an installation model now (versus asking the user to copy files around and invoke `javac` and `java` directly).

On testing, thank you for adding the affirmative check. Do you object to setting up continuous integration or is it just an unfamiliar technology?

**Comment by shah314** [comment] 2019-10-05 23:16
@jedbrown Thank you for the thorough review.

I have made some major changes.

The build now uses Maven (which is standard for Java code).

I have added API documentation. The user can now call the code using a Java API by adding the jar in the classpath (api.md).

I have converted all md files to markdown instead of using HTML.

I have updated the tests to use Maven instead of directly using javac.

I have added a dependency on Apache Commons CLI which will be built in to the uber jar using Maven. I have also added a "-help" and -h" command line arguments to print the help screen on the arguments. Running the code without any arguments will print the help screen.

Please do a git pull and review and verify. 

Thank you.

**Comment by jedbrown** [comment] 2019-10-06 01:44
Excellent, I think really improves the research utility and distribution options. What versions of JDK are meant to be supported? I'm getting this:
```
$ mvn package                                      
[INFO] Scanning for projects...                                                                
[INFO]                                                                                         
[INFO] -----------------------< com.gcol:graphcoloring >-----------------------
[INFO] Building graphcoloring 1.7
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ graphcoloring ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/jed/joss/graphcoloring/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ graphcoloring ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 14 source files to /home/jed/joss/graphcoloring/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by shah314** [comment] 2019-10-06 03:05
I changed pom.xml with the maven compiler version. I think JDK version 1.8 should work fine. Please do a git pull and try again. Thanks.

**Comment by jedbrown** [comment] 2019-10-06 03:24
Works, though I think you need the following to suppress a warning.
```
diff --git i/pom.xml w/pom.xml
index 2a6cb04..7563c12 100644
--- i/pom.xml
+++ w/pom.xml
@@ -30,6 +30,7 @@
             </plugin>
             <plugin>
                 <artifactId>maven-compiler-plugin</artifactId>
+                <version>3.8.1</version>
                 <configuration>
                     <source>1.8</source>
                     <target>1.8</target>
```

**Comment by jedbrown** [comment] 2019-10-06 03:46
@gabrielspadon @sonal-raj @camillescott @hooman650 :wave: Would you be available to review this submission for JOSS?

**Comment by shah314** [comment] 2019-10-26 16:27
@jedbrown Any further thoughts on the review process? Thanks.

**Comment by HaoZeke** [comment] 2019-10-29 11:47
Hi @shah314 and @jedbrown, I'd be willing to look this over, as I have some time now, if it would be helpful.

**Comment by jedbrown** [comment] 2019-10-29 18:02
Thanks, @HaoZeke! I'll start the review now and add a second reviewer (responses to my offline inquiries have been going slowly).

**Comment by jedbrown** [comment] 2019-10-29 18:02
@whedon add HaoZeke as reviewer

**Comment by whedon** [comment] 2019-10-29 18:02
OK, HaoZeke is now a reviewer

**Comment by jedbrown** [comment] 2019-10-29 18:03
@whedon start review

**Closed** 2019-10-29 18:03 UTC
Labels: Java, TeX, pre-review
