### ISSUE TITLE
[REVIEW]: OpenRepGrid.ic: A software for Interpretive Clustering

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3292] opened 2021-05-19 01:30 UTC
**Submitting author:** @markheckmann (<a href="http://orcid.org/0000-0002-0736-7417">Mark Heckmann</a>)
**Repository:** https://github.com/markheckmann/OpenRepGrid.ic
**Branch with paper.md** (empty if default branch):  joss
**Version:** v0.6.1_JOSS_submission
**Editor:** @gkthiruvathukal
**Reviewers:** @aj2duncan, @brunaw
**Archive:** 10.5281/zenodo.7655618

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/72006e596f7c6aac5d315569b417fb29/status.svg)](https://joss.theoj.org/papers/72006e596f7c6aac5d315569b417fb29)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/72006e596f7c6aac5d315569b417fb29"><img src="https://joss.theoj.org/papers/72006e596f7c6aac5d315569b417fb29/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/72006e596f7c6aac5d315569b417fb29/status.svg)](https://joss.theoj.org/papers/72006e596f7c6aac5d315569b417fb29)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/markheckmann/OpenRepGrid.ic" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@aj2duncan & @brunaw, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @gkthiruvathukal know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/markheckmann/OpenRepGrid.ic">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@markheckmann) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/markheckmann/OpenRepGrid.ic">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@markheckmann) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [ ] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [ ] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2021-05-19 01:31
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @aj2duncan, @brunaw it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-05-19 01:31
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.04 s (453.2 files/s, 82699.6 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
R                               10            366            327           1661
HTML                             1              3              0            553
Markdown                         3             83              0            143
Rmd                              2             73            136             56
YAML                             3             17              8             41
-------------------------------------------------------------------------------
SUM:                            19            542            471           2454
-------------------------------------------------------------------------------


Statistical information for the repository 'b59425c4d12ec552f5c00de5' was
gathered on 2021/05/19.
No commited files with the specified extensions were found.
```

**Comment by whedon** [comment] 2021-05-19 01:31
PDF failed to compile for issue #3292 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by markheckmann** [comment] 2021-05-19 09:53
@whedon generate pdf from branch joss

**Comment by whedon** [comment] 2021-05-19 09:53
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-05-19 09:53
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03292/joss.03292/10.21105.joss.03292.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03292/joss.03292/10.21105.joss.03292.pdf) :page_facing_up: :point_left:

**Comment by brunaw** [comment] 2021-05-27 15:35
Dear @markheckmann,

Here are a few of my initial comments/notes about the paper and code. Could you review and give any answers/solutions for what I've pointed out? After that, I'll do my review checklist for your submission: 

- The paper seems to be well written in general 

- I am a little bit confused about whether the focus of the paper is on the shiny app or the IC implementation as an `R` package. Is the IC implementation new and the shiny app is there for demonstration purposes only? I think that's happening because everything is being described as the 'software for IC' 

- In the "Repertory Grid Technique" section, the transition between talking about the data and the results shown in the plot could be smoother (lines 36 and 37). The text seems to assume that the reader is familiar with what is usually plotted in Figure 1

- The figures have two 'Figure x' labels

- I recommend not using terms such as "is shown below" and use the figure numbers instead

- The https://ic.openprepgrid.org/ URL couldn't be reached here (as it is in the paper), but http://ic.openrepgrid.org/ works correctly

- Likewise, the docker image needs a user login. Is that the standard for all Docker users or only allowed users can see the app?

- The shiny app won't open locally to me due to functions not being correctly loaded:
`> Error in rightSidebar: could not find function "rightSidebar"`
  
- Not all functions are fully documented, for example:
  - `count_matches()` , `replace_one()`

I understand that those might be just helper functions, but ideally, they should be properly documented and organized like the rest of the code 
 
- There are a few 'random' lines of comments in the `R` files (e.g. 02-calculate.R file, line 142)

Thank you, 

Bruna

**Comment by whedon** [comment] 2021-06-02 01:31
:wave: @aj2duncan, please update us on how your review is going (this is an automated reminder).

**Comment by aj2duncan** [comment] 2021-06-10 14:42
Apologies @gkthiruvathukal , I'm now ready to start the review but appear to have missed the timings on the invitation. Could it possibly be sent again? Sorry.

**Comment by aj2duncan** [comment] 2021-06-11 08:12
Sorry (again) @gkthiruvathukal I am still unable to edit the checklist. No rush as I'm happy to proceed with the review and catch up on the checklist later.

**Comment by markheckmann** [comment] 2021-06-11 08:39
@aj2duncan : Thanks, I will have a look at it. Could you add info which OS and which R version you use? Best would be a copy of  the `sessionInfo()` output. Thanks!

**Comment by danielskatz** [comment] 2021-06-11 12:18
@whedon re-invite @aj2duncan as reviewer

**Comment by whedon** [comment] 2021-06-11 12:18
OK, the reviewer has been re-invited.

@aj2duncan please accept the invite by clicking this link: https://github.com/openjournals/joss-reviews/invitations

**Comment by danielskatz** [comment] 2021-06-11 12:18
👋 @aj2duncan - ☝️ this should enable you to check the boxes...

**Comment by markheckmann** [comment] 2021-06-26 19:56
@aj2duncan : I fixed the issue you posted on github. There were some breaking changes in a package dep and it should work again now. Thanks!

**Comment by aj2duncan** [comment] 2021-06-26 20:39
@markheckmann, great - thanks. I'll get back to testing the app. @brunaw, has made some queries/comments☝️, have you had a chance to look at any of them?

Thanks again for fixing the app. I'll get back to you as soon as I can.

**Comment by markheckmann** [comment] 2021-06-27 20:19
Dear @brunaw,

thanks for your comments and apologies for the late reply!  I inserted my answeres to your comments below. There is a new version of the manuscript available now in which I made the changes accordingly.

Thanks for your time and effort!

Best wishes
Mark

________

> I am a little bit confused about whether the focus of the paper is on the shiny app or the IC implementation as an R package. Is the IC implementation new and the shiny app is there for demonstration purposes only? I think that's happening because everything is being described as the 'software for IC'

The paper is on the shiny app. It is the only software which implements the IC method. The software is necessary as the steps of the IC procedure are too laborious to be done by hand. So researchers will need a software to do it.  We tried to explain this in the *statement of need* section. Please let me know if this is still too unclear and if so, could you maybe indicate which parts you find confusing? 
	
> In the "Repertory Grid Technique" section, the transition between talking about the data and the results shown in the plot could be smoother (lines 36 and 37). The text seems to assume that the reader is familiar with what is usually plotted in Figure 1

I rearranged and slightly extended the section to make it more readable and give the reader a better understandiong what he/she sees in Figure 1. The paragraph is supposed to give readers who are unfamiliar with repertory grids a rough idea about the resulting data structure. A more thorough introduction to the RGT is, however, beyond the scope of this paper, I think.

> The figures have two 'Figure x' labels

Thanks, I corrected this.
	
> I recommend not using terms such as "is shown below" and use the figure numbers instead

Thanks. I changed this in the latest version of the manuscript.

> The https://ic.openprepgrid.org/ URL couldn't be reached here (as it is in the paper), but http://ic.openrepgrid.org/ works correctly

I changed the url to `http`. The app is currently hosted on a free tier shinyapps.io account, where SSL is not supported. 
I plan to move it to my own server with SSL support in the future. Then both protocols (http and https) will be supported, so http seems to be the best choice for the manuscript.

> Likewise, the docker image needs a user login. Is that the standard for all Docker users or only allowed users can see the app?

The docker image is public, i.e. anyone can pull and use it without authentication.  Assuming you have the docker deamon installed and running, just type `docker pull markheckmann/openrepgrid.ic` into the console/terminal and it should pull the latest image from dockerhub. I also added instructions on how to run the image locally under the [dockerhub link](https://hub.docker.com/repository/docker/markheckmann/openrepgrid.ic) in the manuscript.

> The shiny app won't open locally to me due to functions not being correctly loaded: Error in rightSidebar: could not find function "rightSidebar"

This is the same issue @aj2duncan had and due to breaking changes in a package dep. I fixed it in [release v0.5.1](https://github.com/markheckmann/OpenRepGrid.ic/releases/tag/v0.5.1). 

> Not all functions are fully documented, for example: count_matches() , replace_one() I understand that those might be just helper functions, but ideally, they should be properly documented and organized like the rest of the code

All functions, including all helpers, are documented know.

> There are a few 'random' lines of comments in the R files (e.g. 02-calculate.R file, line 142)

I cleaned up the code. There are a few commented out lines of R code which I want to keep where I added an extra comment why they are there.

**Comment by markheckmann** [comment] 2021-06-27 20:20
@whedon generate pdf from branch joss

**Comment by whedon** [comment] 2021-06-27 20:20
```
Attempting PDF compilation from custom branch joss. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-06-27 20:20
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03292/joss.03292/10.21105.joss.03292.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03292/joss.03292/10.21105.joss.03292.pdf) :page_facing_up: :point_left:

**Comment by aj2duncan** [comment] 2021-08-20 20:22
Hi @markheckmann,

My apologies for the delay in getting back to this review. I'm happy with the paper and I think there are just a few minor things for you to address before I can complete the review. 

- Can you confirm which of the [OSI approved](https://opensource.org/licenses/alphabetical) licenses you are using? 
- The documentation in the repository/app is missing some of the detail that is in your paper. This includes the statement of need, functionality documentation and community guidelines. I think that the detail in the paper is fine but could be completely or partially replicated in the repo. Most of the functionality is documented in the app itself but it took me a minute to work out that "The results of the IC analysis are not displayed interactively but are included in an MS Excel file that can be generated and downloaded." as stated in the paper. It is implied by the popup in the app itself but most shiny users would probably expect the graph to be drawn in the app itself. 
- The step of loading `library(OpenRepGrid.ic)` before running `ic()` is missing from the repo README. As above, it is present in the paper. 

Please let me know if you've got any queries or comments about any of this. 

Thanks,

Andrew

**Comment by gkthiruvathukal** [comment] 2021-10-04 15:29
@whedon commands

**Comment by whedon** [comment] 2021-10-04 15:29
Here are some things you can ask me to do:

```
# List all of Whedon's capabilities
@whedon commands

# Assign a GitHub user as the sole reviewer of this submission
@whedon assign @username as reviewer

# Add a GitHub user to the reviewers of this submission
@whedon add @username as reviewer

# Re-invite a reviewer (if they can't update checklists)
@whedon re-invite @username as reviewer

# Remove a GitHub user from the reviewers of this submission
@whedon remove @username as reviewer

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

# Change editorial assignment
@whedon assign @username as editor

# Set the software archive DOI at the top of the issue e.g.
@whedon set 10.0000/zenodo.00000 as archive

# Set the software version at the top of the issue e.g.
@whedon set v1.0.1 as version

# Open the review issue
@whedon start review

EDITORIAL TASKS

# All commands can be run on a non-default branch, to do this pass a custom 
# branch name by following the command with `from branch custom-branch-name`.
# For example:

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Remind an author or reviewer to return to a review after a
# certain period of time (supported units days and weeks)
@whedon remind @reviewer in 2 weeks

# Ask Whedon to do a dry run of accepting the paper and depositing with Crossref
@whedon recommend-accept

# Ask Whedon to check the references for missing DOIs
@whedon check references

# Ask Whedon to check repository statistics for the submitted software
@whedon check repository

EiC TASKS

# Invite an editor to edit a submission (sending them an email)
@whedon invite @editor as editor

# Reject a paper
@whedon reject

# Withdraw a paper
@whedon withdraw

# Ask Whedon to actually accept the paper and deposit with Crossref
@whedon accept deposit=true

```

**Comment by gkthiruvathukal** [comment] 2021-10-04 15:30
@markheckmann Is there any update? See @aj2duncan's comment above.

**Comment by markheckmann** [comment] 2021-10-05 19:32
Hi @gkthiruvathukal , sorry for my delay. I have not found the time yet to make the changes as suggested by @aj2duncan. Thanks again @aj2duncan for your comments! Things will slow down here in 1,5 weeks and iI will submit a new version by the end of October. I hope that this is okay for everyone. Best wishes Mark

**Comment by gkthiruvathukal** [comment] 2021-10-16 16:28
@markheckmann This is fine. We'll look for your follow-up by the end of October.

**Comment by markheckmann** [comment] 2021-11-04 08:37
Hi, I need some more time and will upload the changes this coming weekend. Bests Mark

**Comment by gkthiruvathukal** [comment] 2021-11-04 22:21
Hi @markheckmann. No problem. Please take your time.

**Comment by gkthiruvathukal** [comment] 2022-01-16 15:42
@markheckmann  Can you please provide an update on when you'll be able to make the changes?

@brunaw Have you also had a chance to review the submission? I guess with the significant changes required, it may make sense to wait until @markheckmann has made the changes proposed by @aj2duncan.

**Comment by markheckmann** [comment] 2022-01-23 21:04
Dear @gkthiruvathukal , thanks for following up on this! I will definitely be able to make the changes by the end of February.

**Comment by gkthiruvathukal** [comment] 2022-03-08 04:17
@markheckmann It's amazing how February always seems to come and go without a warning.  Can you let us know how things are going with your changes? If you need more time, no problem!

**Comment by markheckmann** [comment] 2022-03-10 19:41
@gkthiruvathukal: well, what can I say 🙈🙈🙈. I have found time to implement some of the changes. But especially the request to add an interactive analysis output (not only the static Excel analysis to download) will require some more time. I have two weeks of holiday in April, in which I am confident to find enough time to finish the project. So yes, more time would be appreciated.

**Comment by gkthiruvathukal** [comment] 2022-04-19 02:54
@markheckmann  Can you give me an update? I'd like to move forward on acceptance soon. Having Excel download does not sound difficult. At the same time, it does not seem "mission-critical" either. If you have acted upon all other suggestions, I think we could move forward here. Can you let me know?

**Comment by markheckmann** [comment] 2022-04-24 21:39
@gkthiruvathukal  I found some time to work on it and will finish the changes in the next 1 or 2 days, so we can move ahead.

**Comment by gkthiruvathukal** [comment] 2022-04-24 23:09
Thanks for the update, @markheckmann!

**Comment by markheckmann** [comment] 2022-05-08 19:29
Dear all, 

thanks for your patience and my apologies with regard to the timeliness of our revisions. 

@aj2duncan: please find below our answers to your comments:

> Can you confirm which of the [OSI approved](https://opensource.org/licenses/alphabetical) licenses you are using?

The software uses the MIT license. The license statement is now contained in the package’s DESCRIPTION file. A copy of the MIT license itself is additionally found in the root folder of the  R package repo.
 
> The documentation in the repository/app is missing some of the detail that is in your paper. This includes the statement of need, functionality documentation and community guidelines. I think that the detail in the paper is fine but could be completely or partially replicated in the repo. 

As you suggested, we now replicated the text from the paper (with minor modifications only) directly in the README of the repo.

> Most of the functionality is documented in the app itself but it took me a minute to work out that "The results of the IC analysis are not displayed interactively but are included in an MS Excel file that can be generated and downloaded." as stated in the paper. It is implied by the popup in the app itself but most shiny users would probably expect the graph to be drawn in the app itself.

We now added a new info box at the top of the analysis tab of the software explaining that the final result of the analysis is a downloadable file, so the user will directly see it. We also discussed adding interactivity directly in the tool, but came to the conclusion, that the benefits would be minor. After the quantitative analysis, a researcher must thoroughly look at the results first and make a qualitative interpretation. This process takes quite some time and iterations are rather slow, so we decided against the interactive display of results.

> The step of loading library(OpenRepGrid.ic) before running ic() is missing from the repo README. As above, it is present in the paper.

We now added the line to the repo README.md

@brunaw: We already answered your comments above.


**Further changes compared to the last version**:

* We fixed an issue reported by a user (https://github.com/markheckmann/OpenRepGrid.ic/issues/6) with regard to the output of the intermediate steps of the analysis.
* We added mouse-over pop-ups to the majority of buttons, checkboxes, etc. for a smoother user experience

![image](https://user-images.githubusercontent.com/152927/167312516-db62704e-a4c7-41ec-827e-af06221f6279.png)

Please let me know if you have any further comments / see need for further changes or if we are ready to move ahead. The package version 0.6 will hit CRAN in a few days if you feel comfortable with the current status.

Thanks again!
Mark

**Comment by markheckmann** [comment] 2022-05-10 10:18
@whedon generate pdf

**Comment by markheckmann** [comment] 2022-05-10 10:18
@whedon generate pdf from branch joss

**Comment by markheckmann** [comment] 2022-05-10 10:21
@editorialbot set  joss as branch
@editorialbot generate pdf

**Comment by markheckmann** [comment] 2022-05-10 10:21
@editorialbot generate pdf

**Comment by aj2duncan** [comment] 2022-05-13 09:01
Hi @markheckmann, thanks for this. I will try to check them in detail over the weekend and get back to you.

**Comment by aj2duncan** [comment] 2022-05-15 20:26
Hi @markheckmann, 

Thanks for making those alterations. I think everything is good to go @gkthiruvathukal. Please let me know if you need anything else from me. 

All the best. 

Andrew

**Comment by gkthiruvathukal** [comment] 2022-05-18 03:43
@aj2duncan Thank you for your feedback.
For me to move forward (with acceptance), I need @brunaw to sign off and complete their checklist atop this issue thread.
Once @brunaw completes the checklist and follows up here, we should be good to go. 
From what I can tell, you have done everything asked of you, @markheckmann!

**Comment by gkthiruvathukal** [comment] 2022-07-12 17:39
@brunaw it works perfectly! Thank you!

**Comment by gkthiruvathukal** [comment] 2022-07-16 22:26
@brunaw Thank you!

**Comment by brunaw** [comment] 2022-07-17 03:11
Thanks all, I've finished my review now, my apologies for the delay. I only have a few quick suggestions/comments:

- Because this is a shiny app, I think it would be nice to have a gif in the package README file showing how to use the app instead of just a screenshot of the interface, or at least a few more screenshots indicating the steps to run the analysis
- Also on the exemplification, it woul be nice to have an 'example analysis' in the shiny app (as another tab), because currently, we can only see any results if we input our own data, which might be a bit confusing for someone who is exploring the app and maybe doesn't have their own data yet 
- I found some comments in the code that are in German. I think it would be better to at least have them translated to english, so when people are trying to understand what the functions do or contribute to the work, they won't have this language barrier  
- The tests seemed a bit incomplete to me, it doesn't look like all functions are being tested, just the app function and the file format. Is this enough to test the whole code?

**Comment by gkthiruvathukal** [comment] 2022-07-30 22:58
@markheckmann Can you please follow up on @brunaw's feedback and let us know when you might be able to act upon it?

**Comment by markheckmann** [comment] 2022-08-01 08:40
@brunaw Thanks a lot for the review!
@gkthiruvathukal I am on summer vacation and traveling till the 24. of August. I can finish everything by the first week of September if that is okay.

**Comment by markheckmann** [comment] 2022-08-28 14:57
Hi @brunaw, @gkthiruvathukal, 

I updated the package to `v0.6.1` (not yet on CRAN) making the following changes:

* added an animated gif to the README, that shows how the software works
* all German comments are translated to English now
* no need to bring you own data anymore.  On the `Analysis` tab, you can now  simply press the `Load Sylvias's sample grid` button to load a sample dataset tab. The data can also be downbloaded as an Excel file (this is not new) to be used as a template so store your own grid data.
* there is a new tab `Sample output` showing extracts of the ouput fpr Sylvia's dataset
* Several additional tests raised the test coverage to 93% (from 56%)

I will upload the package to CRAN if there are no further change requirements from your side. Please let me know. 
Thanks!

**Comment by markheckmann** [comment] 2022-10-25 21:11
FYI: Just pushed the latest package version `v0.6.1` to CRAN: https://cran.rstudio.com/web/packages/OpenRepGrid.ic/index.html. Please, let me know in case you need anything else to proceed.
Thanks!

**Comment by markheckmann** [comment] 2022-12-16 16:24
Dear @gkthiruvathukal please let me know if anything else is needed to proceed. Thanks!

**Comment by gkthiruvathukal** [comment] 2022-12-17 00:12
Hi @markheckmann. I have been down with an eye infection but am hopeful I can finalize it this weekend.

**Comment by arfon** [comment] 2023-02-19 15:51
:wave: folks. I'm stepping in here to help out @gkthiruvathukal . This submission looks ready to go from my standpoint so...

@markheckmann – At this point could you:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

I can then move forward with recommending acceptance of the submission.

**Comment by markheckmann** [comment] 2023-02-20 05:59
Thanks for jumping in, @arfon . As requested, I prepared the following:

- New GitHub release tag: [v0.6.1_JOSS_submission](https://github.com/markheckmann/OpenRepGrid.ic/releases/tag/v0.6.1_JOSS_submission)
- Zenodo archive: <https://zenodo.org/record/7655618>
- Metadata was checked.
- DOI: 10.5281/zenodo.7655618

Thanks!

**Comment by arfon** [comment] 2023-02-20 10:44
@editorialbot set 10.5281/zenodo.7655618 as archive

**Comment by arfon** [comment] 2023-02-20 10:44
@editorialbot set v0.6.1_JOSS_submission as version

**Comment by arfon** [comment] 2023-02-20 10:45
@editorialbot recommend-accept

**Comment by arfon** [comment] 2023-02-20 10:52
@tarleb – any chance you could help with this error above from the XML validator? I'm not sure what the issue is here. Also, is there a way to see the intermediate files associated with the GitHub Action workflow @xuanxu ?

@markheckmann – while we wait for a couple of issues to be addressed here, did you check if any of those DOIs suggested above are correct for your references?

**Comment by xuanxu** [comment] 2023-02-20 11:06
The metadata files can be found in the generated [pull request](https://github.com/openjournals/joss-papers/pull/3984).

The error points to lines [104](https://github.com/openjournals/joss-papers/pull/3984/files#diff-51b7cc59f49cb5eb1a03af594c9a97b88be2e6ee70ddd02eeef166216ff71590R104) and [201](https://github.com/openjournals/joss-papers/pull/3984/files#diff-51b7cc59f49cb5eb1a03af594c9a97b88be2e6ee70ddd02eeef166216ff71590R201) of the JATS metadata file.

**Comment by tarleb** [comment] 2023-02-20 13:33
Thanks @xuanxu, I second that and the PR should fix it.

Background: References are automatically linked to the respective entry in the bibliography. Placing a reference within a link thus leads to nested links, which is not allowed in most formats. I wonder if this should be fixed in pandoc, or whether we should add a filter to check for this case.

**Comment by markheckmann** [comment] 2023-02-20 13:54
@editorialbot generate pdf

**Comment by markheckmann** [comment] 2023-02-20 14:06
@xuanxu Thanks for the fix! :)  

@arfon, @xuanxu : I checked the suggested DOIs and added correct ones to the the .bib file. 

I also checked the links in the new PDF and it looks good.

Thanks!

**Comment by arfon** [comment] 2023-02-21 09:41
> The metadata files can be found in the generated https://github.com/openjournals/joss-papers/pull/3984.

Thanks @xuanxu – I'm afraid I hadn't realized the PR was still opened even when these errors happen...

**Comment by arfon** [comment] 2023-02-21 09:41
@editorialbot recommend-accept

**Comment by arfon** [comment] 2023-02-21 09:53
One more minor typo to fix @markheckmann: https://github.com/markheckmann/OpenRepGrid.ic/pull/10

**Comment by markheckmann** [comment] 2023-02-21 11:03
> One more minor typo to fix @markheckmann: [markheckmann/OpenRepGrid.ic#10](https://github.com/markheckmann/OpenRepGrid.ic/pull/10)

@arfon : Thanks, PR is merged now

**Comment by arfon** [comment] 2023-02-21 12:25
@editorialbot recommend-accept

**Comment by arfon** [comment] 2023-02-21 12:56
@editorialbot accept

**Comment by arfon** [comment] 2023-02-21 13:57
@aj2duncan, @brunaw – many thanks for your reviews here and to @gkthiruvathukal  for editing this submission! JOSS relies upon the volunteer effort of people like you and we simply wouldn't be able to do this without you ✨ 

@markheckmann  – your paper is now accepted and published in JOSS :zap::rocket::boom:

**Closed by arfon** 2023-02-21 13:57 UTC
Labels: accepted, review, R, HTML, recommend-accept, published, Track: 5 (DSAIS)

**Comment by markheckmann** [comment] 2023-02-21 17:13
@arfon @gkthiruvathukal @brunaw @aj2duncan @tarleb @xuanxu : Thanks again to all of you for editing and reviewing our submission!  👏👏👏 🌻🌻🌻
