### ISSUE TITLE
[REVIEW]: PopMedNet: A scalable and extensible open-source informatics platform designed to facilitate the implementation and operation of distributed health data networks

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#4062] opened 2022-01-13 23:10 UTC
**Submitting author:** @ddeehere (<a href="http://orcid.org/0000-0001-7021-6227">Daniel Dee</a>)
**Repository:** https://github.com/PopMedNet-Team/popmednet
**Branch with paper.md** (empty if default branch): 
**Version:** PMN-2021.6-JOSS
**Editor:** @danielskatz
**Reviewers:** @jhancock4d, @lrasmus
**Archive:** 10.5281/zenodo.6325732

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b/status.svg)](https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b"><img src="https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b/status.svg)](https://joss.theoj.org/papers/46047e93810d34dbc9d4f389fa55860b)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/PopMedNet-Team/popmednet.git" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@jhancock4d & @lrasmus, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @jhancock4d
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/PopMedNet-Team/popmednet.git">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PopMedNet-Team/popmednet.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ddeehere) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] #4119
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @lrasmus
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/PopMedNet-Team/popmednet.git">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/PopMedNet-Team/popmednet.git">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@ddeehere) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2022-01-13 23:10
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @jhancock4d, @lrasmus it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2022-01-13 23:11
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.13063/2327-9214.1213 is OK
- 10.1097/MLR.0b013e3181d9919f is OK
- 10.17294/2330-0698.1149 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2022-01-13 23:11
Wordcount for `paper.md` is 740

**Comment by danielskatz** [comment] 2022-01-13 23:15
@jhancock4d and @lrasmus - Thanks for agreeing to review this submission.
This is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

Please read the first couple of comments in this issue carefully, so that you can accept the invitation from JOSS and be able to check items, and so that you don't get overwhelmed with notifications from other activities in JOSS.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#4062` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if either of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@danielskatz) if you have any questions/concerns.

**Comment by whedon** [comment] 2022-01-13 23:20
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.04062/joss.04062/10.21105.joss.04062.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.04062/joss.04062/10.21105.joss.04062.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment] 2022-01-27 23:10
:wave: @jhancock4d, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment] 2022-01-27 23:10
:wave: @lrasmus, please update us on how your review is going (this is an automated reminder).

**Comment by danielskatz** [comment] 2022-02-01 17:45
@jhancock4d - thanks!

Re testing, see https://joss.readthedocs.io/en/latest/review_criteria.html#tests
Does this meet the "OK" there?

**Comment by danielskatz** [comment] 2022-02-07 15:08
@jhancock4d - I note you didn't check off the license item - can you?  Or is there a problem?

**Comment by danielskatz** [comment] 2022-02-07 15:08
@lrasmus - It doesn't look like you've gotten started on your checklist. Are there any problems I can help with?

**Comment by danielskatz** [comment] 2022-02-07 15:11
@jhancock4d - can you say a bit more? Is this something where you are unsure about what is needed, or where you know what's needed and are unsure if it's being met?  Is https://joss.readthedocs.io/en/latest/review_criteria.html#tests helpful?

**Comment by lrasmus** [comment] 2022-02-08 23:15
@danielskatz - I am sorry, this was me not being able to balance priorities w/ projects at work.  Things have cleared up, will work on it now and get done ASAP.  Very sorry for the delays.

**Comment by danielskatz** [comment] 2022-02-09 00:44
@lrasmus - no worries - issues come up for all of us

**Comment by lrasmus** [comment] 2022-02-09 21:33
Status update - unchecked items are pending responses from open issues in source repo.

**Comment by lrasmus** [comment] 2022-02-14 21:48
@jhancock4d - I'm working with the authors via https://github.com/PopMedNet-Team/popmednet/issues/38 on setup instructions for running the unit tests.  Curious if you had a CDM database you used for the tests, if you used SynPuf or something else?  Am going to try to get this going on my own, and I know the authors are working on instructions.

**Comment by jhancock4d** [comment] 2022-02-14 21:51
> @jhancock4d - I'm working with the authors via [PopMedNet-Team/popmednet#38](https://github.com/PopMedNet-Team/popmednet/issues/38) on setup instructions for running the unit tests. Curious if you had a CDM database you used for the tests, if you used SynPuf or something else? Am going to try to get this going on my own, and I know the authors are working on instructions.

I just ran the migrations which got me a blank database and worked from there to setup everything by hand.  (I have an SQL DB server laying around)

The setup of the database probably needs better documentation. However, my main issue with testing is that there aren't very MANY tests, not that they don't work (they seem to)

**Comment by lrasmus** [comment] 2022-02-15 23:49
@danielskatz - thank you for your ongoing patience.  I am about ready to sign off.  I have asked the authors to add a 'State of the Field' to the paper, and then I think this meets all requirements.

@jhancock4d - with your assessment of tests, were you able to run code coverage (I was not)?  I was able to get 720 passed tests with the test suite they provided.  They seem more like integration tests than unit tests, but would consider it 'OK' for the purposes of the evaluation.  Curious if there were specific areas you thought needed more testing?

**Comment by jhancock4d** [comment] 2022-02-16 13:15
@irasmus The integration tests are actually a feature not a bug in this case I would say because unit tests on a project that deals with data that would use mocks wouldn't be useful.

Code coverage is relatively lowish from what I can tell (I can't get coverlet to spit out data on it).  I think it's fine for this purpose, but in general it would be nice to see 80%+ code coverage in the future with coverlet commands that would do code coverage reporting along with the testing.

**Comment by danielskatz** [comment] 2022-02-21 16:24
👋 @ddeehere - I think we're just waiting for you to address https://github.com/PopMedNet-Team/popmednet/issues/39 at this point, and I see there that you are working on it. Please let us know when there's something for the reviewers to check.

**Comment by ddeehere** [comment] 2022-02-22 18:18
@danielskatz @lrasmus I added a section "Comparison with i2b2 and SHRINE" for "State of the Field" in paper.md.

**Comment by lrasmus** [comment] 2022-02-22 18:40
Thank you @ddeehere!  

@danielskatz - I've signed off on all checklist items, I think this is in good shape and set to go.

**Comment by danielskatz** [comment] 2022-02-22 18:45
👋 @jhancock4d - can you confirm that you are ready for this to be published?

**Comment by danielskatz** [comment] 2022-02-22 18:46
@whedon check references

**Comment by danielskatz** [comment] 2022-02-22 18:46
@whedon generate pdf

**Comment by jhancock4d** [comment] 2022-02-22 18:46
@danielskatz Confirmed!

**Comment by whedon** [comment] 2022-02-22 18:47
PDF failed to compile for issue #4062 with the following error: 
```
 Error reading bibliography file paper.bib:
(line 36, column 91):
unexpected "a"
expecting space, ",", white space or "}"
Looks like we failed to compile the PDF

```

**Comment by danielskatz** [comment] 2022-02-22 18:50
@ddeehere - I think https://github.com/PopMedNet-Team/popmednet/pull/40 will fix the building issue, along with some formatting

**Comment by danielskatz** [comment] 2022-02-23 13:54
@ddeehere - we're quite close to done; I hope you can accept this ☝️ PR soon, then I can proofread and move this to acceptance.

**Comment by ddeehere** [comment] 2022-02-23 14:02
> @ddeehere - we're quite close to done; I hope you can accept this ☝️ PR soon, then I can proofread and move this to acceptance.

@danielskatz Just merged the PR. Sorry failed to realize I have to do something. Thanks for reminder.

**Comment by danielskatz** [comment] 2022-02-23 14:12
@editorialbot check references

**Comment by danielskatz** [comment] 2022-02-23 14:14
@editorialbot generate pdf

**Comment by danielskatz** [comment] 2022-02-23 14:17
@ddeehere - can you also merge https://github.com/PopMedNet-Team/popmednet/pull/41 - this might have been my error; if so, sorry

**Comment by danielskatz** [comment] 2022-02-23 14:21
@editorialbot generate pdf

**Comment by danielskatz** [comment] 2022-02-23 14:25
@ddeehere - sorry, one more error - please merge https://github.com/PopMedNet-Team/popmednet/pull/42

**Comment by ddeehere** [comment] 2022-02-23 14:29
@danielskatz Merged

**Comment by danielskatz** [comment] 2022-02-23 14:29
@editorialbot generate pdf

**Comment by ddeehere** [comment] 2022-02-23 14:52
@danielskatz Thanks for catching that. Merged.

**Comment by danielskatz** [comment] 2022-02-23 14:53
@editorialbot generate pdf

**Comment by danielskatz** [comment] 2022-02-23 14:55
@ddeehere - please add the DOI mentioned above to your bib file

**Comment by danielskatz** [comment] 2022-02-23 16:13
@editorialbot check references

**Comment by danielskatz** [comment] 2022-02-23 16:33
@ddeehere - proofreading the paper PDF, I found a couple of things that I suggest changing, as shown in https://github.com/PopMedNet-Team/popmednet/pull/44  Please merge this if you agree with these changes.

**Comment by ddeehere** [comment] 2022-02-28 20:11
> @ddeehere - Any news on this?

@danielskatz It processed for a long time and failed today. We are still investigating.

**Comment by ddeehere** [comment] 2022-02-28 20:14
Zenodo appears to still be processing the last release.

**Comment by danielskatz** [comment] 2022-02-28 20:29
You might want to contact their support - this should be very fast when it works, which it always has in my experience

**Comment by ddeehere** [comment] 2022-03-02 19:52
> You might want to contact their support - this should be very fast when it works, which it always has in my experience

@danielskatz Just want to let you know that we are still looking into this. We have sent a support request to Zenodo.

**Comment by danielskatz** [comment] 2022-03-02 19:58
👋 @lnielsen - can you help us debug/solve this?

**Comment by ddeehere** [comment] 2022-03-03 15:14
@danielskatz 

DOI: 10.5281/zenodo.6325732](https://doi.org/10.5281/zenodo.6325732)

**Comment by danielskatz** [comment] 2022-03-03 15:16
hmmm   that DOI does not resolve for me right now.  Does it for you?

**Comment by ddeehere** [comment] 2022-03-03 15:27
@danielskatz It was just generated. Looks like it's resolving now.

**Comment by danielskatz** [comment] 2022-03-03 16:17
@editorialbot set 10.5281/zenodo.6325732 as archive

**Comment by danielskatz** [comment] 2022-03-03 16:20
@ddeehere - Please check that the Zenodo item has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it - I should be removed). You may also add the authors' ORCID.

You can change metadata and then republish the zenodo item without getting or needing a new DOI, as long as you don't change the data itself (the zip file in this case)

**Comment by ddeehere** [comment] 2022-03-03 18:07
> See "How can I edit the metadata of a published record?" on https://help.zenodo.org

@danielskatz Thank you for all your help! Metadata is edited.

**Comment by danielskatz** [comment] 2022-03-03 18:24
@editorialbot recommend-accept

**Comment by danielskatz** [comment] 2022-03-03 18:28
👋 @xuanxu - Any ideas on this error?

**Comment by xuanxu** [comment] 2022-03-03 20:14
It looks like both figures have the same id (fig:PopMedNet) in the paper.md file. Changing it in any of them should fix it.

**Comment by danielskatz** [comment] 2022-03-03 20:25
Thanks @xuanxu

**Comment by danielskatz** [comment] 2022-03-03 20:25
@ddeehere - can you update this?  We don't need a new zenodo deposit, as we only require the software to be archived, not the final paper

**Comment by ddeehere** [comment] 2022-03-03 20:27
@danielskatz Yes, just updated.

**Comment by danielskatz** [comment] 2022-03-03 20:27
@editorialbot recommend-accept

**Comment by danielskatz** [comment] 2022-03-03 20:32
@editorialbot check references

**Comment by danielskatz** [comment] 2022-03-03 20:37
@ddeehere - there are a couple of things I'm not happy about in the metadata and pdf, but these are issues on the JOSS side, not on what you submitted.  Until these are fixed, I'm not going to to ahead with the final acceptance and publishing, but hopefully this won't take long to resolve

**Comment by ddeehere** [comment] 2022-03-04 00:01
@danielskatz I appreciate the status. Looking forward to having it approved in the near future. Thanks!

**Comment by arfon** [comment] 2022-03-04 14:19
@editorialbot recommend-accept

**Comment by arfon** [comment] 2022-03-04 14:30
> @ddeehere - there are a couple of things I'm not happy about in the metadata and pdf, but these are issues on the JOSS side, not on what you submitted. Until these are fixed, I'm not going to to ahead with the final acceptance and publishing, but hopefully this won't take long to resolve

@danielskatz – these should be addressed now.

**Comment by danielskatz** [comment] 2022-03-04 15:48
thanks @arfon

**Comment by danielskatz** [comment] 2022-03-04 15:48
@editorialbot accept

**Comment by danielskatz** [comment] 2022-03-04 16:02
Congratulations to @ddeehere (Daniel Dee) and co-authors!!

And thanks to @jhancock4d and @lrasmus for reviewing!
We couldn't do this without you

**Closed by danielskatz** 2022-03-04 16:02 UTC
Labels: accepted, review, recommend-accept, published
