### ISSUE TITLE
[PRE REVIEW]: uJVM - lightweight JVM implementation for embedded systems

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1251] opened 2019-02-14 15:53 UTC
**Submitting author:** @omoliavko (<a href="http://orcid.org/0000-0003-3167-983X">Oleksandr Moliavko</a>)
**Repository:** <a href="https://github.com/Samsung/uJVM/" target ="_blank">https://github.com/Samsung/uJVM/</a>
**Version:** v0.1
**Editor:** @gkthiruvathukal
**Reviewer:** Pending

**Author instructions**

Thanks for submitting your paper to JOSS @omoliavko. The JOSS editor @gkthiruvathukal, will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@omoliavko if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-02-14 15:54
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @gkthiruvathukal it looks like you're currently assigned as the editor for this paper :tada:

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for the assigned editor (@gkthiruvathukal) to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers]([]) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-02-14 15:54
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-02-14 15:54
PDF failed to compile for issue #1251 with the following error: 

   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    16    0    16    0     0     71      0 --:--:-- --:--:-- --:--:--    72
Could not find bibliography file: 
Error running filter pandoc-citeproc:
Filter returned error status 1
Looks like we failed to compile the PDF

**Comment by arfon** [comment] 2019-02-14 15:54
👋 @gkthiruvathukal - the submitting author suggested you as the handling editor.

**Comment by arfon** [comment] 2019-02-14 15:55
:wave: @omoliavko thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our [submission criteria](http://joss.theoj.org/about#submission_requirements). In particular, this item:

> - Your software should have an obvious research application

Could you confirm here that there _is_ a research application for this software (and explain what that application is)? The section [_'what should my paper contain'_](http://joss.theoj.org/about#paper_structure) has some guidance for the sort of content we're looking to be present in the `paper.md`.

In addition, it looks like you're missing a `paper.bib` file.

**Comment by omoliavko** [comment] 2019-02-15 07:50
.search-word {
	BACKGROUND-COLOR: #ffee94
}
P {
	MARGIN-BOTTOM: 5px; FONT-SIZE: 10pt; FONT-FAMILY: Arial, arial; MARGIN-TOP: 5px
}
TD {
	MARGIN-BOTTOM: 5px; FONT-SIZE: 10pt; FONT-FAMILY: Arial, arial; MARGIN-TOP: 5px
}
LI {
	MARGIN-BOTTOM: 5px; FONT-SIZE: 10pt; FONT-FAMILY: Arial, arial; MARGIN-TOP: 5px
}
BODY {
	FONT-SIZE: 10pt; FONT-FAMILY: Arial, arial
}


P {
	MARGIN-BOTTOM: 5px; FONT-SIZE: 10pt; FONT-FAMILY: Arial, arial; MARGIN-TOP: 5px
}





Hello,
 
It was not probably stated clearly, but the development of uJVM itself is a research project to evaluate feasibility of using Java as cross-platform development language for embedded systems and microcontroller-based devices. So I'd say that uJVM is both a research tool and a research subject. If it is necessary, I can rewrite and resubmit article. Regarding paper.bib file - there's no bibliography in article, so paper.bib is absent.
 
Regards,
Oleksandr Moliavko
 
--------- Original Message ---------
Sender : Arfon Smith <notifications@github.com>
Date : 2019-02-14 17:56 (GMT+2)
Title : Re: [openjournals/joss-reviews] [PRE REVIEW]: uJVM - lightweight JVM implementation for embedded systems (#1251)
 
👋 @omoliavko thanks for your submission to JOSS. From a quick inspection of this submission it's not entirely obvious that it meets our submission criteria. In particular, this item:


Your software should have an obvious research application 
Could you confirm here that there is a research application for this software (and explain what that application is)? The section 'what should my paper contain' has some guidance for the sort of content we're looking to be present in the paper.md.
In addition, it looks like you're missing a paper.bib file.

**Comment by arfon** [comment] 2019-02-24 19:41
Closing as a duplicate of #1268

**Closed by arfon** 2019-02-24 19:41 UTC
Labels: C, C++, Makefile, pre-review
