### ISSUE TITLE
Submission: Git-RDM: A research data management plugin for the Git version control system

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#29] opened 2016-06-17 02:27 UTC
**Submitting author:** @ctjacobs (<a href="http://orcid.org/0000-0002-0034-4650">Christian T. Jacobs</a>)
**Repository:** <a href="https://github.com/ctjacobs/git-rdm" target ="_blank">https://github.com/ctjacobs/git-rdm</a>
**Version:** v1.0.0
**Archive:** <a href="https://dx.doi.org/10.6084/m9.figshare.3443750.v1" target ="_blank">10.6084/m9.figshare.3443750.v1</a>

## Status

[![status](http://joss.theoj.org/papers/d0641341031a50d63d61e6149768d19e/status.svg)](http://joss.theoj.org/papers/d0641341031a50d63d61e6149768d19e)

Status badge code:

```
HTML: <a href="http://joss.theoj.org/papers/d0641341031a50d63d61e6149768d19e"><img src="http://joss.theoj.org/papers/d0641341031a50d63d61e6149768d19e/status.svg"></a>
Markdown: [![status](http://joss.theoj.org/papers/d0641341031a50d63d61e6149768d19e/status.svg)](http://joss.theoj.org/papers/d0641341031a50d63d61e6149768d19e)
```

### Conflict of interest

- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ctjacobs/git-rdm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Version:** Does the release version given match the GitHub release (v1.0.0)?
- [x] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.6084/m9.figshare.3439742.v1">software archive</a> resolve?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

Paper PDF: [10.21105.joss.00029.pdf](https://github.com/openjournals/joss-reviews/files/319656/10.21105.joss.00029.pdf)

- [x] **Authors:** Does the `paper.md` file include a list of authors with their affiliations?
- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **References:** Do all archival references that should have a DOI list one (e.g. papers, datasets, software)?

**Comment by arfon** [comment] 2016-06-17 02:32
/ cc @openjournals/joss-reviewers - would anyone be willing to review this submission?

If you would like to review this submission then please comment on this thread so that others know you're doing a review (so as not to duplicate effort). Something as simple as `:hand: I am reviewing this` will suffice.

**Reviewer instructions**

- Please work through the checklist at the start of this issue.
- If you need any further guidance/clarification take a look at the reviewer guidelines here http://joss.theoj.org/about#reviewer_guidelines
- Please make a publication recommendation at the end of your review

Any questions, please ask for help by commenting on this issue! 🚀

**Comment by desilinguist** [comment] 2016-06-17 02:34
:hand: I am reviewing this

**Comment by jsta** [comment] 2016-06-17 13:01
:hand: I am reviewing this

**Comment by jsta** [comment] 2016-06-17 14:56
- [x] As the reviewer I confirm that there are no conflicts of interest for me to review this work (such as being a major contributor to the software).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/ctjacobs/git-rdm">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [ ] **Version:** Does the release version given match the GitHub release (v1.0.0)?
	No, setup.py has a version number of 1.0 while the github release is 1.0.0

- [x] **Archive:** Does the <a target="_blank" href="http://dx.doi.org/10.6084/m9.figshare.3439742.v1">software archive</a> resolve?

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?

I am concerned about the instruction to install as root with sudo although I understand that this may be necessary in order for system-wide functionality. Also, I had to do a fair amount of fighting with PATH variables because I am a conda user.

- [x] **Functionality:** Have the functional claims of the software been confirmed?
Verified functionality for all items!
- [x] **Performance:** Have any performance claims of the software been confirmed?

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

I would really prefer a more automated package installation solution like integration with conda.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

Overall, I think `git-rdm` works great! I wonder if you could include instructions for viewing and verifying the `.rdm/publications.db` file.
- [x] **Functionality documentation:** Is the functionality of the software documented to a satisfactory level (e.g. API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the function of the software can be verified?

There are no automated tests. However, I think the example usage in README.md is sufficient.
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by desilinguist** [comment] 2016-06-17 14:59
I had replied last night that I would be reviewing this via email. I guess that not everyone saw that? Anyway, I deleted my comment and I am happy to let @jsta review this one 👍.

**Comment by alex-konovalov** [comment] 2016-06-17 15:06
Similar thing happened to me with another paper last week. I was away from browser and was only able to reply by email, but my comment did not appear under that paper so it was reviewed by another person (thanks!).

Could it be a more general problem?

**Comment by jsta** [comment] 2016-06-17 15:19
@desilinguist I saw your reply. However, I neglected to do a thorough check of other submissions or I would have seen that it was the norm to only have one reviewer per submission. I just assumed that multiple people reviewed each submission. My apologies!

**Comment by desilinguist** [comment] 2016-06-17 15:20
Ah, I see. No worries at all! You finished your review faster than I would have anyway which is better for all of us 👍

**Comment by ctjacobs** [comment] 2016-06-17 15:29
Thank you all so much for your interest in this, and for the extremely fast review! I'll start addressing your comments within the next few days.

**Comment by jsta** [comment] 2016-06-17 16:49
I realized that my comment about `.rdm/publications.db` in the **Example Usage** section is solved by:
> `$ git rdm ls`

However, I ended up verifying the contents of the file separately using:
> `$ sqlite3 .rdm/publications.db '.header on' '.mode csv' '.once test.csv' 'SELECT * FROM publications'`

In summary, I can see some room for improvement in the way the output of `$ git rdm ls` is formatted.

**Comment by arfon** [comment] 2016-06-18 02:59
> Could it be a more general problem?

@alex-konovalov - I'm not sure what we can do about this sorry. The only tried-and-tested solution here is to visit the review issue to see if anyone has already commented on it.

Also, while we don't have a firm policy about this, having a second review isn't really a bad thing :wink:

**Comment by ctjacobs** [comment] 2016-06-19 17:39
I have addressed @jsta's comments in the [review branch](https://github.com/ctjacobs/git-rdm/tree/review) of the git-rdm repository. The main changes are:

* Added a new option `git rdm ls --raw` which outputs the raw contents of the `.rdm/publications.db` file for database verification purposes. Also added an example of its use in `README.md`.

* Bumped the version in `setup.py` to v1.0.1 (rather than deleting and re-releasing this revised code as v1.0.0); v1.0.1 will be released via the Git-RDM repository's [Releases page](https://github.com/ctjacobs/git-rdm/releases) (and archived again on Figshare) once everyone is happy with the changes I've made here.

* Packaged up Git-RDM and PyRDM (and the SWORD2 dependency), and uploaded it to [my anaconda.org package channel](https://anaconda.org/ctjacobs). Instructions for installing Git-RDM via Conda are now provided in `README.md`. Once again, the Conda package for Git-RDM will be updated to v1.0.1 once everyone is happy with the changes.

**Comment by ctjacobs** [comment] 2016-06-19 17:50
For a full `diff`, please see https://github.com/ctjacobs/git-rdm/pull/2

**Comment by jsta** [comment] 2016-06-19 22:09
Awesome! I was able to install from your conda channel and test the `git rdm ls --raw` command. I really like the improvements to `README.md` describing local installs. Everything is good-to-go for acceptance as far as I am concerned.

**Comment by ctjacobs** [comment] 2016-06-19 22:21
Fantastic - many thanks for trying it out. I'll merge in the changes and update to v1.0.1.

**Comment by ctjacobs** [comment] 2016-06-19 22:55
All done. The archive for v1.0.1 is available at the following (different) DOI: https://dx.doi.org/10.6084/m9.figshare.3443750.v1

@arfon, is it possible to have the "Archive DOI" [here](http://joss.theoj.org/papers/d0641341031a50d63d61e6149768d19e) updated please?

The Conda package has also been updated to v1.0.1

**Comment by arfon** [comment] 2016-06-20 04:48
Thanks for the excellent review @jsta!

@ctjacobs your paper DOI is http://dx.doi.org/10.21105/joss.00029 . The DOI isn't quite live yet (i.e. it doesn't resolve) but should start working in the next couple of hours once the Crossref queue processes the registration request. 🎉 🚀 💥

**Closed by arfon** 2016-06-20 04:48 UTC
Labels: accepted, review

**Comment by ctjacobs** [comment] 2016-06-20 09:46
Excellent. Thank you everyone!

@arfon, I would be happy to review future submissions for JOSS, so feel free to add me to @joss-reviewers.

Cheers!
