### ISSUE TITLE
[PRE REVIEW]: gdess: A framework for evaluating simulated atmospheric CO~2~ in Earth System Models

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3690] opened 2021-09-03 22:22 UTC
**Submitting author:** @dkauf42 (<a href="http://orcid.org/0000-0002-1487-7298">Daniel E Kaufman</a>)
**Repository:** https://github.com/E3SM-Project/gdess
**Branch with paper.md** (empty if default branch): 
**Version:** 1.0.beta1
**Editor:** @dhhagan
**Reviewers:** @slayoo, @sridge, @simonom
**Managing EiC:** Kyle Niemeyer

 

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/6cc7ba8d3c09f66974550161f740e176/status.svg)](https://joss.theoj.org/papers/6cc7ba8d3c09f66974550161f740e176)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/6cc7ba8d3c09f66974550161f740e176"><img src="https://joss.theoj.org/papers/6cc7ba8d3c09f66974550161f740e176/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/6cc7ba8d3c09f66974550161f740e176/status.svg)](https://joss.theoj.org/papers/6cc7ba8d3c09f66974550161f740e176)
```

**Author instructions**

Thanks for submitting your paper to JOSS @dkauf42. **Currently, there isn't an JOSS editor assigned** to your paper.

The author's suggestion for the handling editor is @dhhagan.

@dkauf42 if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2021-09-03 22:22
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-09-03 22:22
Wordcount for `paper.md` is 1681

**Comment by whedon** [comment] 2021-09-03 22:22
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.09 s (716.9 files/s, 113580.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          53           1503           2142           4122
TeX                              1             18              0            936
Markdown                         2             88              2            293
JSON                             2              3              0            102
YAML                             2             12             17            101
Jupyter Notebook                 3              0           1157             50
Bourne Shell                     3             12             22             24
INI                              1              2              0              9
-------------------------------------------------------------------------------
SUM:                            67           1638           3340           5637
-------------------------------------------------------------------------------


Statistical information for the repository 'c56946cbbbcf0634e403ce4e' was
gathered on 2021/09/03.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
dkauf42                          2            12            261            1.12
kauf418                        418         16092           8016           98.88

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
kauf418                    7767           48.3          4.0               11.42
```

**Comment by whedon** [comment] 2021-09-03 22:23
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.5334/jors.148 is OK
- 10.1175/BAMS-D-13-00080.1 is OK
- 10.25925/20200903 is OK
- 10.1175/JCLI-D-12-00417.1 is OK
- 10.5194/amt-7-647-2014 is OK
- 10.3402/tellusb.v50i5.16216 is OK
- 10.1029/2019MS001766 is OK
- 10.5194/acp-19-14233-2019 is OK
- 10.1029/2008JG000920 is OK
- 10.1029/2018MS001354 is OK
- 10.3402/tellusb.v51i2.16286 is OK
- 10.1007/s10652-009-9163-2 is OK
- 10.5194/acp-17-3861-2017 is OK
- 10.1175/JCLI-D-14-00788.1 is OK
- 10.1175/JCLI-D-16-0543.1 is OK
- 10.5194/gmd-9-1747-2016 is OK
- 10.5194/gmd-9-1937-2016 is OK
- 10.1038/s41558-018-0355-y is OK
- 10.5194/gmd-13-3383-2020 is OK
- 10.1029/2019JD031165 is OK
- 10.1175/JCLI3800.1 is OK
- 10.1016/j.jmarsys.2008.05.006 is OK
- 10.1029/1999JD900311 is OK
- 10.1016/j.atmosenv.2008.12.028 is OK
- 10.3390/atmos9050175 is OK
- 10.1016/j.jmarsys.2008.05.014 is OK
- 10.1175/JCLI-D-12-00554.1 is OK
- 10.5194/gmd-9-2853-2016 is OK
- 10.1029/2019ms001967 is OK
- 10.5194/amt-6-511-2013 is OK
- 10.1029/2004JD004554 is OK
- 10.1007/s00376-019-8150-x is OK
- 10.5194/bg-9-875-2012 is OK
- 10.1175/JCLI-D-12-00589.1 is OK
- 10.1029/JD094iD06p08533 is OK
- 10.1016/j.rse.2017.01.007 is OK
- 10.1002/2013JD020175 is OK
- 10.5194/bg-14-1383-2017 is OK
- 10.1029/95jd00859 is OK
- 10.1029/2000JD000023 is OK
- 10.1029/2011JD016270 is OK
- 10.5194/essd-6-375-2014 is OK
- 10.1007/s10584-011-0156-z is OK
- 10.5194/acp-20-323-2020 is OK
- 10.1029/2003jd003968 is OK
- 10.1371/journal.pone.0146467 is OK
- 10.1002/2014JD022411 is OK
- 10.5194/gmd-13-2149-2020 is OK
- 10.1111/j.2153-3490.1982.tb01804.x is OK
- 10.1073/pnas.0708986104 is OK
- 10.1175/amsmonographs-d-18-0018.1 is OK
- 10.1029/2019MS001629 is OK
- 10.1038/s41558-020-00973-9 is OK
- 10.1002/2017GL076101 is OK
- 10.1126/science.1137004 is OK
- 10.1016/j.jmarsys.2008.03.011 is OK
- 10.1175/1520-0469(1983)040<0303:OTROTS>2.0.CO;2 is OK
- 10.1002/2014JD022591 is OK
- 10.1029/2000JD900719 is OK
- 10.1029/JD094iD06p08549 is OK
- 10.5194/gmd-10-2785-2017 is OK
- 10.5194/gmd-2019-268 is OK
- 10.1029/2019MS001851 is OK
- 10.1038/s41467-020-16236-2 is OK
- 10.5194/acp-19-8269-2019 is OK
- 10.1073/pnas.0701020104 is OK
- 10.1016/j.proenv.2011.05.023 is OK
- 10.5194/gmd-11-1971-2018 is OK

MISSING DOIs

- 10.1071/es19035 may be a valid DOI for title: The Australian Earth System Model: ACCESS-ESM1.5

INVALID DOIs

- https://doi.org/10.1111/gcb.15409 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1029/2018MS001603 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1002/hyp.6989 is INVALID because of 'https://doi.org/' prefix
- 10.1002/2013JG002381.Received is INVALID
- https://doi.org/10.1029/2018GB006086 is INVALID because of 'https://doi.org/' prefix
- https://doi.org/10.1016/j.jhydrol.2020.125553 is INVALID because of 'https://doi.org/' prefix
```

**Comment by whedon** [comment] 2021-09-03 22:23
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03690/joss.03690/10.21105.joss.03690.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03690/joss.03690/10.21105.joss.03690.pdf) :page_facing_up: :point_left:

**Comment by kyleniemeyer** [comment] 2021-09-03 22:25
Hi @dkauf42 thanks for your submission to JOSS! Unfortunately, we don't have an available editor in this area right now, so I have to put this on our waitlist. As soon as someone becomes available, we will assign it and get moving.

In the meantime, could you review and resolve those DOI issues in the article? And, any reviewer suggestions you can give would be welcome.

**Comment by dkauf42** [comment] 2021-09-08 20:09
Hi @kyleniemeyer, thank you for the information. I just updated the paper files to resolve DOI issues.  

For reviewers, I can suggest:

- Dr. Bianca Baier (U.S. National Oceanic and Atmos. Admin.; email: Bianca.Baier@noaa.gov)
- Dr. Lesley Ott (U.S. Nat'l Aeronautics and Space Admin.; email: lesley.e.ott@nasa.gov)
- Dr. Samantha Basile (U.S. National Climate Assessment; webpage: https://www.globalchange.gov/staff/samantha-basile)
- Dr. Havala Pye (U.S. Env. Protection Agency; email: pye.havala@epa.gov; GitHub: havalapye)
- Dr. Jesse Bash (U.S. Env. Protection Agency; email: bash.jesse@epa.gov; GitHub: jessebash)
- Dr. Elizabeth Adams (U.S. Env. Protection Agency; GitHub: lizadams; email: Adams.elizabeth@epa.gov)
- Doctoral candidate, Karolina Pantazatou (Lund University; email: karolina.pantazatou@nateko.lu.se; GitHub: KarolinaPntzt)

**Comment by Kevin-Mattheus-Moerman** [comment] 2021-09-12 07:09
@whedon generate pdf

**Comment by whedon** [comment] 2021-09-12 07:10
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03690/joss.03690/10.21105.joss.03690.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03690/joss.03690/10.21105.joss.03690.pdf) :page_facing_up: :point_left:

**Comment by Kevin-Mattheus-Moerman** [comment] 2021-09-12 07:24
@whedon check references

**Comment by whedon** [comment] 2021-09-12 07:24
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.25925/20200903 is OK
- 10.1111/gcb.15409 is OK
- 10.1029/2018MS001603 is OK
- 10.5334/jors.148 is OK
- 10.1175/BAMS-D-13-00080.1 is OK
- 10.1029/2019MS001766 is OK
- 10.5194/acp-19-14233-2019 is OK
- 10.1029/2018MS001354 is OK
- 10.3402/tellusb.v51i2.16286 is OK
- 10.5194/gmd-9-1747-2016 is OK
- 10.5194/gmd-9-1937-2016 is OK
- 10.5194/gmd-13-3383-2020 is OK
- 10.3390/atmos9050175 is OK
- 10.1175/JCLI-D-12-00589.1 is OK
- 10.5194/bg-14-1383-2017 is OK
- 10.5194/essd-6-375-2014 is OK
- 10.1002/2014JD022411 is OK
- 10.1175/amsmonographs-d-18-0018.1 is OK
- 10.1029/2019MS001629 is OK
- 10.1029/2018GB006086 is OK
- 10.1126/science.1137004 is OK
- 10.1175/1520-0469(1983)040<0303:OTROTS>2.0.CO;2 is OK
- 10.1002/2014JD022591 is OK
- 10.1029/JD094iD06p08549 is OK
- 10.5194/acp-21-9609-2021 is OK
- 10.1016/j.jhydrol.2020.125553 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by Kevin-Mattheus-Moerman** [comment] 2021-09-12 07:25
@dkauf42 thanks for fixing the paper and for listing some suggested reviewers. It would help us also if you could mention their GitHub handles if available (please leave out the @ symbol so they are not yet tagged).

**Comment by dkauf42** [comment] 2021-09-14 22:05
Sure thing. GitHub handles for the last four suggested reviewers (I don't yet know handles for the others) are:
havalapye; jessebash; lizadams; KarolinaPntzt

**Comment by kthyng** [comment] 2021-09-23 14:29
@richardjgowers is this a reasonable fit for you?

**Comment by kthyng** [comment] 2021-09-23 14:30
@whedon invite @richardjgowers as editor

**Comment by whedon** [comment] 2021-09-23 14:30
@richardjgowers has been invited to edit this submission.

**Comment by richardjgowers** [comment] 2021-09-23 15:52
@whedon assign @richardjgowers as editor

**Comment by whedon** [comment] 2021-09-23 15:52
OK, the editor is @richardjgowers

**Comment by richardjgowers** [comment] 2021-10-03 10:13
@KarolinaPntzt @lizadams @havalapye Hi 👋 would any of you be available to review this submission for JOSS? We carry out our checklist-driven reviews here in GitHub issues and follow these guidelines: https://joss.readthedocs.io/en/latest/review_criteria.html

**Comment by dkauf42** [comment] 2021-12-03 17:56
Hi @richardjgowers, just checking back in since the last visible comment is from two months ago: Are there any updates on our manuscript's status?  Thanks!

**Comment by BunnyVon** [comment] 2022-01-05 22:48
@richardjgowers Happy New Year! I'm one of the co-authors of this manuscript. I wonder if you have any updates on the review process. 
There doesn't appear to have been any update for 3 months. So we also wonder if there is any additional information we can provide to you — to help advance our manuscript to the reviewing stage. Thanks :)

**Comment by kthyng** [comment] 2022-01-21 15:04
@dhhagan This submission looks like a better fit for your expertise — could you take it on?

**Comment by kthyng** [comment] 2022-01-21 15:04
@whedon invite @dhhagan as editor

**Comment by whedon** [comment] 2022-01-21 15:04
@dhhagan has been invited to edit this submission.

**Comment by dhhagan** [comment] 2022-01-21 16:29
Hey @kthyng sure thing. I should be able to get to this on Tues morning if that's okay?

**Comment by kthyng** [comment] 2022-01-21 20:27
@dhhagan sounds perfect. Thank you!

**Comment by kthyng** [comment] 2022-01-21 20:27
@whedon assign @dhhagan as editor

**Comment by whedon** [comment] 2022-01-21 20:28
OK, the editor is @dhhagan

**Comment by dhhagan** [comment] 2022-01-25 14:36
@whedon scope query

**Comment by whedon** [comment] 2022-01-25 14:36
I'm sorry human, I don't understand that. You can see what commands I support by typing:

```
@whedon commands
```

**Comment by dhhagan** [comment] 2022-01-25 14:36
@whedon query scope

**Comment by dhhagan** [comment] 2022-02-16 01:48
@dkauf42  First, let me apologize for the long delay at the pre-review stage. After an initial look/review, I made the decision to ask other JOSS editors to evaluate whether or not this submission meets the JOSS guideline for [substantial scholarly effort](https://joss.readthedocs.io/en/latest/review_criteria.html#substantial-scholarly-effort). I will let you know as soon as that is resolved. Again, sorry for the long delay!

**Comment by arfon** [comment] 2022-02-27 17:48
Thanks for flagging this @dhhagan. I think this submission is good to move forward to review.

**Comment by dhhagan** [comment] 2022-03-01 14:02
Hi @dkauf42 - I will now move to find some reviewers for this paper. Thanks for being patient.

**Comment by dhhagan** [comment] 2022-03-01 14:03
👋  @havalapye @jessebash @karolinapntzt Would you have time and interest in reviewing this manuscript for JOSS?

**Comment by BunnyVon** [comment] 2022-03-16 21:09
@dhhagan - Thank you for helping move the review process forward. I'm Sha Feng listed as the second author of this manuscript. I wonder if there is an update on finding the reviewers? It's been 6 months since the first submission. We wonder if we could provide anything to speed up the process.

**Comment by dhhagan** [comment] 2022-04-06 14:22
Hey @dkauf42 and @BunnyVon - so sorry about the delay. I've been trying to find reviewers, but so far have had little luck. I'll be reaching out to a few others today that are more present on GitHub to see if that yields better results. Sorry again - i'll try to get this going.

**Comment by dhhagan** [comment] 2022-04-06 14:34
👋  @slayoo @simonom @rabernat @znicholls @KarolinaPntzt: are you available to review this manuscript for JOSS?

**Comment by znicholls** [comment] 2022-04-07 09:36
I'm sad to say I can't do it quickly, July looks like the earliest time that things free up for me again

**Comment by slayoo** [comment] 2022-04-07 15:37
@dhhagan, let me try to help here, I confirm.

**Comment by rabernat** [comment] 2022-04-07 15:44
I do not have room in my schedule to review right now. However, I will tag a few people I know who are fluent in both Python and CO2 cycles: @sridge, @lgloege. Maybe one of them can step in.

**Comment by simonom** [comment] 2022-04-11 08:45
@dhhagan, I confirm I will review

**Comment by sridge** [comment] 2022-04-11 14:08
Thanks for the tag @rabernat, I would be happy to review @dhhagan

**Comment by slayoo** [comment] 2022-04-11 15:35
@dhhagan, with other confirmed reviewers, please keep me as a backup, if possible, thanks

**Comment by dhhagan** [comment] 2022-04-18 17:22
@editorialbot add @slayoo as reviewer

**Comment by dhhagan** [comment] 2022-04-18 17:23
@editorialbot add @sridge as reviewer

**Comment by dhhagan** [comment] 2022-04-18 17:23
@editorialbot add @simonom as reviewer

**Comment by dhhagan** [comment] 2022-04-18 17:24
@editorialbot start review

**Closed by dhhagan** 2022-04-18 17:24 UTC
Labels: pre-review, Shell, Python, Jupyter Notebook
