### ISSUE TITLE
[PRE REVIEW]: idpflex: Analysis of Intrinsically Disordered Proteins by Comparing Simulations to Small Angle Scattering Experiments

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#895] opened 2018-08-15 19:09 UTC
**Submitting author:** @jmborr (<a href="http://orcid.org/0000-0002-0866-8158">Jose M. Borreguero</a>)
**Repository:** <a href="https://github.com/jmborr/idpflex.git" target ="_blank">https://github.com/jmborr/idpflex.git</a>
**Version:** v0.1.5
**Editor:** @brainstorm
**Reviewers:** @gjeuken

**Author instructions**

Thanks for submitting your paper to JOSS @jmborr. The JOSS editor (shown at the top of this issue) will work with you on this issue to find a reviewer for your submission before creating the main review issue.

@jmborr if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2018-08-15 19:09
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**Comment by whedon** [comment] 2018-08-15 19:09
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-08-15 19:09
PDF failed to compile for issue #895 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/895/paper/paper.md): could not find expected ':' while scanning a simple key at line 12 column 7 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment] 2018-08-15 19:35
@jmborr - it looks like the `orcid` fields in your `paper.md` file aren't formed correctly. Instead of 
```
ORCID 0000-0002-0866-8158
```
they should be 

```
orcid: 0000-0002-0866-8158
```

In addition, your paper doesn't look to be complete?

**Comment by jmborr** [comment] 2018-08-15 22:04
@arfon First, let me thank you for taking the time to review the submission. Second, let me apologize for a silly mistake. I prepared the submission to JOSS in a dedicated branch and I became engrossed to the point that I forgot to merge it into master :blush: 
I've just merged the branch, I believe the paper is now complete.

**Comment by arfon** [comment] 2018-08-15 23:40
@whedon generate pdf

**Comment by whedon** [comment] 2018-08-15 23:40
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-08-15 23:40
PDF failed to compile for issue #895 with the following error: 

 /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse': (tmp/895/paper/paper.md): could not find expected ':' while scanning a simple key at line 12 column 7 (Psych::SyntaxError)
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /app/vendor/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon.rb:68:in `initialize'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `new'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/lib/whedon/processor.rb:32:in `set_paper'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:37:in `prepare'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /app/vendor/bundle/ruby/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /app/vendor/bundle/ruby/2.3.0/bundler/gems/whedon-e0f72c5e8125/bin/whedon:99:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `load'
	from /app/vendor/bundle/ruby/2.3.0/bin/whedon:22:in `<main>'

**Comment by arfon** [comment] 2018-08-15 23:42
Hi @jmborr, please note the `orcid` fields need colons separating the key/value pairs.

i.e. change this `orcid 0000-0002-0866-8158` to this `orcid: 0000-0002-0866-8158`

**Comment by jmborr** [comment] 2018-08-16 02:58
@arfon I just corrected them, thank you.

**Comment by arfon** [comment] 2018-08-16 09:50
@whedon generate pdf

**Comment by whedon** [comment] 2018-08-16 09:50
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00895/joss.00895/10.21105.joss.00895.pdf)

**Comment by jmborr** [comment] 2018-08-16 19:28
@whedon generate pdf

**Comment by whedon** [comment] 2018-08-16 19:28
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2018-08-16 19:28
[--> Check article proof :page_facing_up: <--](https://github.com/openjournals/joss-papers/blob/joss.00895/joss.00895/10.21105.joss.00895.pdf)

**Comment by jmborr** [comment] 2018-08-16 19:36
@arfon I have proof-read the paper and I have two issues I don't know how to resolve.
1. Affiliations (there are two) show up together in the same line. Is this the intended behavior?
2. Hyperlinks in the PDF are not functional but I assume this is the intended behavior.

**Comment by arfon** [comment] 2018-08-20 10:26
> Affiliations (there are two) show up together in the same line. Is this the intended behavior?

Yes, this is expected.

> Hyperlinks in the PDF are not functional but I assume this is the intended behavior.

Are they not functional when rendering on GitHub, or not functional when downloading the PDF? If the former, this is simply GitHub's security policy.

**Comment by jmborr** [comment] 2018-08-20 11:37
@arfon I was viewing the PDF in Github. I downloaded it and the links work and the links are fine 😄

**Comment by jmborr** [comment] 2018-08-24 15:44
@arfon Everything seems in order. Do I have to take any other step or simply wait until I'm assigned a reviewer?

**Comment by arfon** [comment] 2018-08-24 15:55
> @arfon Everything seems in order. Do I have to take any other step or simply wait until I'm assigned a reviewer?

Yes, sorry for the delay. We're a little backed up with submissions currently and are still waiting for an editor to pick up this submission. In the meantime, if you have any suggestions for potential reviewers from [this list](https://bit.ly/joss-reviewers) feel free to mention them here.

**Comment by jmborr** [comment] 2018-08-24 16:08
I would think of reviewers with python as their primary language a background in soft-matter and/or computational biology, with a hint of physics expertise. Some  suggestion:
- tacaswell
- krother
- khinsen
- andim
- afrubin
- a-slide
- conradstack
- semacu

**Comment by arfon** [comment] 2018-08-29 11:11
:wave: @mgymrek - would you be willing to edit this submission for JOSS?

**Comment by arfon** [comment] 2018-09-17 10:47
:wave: @pjotrp @george-githinji @brainstorm - would one of you be willing to edit this submission for JOSS?

**Comment by brainstorm** [comment] 2018-09-17 22:02
Yep @arfon , I can take this one ;)

**Comment by arfon** [comment] 2018-09-17 23:19
@whedon assign @brainstorm as editor

**Comment by whedon** [comment] 2018-09-17 23:19
OK, the editor is @brainstorm

**Comment by brainstorm** [comment] 2018-09-21 07:34
@luminita, would you like to review this JOSS paper for me? :)

**Comment by brainstorm** [comment] 2018-10-08 00:31
@percolator (or one of your students), would you mind helping out reviewing this proteomics/MD software?

**Comment by percolator** [comment] 2018-10-08 16:01
What would such a review comprise? Would we run the software, make a
code.review or should we review a paper?

**Comment by brainstorm** [comment] 2018-10-09 00:31
@percolator Actually both, but it usually doesn't take more than 30 minutes to wrap it all up, see:

https://joss.readthedocs.io/en/latest/reviewer_guidelines.html

The code review is mostly due diligence with unit testing, nothing like a deep full code audit.

Here you have an example checklist on what you should expect from the review:

https://github.com/openjournals/joss-reviews/issues/967

Hope that helps, feel free to inquire more :)

**Comment by brainstorm** [comment] 2018-10-09 11:18
Alright, fantastic, thanks Lukas (and Gustavo).

@whedon assign @gjeuken as reviewer

**Comment by brainstorm** [comment] 2018-10-09 11:39
@whedon assign @gjeuken as reviewer

**Comment by whedon** [comment] 2018-10-09 11:39
OK, the reviewer is @gjeuken

**Comment by brainstorm** [comment] 2018-10-09 11:41
@whedon start review magic-word=bananas

**Closed** 2018-10-09 11:41 UTC
Labels: Jupyter Notebook, Makefile, Python, pre-review

**Comment by jmborr** [comment] 2018-10-09 14:04
@whedon Thanks a lot for reviewing the package!  😄
