### ISSUE TITLE
[PRE REVIEW]: PyVista: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK)

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#1382] opened 2019-04-14 16:18 UTC
**Submitting author:** @banesullivan (<a href="http://orcid.org/0000-0001-8628-4566">C. Bane Sullivan</a>)
**Repository:** <a href="https://github.com/pyvista/pyvista/" target ="_blank">https://github.com/pyvista/pyvista/</a>
**Version:** 0.18.1
**Editor:** @leouieda
**Reviewers:** @Chilipp, @nicoguaro

**Author instructions**

Thanks for submitting your paper to JOSS @banesullivan. **Currently, there isn't an JOSS editor assigned** to your paper.

@banesullivan if you have any suggestions for potential reviewers then please mention them here in this thread. In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission.

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2019-04-14 16:18
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

For a list of things I can do to help you, just type:

```
@whedon commands
```

**What happens now?**

This submission is currently in a `pre-review` state which means we are waiting for an editor to be assigned and for them to find some reviewers for your submission. This may take anything between a few hours to a couple of weeks. Thanks for your patience :smile_cat:

You can help the editor by looking at [this list of potential reviewers](https://bit.ly/joss-reviewers) to identify individuals who might be able to review your submission (please start at the bottom of the list). Also, feel free to suggest individuals who are not on this list by mentioning their GitHub handles here.

**Comment by whedon** [comment] 2019-04-14 16:18
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-04-14 16:19
PDF failed to compile for issue #1382 with the following error: 

 Can't find any papers to compile :-(

**Comment by labarba** [comment] 2019-04-14 16:21
@whedon generate pdf

**Comment by whedon** [comment] 2019-04-14 16:21
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-04-14 16:22
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01382/joss.01382/10.21105.joss.01382.pdf)

**Comment by labarba** [comment] 2019-04-14 16:23
👋  @leouieda — the submitting author suggested you as handling editor, and indeed it looks like this is your cup of tea! I'll assign you now, but do let me know if you are disinclined for any reason.

**Comment by labarba** [comment] 2019-04-14 16:24
@whedon assign @leouieda as editor

**Comment by whedon** [comment] 2019-04-14 16:24
OK, the editor is @leouieda

**Comment by banesullivan** [comment] 2019-04-14 16:37
Thanks, @labarba! It looks like whedon successfully rendered the PDF! 

From the preview, it seems I may need to change a few things in the Markdown:

- One code snippet runs off the page - I'll try to fix this.
- I'm wondering if I added the figure captions in the correct way in Markdown? 
- I may need to shift the figures around. Is there a way to specify the width in markdown that the latex compiler will recognize?

If I edit on the master branch, will whedon update after using a command?

**Comment by banesullivan** [comment] 2019-04-14 16:55
@whedon generate pdf

**Comment by whedon** [comment] 2019-04-14 16:55
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-04-14 16:56
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01382/joss.01382/10.21105.joss.01382.pdf)

**Comment by leouieda** [comment] 2019-04-15 20:50
@labarba I'd be happy to edit this and the PVGeo paper :-1:

**Comment by leouieda** [comment] 2019-04-19 02:10
Hi @banesullivan, I've been going through the paper and I think it's a bit out of our usual format. Quoting from our [guidelines](https://joss.readthedocs.io/en/latest/submitting.html#what-should-my-paper-contain):

> ... JOSS papers are only permitted to contain a limited set of metadata (see header below), **Statement of Need, Summary, Acknowledgements, and References sections**. ... **software documentation** such as API (Application Programming Interface) functionality **should not be in the paper** and instead should be outlined in the software documentation.

Could you please reformat the paper before we proceed with the review? The information is already in the paper so it's only a matter of cutting and reorganizing. You don't have to remove all the figures. In particular, make sure there are:

* A summary describing the high-level functionality and purpose of the software for a **diverse, non-specialist audience**
* A clear statement of need that illustrates the purpose of the software

It would also help if you clarified wether the citations in Mentions are actually using vtki or if they are examples of possible applications of vtki.

**Comment by banesullivan** [comment] 2019-04-19 05:25
Thank you for the feedback @leouieda. I have made updates to the paper addressing your concerns.

1. On the note of the paper's format:

    - I have significantly trimmed the content and made sure the paper only contains: *Statement of Need, Summary, Mentions, and References sections*
    - I have removed all code examples to adhere to JOSS' criteria that *"software documentation such as API (Application Programming Interface) functionality should not be in the paper and instead should be outlined in the software documentation"*

2. On the note of ensuring there is a *"summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience"*:
    
    - I have rewritten the summary to describe the high-level purpose of why we built `vtki` and what need it fills. Particularly, the paper now focuses on what `vtki` achieves and what that looks like for a novice programmer/new user rather than the nuances of how it is implemented. 

3. On the note of ensuring there is a *"clear statement of need that illustrates the purpose of the software"*

    - The paper now conveys a more clear narrative of the current state of 3D visualization in Python and what role `vtki` fills in that space.
    - Specifically, I focused on including this in the first paragraph of the summary:
        > The availability of software for 3D visualization in Python is limited to libraries that are either not capable of handling large, spatially referenced datasets or have inherently complex application programming interfaces (APIs). One of these software libraries is the Visualization Toolkit (VTK) [@vtkbook]; a powerful scientific visualization software library, and with Python bindings, it combines the speed of C++ with the rapid prototyping of Python. Despite this, VTK code programmed in Python using the base VTK python package is unnecessarily complicated as its API merely binds existing C++ calls. The vtki Python package provides a concise, well-documented interface exposing VTK’s powerful visualization backend; enabling researchers to rapidly explore large datasets, communicate their spatial findings, and facilitate reproducibility. 

4. I have clarified the mentions to state that the listed publications do indeed leverage `vtki` for 3D visualization.

**Comment by banesullivan** [comment] 2019-04-19 05:25
@whedon generate pdf

**Comment by whedon** [comment] 2019-04-19 05:25
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-04-19 05:26
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01382/joss.01382/10.21105.joss.01382.pdf)

**Comment by leouieda** [comment] 2019-05-01 19:13
:wave: Hi @rgmyr @Chilipp would you be interested in reviewing this submission for JOSS?

**Comment by Chilipp** [comment] 2019-05-01 23:07
Hey @leouieda and @banesullivan!

I am looking forward to review this during the next week. Looks very interesting.

**Comment by leouieda** [comment] 2019-05-01 23:25
@Chilipp thanks for the quick response! Can I just get a confirmation that you're agreeing to review this submission? (just to make sure)

**Comment by Chilipp** [comment] 2019-05-02 05:04
sure, sorry @leouieda . Yes, I agree to review it

**Comment by banesullivan** [comment] 2019-05-02 05:08
👋 Hi @Chilipp, thanks for taking the time to review `vtki`!!

**Comment by leouieda** [comment] 2019-05-02 21:09
@whedon assign @Chilipp as reviewer

**Comment by whedon** [comment] 2019-05-02 21:09
OK, the reviewer is @Chilipp

**Comment by leouieda** [comment] 2019-05-08 18:53
@Chilipp sorry this is taking so long. @banesullivan is in the process of renaming the vtki package to `vista` (see pyvista/vista#208). We'll need to update this issue before we can start the review.

**Comment by leouieda** [comment] 2019-05-08 18:55
:wave: Hi @RcSepp would be interested in reviewing this submission for JOSS?

**Comment by banesullivan** [comment] 2019-05-12 17:43
@whedon generate pdf

**Comment by whedon** [comment] 2019-05-12 17:43
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-05-12 17:44
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01382/joss.01382/10.21105.joss.01382.pdf)

**Comment by banesullivan** [comment] 2019-05-12 17:44
We have settled on PyVista as the new name of this software - sorry for the delay!

**Comment by Chilipp** [comment] 2019-05-13 09:17
> We'll need to update this issue before we can start the review.

All right @leouieda, just tell me when I can start the review

**Comment by banesullivan** [comment] 2019-05-13 22:57
Please note, @akaszynski and I have changed the paper title to "PyVista: 3D plotting and mesh analysis through a streamlined interface for the Visualization Toolkit (VTK)"

@whedon generate pdf

**Comment by banesullivan** [comment] 2019-05-13 22:57
@whedon generate pdf

**Comment by whedon** [comment] 2019-05-13 22:57
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-05-13 22:58
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01382/joss.01382/10.21105.joss.01382.pdf)

**Comment by banesullivan** [comment] 2019-05-13 23:01
@whedon commands

**Comment by whedon** [comment] 2019-05-13 23:01
Here are some things you can ask me to do:

```
# List Whedon's capabilities
@whedon commands

# List of editor GitHub usernames
@whedon list editors

# List of reviewers together with programming language preferences and domain expertise
@whedon list reviewers

EDITORIAL TASKS

# Compile the paper
@whedon generate pdf

# Compile the paper from alternative branch
@whedon generate pdf from branch custom-branch-name

# Ask Whedon to check the references for missing DOIs
@whedon check references

```

**Comment by leouieda** [comment] 2019-05-15 00:33
@whedon generate pdf

**Comment by whedon** [comment] 2019-05-15 00:33
```
Attempting PDF compilation. Reticulating splines etc...
```

**Comment by whedon** [comment] 2019-05-15 00:34
[ :point_right: Check article proof :page_facing_up: :point_left: ](https://github.com/openjournals/joss-papers/blob/joss.01382/joss.01382/10.21105.joss.01382.pdf)

**Comment by leouieda** [comment] 2019-05-15 00:45
OK, I just renamed the issue and updated the link in the description to the new package. Everything seems to work and the link inserted in the PDF is the correct one now. I'm just waiting on some reviewer invitations to start the review. Hopefully that can be resolved within a week or so.

**Comment by JonathanReardon** [comment] 2019-05-15 02:31
I would like to do the review if possible

**Comment by leouieda** [comment] 2019-05-15 02:54
@whedon add @nicoguaro as reviewer

**Comment by whedon** [comment] 2019-05-15 02:54
OK, @nicoguaro is now a reviewer

**Comment by leouieda** [comment] 2019-05-15 02:56
@JonathanReardon [as I said on twitter](https://twitter.com/leouieda/status/1128493607860654080) @nicoguaro beat you to it this time :slightly_smiling_face: Thanks again for volunteering and I hope you'll consider doing so again the future.

**Comment by leouieda** [comment] 2019-05-15 03:02
@whedon start review

**Comment by whedon** [comment] 2019-05-15 03:02
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/1450. Feel free to close this issue now!

**Closed** 2019-05-15 03:02 UTC
Labels: Python, Shell, TeX, pre-review

**Comment by leouieda** [comment] 2019-05-15 03:04
@banesullivan @Chilipp @nicoguaro please head on over to #1450 for the actual review. Please feel free to post any comments there and open issues in the software repository. Don't hesitate to ask if you have any questions.
