### ISSUE TITLE
[REVIEW]: eyecite: A tool for parsing legal citations

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3617] opened 2021-08-16 12:35 UTC
**Submitting author:** @mattdahl (<a href="http://orcid.org/0000-0001-8437-1455">Matthew Dahl</a>)
**Repository:** <a href="https://github.com/freelawproject/eyecite" target ="_blank">https://github.com/freelawproject/eyecite</a>
**Version:** v2.3.0
**Editor:** @danielskatz
**Reviewer:** @cmaimone, @step21
**Archive:** <a href="https://doi.org/10.7910/DVN/STVKTE" target="_blank">10.7910/DVN/STVKTE</a>

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764/status.svg)](https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764"><img src="https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764/status.svg)](https://joss.theoj.org/papers/afde740e2dd790fb9ac7c352add9c764)
```
**Reviewers and authors**:

Please avoid lengthy details of difficulties in the review thread. Instead, please create a new issue in the <a href="https://github.com/freelawproject/eyecite" target="_blank">target repository</a> and link to those issues (especially acceptance-blockers) by leaving comments in the review thread below. (For completists: if the target issue tracker is also on GitHub, linking the review thread in the issue or vice versa will create corresponding breadcrumb trails in the link target.)

## Reviewer instructions & questions

@cmaimone & @step21, please carry out your review in this issue by updating the checklist below. If you cannot edit the checklist please:
1. Make sure you're logged in to your GitHub account
2. Be sure to accept the invite at this URL: https://github.com/openjournals/joss-reviews/invitations

The reviewer guidelines are available here: https://joss.readthedocs.io/en/latest/reviewer_guidelines.html. Any questions/concerns please let @danielskatz know.

✨ **Please start on your review when you are able, and be sure to complete your review in the next six weeks, at the very latest** ✨ 

## Review checklist for @cmaimone
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/freelawproject/eyecite">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/freelawproject/eyecite">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mattdahl) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

## Review checklist for @step21
✨ Important: Please do not use the _Convert to issue_ functionality when working through this checklist, instead, please open any new issues associated with your review <a target="_blank" href="https://github.com/freelawproject/eyecite">in the software repository associated with the submission</a>. ✨

### Conflict of interest

- [x] I confirm that I have read the [JOSS conflict of interest (COI) policy](https://github.com/openjournals/joss/blob/master/COI.md) and that: I have no COIs with reviewing this work or that any perceived COIs have been waived by JOSS for the purpose of this review.

### Code of Conduct

- [x] I confirm that I read and will adhere to the [JOSS code of conduct](https://joss.theoj.org/about#code_of_conduct).

### General checks

- [x] **Repository:** Is the source code for this software available at the <a target="_blank" href="https://github.com/freelawproject/eyecite">repository url</a>?
- [x] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
- [x] **Contribution and authorship:** Has the submitting author (@mattdahl) made major contributions to the software? Does the full list of paper authors seem appropriate and complete?
- [x] **Substantial scholarly effort:** Does this submission meet the scope eligibility described in the [JOSS guidelines](https://joss.readthedocs.io/en/latest/submitting.html#substantial-scholarly-effort)

### Functionality

- [x] **Installation:** Does installation proceed as outlined in the documentation?
- [x] **Functionality:** Have the functional claims of the software been confirmed?
- [x] **Performance:** If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)

### Documentation

- [x] **A statement of need:** Do the authors clearly state what problems the software is designed to solve and who the target audience is?
- [x] **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
- [x] **Example usage:** Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).
- [x] **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
- [x] **Automated tests:** Are there automated tests or manual steps described so that the functionality of the software can be verified?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Software paper

- [x] **Summary:** Has a clear description of the high-level functionality and purpose of the software for a diverse, non-specialist audience been provided?
- [x] **A statement of need:** Does the paper have a section titled 'Statement of Need' that clearly states what problems the software is designed to solve and who the target audience is?
- [x] **State of the field:** Do the authors describe how this software compares to other commonly-used packages?
- [x] **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
- [x] **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax]( https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html#citation_syntax)?

**Comment by whedon** [comment] 2021-08-16 12:35
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks. @cmaimone, @step21 it looks like you're currently assigned to review this paper :tada:.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

**:star: Important :star:**

If you haven't already, you should seriously consider unsubscribing from GitHub notifications for this (https://github.com/openjournals/joss-reviews) repository. As a reviewer, you're probably currently watching this repository which means for GitHub's default behaviour you will receive notifications (emails) for all reviews 😿

To fix this do the following two things:

1. Set yourself as 'Not watching' https://github.com/openjournals/joss-reviews:

![watching](https://cloud.githubusercontent.com/assets/4483/20250593/64d7ce48-a9de-11e6-9225-d3dfb3e48e68.png)

2. You may also like to change your default settings for this watching repositories in your GitHub profile here: https://github.com/settings/notifications

![notifications](https://cloud.githubusercontent.com/assets/4483/20250604/79eb3144-a9de-11e6-9e51-0fe940966689.png)


For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-08-16 12:35
PDF failed to compile for issue #3617 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by whedon** [comment] 2021-08-16 12:35
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=0.07 s (412.7 files/s, 75808.5 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                          18            478           1039           2564
reStructuredText                 1            147              7            363
YAML                             5             29              3            150
Markdown                         2             29              0             72
TOML                             1             10              5             64
-------------------------------------------------------------------------------
SUM:                            27            693           1054           3213
-------------------------------------------------------------------------------


Statistical information for the repository '2794f5f9e77aab517ba46179' was
gathered on 2021/08/16.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
Faiz Surani                      5           195             30            1.87
Jack Cushman                    49          5495           3728           76.48
Matt Dahl                       12          2229             80           19.15
Michael Lissner                 14            48            127            1.45
Mike Lissner                     1            18              0            0.15
vvilliam                         8            83             27            0.91

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
Faiz Surani                 130           66.7          0.6               20.00
Jack Cushman               3222           58.6          1.8               16.36
Matt Dahl                   703           31.5          3.3               29.30
Michael Lissner              21           43.8          3.7                4.76
vvilliam                      5            6.0          4.6                0.00
```

**Comment by danielskatz** [comment] 2021-08-16 12:36
@whedon check references in branch joss-paper

**Comment by danielskatz** [comment] 2021-08-16 12:37
@whedon check references from branch joss-paper

**Comment by whedon** [comment] 2021-08-16 12:37
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment] 2021-08-16 12:37
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- None

MISSING DOIs

- 10.1093/pan/mpm011 may be a valid DOI for title: Network Analysis and the Law: Measuring the Legal Importance of Precedents at the U.S. Supreme Court
- 10.1111/jels.12012 may be a valid DOI for title: The Citation and Depreciation of U.S. Supreme Court Precedent
- 10.2307/449284 may be a valid DOI for title: Measuring Legal Change: The Reliability and Validity of Shepard’s Citations
- 10.1007/s10506-018-9217-1 may be a valid DOI for title: Automatic Semantic Edge Labeling over Legal Citation Graphs
- 10.1145/3462757.3466066 may be a valid DOI for title: Context-Aware Legal Citation Recommendation Using Deep Learning
- 10.1007/s10506-018-9224-2 may be a valid DOI for title: Bending the Law: Geometric Tools for Quantifying Influence in the Multinetwork of Legal Opinions

INVALID DOIs

- None
```

**Comment by danielskatz** [comment] 2021-08-16 12:37
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment] 2021-08-16 12:37
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-08-16 12:38
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment] 2021-08-16 12:38
@mattdahl - as we get started, you could work on the possibly missing DOIs that whedon suggests, but note that some may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references from branch joss-paper` to check again, and the command `@whedon generate pdf from branch joss-paper` when the references are right to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by danielskatz** [comment] 2021-08-16 12:39
@cmaimone and @step21 - Thanks for agreeing to review this submission.
This is the review thread for the paper. All of our communications will happen here from now on.

Both reviewers have checklists at the top of this thread with the JOSS requirements. As you go over the submission, please check any items that you feel have been satisfied. There are also links to the JOSS reviewer guidelines.

Please read the first couple of comments in this issue carefully, so that you can accept the invitation from JOSS and be able to check items, and so that you don't get overwhelmed with notifications from other activities in JOSS.

The JOSS review is different from most other journals. Our goal is to work with the authors to help them meet our criteria instead of merely passing judgment on the submission. As such, reviewers are encouraged to submit issues and pull requests on the software repository. When doing so, please mention `openjournals/joss-reviews#3617` so that a link is created to this thread (and I can keep an eye on what is happening). Please also feel free to comment and ask questions on this thread. In my experience, it is better to post comments/questions/suggestions as you come across them instead of waiting until you've reviewed the entire package.

We aim for reviews to be completed within about 2-4 weeks. Please let me know if either of you require some more time. We can also use Whedon (our bot) to set automatic reminders if you know you'll be away for a known period of time.

Please feel free to ping me (@danielskatz) if you have any questions/concerns.

**Comment by step21** [comment] 2021-08-19 10:21
@danielskatz I confirmed basic functionality so far. The paper does say 'high performance' extraction but otherwise does not make any specific claims. Thus, I am not sure how to evaluate performance or functionality at scale as I currently do not have a dataset ready for this. Though at least I would look at their tests, which is when I happened upon the mentioned issue. I can later do this on a linux machine.

**Comment by danielskatz** [comment] 2021-08-19 12:37
@step21 - as we say in the checklist, if there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.) I think it's therefor up to you to decide if you are ok with a vague "high performance" statement, to ask the submitter to explain, or to disagree.

**Comment by mattdahl** [comment] 2021-08-22 00:56
@whedon check references from branch joss-paper

**Comment by whedon** [comment] 2021-08-22 00:56
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment] 2021-08-22 00:56
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/pan/mpm011 is OK
- 10.1016/j.socnet.2007.05.001 is OK
- 10.1093/pan/mps019 is OK
- 10.1111/jels.12012 is OK
- 10.2307/449284 is OK
- 10.1007/s10506-018-9217-1 is OK
- 10.1145/3462757.3466066 is OK
- 10.1007/s10506-020-09261-5 is OK
- 10.1007/s10506-018-9224-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by mattdahl** [comment] 2021-08-22 00:57
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment] 2021-08-22 00:57
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-08-22 00:57
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: :point_left:

**Comment by whedon** [comment] 2021-08-30 12:36
:wave: @cmaimone, please update us on how your review is going (this is an automated reminder).

**Comment by whedon** [comment] 2021-08-30 12:36
:wave: @step21, please update us on how your review is going (this is an automated reminder).

**Comment by danielskatz** [comment] 2021-09-08 20:18
👋 @cmaimone, @step21 - we're now about 3 weeks into the process. How is it going? I see some progress by @step21, but no checked items from @cmaimone

**Comment by cmaimone** [comment] 2021-09-08 20:31
On my to-do list for next week

**Comment by cmaimone** [comment] 2021-09-16 21:28
I did an initial review - as you can see above, I added issues to the repo.  

Most are around documentation.  I think this project was pulled out as a separate piece from a larger project.  The documentation still seems to reflect that and isn't yet sufficient for an independent user to come and understand and use the package.  I approached this as if I'm a researcher with a collection of legal texts that I want to pull the citations out of.  

Also, the community guidelines issue should still be open - see new comment after you closed it.

**Comment by mattdahl** [comment] 2021-09-17 02:52
@cmaimone Thank you! We will address those issues and make revisions in the coming days :)

**Comment by cmaimone** [comment] 2021-09-17 03:00
I should also say that the package is impressive - I get a little focused on the checklist and issues sometimes.  But having done similar (but smaller) projects in the past, I appreciate how much effort went into this, and it's great that it's shared for others to use :)

**Comment by step21** [comment] 2021-09-17 10:22
> 👋 @cmaimone, @step21 - we're now about 3 weeks into the process. How is it going? I see some progress by @step21, but no checked items from @cmaimone

I'll get to it today or tomorrow.

**Comment by danielskatz** [comment] 2021-09-17 12:11
Thanks to everyone so far!

**Comment by step21** [comment] 2021-09-18 18:40
Hi, I also finished my initial review now.
Generally most things are fine and for the majority of the checklist I agree with @cmaimone. Especially that documentation could be more detailed, and example datasets for testing would be nice, especially to verify functionality and performance, which I partly mentioned when I first looked at the repo.
However there are tests in the repo, so I checked 'automated tests', as they can be automated.  Community Guidelines I checked at first, because I thought for such a project with at this stage limited contributors, the amount of info is enough, except for mention of the CLA - as in their repo there is a contributor license agreement, so if people are expected to sign this for contributions, this should be explicitly mentioned in the readme. (there are also free solutions to automate signing)
Regarding the paper - generally it's fine, but I had the feeling that once or twice it switches topcis - f.e. under 'statement of need' it switches from explaining the need, directly to explaining how eyecite itself works. In my opinion this should be its own section.

**Comment by danielskatz** [comment] 2021-09-19 14:04
👋 @step21

> However there are tests in the repo, so I checked 'automated tests', as they can be automated. 

It's fine that you checked this, but it shouldn't be because they can be automated, but it can be simply because manual steps exist, as the criterion says.

Thanks overall for your comments.  If you can make any things that you think need to be changed but that don't yet have issues, such as your comment about the paper, can you create an issue for this in https://github.com/freelawproject/eyecite and mention `openjournals/joss-reviews#3617` in it?

**Comment by danielskatz** [comment] 2021-09-19 14:04
👋 @mattdahl - we'll look forward to seeing how you respond to these issues.

**Comment by step21** [comment] 2021-09-20 17:01
> 👋 @step21
> 
> > However there are tests in the repo, so I checked 'automated tests', as they can be automated.
> 
> It's fine that you checked this, but it shouldn't be because they can be automated, but it can be simply because manual steps exist, as the criterion says.
> 
> Thanks overall for your comments. If you can make any things that you think need to be changed but that don't yet have issues, such as your comment about the paper, can you create an issue for this in https://github.com/freelawproject/eyecite and mention `openjournals/joss-reviews#3617` in it?

Ok, thanks for clarifying. I made an issue about the paper structure.

**Comment by step21** [comment] 2021-09-21 20:47
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment] 2021-09-21 20:47
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-09-21 20:47
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment] 2021-09-28 16:05
👋 @step21 - How are things going on your side?

**Comment by mattdahl** [comment] 2021-09-29 03:39
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment] 2021-09-29 03:39
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-09-29 03:40
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: :point_left:

**Comment by mattdahl** [comment] 2021-09-29 03:45
> I don't think I have any remaining issues that would prevent publication (a few open, but some can be closed, and others are for longer term consideration). Good work @mattdahl and team! I hope a lot of legal researchers are able to put this to good use.

Thanks @cmaimone for volunteering to review and for your careful attention. The project is much improved because of your suggestions!

**Comment by step21** [comment] 2021-10-02 15:20
@danielskatz I think everything is fine from my side as well.

**Comment by danielskatz** [comment] 2021-10-02 18:02
Thanks @step21!

**Comment by danielskatz** [comment] 2021-10-02 18:03
@whedon check references in branch joss-paper

**Comment by danielskatz** [comment] 2021-10-02 18:03
@whedon generate pdf in branch joss-paper

**Comment by whedon** [comment] 2021-10-02 18:04
PDF failed to compile for issue #3617 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment] 2021-10-02 18:04
@whedon check references from branch joss-paper

**Comment by whedon** [comment] 2021-10-02 18:04
```
Attempting to check references... from custom branch joss-paper
```

**Comment by whedon** [comment] 2021-10-02 18:04
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/pan/mpm011 is OK
- 10.1016/j.socnet.2007.05.001 is OK
- 10.1093/pan/mps019 is OK
- 10.1111/jels.12012 is OK
- 10.2307/449284 is OK
- 10.1007/s10506-018-9217-1 is OK
- 10.1145/3462757.3466066 is OK
- 10.1007/s10506-020-09261-5 is OK
- 10.1007/s10506-018-9224-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by danielskatz** [comment] 2021-10-02 18:04
@whedon generate pdf from branch joss-paper

**Comment by whedon** [comment] 2021-10-02 18:04
```
Attempting PDF compilation from custom branch joss-paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-10-02 18:05
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03617/joss.03617/10.21105.joss.03617.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment] 2021-10-02 18:08
@mattdahl - I've now proofread the paper, and everything looks good to me.  You might want to check it again to make sure you are happy with it before we move to acceptance and publication.

The next steps are for you to:
- [ ] Make a tagged release of your software, and list the version tag of the archived version here.
- [ ] Archive the reviewed software in Zenodo or a similar service (e.g., figshare, an institutional repository)
- [ ] Check the archival deposit (e.g., in Zenodo) has the correct metadata. This includes the title (should match the paper title) and author list (make sure the list is correct and people who only made a small fix are not on it). You may also add the authors' ORCID.
- [ ] Please list the DOI of the archived version here.

**Comment by mattdahl** [comment] 2021-10-05 04:03
> I think everything is fine from my side as well.

Thank you, @step21, for your very helpful feedback throughout this process! We appreciate you taking the time to serve as a reviewer.

@danielskatz We will complete those tasks in the coming days.

**Comment by danielskatz** [comment] 2021-10-07 10:55
@mattdahl - We expect the archival deposit to be of the full repository, not just selected files.  For example, the tutorial is not in the repository.  The easiest way to do this is to clone the repository somewhere, then tar and gzip it, or just deposit the full cloned repository as a set of files in directories.

**Comment by danielskatz** [comment] 2021-10-07 10:55
@whedon set v2.3.0 as version

**Comment by whedon** [comment] 2021-10-07 10:55
OK. v2.3.0 is the version.

**Comment by whedon** [comment] 2021-10-08 12:18
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1093/pan/mpm011 is OK
- 10.1016/j.socnet.2007.05.001 is OK
- 10.1093/pan/mps019 is OK
- 10.1111/jels.12012 is OK
- 10.2307/449284 is OK
- 10.1007/s10506-018-9217-1 is OK
- 10.1145/3462757.3466066 is OK
- 10.1007/s10506-020-09261-5 is OK
- 10.1007/s10506-018-9224-2 is OK

MISSING DOIs

- None

INVALID DOIs

- None
```

**Comment by whedon** [comment] 2021-10-08 12:18
:wave: @openjournals/joss-eics, this paper is ready to be accepted and published.

 Check final proof :point_right: https://github.com/openjournals/joss-papers/pull/2657

If the paper PDF and Crossref deposit XML look good in https://github.com/openjournals/joss-papers/pull/2657, then you can now move forward with accepting the submission by compiling again with the flag `deposit=true` e.g.
 ```
@whedon accept deposit=true from branch joss-paper 
```

**Comment by danielskatz** [comment] 2021-10-08 12:25
Congratulations to @mattdahl (Matthew Dahl) and co-authors!!

And thanks to @cmaimone and @step21 for reviewing!
We couldn't do this without you

**Closed by danielskatz** 2021-10-08 12:25 UTC
Labels: accepted, review, Python, recommend-accept, published

**Comment by danielskatz** [comment] 2021-10-08 15:14
> Just FYI, if you click on the "tree" view instead of the "table" view, you'll see that the directory structure is preserved. The relative file paths are also visible below the title of each file in the "table" view.

great!
