### ISSUE TITLE
[PRE REVIEW]: pyCSEP: A Python Package For Earthquake Forecast Developers

### ISSUE THREAD

**Issue by whedon** [openjournals/joss-reviews#3507] opened 2021-07-17 16:04 UTC
**Submitting author:** @wsavran (<a href="http://orcid.org/0000-0001-5404-0778">William Savran</a>)
**Repository:** <a href="https://github.com/SCECcode/pycsep" target ="_blank">https://github.com/SCECcode/pycsep</a>
**Version:** v0.4.1
**Editor:** @kbarnhart
**Reviewers:** @nvanderelst
**Managing EiC:** Daniel S. Katz

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

## Status

[![status](https://joss.theoj.org/papers/43f25170c9329d9bb9abc27e3dfabace/status.svg)](https://joss.theoj.org/papers/43f25170c9329d9bb9abc27e3dfabace)

Status badge code:

```
HTML: <a href="https://joss.theoj.org/papers/43f25170c9329d9bb9abc27e3dfabace"><img src="https://joss.theoj.org/papers/43f25170c9329d9bb9abc27e3dfabace/status.svg"></a>
Markdown: [![status](https://joss.theoj.org/papers/43f25170c9329d9bb9abc27e3dfabace/status.svg)](https://joss.theoj.org/papers/43f25170c9329d9bb9abc27e3dfabace)
```

**Author instructions**

Thanks for submitting your paper to JOSS @wsavran. **Currently, there isn't an JOSS editor assigned** to your paper.

@wsavran if you have any suggestions for potential reviewers then please mention them here in this thread (without tagging them with an @). In addition, [this list of people](https://bit.ly/joss-reviewers) have already agreed to review for JOSS and may be suitable for this submission (please start at the bottom of the list).

**Editor instructions**

The JOSS submission bot @whedon is here to help you find and assign reviewers and start the main review. To find out what @whedon can do for you type:

```
@whedon commands
```

**Comment by whedon** [comment] 2021-07-17 16:04
Hello human, I'm @whedon, a robot that can help you with some common editorial tasks.

**:warning: JOSS reduced service mode :warning:**

Due to the challenges of the COVID-19 pandemic, JOSS is currently operating in a "reduced service mode". You can read more about what that means in [our blog post](https://blog.joss.theoj.org/2020/05/reopening-joss).

For a list of things I can do to help you, just type:

```
@whedon commands
```

For example, to regenerate the paper pdf after making changes in the paper's md or bib files, type:

```
@whedon generate pdf
```

**Comment by whedon** [comment] 2021-07-17 16:05
```
Software report (experimental):

github.com/AlDanial/cloc v 1.88  T=3.57 s (27.4 files/s, 207820.3 lines/s)
--------------------------------------------------------------------------------
Language                      files          blank        comment           code
--------------------------------------------------------------------------------
XML                               5              0              0         717119
JSON                              9              0              0           7184
Python                           50           1972           3470           6671
YAML                             10            137             15           3482
reStructuredText                 14            476            395            851
Markdown                          3             67              0            180
Perl                              1             10             12             41
HTML                              2              4             11             22
Bourne Again Shell                1             16             28             19
make                              1              5              6             12
Jupyter Notebook                  1              0            180             10
Bourne Shell                      1              0              0              2
--------------------------------------------------------------------------------
SUM:                             98           2687           4117         735593
--------------------------------------------------------------------------------


Statistical information for the repository 'fb64479a7dddf1b274fedccf' was
gathered on 2021/07/17.
The following historical commit information, by author, was found:

Author                     Commits    Insertions      Deletions    % of changes
MH                               2             5              4            0.02
Pablo Iturrieta                  3           482            105            1.26
Philip Maechling                 1           386              0            0.83
Thomas Beutin ("tb")             4           103             18            0.26
William                         12            54             48            0.22
William Savran                 297         25334          16064           88.95
bayonato89                       2           104             27            0.28
khawajasim                      14          1161            131            2.78
pciturri                        20           810            333            2.46
tb                               6           124              6            0.28
wsavran                         28           913            328            2.67

Below are the number of rows from each author that have survived and are still
intact in the current revision:

Author                     Rows      Stability          Age       % in comments
MH                            4           80.0          1.0               50.00
Pablo Iturrieta             464           96.3          5.8               11.21
Philip Maechling            155           40.2          0.0               54.84
Thomas Beutin ("tb")         29           28.2         15.1                0.00
William Savran            10192           40.2         17.4               14.89
bayonato89                  102           98.1          0.6                9.80
khawajasim                   35            3.0         16.8               11.43
pciturri                    444           54.8          7.8               19.14
wsavran                     688           75.4          4.1                8.87
```

**Comment by whedon** [comment] 2021-07-17 16:05
PDF failed to compile for issue #3507 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment] 2021-07-17 16:08
@whedon generate pdf from branch pycsep_Joss

**Comment by whedon** [comment] 2021-07-17 16:08
```
Attempting PDF compilation from custom branch pycsep_Joss. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-17 16:08
PDF failed to compile for issue #3507 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by danielskatz** [comment] 2021-07-17 16:08
@whedon generate pdf from branch pycsep_joss

**Comment by whedon** [comment] 2021-07-17 16:08
```
Attempting PDF compilation from custom branch pycsep_joss. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-17 16:08
PDF failed to compile for issue #3507 with the following error: 
```
 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.294 ...n@usc.edu}{\nolinkurl{wsavran@usc.edu}}}}

Looks like we failed to compile the PDF

```

**Comment by danielskatz** [comment] 2021-07-17 16:08
@whedon check references from branch pycsep_joss

**Comment by whedon** [comment] 2021-07-17 16:09
```
Attempting to check references... from custom branch pycsep_joss
```

**Comment by whedon** [comment] 2021-07-17 16:09
```
Reference check summary (note 'MISSING' DOIs are suggestions that need verification):

OK DOIs

- 10.1785/gssrl.78.1.30 is OK
- 10.1002/cpe.1519 is OK
- 10.4401/ag-5350 is OK
- 10.2478/s11600-011-0013-5 is OK
- 10.1785/0120090340 is OK
- 10.1785/0120120186 is OK
- 10.1785/0220180033 is OK
- 10.1785/0220180051 is OK
- 10.1785/0220180031 is OK
- 10.1785/0220180053 is OK
- 10.1093/gji/ggaa554 is OK
- 10.1785/0220170045 is OK
- 10.1785/0220180161 is OK
- 10.1785/0120200026 is OK

MISSING DOIs

- 10.1785/gssrl.78.1.7 may be a valid DOI for title: Overview of the Working Group for the Development of Regional Earthquake Likelihood Models (RELM)

INVALID DOIs

- None
```

**Comment by danielskatz** [comment] 2021-07-17 16:11
👋 @wsavran - your paper doesn't compile- please make the headers match those in the [example](https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography).  Also, you might be able to fix the possibly missing DOI that whedon suggests, but note that this may be incorrect. Please feel free to make changes to your .bib file, then use the command `@whedon check references from branch pycsep_joss` to check again, and the command `@whedon generate pdf from branch pycsep_joss` when the references are right and the .md file is updated to make a new PDF. Whedon commands need to be the first entry in a new comment.

**Comment by wsavran** [comment] 2021-07-18 22:48
@whedon check references from branch pycsep_joss/paper

**Comment by whedon** [comment] 2021-07-18 22:49
```
Attempting to check references... from custom branch pycsep_joss/paper
```

**Comment by wsavran** [comment] 2021-07-18 23:20
@whedon generate pdf from branch pycsep_joss/paper

**Comment by whedon** [comment] 2021-07-18 23:20
```
Attempting PDF compilation from custom branch pycsep_joss/paper. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-18 23:21
PDF failed to compile for issue #3507 with the following error: 
```
 Can't find any papers to compile :-(

```

**Comment by wsavran** [comment] 2021-07-18 23:23
@whedon generate pdf from branch pycsep_joss

**Comment by whedon** [comment] 2021-07-18 23:23
```
Attempting PDF compilation from custom branch pycsep_joss. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-18 23:23
PDF failed to compile for issue #3507 with the following error: 
```
 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.294 ...n@usc.edu}{\nolinkurl{wsavran@usc.edu}}}}

Looks like we failed to compile the PDF

```

**Comment by danielskatz** [comment] 2021-07-18 23:28
You can try to merge https://github.com/SCECcode/pycsep/pull/129 and see if that works - if not, the problem is likely the @ in the email address, which perhaps needs to be protected/quoted in some way.  Perhaps @arfon will know the answer

**Comment by wsavran** [comment] 2021-07-18 23:30
@whedon generate pdf from branch pycsep_joss

**Comment by whedon** [comment] 2021-07-18 23:30
```
Attempting PDF compilation from custom branch pycsep_joss. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-18 23:30
PDF failed to compile for issue #3507 with the following error: 
```
 Error producing PDF.
! Use of \\author doesn't match its definition.
\new@ifnextchar ...served@d = #1\def \reserved@a {
                                                  #2}\def \reserved@b {#3}\f...
l.294 ...n@usc.edu}{\nolinkurl{wsavran@usc.edu}}}}

Looks like we failed to compile the PDF

```

**Comment by wsavran** [comment] 2021-07-19 00:09
@whedon generate pdf from branch pycsep_joss

**Comment by whedon** [comment] 2021-07-19 00:09
```
Attempting PDF compilation from custom branch pycsep_joss. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-19 00:09
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03507/joss.03507/10.21105.joss.03507.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03507/joss.03507/10.21105.joss.03507.pdf) :page_facing_up: :point_left:

**Comment by danielskatz** [comment] 2021-07-19 20:45
@kbarnhart - could you edit this submission?

**Comment by danielskatz** [comment] 2021-07-19 20:45
@whedon invite @kbarnhart as editor

**Comment by whedon** [comment] 2021-07-19 20:45
@kbarnhart has been invited to edit this submission.

**Comment by kbarnhart** [comment] 2021-07-19 23:26
@danielskatz I can do this.

@wsavran it will later in this week that I start actively handling this.

**Comment by kbarnhart** [comment] 2021-07-19 23:27
@whedon assign @kbarnhart as editor

**Comment by whedon** [comment] 2021-07-19 23:27
OK, the editor is @kbarnhart

**Comment by kbarnhart** [comment] 2021-07-26 18:56
@wsavran thanks for this submission. I have completed my pre-review screening of this submission and will now start soliciting reviewers. If you have reviewer recommendations, please list them here (either list github handle without the @ symbol, or a name if they do not have a github account). 

A few minor points regarding the paper to consider. 
1. Line 27 - should be "earthquake prediction methods"?
2. Line 53 - should the "the" before "monolithic" be deleted?
3. Line 64 - Europe should be capitalized. 
4. Line 84 - provide citations for cartopy and matplotlib. 
5. Line 90-91 - provide citations for these packages. 
6. Reference section 
    - check capitalization (for example, California on line 111, use double curly braces in .bib title entry where necessary). 
    - disambiguate Ned Field references (use the identical first name in all .bib entries)

Any questions, clarifications, or concerns... feel free to contact me here or at krbarnhart@usgs.gov

**Comment by wsavran** [comment] 2021-07-26 22:11
@whedon generate pdf from branch pycsep_joss

**Comment by whedon** [comment] 2021-07-26 22:11
```
Attempting PDF compilation from custom branch pycsep_joss. Reticulating splines etc...
```

**Comment by whedon** [comment] 2021-07-26 22:11
:point_right::page_facing_up: [Download article proof](https://raw.githubusercontent.com/openjournals/joss-papers/joss.03507/joss.03507/10.21105.joss.03507.pdf) :page_facing_up: [View article proof on GitHub](https://github.com/openjournals/joss-papers/blob/joss.03507/joss.03507/10.21105.joss.03507.pdf) :page_facing_up: :point_left:

**Comment by wsavran** [comment] 2021-07-26 22:22
@kbarnhart, thanks for the feedback on the manuscript. i've asked whedon to compile a new pdf with some changes.

possible reviewers:
* leouieda
* jedbrown 
* lheagy 

thanks!

**Comment by kbarnhart** [comment] 2021-07-27 15:24
@wsavran thanks for making those changes. I have now started to reach out to reviewers. As I am able to confirm reviewers I will add them here. Once I get a sufficient number (2 or 3), I will start the formal review issue.

**Comment by wsavran** [comment] 2021-07-29 17:13
@kbarnhart thanks! i look forward to hearing back from the reviewers!

**Comment by kbarnhart** [comment] 2021-08-10 18:37
@wsavran I wanted to give you a quick update. Specifically, I'm still actively looking for reviewers for this submission.

**Comment by wsavran** [comment] 2021-08-10 18:39
@kbarnhart thanks for the update!

**Comment by kbarnhart** [comment] 2021-08-10 18:57
👋 @calum-chamberlain, @megies, @barsch, @mhearne-usgs would you be interested and able to provide a review of a manuscript at the Journal of Open Source Software (JOSS). The submission I'd like you to review is titled: " pyCSEP: A Python Package For Earthquake Forecast Developers" by William H. Savran, Maximilian J. Werner, Danijel Schorlemmer, and Philip J. Maechling and the submission repository is at: https://github.com/SCECcode/pycsep. Given your extensive experience in earthquake seismology and python development, I would value your review of this submission. 

A bit of background about JOSS and its review process. JOSS is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html. Editors and reviewers post comments on the Review issue, and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

JOSS has worked hard to recognize that because of the challenges of the COVID-19 pandemic, all members of the research community may have reduced availability. At present we are asking reviewers to complete their reviews within 6 weeks. 
 
If you are interested and able, please review the [JOSS Conflict of Interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy). Otherwise I’d value any recommendations you may have for other reviewers.

**Comment by kbarnhart** [comment] 2021-08-11 15:53
@calum-chamberlain thanks for the prompt response and the recommendation!

**Comment by kbarnhart** [comment] 2021-08-11 17:47
👋 @cjhopp would you be interested and able to provide a review of a manuscript at the Journal of Open Source Software (JOSS). The submission I'd like you to review is titled: " pyCSEP: A Python Package For Earthquake Forecast Developers" by William H. Savran, Maximilian J. Werner, Danijel Schorlemmer, and Philip J. Maechling and the submission repository is at: https://github.com/SCECcode/pycsep. Given your extensive experience in earthquake seismology and python development, I would value your review of this submission. 

A bit of background about JOSS and its review process. JOSS is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html. Editors and reviewers post comments on the Review issue, and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

JOSS has worked hard to recognize that because of the challenges of the COVID-19 pandemic, all members of the research community may have reduced availability. At present we are asking reviewers to complete their reviews within 6 weeks. 
 
If you are interested and able, please review the [JOSS Conflict of Interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy). Otherwise I’d value any recommendations you may have for other reviewers.

**Comment by wsavran** [comment] 2021-08-14 16:27
@kbarnhart, I've copied the github handles of a few other reviewers that should reviewers of this paper. Cheers!

baagaard-usgs
willic3
brendanjmeade
MatteoTaroniINGV

**Comment by cjhopp** [comment] 2021-08-16 13:59
Hi @kbarnhart , apologies for the delay in responding, and thanks for reaching out! In the future, I'd be happy to review for JOSS, but I have to decline this time around. Many weeks of impending fieldwork.

**Comment by kbarnhart** [comment] 2021-08-16 15:17
@cjhopp thanks for considering and letting me know. Best of luck with the fieldwork. 

@wsavran thanks for those additional recommendations.

**Comment by kbarnhart** [comment] 2021-08-16 15:22
:wave: @megies, @barsch, @mhearne-usgs a friendly reminder to consider this review request for "pyCSEP: A Python Package For Earthquake Forecast Developers" by William H. Savran, Maximilian J. Werner, Danijel Schorlemmer, and Philip J. Maechling

**Comment by kbarnhart** [comment] 2021-08-16 15:25
👋 @baagaard-usgs, @brendanjmeade @MatteoTaroniINGV would you be interested and able to provide a review of a manuscript at the Journal of Open Source Software (JOSS). The submission I'd like you to review is titled: " pyCSEP: A Python Package For Earthquake Forecast Developers" by William H. Savran, Maximilian J. Werner, Danijel Schorlemmer, and Philip J. Maechling and the submission repository is at: https://github.com/SCECcode/pycsep. 

A bit of background about JOSS and its review process. JOSS is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html. Editors and reviewers post comments on the Review issue, and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

JOSS has worked hard to recognize that because of the challenges of the COVID-19 pandemic, all members of the research community may have reduced availability. At present we are asking reviewers to complete their reviews within 6 weeks. 
 
If you are interested and able, please review the [JOSS Conflict of Interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy). Otherwise I’d value any recommendations you may have for other reviewers.

**Comment by brendanjmeade** [comment] 2021-08-16 15:43
Thanks for reaching out.  Normally I'd certainly do my best to review this paper, but I'm not taking on additional reviews at this time.  I know of this work and am very excited to see it more forward!

**Comment by baagaard-usgs** [comment] 2021-08-16 20:39
Katy,

CSEP is a bit outside my area of expertise. Morgan Page, Nicholas van der Elst, and Andrew Michael are in a much better position than me to review the scientific content and probably the software content as well.

Brad

On 8/16/21, 9:27 AM, "Katy Barnhart" ***@***.***> wrote:




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



👋 @baagaard-usgs<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbaagaard-usgs&data=04%7C01%7Cbaagaard%40usgs.gov%7Cdfda6146f5504d8ee1de08d960ca2f6d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637647244223167454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PuAmPvyqmqztnAolXjmlyZznlcXmgMMszK%2FmZMCw9Bs%3D&reserved=0>, @brendanjmeade<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbrendanjmeade&data=04%7C01%7Cbaagaard%40usgs.gov%7Cdfda6146f5504d8ee1de08d960ca2f6d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637647244223177411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wtggzCtvZYpo7grObUibB%2FMzhYct1K8Bvs38iNPhheQ%3D&reserved=0> @MatteoTaroniINGV<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMatteoTaroniINGV&data=04%7C01%7Cbaagaard%40usgs.gov%7Cdfda6146f5504d8ee1de08d960ca2f6d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637647244223177411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KZCHaY5KHZECYSFwCeOS2OW86luZiXqdsarDpoDCHAo%3D&reserved=0> would you be interested and able to provide a review of a manuscript at the Journal of Open Source Software (JOSS). The submission I'd like you to review is titled: " pyCSEP: A Python Package For Earthquake Forecast Developers" by William H. Savran, Maximilian J. Werner, Danijel Schorlemmer, and Philip J. Maechling and the submission repository is at: https://github.com/SCECcode/pycsep<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSCECcode%2Fpycsep&data=04%7C01%7Cbaagaard%40usgs.gov%7Cdfda6146f5504d8ee1de08d960ca2f6d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637647244223177411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2F57%2B9bvYKoIxo7Iei8C1OsMb7W0dKRZEJERbi0uf%2F4E%3D&reserved=0>.

A bit of background about JOSS and its review process. JOSS is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjoss.readthedocs.io%2Fen%2Flatest%2Freview_criteria.html&data=04%7C01%7Cbaagaard%40usgs.gov%7Cdfda6146f5504d8ee1de08d960ca2f6d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637647244223187367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nDcdX8n%2BimQI1TszyTUSRzS4uNrOWM%2FoEGD8V4CCzVc%3D&reserved=0>. Editors and reviewers post comments on the Review issue, and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

JOSS has worked hard to recognize that because of the challenges of the COVID-19 pandemic, all members of the research community may have reduced availability. At present we are asking reviewers to complete their reviews within 6 weeks.

If you are interested and able, please review the JOSS Conflict of Interest policy<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjoss.readthedocs.io%2Fen%2Flatest%2Freviewer_guidelines.html%23joss-conflict-of-interest-policy&data=04%7C01%7Cbaagaard%40usgs.gov%7Cdfda6146f5504d8ee1de08d960ca2f6d%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637647244223187367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UtJ6DHf8T7TnqGFcaC9is7ypuLElnakXrafKJNWfUEA%3D&reserved=0>. Otherwise I’d value any recommendations you may have for other reviewers.

**Comment by MatteoTaroniINGV** [comment] 2021-08-17 10:48
Dear Katy,
                 now I'm on vacation and I will stay on vacation for the
next few weeks.
I suggest these three possible reviewers:

Giuseppe Falcone: ***@***.***
Angela Stallone: ***@***.***
Ilaria Spassiani: ***@***.***

                       Matteo Taroni

=======================================================================

Il giorno lun 16 ago 2021 alle ore 17:25 Katy Barnhart <
***@***.***> ha scritto:

**Comment by kbarnhart** [comment] 2021-08-17 19:32
Thanks to @brendanjmeade @baagaard-usgs and @MatteoTaroniINGV for your quick responses and the recommendations.

**Comment by kbarnhart** [comment] 2021-08-19 17:30
@nvanderelst has kindly agreed to provide a review. Many thanks!

**Comment by kbarnhart** [comment] 2021-08-19 17:31
@whedon add @nvanderelst as reviewer

**Comment by whedon** [comment] 2021-08-19 17:31
OK, @nvanderelst is now a reviewer

**Comment by kbarnhart** [comment] 2021-08-19 17:41
👋 @angystallone would you be interested and able to provide a review of a manuscript at the Journal of Open Source Software (JOSS). The submission I'd like you to review is titled: " pyCSEP: A Python Package For Earthquake Forecast Developers" by William H. Savran, Maximilian J. Werner, Danijel Schorlemmer, and Philip J. Maechling and the submission repository is at: https://github.com/SCECcode/pycsep. 

A bit of background about JOSS and its review process. JOSS is a free, open-source, community driven and developer-friendly online journal (no publisher is seeking to raise revenue from the volunteer labor of researchers!). The review process at JOSS is unique: it takes place in a GitHub issue, is open, and author-reviewer-editor conversations are encouraged. JOSS reviews involve downloading and installing the software, and inspecting the repository and submitted paper for key elements. See https://joss.readthedocs.io/en/latest/review_criteria.html. Editors and reviewers post comments on the Review issue, and authors respond to the comments and improve their submission until acceptance (or withdrawal, if they feel unable to satisfy the review).

JOSS has worked hard to recognize that because of the challenges of the COVID-19 pandemic, all members of the research community may have reduced availability. At present we are asking reviewers to complete their reviews within 6 weeks. 
 
If you are interested and able, please review the [JOSS Conflict of Interest policy](https://joss.readthedocs.io/en/latest/reviewer_guidelines.html#joss-conflict-of-interest-policy). Otherwise I’d value any recommendations you may have for other reviewers.

**Comment by kbarnhart** [comment] 2021-08-22 18:53
👋 @angystallone a friendly reminder to consider serving as a reviewer for "pyCSEP: A Python Package For Earthquake Forecast Developers" by William H. Savran, Maximilian J. Werner, Danijel Schorlemmer, and Philip J. Maechling at the Journal of Open Source Software. I'll also send you a message via email. Many thanks for considering.

**Comment by kbarnhart** [comment] 2021-08-25 15:23
I'm going to start the review issue so that @nvanderelst can see the review structure and checklist. Once I find a second reviewer I'll manually add them. 

@wsavran - Know that I'm still actively seeking reviewers (here and over email).

**Comment by kbarnhart** [comment] 2021-08-25 15:23
@whedon start review

**Comment by whedon** [comment] 2021-08-25 15:23
OK, I've started the review over in https://github.com/openjournals/joss-reviews/issues/3658.

**Comment by angystallone** [comment] 2021-08-25 15:42
Dear Katy,

thank you for your email, but I am not the right person for this review.
I would recommend Ilaria Spassiani instead.

Best regards,
Angela

**Comment by kbarnhart** [comment] 2021-08-30 17:51
I've now found a second reviewer and am thus closing this issue.

**Closed by kbarnhart** 2021-08-30 17:51 UTC
Labels: pre-review, Shell, Python, Perl 6

**Comment by wsavran** [comment] 2021-11-08 18:33
Hi @kbarnhart! I hope everything is going well. I'm just checking in on the status of the review for our manuscript. Thanks!

**Comment by wsavran** [comment] 2021-11-09 18:54
@kbarnhart thank you very much.

**Comment by megies** [comment] 2022-02-22 10:53
@kbarnhart sorry about not having replied when pinged in this ticket :grimacing:
